### ISSUE TITLE
NavigationView does not show PaneHeader or PaneTitle when IsPaneToggleButtonVisible is false

### ISSUE THREAD

**Issue by knightmeister** [microsoft/microsoft-ui-xaml#1005]
**Describe the bug**
The `NavigationView` does not show `PaneHeader` or `PaneTitle` content when IsPaneToggleButtonVisible is false and the hamburger icon is not shown.

**Steps to reproduce the bug**
Set a `PaneHeader` or `PaneTitle` content and set `IsPaneToggleButtonVisible` to false. The content will not be shown.

**Expected behavior**
If header or title is set, it should be shown regardless of the visibility of the pane toggle button. For my particular scenario, I want the UX of my app such that the navigation view cannot be manually collapsed so the pane toggle button isn't shown, but I'd like to show header content.

**Screenshots**
N/A

**Version Info**
Seen on both 1903 (Desktop) and Nuget 2.1.190606001

NuGet package version: 
2.1.190606001

**Comment by RBrid** [comment]
@YuliKl, this looks like all By Design to me based on what I'm seeing the NavigationView's control template:

1. The PaneTitle is actually part of toggle button's content:
<Button
    x:Name="TogglePaneButton"
    Style="{TemplateBinding PaneToggleButtonStyle}"
    AutomationProperties.LandmarkType="Navigation"
    Visibility="{Binding RelativeSource={RelativeSource TemplatedParent}, Path=TemplateSettings.PaneToggleButtonVisibility}"
    VerticalAlignment="Top">
    <TextBlock
        x:Name="PaneTitleTextBlock" 
        Grid.Column="0"
        Text="{TemplateBinding PaneTitle}"
        HorizontalAlignment="Left"
        VerticalAlignment="Center"
        Style="{StaticResource NavigationViewItemHeaderTextStyle}"/>
</Button>

2. When IsPaneToggleButtonVisible is set to False, we go into the TogglePaneButtonCollapsed state which squeezes the height of the row containing the PaneHeader to 4px.
<VisualStateGroup x:Name="TogglePaneGroup">
  <VisualState x:Name="TogglePaneButtonVisible" />
  <VisualState x:Name="TogglePaneButtonCollapsed">
    <VisualState.Setters>
      <Setter Target="PaneContentGridToggleButtonRow.Height" Value="4" />
    </VisualState.Setters>
  </VisualState>
</VisualStateGroup>

We can't change this lightly. I think it'll need some spec'ing if re-templating the control (by the customer)  is not the solution here.

**Comment by YuliKl** [comment]
@RBrid, I believe the implementation does not correctly reflect the intent of the design. The hamburger button and the pane title are conceptually independent elements (that have some deliberate visual alignment). Without knowing the implementation details, I see no reason to prevent apps from showing the pane title while hiding the hamburger button. The current implementation details may require significant refactoring to fix, but that doesn't change my view that the current behavior is a bug.

**Comment by jevansaks** [comment]
Giving to @RBrid since he's in that code recently, but if this is hard to fix then unassign and we'll find someone else while @RBrid is on vacation.
