### ISSUE TITLE
Why apps powered by WinUI are so laggy?

### ISSUE THREAD

**Issue by HppZ** [microsoft/microsoft-ui-xaml#10112]
### Describe the bug

such as New Microsoft Store.

### Steps to reproduce the bug

laggy

### NuGet package version

None

**Comment by Sebbe909** [comment]
Because MS is only a 3.12 trillion dollar company and instead of low level fixing and optimizing, they make layer on top of layer on top of layer. A trillion layers of overhead. Remember Windows Vista? It could render the Aero blur in real time super fast, as it was core part of dwm. Now, the Acrylic and even Mica effect for example are so slow, you can see Acrylic being rendered over the window's background when you resize a window with Acrylic BG for example.

Well done MS.

**Comment by ghost1372** [comment]
With all due respect to Indians, today Indians manage all Microsoft products and unfortunately they do it in the worst way.

**Comment by Sebbe909** [comment]
> With all due respect to Indians, today Indians manage all Microsoft products and unfortunately they do it in the worst way.

@ghost1372 I'm glad you've mentioned this as I didn't want to do that. But 100% true.

**Comment by karkarl** [comment]
This doesn't look like a specific bug report. Please follow the template, and for something like this provide a repro and diagnostics. As is this isn't actionable.

**Comment by HppZ** [comment]
FFFF
