### ISSUE TITLE
Window size not correctly applied

### ISSUE THREAD

**Issue by char8t** [microsoft/microsoft-ui-xaml#10204]
### Describe the bug

When specifiying the Window size via `AppWindow.Resize(new SizeInt32(800, 450))` the actual window size appears to be little bit smaller than what is requested:

![Image](https://github.com/user-attachments/assets/750995d9-7a30-427f-8ef6-5c18ebce2062)

One Idea of @dotMorten was (https://github.com/dotMorten/WinUIEx/issues/200) that setting the window dimension is "taking the drop shadow into account". Is that true? If so how to get a window of exactly the size specified?

https://github.com/dotMorten/WinUIEx/issues/200

### Steps to reproduce the bug

1. Create WinUI3 app
2. Specifiy window dimensions
3. Measure real results

### Expected behavior

The window size to be exact to the requested size minus border

### NuGet package version

WinUI 3 - Windows App SDK 1.6.3: 1.6.241114003

### Windows version

Windows 11 (24H2): Build 26100

**Comment by castorix** [comment]
It is because of DWM
On Windows 10, If I add the difference from GetWindowRect - (DwmGetWindowAttribute and DWMWA_EXTENDED_FRAME_BOUNDS), I get the right size (got after the window has been displayed, not at beginning)
(I get 786 * 443 : 
104-904 vs 111-897 => 2 * 7
104-554 vs  104-547 => 7
=> 786 + 14, 443 + 7 => 800, 450

**Comment by DarranRowe** [comment]
If you want the client area to be set to the size specified, remember that AppWindow has the ResizeClient member. This will set the client area to the size specified by taking the styles into account.

Since the screenshot of your code shows that you are using ExtendContentIntoTitleBar, then what you are measuring there is the client area. Resize sets the window size and ResizeClient sets the window size to give a specified client size.

**Comment by char8t** [comment]
Oh i didn't know about `ResizeClient`. It works as expected just one thing to note: When using `ExtendContentIntoTitleBar = true` the client area will become a little bit bigger then what is requested 800, 450 -> 800, 480. Is there a way to programmatically get the title bar height so i can account for the extra size when using `ExtendContentIntoTitleBar`?

**Comment by DarranRowe** [comment]
The implementation of the title bar customisation functionality is shared with AppWindow in current versions. This means that you should be able to go through AppWindow to get an AppWindowTitleBar instance. AppWindowTitleBar has a Height property which reports the height of the title bar.

**Comment by char8t** [comment]
Thank you. Using `AppWindow.TitleBar.Height` together with `ResizeClient` when using `ExtendContentIntoTitleBar = true` does the job
