### ISSUE TITLE
`PivotItem` collapses after dragging `TabViewItem`

### ISSUE THREAD

**Issue by ProJend** [microsoft/microsoft-ui-xaml#10254]
### Describe the bug

 TabViewItem dragging causes PivotItem to collapse unexpectedly

### Steps to reproduce the bug

1. Add `TabViewItem` containing a `Pivot`
2. Drag the `TabViewItem`
3. Release the dragging after the Storyboard completion

### Screenshots

![Image](https://github.com/user-attachments/assets/2dd0c6fc-b655-449e-a782-72119550fa94)

### NuGet package version

WinUI 2 - Microsoft.UI.Xaml 2.8.2

### Windows version

Windows 11 (24H2): Build 26100

**Comment by karkarl** [comment]
TabView content is supposed to be associated with the tab, so its content switches when toggling through tabs. This seems to be by design. 

Furthermore, Pivot is not recommended anymore, and we are not planning on making fixes in this control. Please consider using SelectorBar - https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.selectorbar?view=windows-app-sdk-1.5
