### ISSUE TITLE
Question:  duplicated XAML resources

### ISSUE THREAD

**Issue by HppZ** [microsoft/microsoft-ui-xaml#1040]
1, why there are many duplicated XAML resource definitions in generic.xaml and themeresources.xaml files here
C:\Program Files (x86)\Windows Kits\10\DesignTime\CommonConfiguration\Neutral\UAP\10.0.18362.0\Generic

2, why do you use two files for theme resources, what is their difference?

**Comment by mdtauk** [comment]
My understanding is, XAML uses the **generic.xaml** for for handling control templates unlikely to change at run time, whilst colours, metrics, and other shared resources that could change whilst the app is running, would be in the **themeresources.xaml**.

With WPF where the apps will run on older versions of Windows going back to XP, there would be Theme Resources to match the Aero, Royale, Luna, etc visual styles you could choose, and so less would have to be reloaded and redrawn, if it was only the colours and borders etc that would change

**Comment by jevansaks** [comment]
In the system there's just generic.xaml. I believe these are split apart for the VS designer for some reason. @fabiant3 may be able to explain why it continues to exist.

**Comment by HppZ** [comment]
@fabiant3 please help

**Comment by fabiant3** [comment]
Those are included in the SDK for use by the designer. Themeresources.xaml is a subset of generic.xaml, hence the duplication of resources. Visual Studio verified a few months back that they only use generic.xaml. I don’t know why or how the SDK originally decided it should include both (rather than just generic.xaml). 
When we ship the WinUI 3.0 Nuget, it will only be including generic.xaml. Are you seeing an actual issue?

**Comment by HppZ** [comment]
Are you seeing an actual issue?
No. I just feel confused. Thanks for your answer.

**Comment by mdtauk** [comment]
@fabiant3 This issue is listed as a question.

I suspect the answer to your question @HppZ goes far back, because I believe WPF, Silverlight, and Windows Phone have similar generic.xaml and themeresources separation.

![image](https://user-images.githubusercontent.com/7389110/61499055-b3aec800-a9bd-11e9-94a7-a65180b92463.png)
