### ISSUE TITLE
CommandBarFlyout: When you have a Secondary command button that opens up another CommandBarFlyout, that second commandbarflyout just flickers.

### ISSUE THREAD

**Issue by alanlai-ms** [microsoft/microsoft-ui-xaml#1159]
**Describe the bug** (Sent email to you about this but I think it got lost, so filing this bug to track this work item)
When you have a Secondary command button that opens up another CommandBarFlyout, that second commandbarflyout just flickers.

On Paste (clicking on paste button within commandbarflyout), the Commandbarflyout goes away due to the action.
At this point, we want to launch a 2nd command bar flyout in case user wants to switch its paste type. (Paste as Text? Paste as Image?)
Are you using Outlook Win32 for your email client? If you are, try pasting and you will see what we are trying to do.
You can also try in any of OneNote/Word/Office suite’s Win32 app.
One of the motivation for doing the CommandBarFlyout is give that Win32 feeling, so that’s what we are trying to achieve.

**Steps to reproduce the bug**
https://microsoft-my.sharepoint-df.com/:u:/p/yucu/EUNg00vH4sNBiVm8X5w7o88B7I460r6Ogpi3AgTdgwtQdA?e=lcrDcC

**Screenshots**

![image](https://user-images.githubusercontent.com/49052408/62920163-c1a3fe80-bd59-11e9-80c5-c534d2f69fa2.png)

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |    |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by alanlai-ms** [comment]
@jevansaks

**Comment by jevansaks** [comment]
Yeah looks like that email thread fell off @llongley's radar, I've just pinged it.

**Comment by llongley** [comment]
I responded via email, but I haven't heard back yet.  This seems by design - we close a flyout when the flyout’s placement target no longer is in the visual tree.  In this case, the placement target is the paste button, which is in the flyout that is in the process of closing because a button in its secondary content was clicked.  Once the flyout’s UI unloads, the paste button goes with it, so we close the flyout with it as its placement target.

I checked and it works to open a second flyout without a placement target, by passing in null as the second parameter of ShowAt and giving it a position.  You’d need to figure out the position at which you need to open the flyout, but that should be doable with some transforms based on the original flyout.  Let me know if this won't work for you as a workaround.
