### ISSUE TITLE
NavigationView pane doesn't correctly open after navigating to page with enabled cache

### ISSUE THREAD

**Issue by Dieveral** [microsoft/microsoft-ui-xaml#1178]
**Describe the bug**

Sometimes NavigationView pane doesn't open, after navigating to MainPage with NavigationView that has DisplayMode property set to "Expanded" and IsPaneOpen property set to "false".

**Steps to reproduce the bug**

MainPage has NavigationView control. NavigationCacheMode of MainPage is Enabled. DisplayMode of NavigationView is Expanded. Button "Click me" navigates you to ViewerPage. You can navigate back to MainPage from ViewerPage.
Demo project on GitHub: [https://github.com/Dieveral/NavPaneBug](https://github.com/Dieveral/NavPaneBug)

1. Make sure the window width is large enough that the DisplayMode property of the NavigationView is "Expanded";
2. Close NavigationView pane by clicking Menu button;
3. Click button "Click me";
4. Click return button in top-left corner to navigate to MainPage;
5. Open NavigationView pane by clicking Menu button.

Pane should open but sometimes pane is drawn like closed (pane is open but it looks like it is cut or right panel of NavigationView with content is over it). NavigationView property IsPaneOpen has value "true". Next click closes the pane, and the next one opens the pane. If you didn't get such behavior, you can repeat steps 2-5 until you will get it.

**Expected behavior**

Navigation view should correctly display open state of the pane after clicking Menu button.

**Screenshots**

Actual behavior:
![nav_pane_bug](https://user-images.githubusercontent.com/50696412/63253069-d280d280-c279-11e9-93e5-024e1fa6da75.gif)

Expected behavior:
![nav_pane_expected](https://user-images.githubusercontent.com/50696412/63255850-2510bd80-c27f-11e9-99cb-d17e071e144a.gif)

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.1.190606001

**Comment by jevansaks** [comment]
This sounds like #1488 but that fix is in the nuget package version you specified. @licanhua can you take a look at this repro?

**Comment by licanhua** [comment]
I can repro it on 19h1 machine with the app provided. There are 1/3 or 1/4 of chance to hit this issue in my environment. Most likely, it's a problem of SplitView.
If the livevisualtree provides correct information, after IsPaneOpen = true, the Width of the first Grid inside SplitView should be a binding, and its value is 320 but actual value is still 40.
From livevisualtree, NavigationView already provides correct settings for SplitView and its children.
Because SplitView itself has 40 for the first column, all its children are cut if they are outside of 40.

![image](https://user-images.githubusercontent.com/6290692/63298393-33afa280-c288-11e9-9cbb-560a16f4114f.png)

**Comment by chingucoding** [comment]
I tried the repro project with the latest WinUI prerelease, and in the around 50 tries, everytime, the pane rendered correctly. Maybe this is something fixed with the latest Windows builds or changes made to the NavigationView? Can this issue be closed then? @StephenLPeters FYI.
