### ISSUE TITLE
TabView collapses to minimum size when all tabs removed

### ISSUE THREAD

**Issue by stmoy** [microsoft/microsoft-ui-xaml#1205]
**Describe the bug**

When I close all of the tabs from the TabView, then try to add some, the tab strip doesn’t grow to make space for the tabs. (This only repros when I remove all of the tabs.) 

**Initial state ✔**
 
![image](https://user-images.githubusercontent.com/25991996/63629201-9a54f900-c5c5-11e9-84ae-067cb784c88b.png)

**Removed all the tabs – the TabView collapses, but should it? ❓**
 
![image](https://user-images.githubusercontent.com/25991996/63629206-a8a31500-c5c5-11e9-8b9f-88c43b87c940.png)

**Add a tab (space is not made for the new tab ☹) ❌** 

![image](https://user-images.githubusercontent.com/25991996/63629218-b789c780-c5c5-11e9-940d-498b56b04f00.png)

Notice that I’m hovering over something in this image. I don’t think it’s a tab since it has reveal, but I honestly don’t know what it is. A ListViewItem? 

**Steps to reproduce the bug**

1. Build and compile the Xaml Controls Gallery from the below links
1. Open the TabView page
1. In the first sample, close all the tabs
1. Attempt to add a tab with the + button

https://github.com/microsoft/Xaml-Controls-Gallery/blob/w/stmoy/TabViewPreview/XamlControlsGallery/ControlPages/TabViewPage.xaml.cs 

https://github.com/microsoft/Xaml-Controls-Gallery/blob/w/stmoy/TabViewPreview/XamlControlsGallery/ControlPages/TabViewPage.xaml 

**Expected behavior**

TabView makes space for recently added Tabs (and also doesn't collapse down to nothingness when no Tabs are in the TabView)

**Screenshots**

Above.

**Version Info**

NuGet package version: 

MUX 2.2.190820003

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |    |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by kmahone** [comment]
I tried out the latest build of MUX with the Xaml Control Gallery. I can confirm that this bug is partially fixed.

When you close all tabs, the TabView still shrinks to a diminutive size:
![tab1](https://user-images.githubusercontent.com/41657372/64048270-1f8c6080-cb26-11e9-9dfa-bc8a91210360.png)

 

But unlike before, you can recover from this by adding a new tab:
 
![tab2](https://user-images.githubusercontent.com/41657372/64048321-3af76b80-cb26-11e9-8b92-0640dd074224.png)


Notice that the TabView strip is not stretching horizontally. Once you select a tab, this gets resolved:
 
![tab3](https://user-images.githubusercontent.com/41657372/64048324-3df25c00-cb26-11e9-8c12-9b671949845a.png)



So, there is still a bug here, but it is not nearly as bad as before. Previously once you got into the squashed state the TabView was useless.


Note: I was only ever able to reproduce this bug in the Xaml Controls Gallery. It does not repro in the MUXControlsTestApp, or in an ad hoc app I tried. I don’t know what are the specific conditions that are required to hit this bug.

**Comment by jevansaks** [comment]
Recent fixes made this better so not blocking WinUI 2.2 release, but we'll try to get it in as an update.

**Comment by chingucoding** [comment]
Since apparently the bar stretches when a tab gets focused, maybe a reasonable fix would be automatically put the focus on the newly created tab. 
This kind of behavior, that a newly created tab has the focus, is quite dominant in other programs e.g. Edge and Chrome so I think it would be good for the TabView to do the same.

**Comment by kmahone** [comment]
@stmoy, I took a look at this. This is actually By Design. In Xaml Controls Gallery, the TabView is displayed in a ContentPresenter with HorizontalContentAlignment="Left", which means that it will try to render to fit aligned to the left.

Normally, the TabView still renders "large", since it is displaying tab content and so needs to grow to accommodate.  With no tabs, no tab is selected and so there is no tab content and so the TabView renders as a small vertical sliver.

The fix is to set HorizontalContentAlignment="Stretch" on the ContentPresenter - specifically I am referring to the '<local:ControlExample >' element in TabViewPage.xaml.
