### ISSUE TITLE
XamlUICommand does not notifycanexecutechanged when underlying Command raisecanexecutedchanged

### ISSUE THREAD

**Issue by MarkIvanDev** [microsoft/microsoft-ui-xaml#1244]
**Describe the bug**
XamlUICommand does not notifycanexecutechanged when underlying Command property raisecanexecutedchanged. 

**Steps to reproduce the bug**
1. Create an ICommand property in code behind or in a View Model. 
2. Add some CanExecute logic by returning the value of a property of type bool (Make sure that the property notifies of property changes)
3. Bind it to the XamlUICommand's Command property in XAML.
4. Use the XamlUICommand as a command to a button.
5. Change the bool property from to true to false, and raisecanexecutechanged.
6. The button is not enabled or disabled

**Expected behavior**
When the underlying Command raises the CanExecuteChanged, the XamlUICommand must also raise NotifyCanExecuteChanged,

**Screenshots**

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        | Yes   |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by chinwobble** [comment]
+1 this I was relying this behaviour too

**Comment by gwalschlager** [comment]
This is still a problem! Please fix this. Without a fix, it renders commanding useless for this case.

**Comment by seven-mile** [comment]
@StephenLPeters Hello! We hope this issue to keep open. Without this default subscription behavior, we have to workaround by raising the event from ViewModel. It means we have to hold a reference of Xaml objects in my ViewModel, which breaks the MVVM design completely.
This doesn't seem like a complex change, with no compatibility issue.

**Comment by cdaylin** [comment]
Why has this issue been closed without the defect having been fixed?  XamlUICommand is effectively useless due to this defect.

This defect caused me to waste many hours.  I followed Microsoft's advice and examples, only to find that XamlUICommand does not work correctly.  This has likely cost a great many hours of lost development time for the community as a whole.  Please spend a few hours to fix your defect.

Of course, there is another design problem with XamlUICommand that limits it's usefulness as well.  Keyboard accelerators assigned to a XamlUICommand object that is shared among multiple locations in the UI cannot be scoped, because an accelerator instance can only have a single scope defined.  This means that a XamlUICommand defined as a static resource cannot actually be used in multiple locations if scoped accelerators are needed.
