### ISSUE TITLE
Question: Should CornerRadius set on control, affect subcontrols?

### ISSUE THREAD

**Issue by mdtauk** [microsoft/microsoft-ui-xaml#1301]
Should controls like the Colour Picker, as well as ListView/GridView/TreeView - apply the control's CornerRadius to the ComboBoxes, TextBoxes, CheckBoxes contained within them?

![image](https://user-images.githubusercontent.com/7389110/64632560-33bb4200-d3f1-11e9-9296-4ee5fa47181b.png)

![image](https://user-images.githubusercontent.com/7389110/64632774-aa583f80-d3f1-11e9-9970-fc7cb24a5497.png)

![image](https://user-images.githubusercontent.com/7389110/64632717-8b59ad80-d3f1-11e9-8cb5-f46fe539ba3a.png)

**Comment by jevansaks** [comment]
I don't know ... should it? I don't think there's always a right answer. If it clearly should apply (like in the case of the nested buddy buttons in TextBox that Rudy just fixed) then it's just a bug. But in other cases like ColorPicker i don't think it's so clear. 

We would like to make our styling story better in this department and enable targeting "parts" of a complex control's tree more easy so that there isn't as much of a dilemma about which things should have CornerRadius/Border properties applied to them.

**Comment by mdtauk** [comment]
The Colour Spectrum box, and the Selected Color column, both adjust their corner radius, but the controls below use the defaults.
