### ISSUE TITLE
Question: Prepare for WinUI desktop

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#1365]
I understand that following three use cases would be supported by WinUI 3

1. WinUI for UWP
2. WinUI for Win 32 (WinUI desktop)
3. WinUI for WPF using XAML Island

@marb2000  I would like to understand if WinUI desktop would be available when the WinUI 3 preview is made available later this year. 

Also what would be the best approach to take when we are just starting developing a new LOB app, which is to be released, say 1 year from now? Should be start with a WinUI for WPF with XAML Island? or Plain WPF? UWP is not an option for us, as we need to have plugins which are implemented through  [AssemblyLoadContext](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext?view=netcore-3.0) in .Net Core 3.0 (+ many other reasons).

**Comment by marb2000** [comment]
**Q: Would WinUI desktop be available when the WinUI 3 preview is made available later this year?**

**A:** As of today's plan, it won't be available for the first WinUI preview. It takes more of time to get WinUI 3 working on Desktop app model than UWP app model.

**Q: What would be the best approach to take when we are just starting developing a new LOB app, which is to be released, say one year from now?**

**A:** I'm assuming that you want to use .NET, XAML language, and targeting Windows 10,  right? In this case, our recommendation is always to go with .NET Core 3. Then you should choose between WPF and WinUI Desktop (given you discarded UWP per limitations)
WPF is a robust and mature framework with well-known advantages and limitations. If you are OK with the limitations and you and your team know how to create WPF apps, it is reasonable to use WPF. If you require some specific and not too much WinUI 3 features, WinUI XAML Islands will help you. 

However, if your UI is going to be majority WinUI (and you want to take advantage of all the good things of WinUI framework), then you should think about using just WinUI in Desktop for .NET Core 3. It will be a .NET Core 3 app so what AssemblyLoadContext API and other .NET Core 3 API ones should be available too. 

Additionally, you have a one-year constraint. We are saying that WinUI 3 will happen next year, but, unfortunately, we can't commit a release date yet because the complexity of all the engineering work that making WinUI 3 (UWP and Desktop) requires. In the following weeks, we will get more clarity on it.
