### ISSUE TITLE
Question: RootScrollViewer and Focus behavior

### ISSUE THREAD

**Issue by hooligan495** [microsoft/microsoft-ui-xaml#1380]
I am not sure this is the right forum to ask my question but I'm hoping if it isn't you could point me in a direction.  

I've a Windows 10 UWP application where I am using Focus navigation and mouse interaction on UWP pages with some UserControls we are creating (and using standard controls too).  

With Focus Navigation we are using the keyboard to move to different controls on a page.  And if I switch to using the mouse and click somewhere (say in a border area of my control or another user control).  It appears that the RootScrollViewer gets the focus of the mouse.  I suspect some of our code got us in this weird state but once the RootScrollViewer has gotten this focus aspects of the page stop working until I hit "tab" to move the focus off this scroll viewer.  

Anyone have any thoughts on how I can prevent this from happening?   OR what a cause of this getting focus in the RootScrollViewer could be?  I'm not even sure I should be programmatically trying to hook into any of the rootscrollviewer events as I can find no documentation on this internal class. 

I think it's something to do with how I implemented my User Controls so I'm tracking through that.   But this RootScrollViewer getting the focus is odd.     These pages make use of a User control that I use as a default page template (with ContentPresenters) that are essentially grids with layouts that I reuse across multple pages to get the base look and feel.  And within the MainContent area we are adding more usercontrols.   In that whole process we have a flow of handling mouse and keyboard events that I think needs to be cleaned up...  so it's entirely possible we've munged some event routing.  I'll focus my bandwidth there.  

But if anyone knows more about the RootScrollViewer and can share that'd be great?  (I suspect its there for when you take the app and reduces it's size it will kick in.  But apparently we shouldn't programmatically interact with it?  

Thanks!

**Comment by jevansaks** [comment]
There's another issue (#597) discussing a similar problem just with vanilla ScrollViewer. The short answer, I believe, is that if ScrollViewer receives a mouse down then it sets focus to itself or the first focusable thing. You ought to be able to avoid this by making the app content have a background and thus receive the clicks instead of the RootScrollViewer.

To the other question, the purpose of the RootScrollViewer is to handle scrolling the app when the Touch keyboard comes up in case that the TextBox with focus isn't inside something which can scroll enough to bring that TextBox into view.
