### ISSUE TITLE
Discussion: Surface Duo - Return of the Android Bridge for Windows 10

### ISSUE THREAD

**Issue by mdtauk** [microsoft/microsoft-ui-xaml#1400]
# Discussion: Android Bridge for Windows 10

With Microsoft now confirmed to be cooking up it's own version of Android for this new Surface Duo device - can and will the Android Bridge arrive in Windows 10/10X proper?

The ability to download Android apps in the Microsoft Store would be very helpful for users, as well as tighter integration with the Your Phone experience, could be possible.

![image](https://user-images.githubusercontent.com/7389110/66078116-4ee52180-e559-11e9-9a3b-7ee4c12cdb91.png)

**Comment by ryandemopoulos** [comment]
Interesting idea; I'm not aware of any plans for this to be re-opened.  If it's something you think we should consider, Feedback Hub might be a good place to offer that idea.  I'll close the issue (since this isn't really a WinUI question), but feel free to continue commenting if folks want to riff on this idea.  :)
