### ISSUE TITLE
Packaging Project Build Failed

### ISSUE THREAD

**Issue by clurch** [microsoft/microsoft-ui-xaml#1408]
.NET Core Version: 3.0.0
Windows version: 1903 (10.0; Build 18362)
Does the bug reproduce also in WPF for .NET Framework 4.8?: Yes
Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? No
Problem description:
Upon building a .NETCore WPF project package, the Microsoft.Toolkit.Win32.UI.XamlHost.dll cannot be found. I don't believe this dll is used for the Microsoft.Toolkit.Wpf.UI packages.

Actual behavior:
MSB3030 Could not copy the file "...source\repos\ToastNotifcationTestingNetCore\ToastNotifcationTestingNetCore\bin\Debug\netcoreapp3.0\Microsoft.Toolkit.Win32.UI.XamlHost.dll" because it was not found. ToastNotificationTestingNetCore.Package C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\DesktopBridge\Microsoft.DesktopBridge.targets line 567

Expected behavior:
Package should build successfully.

Minimal repro:
Follow the instructions found in https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/modernize-wpf-tutorial-4 for "Add a notification" then perform https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/modernize-wpf-tutorial-5.

NOTE
This issue looks to have been resolved in MicrosoftDocs/windows-uwp#1811 about 3 months ago, however it may have resurfaced with v6.0.0-preview9.1 of Microsoft.Toolkit.Wpf.UI.Controls and Microsoft.Toolkit.Wpf.UI.XamlHost. I am sorry if I am reporting this issue to the incorrect place.

NuGet package version: 
 Microsoft.Toolkit.Wpf.UI.Controls v6.0.0-preview9.1
Microsoft.Toolkit.Wpf.UI.XamlHost v6.0.0-preview9.1

This issue occurred on a Desktop

**Comment by ocalvo** [comment]
I have created a sample repro [here](https://github.com/marb2000/XamlIslands/tree/WAPBuild/1903_Hands_On_Labs/Exercise01)

**Comment by clurch** [comment]
@ocalvo The link appears to be broken for your repro.

**Comment by thomasclaudiushuber** [comment]
@clurch I was able to reproduce this issue. I think @ocalvo accidentally pointed you to a branch of the repo that does not exist anymore. This is the link from the master branch that works: https://github.com/marb2000/XamlIslands/tree/master/1903_Hands_On_Labs/Exercise01

What you can see there is that a XAML application object is created. When you look at the section **Creating the XAML application object** you'll see that they reference there the *Microsoft.Toolkit.Win32.UI.XamlHost NuGet* package. And that XamlHost.dll from that package is what is missing in your output folder. So, you can follow these steps, and then you should be able to get rid of this error. 

@ocalvo @marb2000 I don't know if the XAML application object is required now for all scenarios with a packaging project. It looks like the previous behavior (from previous previews) of just adding a NuGet package and creating a Packaging Project is broken. Adding for example a simple MapControl to a clean WPF project, create a packaging project and run it is not possible without the XAML Application object. It leads to the behavior described here by @clurch. 

On the other side, if I use an app.manifest file in the WPF project instead of creating a separate application packaging project, it just works without that extra UWP project for the XamlApplication object. 

Now the question for this issue is: 
Is adding the separate UWP project with the XamlApplication object a necessary step today AND in the future? Then this issue can be closed, as it is the expected behavior. 

If it shouldn't be necessary to add the separate UWP project, this issue needs to be fixed.
