### ISSUE TITLE
Discussion: Scripting support in UWP

### ISSUE THREAD

**Issue by adrientetar** [microsoft/microsoft-ui-xaml#1421]
# Discussion: Scripting support in UWP

One of the main missing desktop apps feature in UWP currently is C# scripting/plugins support. Thus far UWP [cannot do](https://github.com/dotnet/roslyn/wiki/Scripting-API-Samples#supported-platforms) roslyn scripting because of app model limitations and use of AOT compilation.

On twitter @marb2000 said:

> Our current plan is that managed WinUI 3 apps uses .NET Core 3 instead of .NET Native at release time.

Does that mean UWP will be able to do roslyn scripting? Is scripting support a goal of UWP development team?

Other than C# itself, Python and Javascript are popular scripting languages. [pythonnet](https://github.com/pythonnet/pythonnet) looks like a great project, but I'm not sure it can run in the UWP sandbox.

There is the possibility of Javascript scripting using [the JsRT hosting APIs](https://github.com/microsoft/Chakra-Samples/tree/master/Chakra%20Samples/JSRT%20Universal%20Windows%20Apps%20Hosting%20Samples/C%23), by adding the code for that wrapper in your app, to use the Chakra js engine of Windows. Winrt namespaces can be projected in js, however this forces to use a different language for scripting.

## Why scripting?

Usually an app is a finite set of commands/actions made available by the dev to the app user, through buttons/dialogs/etc. However some complex desktop apps need to go beyond this simple model to reach full expressivity – for the user to automatize certain tasks, simply to program his own desired actions, or simply add his own commands to the existing ones in the application. Design tools often make use of scripting.

![image](https://user-images.githubusercontent.com/1250894/66565289-67a99480-eb62-11e9-9cf6-6a18938c2809.png)  
*Example of scripting in Blender*

Important capabilities:

- Execute arbitrary code with access to the app's data/internals
- Write new pieces of UI, packageable as plugins
- Add new parts to the app's UI at runtime

**Comment by kmgallahan** [comment]
> Write new pieces of UI, packageable as plugins

This scenario should be covered by UWP extensions, [see here](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/how-to-create-an-extension). As stated:

> In the Universal Windows Platform (UWP), app extensions provide functionality similar to what plug-ins, add-ins, and add-ons do on other platforms. Microsoft Edge extensions are UWP app extensions, for example. UWP app extensions were introduced in the Windows 10 Anniversary edition (version 1607, build 10.0.14393).

If the existing extension system doesn't meet your "packageable as plugin" needs, then you might want to specifically explain why they don't and how you'd want them to be different.

> Add new parts to the app's UI at runtime

I haven't experimented with extensions enough to know if loading new ones always requires a restart, so that is worth investigating.

You might also want to clarify if you mean loading new UI components as a result of scripts being created at runtime or not.

> Execute arbitrary code with access to the app's data/internals

Note: I'm not suggesting the extension system could handle this requirement.

**Comment by huoyaoyuan** [comment]
The managed world has been ready for scripting. There are **assembly hot load and unload**, **dynamic code generation**, and **scripting dialect of C#**.
Within current UWP application model, extensions can already provide assemblies in byte array, like providing js in string.

**Comment by dentistfrankchen** [comment]
You should really consider adding python support. Actually if you ask a python programmer to write c# code, it would be like hell... Because most python programmers just want to do some simple work instead of tedious programming...
Accomplishing this won't be too hard, since what you need to do is to expose some API in a dll file, and other programmers could call function in it. It would act like a wrapper for the base-level xaml. PLEASE do consider this.

**Comment by pbk0** [comment]
Looks like someone from Microsoft has reserved the name on PyPI .... https://pypi.org/project/winui/ .... so lads keep your hopes high :)
