### ISSUE TITLE
Setting AnimatedVisualPlayer to loop doesn't do anything if it's already playing

### ISSUE THREAD

**Issue by jaredhms** [microsoft/microsoft-ui-xaml#1501]
I'm implementing a version of ReactNative's LottieView for Windows.  The Play command can come through just before the prop update to set Loop to true.  This works properly on other platforms, but special care must be taken with AnimatedVisualPlayer to ensure that:

a) The animation starts to loop.

and 

b) The animation completed event does *not* fire for the short-lived animation that played before we transitioned to looping.

This should be handled internally by AnimatedVisualPlayer as this seems a bit fragile to have to handle in our code.  Fortunately, the gap between playing and updating the property is very small, so we're not likely to see a glitch.  However, it would be better for AnimatedVisualPlayer to jsut start looping if playing while loop is set.

        else if (propertyName == "loop")
        {
            const auto loop = propertyValue.asBool();
            const auto loopChanged = m_loop != loop;
            m_loop = loop;

            // The player doesn't automatically handle adding a loop while already playing
            // TODO: File a github issue on the player -- seems like this should happen automatically.
            if (player.IsPlaying() && loopChanged)
            {
                if (m_playOperation)
                {
                    m_playOperation.Cancel();
                }

                if (m_loop)
                {
                    Play();
                }
            }
        }

...

    m_playOperation = player.PlayAsync(start, end, m_loop);
    m_playOperation.Completed([weakThis = std::weak_ptr<LottieAnimationView>(shared_from_this()), this](const auto& asyncOp, const winrt::AsyncStatus& status)
    {
        if (auto strongThis = weakThis.lock())
        {
            // Don't fire the completed event if we had to cancel the play operation due to 
            // a prop update.  For example; if we're playing and loop is set to true, we need to cancel/
            // restart the play without firing the completed event so the app code doesn't get confused.
            if (status != winrt::AsyncStatus::Canceled)
            {
                OnAnimationComplete();
            }
        }
    });

**Comment by simeoncran** [comment]
The work you're having to do to manage the state of the player is a reflection of the Windows architecture: the animations are being calculated and rendered in another process (DWM) using Windows.UI.Composition animations. Looping isn't something that can be changed on the fly - it requires a reconfiguration of the animation once it has been started.

Handling it the way you are seems reasonable, or you could do the looping yourself (when the animation finishes start it again as long as you're looping).

Is the Loop configuration request arriving significantly after the Play request (and by significant I mean that the thread has returned to the dispatcher between the Play and Loop requests)? If not, then glitching will not be an issue (because the request to play without looping will get replaced by the request to play with looping before the playing starts). The main problem seems to be having to handle the arbitrary order of events from ReactNative, right?

Does ReactNative have some sort of "current transaction finished" notification so that you could collect the set of requests for the current transaction, and apply them once you have all the info?

When you say that it's fragile, do you mean that there is some condition where the way you're handling it isn't correct, or that every place that ReactNative uses this will have to reimplement it, or something else? I'm wondering what a non-fragile implementation would look like. Is the right fix simply that we should provide and official ReactNative implementation?

**Comment by jaredhms** [comment]
By fragile, I mean that AnimatedVisualPlayer could more easily handle this 'gotcha' internally (even if that means replacing DWM commands) than it was for me to figure out the right pattern here.  An official ReactNative implementation is not currently possible due to the need to code gen the animations.

**Comment by simeoncran** [comment]
Is there an API that you would like added to AnimatedVisualPlayer that would satisfy this?

**Comment by jaredhms** [comment]
The API seems fine to me, but it would be great if updating the loop value would update the internal state even if that means kicking off a new set of composition calls _internally_.   

The out-of-order play call and property updates from the below code are by design in react native, yet the Android and iOS implementations handle this calling pattern without any issues.  

            <LottieView
                source={QUEUE_ANIMATION_SOURCE}
                imageAssetsFolder={'lottie/Provisioning'}
                loop={animationState === AnimationState.Loop}
                resizeMode="cover"
                autoPlay={false}
                hardwareAccelerationAndroid
                onAnimationFinish={() => {
                    Logger.debug(TAG, `Completed animation with state ${animationState}`);

                    if (animationState === AnimationState.Intro) {
                        Logger.debug(TAG, 'Playing looping animation');
                        setAnimationState(AnimationState.Loop);
                        currentAnimation.current!.play(LOOP_START_FRAME, LOOP_END_FRAME);
                    } else if (animationState === AnimationState.Outro) {
                        Logger.debug(TAG, 'Completing animation');
                        setAnimationState(AnimationState.Completed);
                    }
                }}
                ref={currentAnimation}
                onLayout={() => {
                    if (animationState === AnimationState.None && currentAnimation.current) {
                        Logger.debug(TAG, 'Playing intro animation');
                        setAnimationState(AnimationState.Intro);
                        currentAnimation.current!.play(INTRO_START_FRAME, INTRO_END_FRAME);
                    }
                }}
            />

It would be a bummer to have to resort to chaining loops myself since that's an advertised feature on the API.

If I run with my workaround, maybe we'll see glitches, and more than likely over time the internal API implementation could do a better job than I'm able to do from outside.
