### ISSUE TITLE
Question: Will WinUI 3.0 be buildable with Clang/LLVM (and CMake/Ninja)?

### ISSUE THREAD

**Issue by MarkIngramUK** [microsoft/microsoft-ui-xaml#1571]
[Assuming that WinUI 3.0 will be compilable from source, rather than relying on Nuget packages...]

Given CMake is a first class citizen in Visual Studio now, will it be a supported build system for WinUI 3.0? Also, for cross platform projects that use clang on other platforms (e.g. macOS) it is useful to use the same compiler on Windows to minimise (or compare) performance and compilation differences. Will WinUI 3.0 be compilable with clang & lld-link?

**Comment by kmahone** [comment]
When WinUI 3 goes open source, it will be compilable from source. It uses MSBuild and the msvc compiler to build. 

With regards to your questions about CMake and Clang. Are you asking if you will be able to build a WinUI 3 **app** using these tools? Or are you asking if you will be able to build the WinUI runtime itself from source using these tools?

When it comes to compiling a WinUI app in C++ with Clang; I expect it would be possible. C++/WinRT does not depend on any msvc specific features and can be compiled using any standards compliant C++ compiler. With regards to using CMake as the build environment; all of the Visual Studio templates that we ship are MSBuild based. We do not currently plan to ship any CMake-based templates. But there should be nothing that would fundamentally prevent someone from creating a CMake-based build process that produces a WinUI app. There would be a certain amount of work involved in this, for example the build process would need to invoke some of the sdk tools, such as the Xaml Compiler or midlrt to produce the required output. So it is not something that would be supported "out of the box", but it certainly seems feasible. We would welcome any community contributions in this area if this was seen as a useful scenario.

When it comes to compiling the WinUI platform itself: As mentioned, the platform is currently built with msvc. It is not currently possible to compile the WinUI platform using Clang, as not all of the code is fully standard compliant C++ code. There are a couple of places where we use msvc-specific features. However, we certainly would value getting the code into a more compliant state and this is another area that we would welcome any community contributions.

With regards to building the WinUI platform itself with CMake: we currently use MSBuild to define our build process. Though it is theoretically possible that CMake could be used instead, given that WinUI build process is a quite large and complex with many components involved, it would not be feasible without a very significant effort. We do not have any plans to move away from MSBuild.

Let me know if you have any further questions, or if you have any specific scenarios in mind.

**Comment by MarkIngramUK** [comment]
Hi @kmahone , I'm talking about the compilation of the actual WinUI library, not an app that uses WinUI. My plan is to compile WinUI from source, within our solution. Currently we have a `.sln` and a `CMakeLists.txt` which we maintain side-by-side. The app is developed and built using Visual Studio (via `.sln` file), but we also compile for performance tests and validation using CMake | clang | Ninja.

As you've mentioned in your reply, there are two parts to this question:

1) Can we compile the WinUI library with Clang - if not, can we submit PRs to enable this?
2) Can we write a `CMakeLists.txt` for WinUI - this doesn't have to be in the upstream repo (i.e. your repo) but I'd be interested to know about any steps that Visual Studio or VSIX plugins performs for the developer behind the scenes.

**Comment by kmahone** [comment]
>Can we compile the WinUI library with Clang - if not, can we submit PRs to enable this?

With the source code as it is today (and as it will be when it is make is OSS), it would not be possible to compile it with clang. The code is close to C++ standards conformance, but not entirely. For example there are cases where msvc will allow an implicit cast that is not standard. There are also a few places where we use msvc specific features such as [__super](https://docs.microsoft.com/en-us/cpp/cpp/super?view=vs-2019). These are just some issues that I know of off the top of my head. So these and any other issues would need to be resolved before it could be compilable in Clang. We have never tried to compile with Clang, but we have tried to compile using msvc with [/permissive-](https://docs.microsoft.com/en-us/cpp/build/reference/permissive-standards-conformance?view=vs-2019) set, which switches msvc to a more standards compliant mode. We don't yet compile successfully in permissive- mode. But we would accept any PRs that would help get the code base into a more standards compliant state.

>Can we write a CMakeLists.txt for WinUI - this doesn't have to be in the upstream repo (i.e. your repo) but I'd be interested to know about any steps that Visual Studio or VSIX plugins performs for the developer behind the scenes.

I expect it would be possible. However, it would not be a trivial task, as the WinUI build is quite complex. CMake would need to be able to invoke many of the sdk build tools (such as midlrt, the XamlCompiler, etc.). When WinUI 3 goes OSS, you will be able to examine the msbuild files and see what it is doing. Porting to CMake would be quite an involved task, but I can't think of a reason why it would not be possible. As for whether we would accept a PR into this repo that added the CMakeLists.txt files to build WinUI: there would have to be a discussion about that, but my guess is that we would likely not accept such a PR due to cost of keeping two build systems working and in sync.

I have a broader question for you: why do you want to compile WinUI from scratch using CMake instead of consuming the built binaries from the nuget package? Building WinUI from source as part of your app would dramatically increase the build time of your app and would introduce a significant amount of complexity to your build. Is there a reason you would want to do that over just picking up the dll and winmd from the nupkg?

**Comment by MarkIngramUK** [comment]
A couple of reasons why I'd like to build WinUI from source and preferably with CMake (and Ninja):

1) We're a cross-platform application. CMake is the cross-platform build system.
2) All third party libraries are built from source as part of our application build (we have approx. 35 third party libraries built this way).
3) Building from source avoids potential pitfalls such as C++ ABI breaks, missing dependencies, etc
4) If WinUI and C++/WinRT are "just" C++ with no extensions (i.e. not C++/CLI) then it should be compilable by any compliant compiler.
5) We can't use the LLVM toolset within Visual Studio, as Clang doesn't obey the `/MP` flag (parallelism should be provided by the build system, not the compiler). Release builds take 2 hours 45 minutes with 28 cores, so we can't entertain the idea of dropping down to a single core build.

Slight side question, but can WinUI be included in [vcpkg ](https://github.com/Microsoft/vcpkg) with this approach?

**Comment by kmahone** [comment]
Thanks for the info. I should also point out that WinUI itself has some dependencies on nuget packages. So even if you were compiling WinUI from source, there would still be a requirement to pull down some packages.

We do not currently have any plans to publish WinUI as a vcpkg since nuget will be our primary distribution method. But this might be something that could be driven by the community.

**Comment by twhall-umich** [comment]
@kmahone  +1 for making MIDL, MDMERGE, CPPWINRT, and the "Xaml Compiler" usable from CMake.  This is something I have been struggling with for some time: there is very little documentation for using any of those tools directly in a command-line, batch file, or CMake script.  I think I've finally got a handle on most of them, except for the "Xaml Compiler" -- which I have not been able even to locate, let alone to use from CMake.  Do I have to resort to having a "standard" Visual Studio solution setup to generate the *.xaml.g.{cpp,h} files?

**Comment by kmahone** [comment]
> @kmahone +1 for making MIDL, MDMERGE, CPPWINRT, and the "Xaml Compiler" usable from CMake. This is something I have been struggling with for some time: there is very little documentation for using any of those tools directly in a command-line, batch file, or CMake script. I think I've finally got a handle on most of them, except for the "Xaml Compiler" -- which I have not been able even to locate, let alone to use from CMake. Do I have to resort to having a "standard" Visual Studio solution setup to generate the *.xaml.g.{cpp,h} files?

@alwu-msft is it possible to invoke the Xaml Compiler directly outside of MSBuild? Or is this something that only MSBuild is able to do?

**Comment by alwu-msft** [comment]
@RealTommyKlein created a CLI version of XamlCompiler that is included in the Nuget package. We ourselves don't use it yet, though.
