### ISSUE TITLE
Microsoft.UI.Xaml nuget package requires TargetPlatformVersion >= 10.0.17763.0 (current project is 17134)

### ISSUE THREAD

**Issue by jbakholt** [Microsoft/microsoft-ui-xaml#16]
**Describe the bug**
Creating a new barebone uwp app yields the error

**Steps to reproduce the bug**

In visual studio 2017
1. New project
2. Select UWP
3. Select Blank App
4. Manage nugets
5. Add Latest stable Microsoft.Ui.Xaml 
6. Build the solution

**Expected behavior**
It should build

**Screenshots**

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.0.181018003

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [ ] October 2018 Update (17763)
- [X ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [ X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by jevansaks** [comment]
This is intentional behavior. We need to enforce that consuming apps are running in the right compatibility mode when running on the latest OS. Note that your TargetPlatformVersion can be 17763 but you can keep your Minimum version the same. 

If retargeting is a problem for you, we'd like to understand why. 

There is an escape hatch, you can set the following in your project:

```xml
<SkipMicrosoftUIXamlCheckTargetPlatformVersion>true</SkipMicrosoftUIXamlCheckTargetPlatformVersion>
```

But you may run in to bugs due to running in older compatibility modes in newer versions of Windows.

**Comment by jbakholt** [comment]
I'm not sure we're on the same page. Compatible OS'es:

Windows Insider Preview (17135+)
April 2018 Update (17134)
Fall Creators Update (16299)
Creators Update (15063)
Anniversary Update (14393)


My installed OS version is 17134 so I can't set the Target to 17763 unless there's a way to update the SDK some way?

**Comment by jevansaks** [comment]
You can install it via the Visual Studio Installer (it's in the Individual Components list) or you can use the standalone installer. https://developer.microsoft.com/en-US/windows/downloads/windows-10-sdk has more details.

**Comment by jbakholt** [comment]
So the "Supported OS versions" is somewhat outdated I guess. Thanks anyway.

**Comment by jevansaks** [comment]
You're saying that it should say 17763? Yes we should probably list the fall creator's update. I'll fix it, thanks!
