### ISSUE TITLE
New ProgressBar doesn't always show the right width

### ISSUE THREAD

**Issue by YuliKl** [microsoft/microsoft-ui-xaml#1621]
**Describe the bug**

Under certain circumstances, the new ProgressBar disappears, presumably because its width goes to 0.

**Steps to reproduce the bug**

```Xaml
        <Grid Margin="24">
            <Grid.ColumnDefinitions>
                <ColumnDefinition/>
                <ColumnDefinition/>
            </Grid.ColumnDefinitions>
            <StackPanel Orientation="Horizontal">
                <TextBlock>WUX ProgressBar</TextBlock>
                <ProgressBar IsIndeterminate="True"/>
            </StackPanel>
            <StackPanel Grid.Column="1" Orientation="Horizontal">
                <TextBlock>MUX ProgressBar</TextBlock>
                <muxc:ProgressBar IsIndeterminate="True"/>
            </StackPanel>
        </Grid>
```

**Expected behavior**

Both ProgressBar controls are visible on screen.

**Screenshots**

![ProgressBarWidth](https://user-images.githubusercontent.com/13142665/68980771-46b60e00-07b6-11ea-8c45-f08600294fe2.gif)

**Version Info**

NuGet package version: 

2.3.191107001-prerelease

**Additional context**

The problem does not repro in other layout permutations, e.g. when the StackPanels have vertical orientation or when the ProgressBars are placed in the Grid directly.

**Comment by karenbtlai** [comment]
@YuliKl Turns out this is because the `ProgressBar` in WUX has an extra `StackPanel` in the XAML that gives it a minimum width from the `EllipseOffset` template settings property. 

So, if `IsIndeterminate` starts out as `false`, the **WUX ProgressBar** has 0 width as well and only appears when `IsIndeterminate` switches to `true`. It also stays at that minimum width when switched back to `false` (rather than disappearing / width going back to 0). 

Personally, I think this is a bug from WUX so the MUX progressbar should be left as is. Alternatively, I can give it a default width rather than it being `auto` when unspecified.

**Comment by YuliKl** [comment]
Agreed that this sounds like a bug in WUX, so closing this issue.
