### ISSUE TITLE
AutoSuggestBox sometimes gets focus when setting the Text property

### ISSUE THREAD

**Issue by zhuxb711** [microsoft/microsoft-ui-xaml#1641]
I found that when setting the Text property of AutoSuggestBox, it will occasionally cause the AutoSuggestBox to get the focus.

I only set the Text property of the AutoSuggestBox without setting any focus.

Like this:

![bug](https://user-images.githubusercontent.com/42038175/69130637-cd872580-0aeb-11ea-8825-ef46e7b52f19.gif)

OS Version: Win10 1909  18363.476
Microsoft.UI.XAML Version:  2.2.190917002

**Comment by jevansaks** [comment]
@zhuxb711 are you sure it's because the Text property is changing? We also notice in your video that the back button is getting clicked on and then disabled. It seems likely that clicking the back button sets focus to it and then the button gets disabled so XAML tries to find another focusable element, which might be the AutoSuggestBox.

Can you provide a standalone repro that demonstrates this problem?

**Comment by zhuxb711** [comment]
@jevansaks you are right. XAML will try to find another element. This problem disappears when I set the property "AllowFocusWhenDisabled" of the back button to "True"

**Comment by jevansaks** [comment]
Well, thanks for including a video! It helped a lot. :)
