### ISSUE TITLE
XAML Ribbon

### ISSUE THREAD

**Issue by adambarlow** [microsoft/microsoft-ui-xaml#168]
# Proposal: XAML Ribbon

![image](https://user-images.githubusercontent.com/16247808/50939538-20a33d00-1432-11e9-8102-384cc60ee932.png)

## Summary

**tl:dr;** Provide a Ribbon control for XAML apps which utilizes recent advancements in XAML commanding infrastructure, which is simple to implement and simple to interact with.

Since the release of the ribbon in Microsoft Office products in 2007 it has been a successful and frequently imitated commanding paradigm. It's success is demonstrated in the many implementations in frameworks on various platforms, as well as the ongoing requests for it's inclusion in WinUI.

This proposal details the creation of a simplified single-row Ribbon control, which can natively host XAML controls with great styling out of the box. This ribbon control will be familiar to those who have worked with the commandbar control and will allow for apps with more advanced commanding capabilities than are currently possible with XAML.

## Rationale

Implementing a XAML Ribbon will provide the following for the community:
1. Allow for the creation of apps that scale to have offer many commands to users (e.g sophisticated apps with more commands than comfortably fit in, say, a current XAML commandbar)
2. Provide users with commanding UX which is familiar, usable, and coherent with what they see across other apps on Windows (e.g. Microsoft Office)
3. Provide a commanding surface that complements our existing suite of XAML commanding assets (e.g. button, ToggleButton, SplitButton, XamlUICommand, StandardUICommand, CommandBarFlyout, CommandBar, Menubar, etc.)

### Terminology
* **_Ribbon_**  A set of toolbars that are grouped by tabs
* **_QAT_**  "Quick Access Toolbar" a small group of commands in the Ribbon which always stays around no matter which tab currently has focus
* **_Contextual Tab_**  A tab of commands representing actions that are available only because of the current app context
* **_File Menu_** A section of the Ribbon which contains commonly used commands that refer to the document in general or the app in general. Commonly used for, "open, save, close, etc."
* **_Chunk_** A sub-section of a given tab. These can be named and are separated by vertical separators
* **_Overflow_** An area which contains commands that do not fit in the currently visible ribbon tab

## Functional Requirements

| # | Feature |  Priority | Wave
|:-:|:--|-|:-:|
| 1 | Basic Ribbon tabbing experience (e.g. a tabbed set of command bars) | Must | 0
| 2 | Animation when switching tabs | Should | 1
| 3 | Contextual tabbing support | Should | 1
| 4 | Support for overflow of items (one per tab) | Must | 1
|4.1| Ability for the end-user to add and remove items from the overflow | Could | 2
|4.2| Split or dropdown buttons in the overflow have cascading menus | Should | 1
|4.3| Overflow area organized by the ‘chunk’ commands came from | Could | 2
| 5 | Supports resize behavior (e.g. losing labels, dropping commands into the overflow for each tab on window resize | Should | 1
|5.1| Support for mandatory text labels | Should | 1
|6| Optional built-in menu for ‘File Menu' (a contextflyout hosted in the ribbon for commands like Save and Open) | Should | 1
|7| Support for a QAT menu for frequently used commands | Should | 1
|7.1| Ability for end-users to add / remove items from the QAT | Could | 2
| 8 | Able to host a set of commonly used controls in the control without the need to style them (drop in support) <br/> List: <br/> - Button<br/> - Split Button<br/> - DropDown Button <br/> - Combo-box <br/> - Toggle Button| Should | 1
| 9 | Ability to host arbitrary XAML (developer would not get styling for free) | Should | 1
|10| Supports icon only commands | Should | 1
|11| Integrates with XamlUICommand registry (when developed) | Could | 1
|12| Built-in search bar across XamlUICommand registry | Could | 2

## Open Questions

* What is the object model for Ribbon (is it multiple command bars in a tabbing control? QAT as a separate commandbar, file menu as a MenuFlyout?)
* How do we achieve the drop in styling? (is it an interface, like IRibbonStylable that Button, DropDownButton, etc. implement?)

**Comment by mdtauk** [comment]
The Ribbon control was mentioned at Build, as something coming to XAML in 2019.  Of course the data validation for text fields was delayed, so who knows if any work has begun on it.  
![image](https://user-images.githubusercontent.com/7389110/50945061-eb770900-148a-11e9-98b7-3e0a2080daee.png)

Office UWP apps would be a good guide to implementing it - in fact if the Office UWP team were to commit their work, it would be something to build off.

However the Ribbon shows up in UWP, it needs to be consistent from app to app. Implement UICommands as with CommandBarFlyouts and ApplicationBars. Be responsive for device type, and window size. And perhaps some thought about how to integrate visually with an extended Title Bar and the Sets Tab.

**Comment by adambarlow** [comment]
@mdtauk 
Yes, we mentioned it at Build and continue to move the conversation forward, which includes this feature proposal.

I agree that we will want to ensure it's consistent app to app and that it is responsive to screen size and all input modalities. I am working closely with Office and intend for the designs to align as much as possible.

So i am sure, what are you referring to specifically when you say extended Title Bar and the Sets tab?

**Comment by mdtauk** [comment]
> @mdtauk
> Yes, we mentioned it at Build and continue to move the conversation forward, which includes this feature proposal...

> ...So i am sure, what are you referring to specifically when you say extended Title Bar and the Sets tab?

I hadn't realised this was an official proposal, as in you are someone at Microsoft beginning the process, and just wanted to ensure there was not cross purposes, like a third party proposing a Ribbon, whilst an official one was being made.  No offence intended. :)

The Ribbon usually is set to the top of the window in which it is placed.  Many apps extend their app into the TitleBar area to give a cleaner UI and use Acrylic.  And then there is Sets which will someday replace the default TitleBar experience in UWP apps.

The Windows 7 and right back to the original implementation of the Ribbon UI, custom drew the Titlebar for the window they were in, but those Windows Vista/7 Ribbons need not dictate the new implementation of it - and UWP apps have different ways of handling the window chrome.

When developing a design for the UWP Ribbon, and devising how it is recommended for use in an App's UI - the fluent team should consider how it will look and work in both of those scenarios (extended title bar and within the tab used by Sets), as well as while using the current default TitleBar, and a coloured TitleBar.

Rather than just designing the control in isolation, from how it fits in with the rest of the App UI, Window Chrome, and the OS Shells.

**Comment by adambarlow** [comment]
@mdtauk, don't worry, absolutely no offense taken. Thanks for the clarifications and the explanation. I agree completely and I'll work on a way to ensure this goal is included in the proposal as we continue to flesh it out in more detail.

**Comment by mdtauk** [comment]
For what it is worth, here are my initial thoughts on how you would integrate the Ribbon with the various combinations of TitleBars you would get.

![uwp ribbon initial ideas](https://user-images.githubusercontent.com/7389110/51001760-f54f4980-1528-11e9-8c79-4fa79d3bc096.png)

If these were to be considered, the Tab Bar, and the Tool Bar would each need their own Background Brush property, which would allow both to use the same colour/acrylic - or different ones.

**Comment by contextfree** [comment]
Win32 Office ribbon (including the single-line version in Outlook) also supports browsing through tabs using the mouse scroll wheel. This is something I miss in the OneNote UWP ribbon, which doesn't support it; it somewhat replicates the browsability of traditional menu bars, where you can hold the mouse conveniently "scrub" through the menus to see all the commands available. If it were expanded to also support horizontal scrolling with two-finger touchpad or swiping with touch, it would also be more consistent with the Pivot model, which the ribbon now resembles visually with its current design.

**Comment by contextfree** [comment]
Collapsed-mode ribbon (where the tab contents are hidden by default and appear transiently on demand on click) is another aspect of most of the various existing ribbon implementations not explicitly called out in the requirements. UWP OneNote, Win32 Office (including Outlook's one-line version), Windows ribbon all support some form of this (with various ways of toggling it - double-click on a tab, expand/collapse button, dropdown menu in the title bar). 

It does work differently in UWP OneNote than in the Win32 implementations though - instead of a persistent mode, it's just a way to temporarily collapse an existing tab by tapping/clicking on it again. While this isn't as important with the single-line ribbon as it was with the full-height version, I still have found it handy to collapse sometimes while using OneNote on smaller screen sizes.

**Comment by mdtauk** [comment]
Collapsed mode would make a lot of sense, and the NavigationView / SplitView control does this already for the sidebar when in collapsed and overlay modes.

There could be a property like **DisplayMode** for the Ribbon.  With options like **Expanded, Minimal, Collapsed** and when it is set to collapsed, only the tabs are displayed permanently, and the toolbar appears when an item is pressed, with a light dismiss interaction.

I would like to suggest that if it is set to collapsed or minimal - that a chevron be added to the right of the tabs, to toggle it into view.

![uwp ribbon collapse](https://user-images.githubusercontent.com/7389110/51069411-940da000-1626-11e9-844e-3cd8325c2ec4.png)

**Comment by TiredTrident** [comment]
@adambarlow How easy will it be to try to invoke the ribbon animation/content changes, when the app context changes, rather than the tab? For example, what has been seen in Outlook wit the Email/Meetings/Contacts button that changes the ribbon contents but not the tab.

**Comment by adambarlow** [comment]
When you say it changes the Ribbon contents, you mean the contents of the tabs themselves? I don't quite understand the scenario you are describing. What and example of the context switch you are describing?

**Comment by TiredTrident** [comment]
Sorry for the confusion @adambarlow . If I was looking to develop an application where the context referenced in the main window could change, would it possible to push an event to swap the contents of the Ribbon to match the new contents?

For example, when using Outlook and I switch from the email page to my calendar, the contents of the Home tab on Ribbon change swap with an animation.

**Comment by adambarlow** [comment]
Yes, good point. This certainly should be possible. I'll include this in the requirements section.

**Comment by mdtauk** [comment]
Good luck @adambarlow with making this control a reality.  Hopefully the Office team will be able to help, as well as getting the Windows teams on board, for that one day in the future re-write of File Explorer which may have need for it. 😆

**Comment by duke7553** [comment]
I'm no XAML expert, but we could base the Ribbon control off a custom TabView that contains a CommandBar as TabContent. Further, the selection indicator should have CornerRadius. I managed to recreate this control in my own app if anyone is interested.
![57668972-4787a080-75d7-11e9-961c-2063ef0fd53c](https://user-images.githubusercontent.com/20365014/57796426-40b37780-7716-11e9-9770-06cd189d86eb.png)

**Comment by duke7553** [comment]
Another "nice-to-have" is the ability to collapse the ribbon.

**Comment by duke7553** [comment]
@adambarlow Developers should also have access to guidelines regarding how to differentiate the Ribbon from the rest of the UI. For instance Z-depth, background colors, acrylic?

**Comment by YuliKl** [comment]
> @adambarlow Developers should also have access to guidelines regarding how to differentiate the Ribbon from the rest of the UI. For instance Z-depth, background colors, acrylic?

@duke7553, you're absolutely right. When this control is implemented (we're a little busy working on [WinUI 3.0](https://github.com/microsoft/microsoft-ui-xaml/issues/717) at the moment), it will incorporate the styles into its default template. Are you noting this need because you want to incorporate into your custom control?

**Comment by duke7553** [comment]
@YuliKl I was just trying to ensure the makeshift XAML ribbon I created was in-line with Fluent Design guidelines, so I'll be anxiously awaiting the official WinUI ribbon control.

**Comment by YuliKl** [comment]
@duke7553, while I don't yet know what colors the ribbon control will use, I'm fairly confident in saying that it won't use acrylic or shadow, at least not in its non-transient pinned state. [Shadow](https://docs.microsoft.com/en-us/windows/uwp/design/layout/depth-shadow#what-is-shadow) is designed to show elevation (which the ribbon doesn't have relative to the rest of its parent page), and [acrylic](https://docs.microsoft.com/en-us/windows/uwp/design/style/acrylic#when-to-use-acrylic) is for temporary UI surfaces.

**Comment by mdtauk** [comment]
The OneNote UWP app's Ribbon has a shadow and has an implied elevation.
![image](https://user-images.githubusercontent.com/7389110/59138352-7ef22e80-8984-11e9-985d-03af5bad1792.png)

By default it may not have an Acrylic brush as its background colour, but that would be possible by changing the brush to an Acrylic one.

Settings also uses Acrylic for it's sidebar, which aesthetically (along with extending into the Titlebar area) is quintessentially the Fluent design style which distinguishes Windows modern design.
![image](https://user-images.githubusercontent.com/7389110/59138476-3c7d2180-8985-11e9-9139-ceffbb8ec5e1.png)


Alarms & Clock uses Acrylic for its Top orientated NavigationView which extends into the Titlebar area.
![image](https://user-images.githubusercontent.com/7389110/59138452-1fe0e980-8985-11e9-8c92-14c0059fa981.png)


The Microsoft Store uses in-app Acrylic as you scroll down a page, so the contents can be seen through, which would equate with a collapsible Ribbon which you pull down on top of the view, rather than the static/pinned one which pushes the content down.
![image](https://user-images.githubusercontent.com/7389110/59138553-b1505b80-8985-11e9-9b51-8cf7bb3e4260.png)

**Comment by duke7553** [comment]
@mdtauk While the acrylic material looks really nice, it and other Fluent effects should really be used sparingly. Otherwise, it rapidly becomes either distracting or loses its “Wow” effect. While transient UI *deserves* acrylic, and context flyouts *deserve* Z-depth, pretty much everything else needs to be approached from a utilitarian point of view. I, for one, appreciate the revisions that have been made to the design system to reflect this understanding.

However, it definitely should (and likely will) be possible to theme these XAML controls with acrylic.

**Comment by shaheedmalik** [comment]
I'd like to see it tie in more with the other UWP designed apps with the back buttton, share button, profile, search, etc. Here's an example of those tied in.

![image](https://user-images.githubusercontent.com/51347950/59141181-582cfb80-8976-11e9-882d-623bf55590ed.png)

**Comment by mdtauk** [comment]
> I'd like to see it tie in more with the other UWP designed apps with the back buttton, share button, profile, search, etc. Here's an example of those tied in.
> 
> ![image](https://user-images.githubusercontent.com/51347950/59141181-582cfb80-8976-11e9-882d-623bf55590ed.png)

There could be a **BeforeRibbonTabs** area where a back button could be placed if needed.  And an **AfterRibbonTabs** area which is to the right hand side.  This area could have a chevron button to collapse the Ribbon?

**Comment by YuliKl** [comment]
> There could be a BeforeRibbonTabs area where a back button could be placed if needed. And an AfterRibbonTabs area which is to the right hand side. This area could have a chevron button to collapse the Ribbon?

When we get around to putting more thought into the Ribbon control, we will undoubtedly borrow concepts and APIs from the new Tabs control, #304.

**Comment by Poopooracoocoo** [comment]
I hope we also get a full ribbon. I hope we get some WinUI on Office and still keep the amazing customisability and functionality. 

Honestly, OneNote's new-ish undo and redo placement bugs me. It would be nice in the titlebar like other Office apps but that's a little off topic.

**Comment by shaheedmalik** [comment]
> I hope we also get a full ribbon. I hope we get some WinUI on Office and still keep the amazing customisability and functionality.
> Honestly, OneNote's new-ish undo and redo placement bugs me. It would be nice in the titlebar like other Office apps but that's a little off topic.

If anything, they need to move away from putting stuff in the title bar. Those title bar buttons were a mess for implementing into sets.

**Comment by mdtauk** [comment]
Sets is dead btw

**Comment by Poopooracoocoo** [comment]
reply to @shaheedmalik 

in addition to what @mdtauk said, OneNote already has things in the titlebar (name and navigation arrows)

**Comment by shaheedmalik** [comment]
OneNote's placement isn't consistent with the rest the apps.

**Comment by duke7553** [comment]
How about having a collapsed state for some ribbon items when the window is resized small enough before the overflow has to kick in? This can look something like this:
![image](https://user-images.githubusercontent.com/20365014/71495893-24d09200-281e-11ea-947d-0360432608dc.png)
Full Size:
![image](https://user-images.githubusercontent.com/20365014/71495901-2b5f0980-281e-11ea-9393-6e409bf2498a.png)

**Comment by sharpninja** [comment]
I think it's important to allow icons and buttons of differing sizes as it helps the user identify coomon and not-common functions in the same group.

**Comment by yoshiask** [comment]
I started creating a Ribbon control with the intent of it being added to the Windows Community Toolkit at [yoshiask/UWPRibbon](https://github.com/yoshiask/UWPRibbon). It's far from complete, and I could use a little help with it. It's written using C# and templated controls, so I don't know how easy or difficult it would be to add to WinUI.

**Comment by yoshiask** [comment]
Regarding current implementations of ribbons in UWP, I'd argue that they're not ribbons. They look, act, and feel just like a left-aligned CommandBar. Look at the ribbon in PowerPoint:
![image](https://user-images.githubusercontent.com/7549325/85379038-25599500-b4f0-11ea-8b1d-c0a209a052fa.png)

- It has the Quick Access Toolbar, which can be implemented as it's own control and optionally placed in the TopHeader of a RibbonControl.
- Office's ribbons have "Gallery" controls, which allow users to select options from a grid of thumbnails/icons. Some examples include the shape picker in the "Drawing" group, the "New Slide" dropdown, and the theme picker in the "Design" tab.
- Unlike most UWP ribbons, Office ribbons use Split and DropDownButtons a lot.
- Buttons in a ribbon can be a lot of different sizes, depending on the context. For example, the "Clipboard" group has one large primary button, and to the right of it are three smaller secondary buttons, stacked on top of each other. 
![image](https://user-images.githubusercontent.com/7549325/85381416-cba69a00-b4f2-11ea-9c0a-12a91279fd32.png)
These buttons can have labels, like they do in the "Slides" group, but it's not required.
- Groups group together related controls. A RibbonControl should probably only accept RibbonGroups as content, rather than allowing RibbonButtons and such directly. Groups can be divided into columns (the "Slides" group has two, the "Font" group has one, and the "Drawing" group has four). These columns can be divided into one big row for a full-size ribbon button (like the Paste button), two 1/3rd-height rows centered vertically (like the "Font" group), or three 1/3rd-height rows (like the "Editing" group).
- Office also has what I think is called "backstage". It's what shows up when you click on the "File" tab:  ![image](https://user-images.githubusercontent.com/7549325/85382527-e9283380-b4f3-11ea-9bb7-d5d760405321.png) While it would be cool for this to be a control on its own, it might be difficult to implement, since it covers all of the window's content. This should probably be left to developer to implement for their own app(s).

I tried to make this as comprehensive as possible, hopefully this serves as a guide to what features and paradigms user's are familiar with from the Office suite.

**Comment by yoshiask** [comment]
Might also be worth checking out the VSTO docs for the object model: https://docs.microsoft.com/en-us/visualstudio/vsto/ribbon-object-model-overview

**Comment by mdtauk** [comment]
> Regarding current implementations of ribbons in UWP, I'd argue that they're not ribbons. They look, act, and feel just like a left-aligned CommandBar. Look at the ribbon in PowerPoint:
> ![image](https://user-images.githubusercontent.com/7549325/85379038-25599500-b4f0-11ea-8b1d-c0a209a052fa.png)
> 
I think Office is considering it's ribbon design, as there is the full Win32 apps with its Ribbon, and the newer Simplified Ribbon.

Does a new Xaml Ribbon go for simple or dense - or does it do both, and it becomes a **RibbonType** property the developer chooses?

**Comment by yoshiask** [comment]
I think it should have both. If it's an option in Office, it should be available in the UWP version too. Same goes for the touch option.

**Comment by michael-hawker** [comment]
Hey All, I synced up with @yoshiask and the WinUI folks. @yoshiask's going to put together an initial version of this control for the Windows Community Toolkit.

Feel free to join the process and discussion over on our repo in [this issue](https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/3259). 

Thanks! 🦙❤

FYI @adambarlow @ryandemopoulos

**Comment by yoshiask** [comment]
@adambarlow In your proposal, you mention the "XamlUICommand registry". What is this? Is there any documentation of it (or what it's supposed to be)?

**Comment by adambarlow** [comment]
@yoshiask , the command registry was an idea that I had been exploring of having a component which would track the commands for the application. You would create an entry in the registry and then you could refer to the commands in the registry in other components like the ribbon or a menubar, etc. Essentially a way to have an app wide registry of UICommands which could be then bound to actions and exposed in various UI controls. It was never spec'd or built, IIRC.

**Comment by yoshiask** [comment]
Ah, okay. So is that something you'd still want in the initial version of the control, or can it wait at least until a full spec is written out?

**Comment by adambarlow** [comment]
There is not currently a plan to develop this control, so I don't think it should be a consideration for a V1 of a ribbon control.

**Comment by sharpninja** [comment]
> @yoshiask , the command registry was an idea that I had been exploring of having a component which would track the commands for the application. You would create an entry in the registry and then you could refer to the commands in the registry in other components like the ribbon or a menubar, etc. Essentially a way to have an app wide registry of UICommands which could be then bound to actions and exposed in various UI controls. It was never spec'd or built, IIRC.

I have written this multiple times in multiple ways in both WPF and UWP.  What I have found is that it requires dispatcher tracking to ensure that events are raised on the correct thread as the commands may be instantiated in different places.  Or, you could have a CommandFactory that creates all commands from a single thread, but also tracks the thread that requested the command so that the command's updated event is dispatched correctly.  Microsoft.Extensions.DependencyInjection would be perfect as the call to ServiceManager can be done from the GUI thread and thus the anonymous factory method just captures the Dispatcher and feeds it to the newly created command.  I actually have a request with WinUI to allow specifying a DI provider for instantiating objects declared in Xaml that would go right with this.

**Comment by shaheedmalik** [comment]
> There is not currently a plan to develop this control, so I don't think it should be a consideration for a V1 of a ribbon control.

If there is no plan to develop the control, what are all of the apps that use it are going to do?

**Comment by adambarlow** [comment]
@shaheedmalik , when you say use it, what are you referring to? I have edited my comment above, there is no current spec or plan for the command registry that we were discussing.

**Comment by yoshiask** [comment]
> If there is no plan to develop the control, what are all of the apps that use it are going to do?

To be clear, we're referring to the command registry, not the ribbon control

**Comment by ad1Dima** [comment]
Just noticed that WPF Ribbon was opensourced https://github.com/dotnet/wpf/tree/master/src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/Microsoft/Windows/Controls/Ribbon

**Comment by michael-hawker** [comment]
Thanks @ad1Dima, we've been aware. 🙂 I believe @yoshiask is looking at that occasionally as a reference, but WPF and UWP are pretty different and the UX designs for this pattern have changed recently, so we're not trying to port it directly.

**Comment by yoshiask** [comment]
@adambarlow Can you elaborate on what you meant by "Support for mandatory text labels" in the original proposal?

**Comment by trsht-tmyk** [comment]
> ![image](https://user-images.githubusercontent.com/16247808/50939538-20a33d00-1432-11e9-8102-384cc60ee932.png)

Hello,

How can I design it to look like this image?
I'm new to XAML / C # (WinUI ??).
I would like to know if possible.
I also want you to upload that code as OSS to your GitHub.

Thanks.

**Comment by adambarlow** [comment]
@yoshiask , it's been a long time since I wrote this. But I believe that I meant that the ribbon author should be able to force an item to display a text label if they want, instead of an icon.

@trsht-tmyk , this control doesn't yet exist, so sadly it's not available to open source or use.

**Comment by michael-hawker** [comment]
Thanks @adambarlow, @yoshiask I think you support the labels already as you're just using the standard CommandBarItem, eh?

@trsht-tmyk we have a PR for this open by Yoshi on the Windows Community Toolkit here: https://github.com/windows-toolkit/WindowsCommunityToolkit/pull/3556

You can find out about pulling a preview NuGet of it from our preview feeds here: https://github.com/windows-toolkit/WindowsCommunityToolkit/wiki/Preview-Packages - Would love any feedback you have on it as we continue development. We'll hopefully ship this as part of our upcoming 7.0 release.

**Comment by yoshiask** [comment]
> @yoshiask I think you support the labels already as you're just using the standard CommandBarItem, eh?

I don't, precisely because I'm using a standard CommandBar. The AppBarButton template(s) assume that you'll always have both a label _and_ an icon, not one or the other. As a result, if you only use a label or icon, the content of the button will be off-center.

I think I can fix this, but I would have to duplicate the template and switch it from hardcoded margins to ColumnSpacing

**Comment by ad1Dima** [comment]
@adambarlow why did you close this?

**Comment by adambarlow** [comment]
@ad1Dima mistaken button press. Thank you.

**Comment by trsht-tmyk** [comment]
@adambarlow thank you for your answer.
So did you mean that this image was created in photoshop or something?

 ![57668972-4787a080-75d7-11e9-961c-2063ef0fd53c](https://user-images.githubusercontent.com/20365014/57796426-40b37780-7716-11e9-9770-06cd189d86eb.png)


 ![uwp ribbon initial ideas](https://user-images.githubusercontent.com/7389110/51001760-f54f4980-1528-11e9-8c79-4fa79d3bc096.png)
Isn't this image also a uwp app?

**Comment by trsht-tmyk** [comment]
I'm thinking of creating software that extends word with uwp so that I can experience more experiences. I would like to make a ribbon that can be folded like a split view like onenote for windows 10.

The tabbedcommandbar is a good control to achieve this, but it doesn't allow you to display two lines without expanding, and it's far from being achieved using it.

Like this
![image](https://user-images.githubusercontent.com/62196528/99866847-dd05e680-2bf7-11eb-9ee8-ec75dd777490.png)

This image is powerpoint ribbon.
In this image, multiple controls are lined up vertically in the command bar. Since word app has many functions, we have to increase the number of controls. Therefore, I would like to add or turn on such a function.

**Comment by mdtauk** [comment]
@trsht-tmyk   Those images are mock-ups for how a UWP Ribbon could look, if it were to be made.

**Comment by trsht-tmyk** [comment]
Well...., what control is used to create the ribbon-like appearance of onenote for windows10? Also, does it mean that it is impossible to create with navigation view / split view etc.? I'm so so sorry I'm ignorant.

**Comment by mdtauk** [comment]
> Well...., what control is used to create the ribbon-like appearance of onenote for windows10? Also, does it mean that it is impossible to create with navigation view / split view etc.? I'm so so sorry I'm ignorant.

I think Office created a custom control for their UWP apps

**Comment by michael-hawker** [comment]
Wanted to call out that we have the [TabbedCommandBar](https://docs.microsoft.com/windows/communitytoolkit/controls/tabbedcommandbar) that we shipped in the 7.0.0 version of the Windows Community Toolkit.

**Comment by Shomnipotence** [comment]
unbeliveable that it is 2022, today , we still cannot have it

**Comment by adambarlow** [comment]
Thank you all for the feedback given. Please see the [https://docs.microsoft.com/windows/communitytoolkit/controls/tabbedcommandbar]TabbedCommandBar

**Comment by thatsofia** [comment]
I'll go out on a limb here and say that Paint in Windows 11 and OneNote do not use TabbedCommandBar from the Windows Community Toolkit.

**Comment by kmgallahan** [comment]
@adambarlow Should you inform @andrewleader so he can remove it from the [productboard page that links this issue](https://portal.productboard.com/winappsdk/1-windows-app-sdk/c/45-ribbon-control)?.

**Comment by adambarlow** [comment]
@kmgallahan, I don't think that is necessary. You'll notice on that page that this is marked as on the 'backlog', and this feature was previously marked in the freezer. I am not saying that this feature will never be built, just that it's not currently being developed. I just want to set expectations correctly.

**Comment by soroshsabz** [comment]
ITNOA

@adambarlow How to chose feature for your roadmap, this feature has many votes here and 31 votes on https://portal.productboard.com/winappsdk/1-windows-app-sdk/tabs/7-backlog

**Comment by mdtauk** [comment]
Someone should speak to the people who updated the Paint UI, because they have the basis for a XAML Ribbon control.  If it can be generalised to be flexible, and possibly add a Compact mode in a similar vein to the Office's Simplified Ribbon.

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/7389110/9e76d92c-9120-4fd0-82be-88de5850994b)

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/7389110/d5c96816-19b9-4b1a-8916-91810b7f03f7)
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/7389110/79c8abde-3bd7-49a7-a9d4-b42b16608624)
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/7389110/496317b9-7269-4de5-a6e9-c8a53a59fff5)

**Comment by michael-hawker** [comment]
The simplified ribbon is basically the `TabbedCommandBar` we have in the Toolkit. @Niels9001 not sure if this has come up with your discussions with the design team. Not sure what the current modern guidance is here? I think that's certainly why we went with looking at the more simplified experience over trying to create the larger ribbon experience, as I think the direction has been towards the simplified pattern, eh?

**Comment by niels9001** [comment]
> The simplified ribbon is basically the `TabbedCommandBar` we have in the Toolkit. @Niels9001 not sure if this has come up with your discussions with the design team. Not sure what the current modern guidance is here? I think that's certainly why we went with looking at the more simplified experience over trying to create the larger ribbon experience, as I think the direction has been towards the simplified pattern, eh?

Not specifically.. I agree that the simplified ribbon and the `TabbedCommandBar` have a lit in common. Would be worthwhile to port this over and making sure we adopt the latest W11 styling and make sure we come close to what is shown in Office/Paint!

**Comment by mdtauk** [comment]
If there was to be an option for a Full and Simple Ribbon, perhaps you could use a Tag on the "important" controls, and the others move to an overflow when in the Simple mode?

But there are two examples of Ribbon like experiences that can inform the design spec.
The Fluent 2 Web kit seems to be the best official Guidance available for Toolbar designs in Fluent.  I would imagine the Paint team did their own design spec, as would have Office.

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/7389110/fb83f938-25a5-49fc-a421-fc37c17bebd2)

**Comment by yoshiask** [comment]
The simple ribbon is way simpler than the full ribbon, I would implement them as completely separate controls.

**Comment by mdtauk** [comment]
> The simple ribbon is way simpler than the full ribbon, I would implement them as completely separate controls.

Two separate controls makes it harder for devs to offer the user the choice.  Its the same set of tools, just presented differently.

**Comment by mdtauk** [comment]
> I understand that, but again they are very different controls. For one, the full ribbon has button layout options that the simple one just doesn't support. The "simple ribbon" really is nothing more than a command bar in a navigation view. Making the simple and full ribbon the same control would require completely rebuilding the simple one as well.

But with a simple tag or property on the buttons, you could set which ones appear in the Simplified view, and the others move to the flyout.

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/7389110/4be8e9a1-ee51-4f3f-9192-a7597a039a57)

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/7389110/e6951951-4f78-49cf-8b8c-ef7e9e46572e)

**Comment by ShadowOfPripyat** [comment]
This type of control is very relevant in business applications, and should DEFINETLY be implemented.
Because most of microsoft office tools come with this type of interface, the user will be more familiar with Ribbon-type controls, and it looks very professional too and easy to implement it as a menu. Why in WinUI? WinUI is the only "framework" that comes with native windows theming.

For me and much other people would be a very solid reason to switch from WPF to WinUI.

**Comment by michael-hawker** [comment]
Not sure if we called it out clearly above, but the Windows Community Toolkit Labs has a .NET based Ribbon control available, details here: https://github.com/CommunityToolkit/Labs-Windows/issues/545
