### ISSUE TITLE
Nuget 2.3 fails to load Microsoft.UI.Xaml.dll due to mismatched vcruntime140_1_app.dll dependency

### ISSUE THREAD

**Issue by jaredhms** [microsoft/microsoft-ui-xaml#1728]
After upgrading to 2.3, none of the Microsoft.UI.Xaml classes are registered at runtime.  It looks like this is due to our inability to load vcruntime140_1_app.dll.  Our app is using a different version than the 2.3 Microsoft.UI.Xaml:

**Microsoft.UI.XAML:**
\WindowsApps\Microsoft.VCLibs.140.00_14.0.27810.0_x64__8wekyb3d8bbwe\vcruntime140_1_app.dl

**Our App :** 
\WindowsApps\Microsoft.VCLibs.140.00.Debug_14.0.27023.1_x64__8wekyb3d8bbwe\VCRUNTIME140_APP.dll

**Comment by jevansaks** [comment]
@kmahone @ranjeshj I can't think of a good way to address this. The problem is that we now need apps to depend on the newer VCLibs. This works if the app is built by VS 16.3 (maybe even 16.1 or .2) but older versions of VS like VS2017 won’t produce the right dependency.

Maybe we just emit an error if we detect this condition?

**Comment by jevansaks** [comment]
(This is because VS 16.3 made the new C++ exception handling on by default and that requires runtime support in VCLibs)
