### ISSUE TITLE
Narrator announces a % for indeterminate ProgressBar

### ISSUE THREAD

**Issue by YuliKl** [microsoft/microsoft-ui-xaml#1746]
**Describe the bug**

When Narrator focus is placed on an indeterminate ProgressBar, Narrator announces "0% progress bar", which is not distinguishable from an empty determinate ProgressBar. This announcement is the same for both WUX and the new MUX progress bars.

**Steps to reproduce the bug**

1. Go to the ProgressBar page in Xaml Controls Gallery
2. Turn on Narrator
3. Use items navigation to move focus to the indeterminate progress bar (Caps+Left)

**Expected behavior**

Narrator should announce "busy progress bar" (similar to ProgressRing's behavior)

**Comment by ranjeshj** [comment]
We tried fixing the automation peer to not provide the appropriate pattern but unfortunately Narrator caches the patterns and changing from determinate to indeterminate at runtime does not pick up the change in the patterns. This issue is tracked by [this ](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmicrosoft.visualstudio.com%2FOS%2F_workitems%2Fedit%2F25485166&data=02%7C01%7Cranjeshj%40microsoft.com%7C1604e48d46d24fb02bd008d7c4471425%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637193681874512696&sdata=Abr9te8LYW0tCJ0ibHOmv5jt794rubVrf8bUimLVX1E%3D&reserved=0)internal bug.

**Comment by karenbtlai** [comment]
Sounds good. Let's wait until the Narrator bug is fixed, then.

**Comment by karenbtlai** [comment]
@YuliKl Turns out the bug mentioned above is not the case, so the changes are merged into master. Currently, it announces "Busy 0% [ProgressControlName]" for Indeterminate, and "x% [ProgressControlName]" for Determinate.

**Comment by bpulliam** [comment]
Closing stale external bug. If you are still seeing this issue, please open a new issue with updated repro steps and logs/diagnostics.
