### ISSUE TITLE
Corner radius on scrollbar does not look right

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#1771]
**Describe the bug**

The scrollbar doesn't look okay

![image](https://user-images.githubusercontent.com/8557046/70962989-38bc1b80-20db-11ea-8e31-d492abc9d09d.png)

**Steps to reproduce the bug**

```xaml
    <Grid x:Name="ContentArea" Margin="{StaticResource SmallLeftMargin}">
        <muxc:ItemsRepeaterScrollHost>
            <ScrollViewer x:Name="ScrollViewer">
            ... 
            </ScrollViewer>
        </muxc:ItemsRepeaterScrollHost>
    </Grid>
```
**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/8557046/70962989-38bc1b80-20db-11ea-8e31-d492abc9d09d.png)

**Version Info**

NuGet package version: 
2.3.191127001-prerelease 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          | Yes |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by mdtauk** [comment]
It looks as if the Scroll indicator/thumb is stretching rather than resizing, and that is distorting the corner radii.

**Comment by StephenLPeters** [comment]
I think @mdtauk is correct, looks like we are stretching a small scrollbar. @kaiguo if you are not sure what this is supposed to look like you should reach out to @chigy for redlines.

**Comment by kaiguo** [comment]
Yes ScrollBar uses scale animation to stretch the thumb.

I think the issue here is that the rounded corners should go away (T rule) when thumb is expanded but it doesn't. I wasn't able to repro it locally (tried with animations on & off). @harvinders was the screenshot from a transient state or does the thumb looked like this when it fully expanded? Can you share a minimal repro app if it's the latter? Thanks!

**Comment by harvinders** [comment]
@kaiguo The screenshot is of the fully expanded thumb and not transition. As for repo, 

1. Create a blank UWP app using visual studio 2019
2. Set the target to 1903 and min target to 1803
3. Include the Microsoft.UI.Xaml prerelease package
4. Make the neccessary resource dictionary change in app.xaml
5. Add the following in MainView.xaml

```xaml
    <Grid x:Name="ContentArea" Margin="{StaticResource SmallLeftMargin}">
        <muxc:ItemsRepeaterScrollHost>
            <ScrollViewer x:Name="ScrollViewer">
               <StackPanel>
                    <Rectangle Height="200" />
                    <Rectangle Height="200" />
                    ...
                    <Rectangle Height="200" />
              </ScrollViewer>
        </muxc:ItemsRepeaterScrollHost>
    </Grid>
```
6. Run on 1803

**Comment by kaiguo** [comment]
Thanks harvinders!

I think 1803 is the problem. CornerRadius property was introduced in RS5, in 1803, we couldn't access the property in state setters so they were not set back 0 when thumb got expanded. @chigy I think we should disable rounded corners on lower os versions for Scroller in this case? Not having rounded corners in rest mode feels better than having weird rounded corners in expand mode.

**Comment by chigy** [comment]
@kaiguo , if CornerRadius was introduced in RS5 and this is the problem, will other controls have this problem or is it just the scrolller?

**Comment by kaiguo** [comment]
> @kaiguo Kai Guo FTE , if CornerRadius was introduced in RS5 and this is the problem, will other controls have this problem or is it just the scrolller?

Most other controls have static CornerRadius so they should be fine. The problem comes when we need to change CornerRadius values dynamically based on control state. So CommandBarFlyout has similar issues that makes it violates the T rule before RS5 (doesn't look as bad as Scroller in my opinion).

![WeChat Screenshot_20191218155527](https://user-images.githubusercontent.com/4424330/71133312-fcf28600-21ae-11ea-84f4-3f6d6f2cd7fa.png)



Scroller is unique because it has a scale transform applied to the thumb, which makes it looks particularly bad when CornerRadius are not set to 0 in expanded state :/

**Comment by chigy** [comment]
@kaiguo , I see thanks. Your suggestion makes sense to keep the CommandBarFlyout as is and fix scrollbar only.
