### ISSUE TITLE
Proposal:Adjust `NavigationView`' style to Xbox

### ISSUE THREAD

**Issue by hupo376787** [microsoft/microsoft-ui-xaml#1795]
# Proposal: Adjust `NavigationView`'s style to XBox

## Summary
`NavigationView`'style on PC seems comfortable, either item size and style, etc. But on Xbox, especially on a big screen, the `NavigationView` looks wired when set `PaneMode` to `Left`.

A good example is NetFlix, their menu differs from Xbox and PC.

What do you think, guys?

**Comment by ranjeshj** [comment]
@chigy NavigationView does change its appearance based on window size. This looks like a request to change the small window size behavior.

**Comment by chigy** [comment]
@hupo376787 , We currently purposefully do not create different style for Xbox. As Ranjesh indicates, we only make different behaviors on size.

What you are suggesting is righteous, but it opens up a bigger question whether Xbox should be a separate style or not which we currently are saying it is not and we have no plans to open up for this discussion at this time.

That said, if you are willing to suggest a holistic approach to Xbox including more than NavigationView, I'd be curious to hear your thoughts. And we do have an exception to this rule today with our [back button recommendation](https://docs.microsoft.com/en-us/windows/uwp/design/basics/navigation-history-and-backwards-navigation#optimizing-for-different-device-and-form-factors).

**Comment by hupo376787** [comment]
@chigy I'm using NetFlix and designing my app.
NetFlix has different menu style on Xbox and PC, if I use `NavigationView`, it has the same style with NetFlix. But when my app runs on Xbox, the menu style is not suitable for TV users.
So I wonder if the two different style can be merged in a single control?
Thanks.

**Comment by chigy** [comment]
Hello @hupo376787 , I would like to make sure I'm understanding you correctly. Are you designing your app based on NetFlix design? If so, the fact it uses two different design might be due to the possibility they do not use NavigationView on Xbox since these apps existed before the control was created. There's a bit of a long story here with Xbox not using XAML control when it first started out.

That said, can you clarify what you mean by "when my app runs on Xbox, the menu style is not suitable for TV users"? Can you pinpoint what exact changes you seek when the control is running on Xbox so we can evaluate your suggestion in a more systematic manner? For example (just example here), if you were to say the font is bigger for better visibility. Then, the change cannot be just made for NavigaitonView, but need to be considered for all other controls. I'd like to better understand individual actions to be taken to make this experience better with your help. Can you help?

Do you happen to have a side-by-side visual comp and behavior comparison that you can share to discuss item by item?

**Comment by mdtauk** [comment]
There is documentation about NavigationView should change for TV apps?  Do these changes happen automatically when running on the Xbox, or does each developer need to make them manually?

https://docs.microsoft.com/en-us/windows/uwp/design/devices/designing-for-tv

**Comment by chigy** [comment]
> There is documentation about NavigationView should change for TV apps? Do these changes happen automatically when running on the Xbox, or does each developer need to make them manually?
> 
> https://docs.microsoft.com/en-us/windows/uwp/design/devices/designing-for-tv

@mdtauk , is it a question or statement? Currently, the only thing we recommend doing is to hide the back button which is documented [here](https://docs.microsoft.com/en-us/windows/uwp/design/basics/navigation-history-and-backwards-navigation#optimizing-for-different-device-and-form-factors) and developer needs to write their own code to achieve it also documented [here](https://docs.microsoft.com/en-us/windows/uwp/design/devices/designing-for-tv#custom-visual-state-trigger-for-xbox).

**Comment by mdtauk** [comment]
> > There is documentation about NavigationView should change for TV apps? Do these changes happen automatically when running on the Xbox, or does each developer need to make them manually?
> > https://docs.microsoft.com/en-us/windows/uwp/design/devices/designing-for-tv
> 
> @mdtauk , is it a question or statement? Currently, the only thing we recommend doing is to hide the back button which is documented [here](https://docs.microsoft.com/en-us/windows/uwp/design/basics/navigation-history-and-backwards-navigation#optimizing-for-different-device-and-form-factors) and developer needs to write their own code to achieve it also documented [here](https://docs.microsoft.com/en-us/windows/uwp/design/devices/designing-for-tv#custom-visual-state-trigger-for-xbox).

The documentation may be helpful to @hupo376787.

I remember a similar discussion in another issue #698 about introducing specific templates for the WinUI controls when running on Xbox.

**Comment by hupo376787** [comment]
@chigy , Yes, we're developing an app like NetFlix. Here is NetFlix's screen shot on xbox and pc.
![微信截图_20200107142833](https://user-images.githubusercontent.com/14960168/71873413-0cd00b00-315a-11ea-8a1f-9f7a0eb9891e.jpg)
![微信截图_20200107142849](https://user-images.githubusercontent.com/14960168/71873417-0e99ce80-315a-11ea-93d2-8a12387fae92.jpg)


![微信截图_20200107142104](https://user-images.githubusercontent.com/14960168/71873247-b236af00-3159-11ea-814d-e84f85cafce5.jpg)

I like NetFlix's style on Xbox better, cause on pc, `NavigationView` is the best now.

Base on my opinion, I suggest `NavigationView`(on XBox):
1. Bigger font size
![image](https://user-images.githubusercontent.com/14960168/71873754-eeb6da80-315a-11ea-9496-9b07a519db67.png)
Bigger font can be readable on big screen for tv users.

2. Bigger item margin
![image](https://user-images.githubusercontent.com/14960168/71873800-0f7f3000-315b-11ea-92ef-858000fc5a96.png)
Bigger margin means more comfortable feeling while using app.

3. Focus visual things
![image](https://user-images.githubusercontent.com/14960168/71873865-3d647480-315b-11ea-8b21-465aa5436597.png)
Current NetFlix bold the font, we use the style like Android, change item background instead.

4. More fantastic things


And if possible, is there a style that can apply above styles to `NavigationView`?

**Comment by chigy** [comment]
@hupo376787 , thank you for your list. At the moment, I am not convinced the changes you are suggesting makes sense for us to bake into our default control for the reasons below. 

Please note that you can certainly try the custom route through [custom visual state trigger](https://docs.microsoft.com/en-us/windows/uwp/design/devices/designing-for-tv#custom-visual-state-trigger-for-xbox) and I am not suggesting against it. This comment is about baking this idea into a control to impact many others.

Is the 3rd image your app running on Xbox? If so, are you opting out of scale factor because the font looks smaller than I expect it to look on Xbox. On Xbox, the [scale factor](https://docs.microsoft.com/en-us/windows/uwp/design/devices/designing-for-tv#scale-factor-and-adaptive-layout) is set on 200% so they naturally look much bigger. I suggest you make sure you are not overriding the scale factor that may address your # 1 and # 2.

Also, the navigation list you are showing of your app is distinctly different from that of Netflix. Your list is so much longer and is used not as an easy jumping off point like Netflix version is, but many selection of choices that user will have to scroll through. This is much more cognitive load to user irregardless of the size of the items. I am not suggesting it is good or bad, I am commenting that these things do make differences and should be taken into consideration. These could potentially make a bigger impact to usability than sizes and styles.

Focus visual on Xbox for # 3 is something we coordinated with the Xbox shell team and built in a [default focus behavior ](https://docs.microsoft.com/en-us/windows/uwp/design/style/reveal-focus) that is appropriate for Xbox. A lot of thoughts and evaluation went into this decision. We currently have no plans to revisit the focus visual especially if that takes us away from consistency with the shell as well as the usability assumption we built around the current model.

All these said, I would suggest you try out your idea with the custom implementation and let us know how it made the impact.

**Comment by mdtauk** [comment]
@hupo376787  You don't seem to be following the guidance for the TV Safe Areas, and the content should be moved away from the edges of the screen, whilst allowing background imagary to be "full bleed" touching the edges.

**Comment by hupo376787** [comment]
@chigy @mdtauk We have 4~6 item one row, 200% will result in 2 items, this is a bad experience. And 200% will result in pictures more blur, so 200% is a very unresponsible and lazy solution. I have read all the guideline for xbox, some advice may not be suitable for prodution, really.

**Comment by chigy** [comment]
@hupo376787 , I do not understand your comment about 4-6 items becoming 2. If 4-6 items are appropriate number of items for your app on Xbox, then you should make sure you have 4-6 items at 200%.

Screen scale do not make things blur if you are providing appropriate sized assets.

**Comment by hupo376787** [comment]
OK, thanks guys.
