### ISSUE TITLE
Code intelligence doesn't work in Xaml designer!

### ISSUE THREAD

**Issue by zenjia** [microsoft/microsoft-ui-xaml#1805]
**Bug**：Code intelligence doesn't work in Xaml designer in Winui 3.0/C++ project.

**IDE**: Microsoft Visual Studio Community 2019 Version 16.4.2
**Target platform min version**: 10.0.17763.0

**Comment by stevenbrix** [comment]
Thanks for filing this @zenjia 

@mgoertz-msft, is this a known issue?

**Comment by mgoertz-msft** [comment]
WinUI isn't officially supported by the XAML designer/editor yet. IntelliSense sort of works for C# but only because it thinks it's dealing with Winows.UI.Xaml types and not Microsoft.UI.Xaml. We had to turn off error reporting for the 3.0 Alpha. I have never tried WinUI 3.0 with C++ so I'm not terribly surprised to hear that it doesn't work.

**Comment by stevenbrix** [comment]
Is the XAML language service in VS different for .NET and c++ projects? Or will this work once the Xaml designer work is complete?

**Comment by mgoertz-msft** [comment]
Same language service but some code paths are obviously different, and it also depends on the WinUI C++ project system support, which is also different from .NET. Eventually it's all supposed to work though but I can't say which pieces will light up when.

**Comment by zenjia** [comment]
@mgoertz-msft, Many thanks for your great works! Can't wait to see the new version of WinUI!

**Comment by danzil** [comment]
Adding @alwu-msft

**Comment by stevenbrix** [comment]
This was fixed in WinUI 3 Preview 3. Closing.
