### ISSUE TITLE
[uwp] UserControl.Loaded firing too late

### ISSUE THREAD

**Issue by jtorjo** [microsoft/microsoft-ui-xaml#1810]
**Describe the bug**
UserControl.Loaded fires too late.
I have a highly complex control and I can only initialize resources in Loaded event.
However, certain events can fire sooner. I understand why this can happen (implementation wise), but conceptually, I believe it should not happen.

**Steps to reproduce the bug**

	<UserControl x:Class="edit_ui.startup_pane.new_project_ctrl"
				 xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
				 xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
				 xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
				 xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
				 Loaded="New_project_ctrl_OnLoaded"
				 >
		<Grid x:Name="grid" PointerMoved="grid_mouse_move">
		</Grid>
	</UserControl>

grid_mouse_move can get triggered before the user control's Loaded.

I have quite a few controls like this, and the only way I found this out was via crashes from AppCenter (I couldn't trigger it in debug).

_I encountered this in UWP, and since WinUI is based on that, I assume this will happen here as well._

**Expected behavior**

Any event that happens in UserControl, should happen AFTER usercontrol's `Loaded` event. I want to place initialization code in Loaded event, and the fact that other events can happen before `Loaded` event, will unnecessarily complicate the code

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| October 2018 Update (17763)        |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |    |

**Comment by kmgallahan** [comment]
Using your example, the `UserControl` would not actually be in a loaded state if if its child `Grid` weren't loaded itself and firing events.

It would not make sense to suppress the functionality of child elements until all parent elements are "loaded", then make another pass to stop suppressing everything - at which point the parent is actually now in a "loaded" state (because its children are only now actually doing what they're supposed to). That would be confusing and considering buggy behavior.

Why not just attach the event handlers during the Loaded event? ~If you can't just handle the unwanted events gracefully otherwise.

**Comment by jtorjo** [comment]
> Using your example, the UserControl would not actually be in a loaded state if if its child Grid weren't loaded itself and firing events.

I totally get that. However, to me, it's surprising to receive events from a child of the UserControl, before the user control itself is loaded.

> It would not make sense to suppress the functionality of child elements until all parent elements are "loaded", then make another pass to stop suppressing everything - at which point the parent is only now in true "loaded" state (because its children are only now doing what they're supposed to). That would be confusing and considering buggy behavior.

Personally, I can't think of any example where you would want to handle events from children BEFORE the UserControl is loaded.

> Why not just attach the event handlers during the Loaded event? ~If you can't just handle the unwanted events gracefully otherwise.

This is clearly the path I'll take for now.

Having said that, I defer to you guys - you definitely know better implementation wise and you probably will think of a lot of stuff I'm not, but conceptually, I believe UserControl.Loaded should be the first event to fire.

**Comment by kmgallahan** [comment]
> Personally, I can't think of any example where you would want to handle events from children BEFORE the UserControl is loaded.

An analogy:

Construction company: "We finished the building!" (UserControl OnLoaded)

Tenants: "But none of the lights can turn on..." (some code listening for OnLoaded)

CC: "I'm doing to go wire up the lighting right now!" (after the OnLoaded event or asynchronous during it?)

T: "I thought the building was finished?..." (people wondering why the UserControl is claiming to be loaded even though its children aren't functional yet)

**Comment by jtorjo** [comment]
@kmgallahan I see what you're trying to do with the analogy, but I don't see how it would apply here.

Let me ask you this: in my original scenario, why would I ever want to listen to mouse events from the grid, before the user control is fully loaded?

The UserControl is supposed to orchestrate everything - that's why **it listens** to events from its descendants.

**Comment by kmgallahan** [comment]
> why would I ever want to listen to mouse events from the grid, before the user control is fully loaded?

You are the one that decided to listen for the events before you are ready to handle them. Your event handling logic requires the UserControl to be loaded before handling the child events (otherwise exceptions are thrown), yet you are still listened before you are ready.

Framework elements execute their code once loaded, which includes dispatching events. It doesn't matter what state other framework elements are in, including parents. Being loaded means you are working as advertised, and that means following the logic of the event system:

https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/events-and-routed-events-overview

**Comment by jtorjo** [comment]
@kmgallahan Got it, thanks.
