### ISSUE TITLE
Allow PreferredMinSize larger than 500x500

### ISSUE THREAD

**Issue by adrilow** [microsoft/microsoft-ui-xaml#1824]
There are some use cases where an application is simply not usable in small sizes, and anything other than setting an appropriate PreferredMinSize is just a workaround. (See [1](https://stackoverflow.com/questions/59665646/uwp-minimal-window-size-larger-than-500x500/59667201))

In my opinion, style guidelines should be recommendations and not hard-coded limitations. I think this can be a useful feature in those use cases. The current state of affairs is documented [here](https://docs.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.applicationview.setpreferredminsize#remarks).

**Comment by Aminator** [comment]
I disagree. When developing a UWP app, a big focus should be making it responsive so that it can run on many different display sizes with no problem. I absolutely hate Win32 apps that set a really big min size, which leads to me not being able to put that window side by side with another window on my Surface device. Ideally an app should be able to fit in one rectangle of the 2x2 grid that Windows 10 provides, which is especially useful when multitasking.

Also, that restriction is set by the OS and it may even be different depending on the OS variant. So my suggestion is to fit your app to that restriction instead of lifting it, mainly to provide a better user experience.

**Comment by kmahone** [comment]
@Austin-Lamb can you please find the right owner for this?

**Comment by Austin-Lamb** [comment]
@chigy - would you be able to help with this?

**Comment by chigy** [comment]
@adrilow , as @Aminator put it, we would like apps to be responsive. Supporting responsive layout becomes more important with Windows 10X devices with different screen sizes and [even dual-screen](https://docs.microsoft.com/dual-screen/introduction). 

That said, if you would like to make a request, this is an OS request so it will need to be directed to Feedback Hub.
