### ISSUE TITLE
Reusing XAML Path Style does not work

### ISSUE THREAD

**Issue by MartinZikmund** [microsoft/microsoft-ui-xaml#1874]
**Describe the bug**

A XAML Path Style cannot be reused in multiple places . The path successfully shows up only once.

**Steps to reproduce the bug**

1. Create Blank UWP app
2. Paste the following in the `MainPage.xaml`:

```
<Page.Resources>
    <Style x:Key="StarPath" TargetType="Path">
        <Setter Property="Data" Value="F1 M 126.578613,11.297852 L 162.373535,83.825684 L 242.412598,95.456055 L 184.495605,151.911133 L 198.167480,231.626953 L 126.578613,193.990234 L 54.988770,231.626953 L 68.661621,151.911133 L 10.744629,95.456055 L 90.783691,83.825684 L 126.578613,11.297852 Z"/>
        <Setter Property="Fill" Value="Gold" />
    </Style>
</Page.Resources>
<StackPanel>
    <Path Style="{StaticResource StarPath}" />
    <Path Style="{StaticResource StarPath}" />
</StackPanel>
```
3. Launch the application.
4. Observe **only one "star" appears instead of two in UWP**.
5. Repeat the steps with WPF app.
6. Observe **two "stars" appear successfully in WPF**.

**Expected behavior**

Two "stars" should be displayed on both UWP and WPF.

**Workaround**

Workaround is to share the path data as a simple string resource, for example:

```
<Page.Resources>
    <x:String x:Key="UserIconGeometry">M0 58l0 13 70 0 0 -12c-39,-33 -70,-1 -70,-1zm53 -40c0,-10 -8,-18 -18,-18 -9,0 -17,8 -17,18 0,9 8,17 17,17 10,0 18,-8 18,-17z</x:String>
</Page.Resources>
<StackPanel>
    <Path Data="{StaticResource UserIconGeometry}" Fill="Red" />
    <Path Data="{StaticResource UserIconGeometry}" Fill="Red" />
</StackPanel>
```

**Screenshots**

![image](https://user-images.githubusercontent.com/1075116/72963581-0e373f80-3db8-11ea-814c-e91d85fe9114.png)

**Version Info**

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | Yes   |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by codendone** [comment]
The issue here is that Geometry, the type of the Path.Data property, is implemented as a regular DependencyObject, which can have only one owner.  So the first Path becomes the owner and can draw, and the second Path has the Data property get rejected (because the Geometry already has an owner) so it has nothing to draw.  To support this scenario, it needs to be changed to be a MultiParentShareableDependencyObject (an internal type).

The workaround you found avoids any attempt to share the Geometry, which allows it to work. The downside of the workaround is that there isn't any sharing, so the path data gets parsed twice and the path will get drawn twice, even if the rendered bits are identical.  So fixing this would improve performance.

**Comment by MartinZikmund** [comment]
@codendone Thank you for the detailed explanation!

**Comment by trivalik** [comment]
A better workarround would then define not a string, use the `Geometry ` direct:
```
<Page.Resources>
    <Geometry x:Key="UserIconGeometry">M0 58l0 13 70 0 0 -12c-39,-33 -70,-1 -70,-1zm53 -40c0,-10 -8,-18 -18,-18 -9,0 -17,8 -17,18 0,9 8,17 17,17 10,0 18,-8 18,-17z</Geometry >
</Page.Resources>
<StackPanel>
    <Path Data="{StaticResource UserIconGeometry}" Fill="Red" />
    <Path Data="{StaticResource UserIconGeometry}" Fill="Red" />
</StackPanel>
```

**Comment by JJBrychell** [comment]
Geometries (the data for the paths) are not currently sharable objects. Since the style only creates a single Geometry that geometry is then set on multiple path objects (each one that has that style). This causes the second one to fail and no data for that path is set, so it does not appear.

Since there are work arounds outlined in the comments, we are going to close this issue. If you feel that is important that geometries are treated as a shared resources, please feel free to reopen this issue as a feature proposal.
