### ISSUE TITLE
ItemsStackPanel extends beyond containing Grid

### ISSUE THREAD

**Issue by Ponant** [microsoft/microsoft-ui-xaml#1876]
**Describe the bug**
This problem was first a question on StackOverlfow about UWP (see end of this post), but I feel it is a bug which will be difficult to fix. I later tried out `WinUI`  and found that the bug is even worse.

The example shows a ListView where Items extend beyond the Grid containing the `ListView` whenever the number of items is too large (beyond 30000 items in our case).
Look at the ctor in `MainPage` and increase or decrease the loop length.
Below a certain loop-length the items are contained in the parent grid, but above the `ItemsStackPanel` gets out of the parent Grid. Both orientations of the ItemsStackPanel show this problem, but it gets sooner (lower loop length) with a Horizontal orientation.

In addition to the UWP case, in WinUI, scrolling is strongly affected.

**Steps to reproduce the bug**
https://github.com/Ponant/WinUIItemsStackPanel
Run the project and check out the loop in the ctor of MainPage and increase the length until you see the behavior (the threshold may depend on your pc/laptop capabilities). 

**Expected behavior**
The Items in the ListView should not exceed the parent control (Grid in our case)

**Screenshots**
![ItemsStackPanelBug](https://user-images.githubusercontent.com/19961806/72974860-156a4780-3dd0-11ea-9250-18814586643b.PNG)
[](url)

Related
https://stackoverflow.com/questions/59850251/itemsstackpanel-extends-beyond-grid-container-for-a-large-source
https://github.com/Ponant/ItemsStackPanelUWPBug

**Comment by ranjeshj** [comment]
@kmelmon as FYI.
This looks like an issue with hitting the numeric limit for inset clips. I believe you can workaround it by setting a clip on the ListView.

 ListViewVisual.Clip =  Window.Current.Compositor.CreateInsetClip();

**Comment by Ponant** [comment]
@ranjeshj , I do not see yet where the `ListViewVisual` lives. If my ListView is named myListView, how would you set the inset Clip in code behind, or better in XAML?
Also, what is th enumeric limit of the inset clips.
The idea would be to be able to detect the number of items needed for display and clip if I know ahead I exceed the limit or not.
Thank you, I hope your solution will work (but please provide a bit more code if possible).

**Comment by ranjeshj** [comment]
I meant the composition visual for ListView. You can get it using ElementCompositionPreview.GetElementVisual(listView)

**Comment by Ponant** [comment]
I can confirm your suggestion works (without heaving testing that I will do latter).
However, what is the morale of the story? I mean, why isn't that a default?
I am wondering in particular if I loose virtualization, or any performance penalty to be expected?
Thank you, I would not have found this on my own.

**Comment by Ponant** [comment]
Please also let me know if this is considered a bug or an "issue", than I know if your solution is a temporary workaround or not.
Thanks again.

**Comment by ranjeshj** [comment]
@Ponant, I do not believe there is a performance penalty for this. There is still virtualization going on.  @kmelmon  or @gegao18 might be able to provide more details on why we hit this issue when the extent is very large.

**Comment by Ponant** [comment]
OK thank you @ranjeshj. In the end it works well for UWP but seems to cause some instability in the WinUI project above. I will submit it as an answer on SO as a matter of principle, with proper credits to you of course.

**Comment by codendone** [comment]
The problem here is a combination of the numeric limits mentioned above plus an optimization in XAML to avoid creating Composition Visuals where not needed.  In this case, the ScrollContentPresenter has the necessary clip and is only as large as the visible grid on screen, so setting the clip on a Visual for that element would work correctly.  But since it doesn't otherwise need a Visual, we optimize not creating one and pass the clip down to be applied as an "ancestor clip" where needed, which is the ItemsPresenter in this case.  When applying the ancestor clip, the size of that element is used in the calculations, and the size in this sample is 2,640,000 which is over the ~2 million limit for Visual clips, and the result is a broken clip.

The workaround mentioned above is forcibly applies a proper clip out at the container level, avoiding the bug.  It would also be possible dig into the generated template of the ListView's ScrollViewer and force a Visual to be created for the ScrollContentPresenter (by calling ElementCompositionPreview.GetElementVisual on it), but that is more complicated.

And, of course, we can fix XAML to either force creation of the Visual when necessary or to ensure that the ancestor clip calculation is done correctly.  We'll need WinUI3 for either of these.

**Comment by marcos-marimon** [comment]
Awesome solution @ranjeshj !!! Thank you very much so!!
