### ISSUE TITLE
Question: Why is it Windows UI (WinUI) instead of Microsoft UI

### ISSUE THREAD

**Issue by robloo** [microsoft/microsoft-ui-xaml#1908]
# Question: Why is it Windows UI (WinUI) instead of Microsoft UI

Aside from sounding better, why do we refer to this platform as Windows UI "WinUI"? Instead, Microsoft UI would make more sense although there is no cool sounding shorter term equivalent to "WinUI" I can think of.

Reasons for question:
 * WinUI goes with the old "Windows.UI.Xaml" namespace not the new "Microsoft.UI.Xaml"
 * GitHub repo is called "microsoft-ui-xaml"
 * There is some possibility of taking this framework cross-platform. In that case there would be no Windows. Microsoft naming would make more sense.

Just curious to see what the thinking is behind the naming. Not asking for it to be changed and we can close this question soon.

**Comment by jesbis** [comment]
We had lots of discussion about this and there was no perfect solution 🙂

We can't ship it in the `Windows` namespace because that's reserved for system binaries that ship with the OS. If we ever did have to add support for `Windows.UI` and `Microsoft.UI` content in the same process then there could also be namespace resolution problems.

"Microsoft UI" seemed too broad because it's not a UI platform for all endpoints (devices and platforms).

We've been moving more toward "WinUI" as the product name and package name (rather than "Windows UI") which arguably helps too. Namespaces and product names are often different.

**Comment by robloo** [comment]
"FluentUI" anyone? :)

Appreciate the comments though, that makes sense for the most part.
