### ISSUE TITLE
Feedback Requested: Community Call content

### ISSUE THREAD

**Issue by jesbis** [microsoft/microsoft-ui-xaml#1910]
Now that we [moved our monthly Community Calls to YouTube](https://www.youtube.com/playlist?list=PLI_J2v67C23ZqsolUDaHoFkF1GKvGrttB) I was wondering if anyone had any general feedback on the content or format.

Sorry about the technical issues with audio - we're working on sorting it out 🙂 It looks like we may have had a hardware issue with looping Teams audio correctly.

Particular questions:

1. **Is anyone completely unable to use YouTube** due to firewalls or other reasons? We also have a Teams call but it's a subpar experience because you can't see the video feed. I don't know if we can change much, but it would be helpful to know if this is affecting lots of people

2. **Does anyone still need .ics reminders?** E.g. because you can't use a Google account? We previously had a .ics calendar invite file and @salmanmkc has helpfully [opened a PR](https://github.com/microsoft/microsoft-ui-xaml/pull/1907) to update it, but:
   * .ics files can be wrong and out of date since there's no way to update them if we need to reschedule (which has already happened once)
   * some people were having trouble loading the previous .ics file into some calendar apps
   * it's work to create and maintain the .ics file(s)
   * YouTube event reminders seem superior and seem to work for other community calls

3. **What type of content would you like to see more of?** Live coding? More interview-style time with devs? More Q&A time? More community showcase content?

**Comment by Symbai** [comment]
More Q&A time, especially about the non-UWP future. For instance https://github.com/microsoft/microsoft-ui-xaml/issues/1531#issuecomment-565545235

**Comment by yaichenbaum** [comment]
I personally liked the format of Microsoft Teams better and I try to stay away from using YouTube. You mentioned that you cant watch the video from Teams but what about streaming on Mixer as well?

**Comment by kmgallahan** [comment]
> What type of content would you like to see more of?

I'd say the main purpose of the calls should be to share information that otherwise wouldn't be available (e.g. in release notes, on GitHub, etc.). Examples:

* Answers & thoughts regarding tough community questions
* How the WinUI team is working through challenging problems they've faced since the last call
* Mini-roadmap for the next ~month, and which GitHub issues the team like the most help with from the community during that time (e.g. how far off is work on a DataGrid, 1 month or 6 would drive the need for feedback)

> More interview-style time with devs?

The more WinUI devs we get to interact with the better! Doesn't need to be a round-table type thing, just maybe 1-2 more dropping in for the livestream.

> Live coding?

Not during the community call. What I had in mind was just have 1 or more brave WinUI full-time developers stream their work on the codebase on occasion.

The easiest way to try this out would be to capture a bug hunt session. Bug squashing has a well-defined scope with clear problems to solve (not a lot of open-ended work). People of all experience levels could tune in to observe, not necessarily requiring constant engagement from the streamer (after all, they need to get work done).

> More community showcase content?

On the above note: "share information that otherwise wouldn't be available" - if the same information could be provided by just saying: "hey go look at this thing over here", then there really isn't a need to do live-demos and walkthroughs (IMO).

**Comment by robloo** [comment]
I was going to leave a more detailed comment but @kmgallahan covered pretty much everything I was going to say.

Another idea I've had before is to address the top bugs discussing how/if they will be fixed and by when. There are several issues that affect the usefulness of many controls. I realize we can't address those in force until after WinUI 3.0; however, perhaps it would be good to get a consensus of which ones need to be prioritized. Maybe we need a voting system but I hate to make anything more complex than it needs to be. I also realize Microsoft may not have time to even keep track of all open bugs in this repo as you are stretched thin internally working on other things. This would also help to bring things to your attention that are causing problems for consumers of WinUI.

**Comment by infoequipt** [comment]
I'd like to see a track/topics on WinUI in the Enterprise.  Focus on issues designing, developing and deploying multi-platform apps for business/LOB.

**Comment by jesbis** [comment]
Thanks everyone for the feedback! This is useful as we plan future content. 

We'll be sticking with YouTube for this month again since it takes time to get other targets set up but will look into expanding to other targets like Mixer if interest continues.
