### ISSUE TITLE
Assigning a Source to Image  (c# uwp Vs2019)

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#1926]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/897018/assigning-a-source-to-image-c-uwp-vs2019.html)._

---
I opend an issue on StackOverlfow.  I did get a work around. I was not going to report this, but then, better to let you know. 

[https://stackoverflow.com/questions/59805023/re-run-the-program-and-get-different-results-c-sharp-uwp-vs2019/59832780#59832780] ()

In the program, Im looking for a Memory leak.  So, its writing 25 images to the screen. Button press deletes them and adds 25 more.

But, I was getting the 25 images sometimes and others only one.  Someone suggested assinging the source to A bitmap instead of a Image control.  After a bit if fiddling, that was done and it worked.  But, I applied that same solution to the program where I was having the problem. It seemed to work, but then the original method did too. Then, my storyboard popped in.  It was a zoom in  used at when there was success.  That image was just awful. It was like  10x10 image blown up to 1000 and distorted.

So.. The real thing is.  Shouldn't the  assign source to Image just work with no work-around.

---
#### Visual Studio Feedback System on 1/27/2020, 08:08 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by codendone** [comment]
This is definitely a bug, and I was able to repro with the steps mentioned on StackOverflow.  I see the main XAML data structures as having the correct information for the images and sharing the same graphics surface, but something went wrong in using the shared surface for rendering.  More debugging will be required to track down the issue.

The problem is in the core XAML code, so we'll need WinUI 3 to fix this.
