### ISSUE TITLE
Proposal: Allow for shared WinUI 3.0 control libraries that can be used in either UWP or win32

### ISSUE THREAD

**Issue by matthew4850** [microsoft/microsoft-ui-xaml#1952]
# Proposal: Allow for shared WinUI 3.0 control libraries that can be used in either UWP or win32

## Summary
It would be nice to have a shared library type for win ui 3.0 that would allow for creation of custom controls that can be shared between UWP and win32.

## Rationale
* This would make it easy to target both UWP and win32
* This would allow nuget packages that contain winui controls to work on both UWP and win32

**Comment by stevenbrix** [comment]
At a minimum I think developers should be able to accomplish the following:

1. Easily share code between a WinUI library that is built for both WinUI Desktop and WinUI UWP
2. Produce a Nuget that contains both 

A project type that does this would be ideal. If we don't get that, then at least a well documented blog post on how to achieve this.

**Comment by ranjeshj** [comment]
@marb2000 as FYI

**Comment by michael-hawker** [comment]
This would be invaluable for the Windows Community Toolkit.  We plan to port over to WinUI 3, so if we could easily ensure that the majority of our controls could work in both landscapes, that'd be a huge win for everyone.

I honestly was just kind of expecting this to be the case and work for anything built on-top of WinUI 3; so glad it's being called out specifically as it'd be good to know the details.

FYI @azchohfi @onovotny

**Comment by Gavin-Williams** [comment]
What do you mean here with Win32? Do you mean .Net Standard, .Net Core or C++/Win32 (legacy C style app)?

There shouldn't be an app platform that isn't universal. So really, Win32 should be removed from Windows and UWP/WinRT app model should be extended to run both in the UWP container and as an unrestricted application. That would be the best way to universalize WinUI, do we really want to keep the C style Windows app around? Sheesh.

**Comment by prayaas-a** [comment]
@Gavin-Williams WinRT wasn't a complete rewrite. It's a subset of Win32 and depends on it. You can't "remove" Win32. Older parts of it could be deprecated, APIs replaced. Further, there are many Win32 APIs that have no convenient UWP replacement yet and need work.
WinUI 3 will allow WinForms, WPF, and MFC developers to support a modern UI. None of those platforms are "universal" and it looks like they'll be here to stay for now.
WinRT definitely needs more work as a platform including feature parity with WPF (and desktop APIs including file access which is much easier in winforms/wpf) before it can get .NET devs to port codebehinds, let alone legacy native Windows apps. WinUI will at least allow them to change the UI part of it.

**Comment by StephenLPeters** [comment]
@marb2000 maybe you can weigh in here?  @jesbis fyi.

**Comment by Gavin-Williams** [comment]
> You can't "remove" Win32

This is a bit off topic, but my perspective is trying to bring Windows developers onto a common app model and api surface. So ...

I don't mean get rid of all Win32 API's. I mean that the Win32 application models, templates, input API's, graphics API's (GDI+) and probably a few more things, should be removed from Windows and Visual Studio. When a developer sits down in 2021 to write a Windows desktop app/game they shouldn't have the choice for legacy app stubs - they should be forced to write against the Universal Windows Platform - whether they use C++ or C# ( on .net 5). They can call into Win32 API's if they need certain functionality (can't think of anything useful but there must be stuff that people still use - there's a lot of apps out there).

A big problem i think is that there are too many greenfield projects choosing C style win32 and .net framework winforms app templates just because they are traditional models, and that's what educators push, not because they are the best choice today and moving forward. Look at HandmadeHero or TheCherno for examples of educators pushing legacy app platforms.

WinRT and WPF are not the same kind of thing.  WPF is a UI platform, it runs on .net framework, WinRT is a complete system platform and API surface - it is utilized and consumed by both C++ and C# (via .net core or uwp apps - and by .net 5 in the future). 

WinForms and WPF are indeed universal (or will be) now that they run on .net core - and eventually .net 5. That is they will run on all Windows 10 devices.

And how is reading and writing files with UWP more difficult? I don't get this claim. Are you talking about folder access restrictions? Full system access is being wound back in Windows - for good reason. I'm still not convinced that UWP needs wider access. It gives access to the user folders. Can anybody explain to me why I would want an app to have access to the system drive?

**Comment by Felix-Dev** [comment]
@Gavin-Williams This is indeed getting off-topic for this specific proposal. I would kindly suggest issue https://github.com/microsoft/microsoft-ui-xaml/issues/1856 to you where you can voice your view on Win32 vs UWP and how they should be treated by Microsoft going forward. There are fundamental UWP API gaps around which will force devs to currently write apps based on the Win32 app model and the linked thread above should cover this type of discussion and how UWP needs to be further improved. (Might as well just re-post your above post there.) Much appreciated 🙂

**Comment by michael-hawker** [comment]
@sonnemaf I think the crux of this issue is the .NET 5 story. It's the same problem. Once everything is aligned on .NET 5, this should just work. That's why we've migrated our previews in the WCT to .NET 5 for WinUI 3 Desktop and focusing on the previews there.

@ryandemopoulos getting to .NET 5 for both Desktop and UWP should be part of the release criteria for 3.0. It's going to be too painful for library developers otherwise to try and support both, especially when certain mappings don't work with WinUI 3 + .NET Native.

**Comment by dotMorten** [comment]
> Once everything is aligned on .NET 5, this should just work.

I assume that's because they would have the same TFM by then? That would worry me though - there are certain things you can do in UWP that you can't in Desktop and vice-versa. We handle that today with multi-targeting, but how do we handle that if the TFM isn't the differentiator?
