### ISSUE TITLE
Question: The State of Live Tiles on Windows

### ISSUE THREAD

**Issue by Felix-Dev** [microsoft/microsoft-ui-xaml#1958]
Some of us in the [UWP Community](https://discordapp.com/channels/372137812037730304/) are getting concerned for some time now about the future of the Windows Live Tiles. We've seen multiple reports over the past months about Windows 10X and its new Start menu which is supposedly similar to app launchers we know from Android and Co. Recently, (early) images of the revamped Start menu where shared and there are no signs of Live Tiles in them which seems to indicate those reports are on to something:
![alt text](https://cdn.neow.in/news/images/galleries/4284/1578530632_w15.jpg)

Some of us are using or planning to utilize Live Tiles in our Windows apps. Reports about Windows 10X possibly ditching Live Tiles have been unanswered by Microsoft so far. The leaves us developers entirely in the dark about the fate of an important UX aspect. We developers need certainty though to ship the best possible Windows apps. I thus strongly urge Microsoft to give us an official statement in response to these reports which will give developers much needed clarity on this subject.

**What will be the future role of Live Tiles on Windows?**

**Comment by Arlodotexe** [comment]
As a **heavy** user of the tile interface (not necessarily the live part) and a UWP dev, I would also like to know if the interface is here to stay.

I think the tiled interface is one of the best things about Windows 10. It makes ALL my apps very accessible and gives them a visual hierarchy (judging importance at a glance), and does so while keeping clutter under control.  

Every app I'll ever need is pinned, and because of tiles, I can organise everything cleanly, in a way that just isn't possible with icons. 
![image](https://user-images.githubusercontent.com/9384894/74105621-1831a000-4b25-11ea-9f66-f89cca281346.png)


Are tiles making their way to 10X eventually? Are they staying on Windows 10 at all? We need more clarification on this.

**Comment by shaheedmalik** [comment]
I hate the lack of tiles in Windows 10X.

**Comment by widersky** [comment]
As long as I can remember, the tiles have always made an incredible mess of Windows for me. Maybe if MS standardized their appearance strongly, it would be better. At the moment we have different colors, different styles of application icons, different sizes of icons, there is a picture on some tiles, on others icons, some are moving, others are not. I think that sooner or later the tiles will land in the basket.

**Comment by yoshiask** [comment]
@widersky That isn't a problem with tiles though. That same issue will continue with or without tiles or live tiles.

**Comment by shaheedmalik** [comment]
I wish for the tiles in start menu to mirror the way that icon, list, and detail views are in Explorer. They all should be a different view.

**Comment by Nepxune** [comment]
Live tiles are very, if not extremely integral to my workflow, Live tiles when utilized correctly can transform the start menu into a versatile central hub of information, which is how I currently utilize it. I can take a quick glance at my Start screen and if I see anything important I can choose to go to the app and view the context, otherwise I would be dependent on waiting for a push notification or a badge to show up next to a static icon to which then I would be forced to open.

The 10x's Start menu is a downgrade for me in every way, the customization aspects of the tiled start menu are simply unmatched in comparison to a static grid of icons that 10x currently has. Tile groups, tile folders and the information that may or may not be displayed on a tile all add to this, and at least with tiles you can add some personality to your start menu thanks to the fact the accent color is implemented.

Not to mention the untapped potential a improved Tiled menu could have, with the simple addition of actionable Tiles (Tile Widgets), tiles could become even more useful now doubling as a rich extension of the app itself giving new function to the Start menu, sure you could have these be a "Persistent Notification" but that would just take up space in a place that would otherwise be for notifications.

**Comment by sharpninja** [comment]
Move tiles to desktop with more shapes and arrangement options.

**Comment by Gavin-Williams** [comment]
I think icons, live tiles and shortcuts need to be upgraded so that we have even more flexibility with how we organize and control our apps. 

* Rounded edges. 
* Increase Win32 icon graphics to be consistent with UWP.
* Bigger icon grids, as big as we want.
* Live tiles / on desktop - this would be part of a live tile / icon unification.
* Separate background images for categories.

**Comment by sharpninja** [comment]
> * Live tiles on desktop

I want this more than an other UI improvement for Windows.

**Comment by ranjeshj** [comment]
This is unrelated to WinUI but great feedback for the shell team. I have relayed this issue link to our shell team. The shell team does track feedback hub votes. So please also use the Windows Feedback Hub to raise and upvote concerns. Here are some issues on feedback hub that potentially align with your feedback.

![image](https://user-images.githubusercontent.com/28935693/77068240-7dd63f00-69a3-11ea-9aa1-9b40a704a479.png)

**Comment by mdtauk** [comment]
![live tile changes 2020](https://user-images.githubusercontent.com/7389110/77114787-0f39c580-6a25-11ea-9244-3bb35152f503.gif)

**Comment by PhilLB1239** [comment]
Seems that Outlook gets Live Tile support?

**Comment by mdtauk** [comment]
> Seems that Outlook gets Live Tile support?

Not before time.  It's obviously a teaser video, made because of the 1 Billion active user mark - but hopefully its a declaration of continued support and embracing of Live Tiles.

It would be nice if Live Tiles could be pinnable to the Windows 10X desktop, like widgets on Android.

https://www.instagram.com/p/B97VqkXg0iN/?utm_source=ig_web_button_share_sheet

**Comment by FireCubeStudios** [comment]
tiled interface = good

**Comment by mdtauk** [comment]
Interesting new "Live Tile" like UI for a Taskbar Flyout - **Insider Build 21286**
![image](https://user-images.githubusercontent.com/7389110/103806072-66f4fc00-504c-11eb-9e31-e99381fa18f1.png)

**Comment by yoshiask** [comment]
That's an interesting development. It's basically a new flyout specifically for live tiles, which doesn't make a whole lot of sense. Isn't that what the tiled Start Menu is for? And if Microsoft really wants to have taskbar widgets... well, Windows already has those in the form of toolbars, like this one for Zune Desktop. Why not improve live tiles and modernize the taskbar toolbar APIs?
![image](https://user-images.githubusercontent.com/7549325/103808373-8294de00-501d-11eb-9ce1-9e12f38a3649.png)

**Comment by mdtauk** [comment]
10X has removed Live Tiles from their Launcher (Start Menu) and also removes Taskbar flyouts and icons.

So is this a way for 10X to add support for Tiles in the future?

**Brandon LeBlanc** on Twitter is saying we shouldn't read too much into this, and says its an exclusive UI for News and Interests.  And talks about it being a **Windows 10** thing, and is not discussing this feature with **10X**
