### ISSUE TITLE
Tap and key events doesn't work for TeachingTip Controls

### ISSUE THREAD

**Issue by soumyamahunt** [microsoft/microsoft-ui-xaml#1960]
**Describe the bug**
For a TeachingTip control tapped events like single tapped, double tapped, right tapped and key events like key up, key down aren't invoked.

**Steps to reproduce the bug**
Simply implementing TeachingTip control in xaml produces the issue.

**Expected behavior**
These events should be invoked and their subsequent method should be executed.

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.3.191211002

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19555)              |   Yes   |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by StephenLPeters** [comment]
I think this is likely a symptom of the way teaching tip displays its content, by putting it in a popup. That being said, why do you want a click handler on your teaching tip? wouldn't it be more appropriate to but the handler on the teaching tips content (which will work).

**Comment by soumyamahunt** [comment]
> I think this is likely a symptom of the way teaching tip displays its content, by putting it in a popup. That being said, why do you want a click handler on your teaching tip? wouldn't it be more appropriate to but the handler on the teaching tips content (which will work).

I wanted the teaching tip to close when a user taps anywhere on it.

**Comment by YuliKl** [comment]
> I wanted the teaching tip to close when a user taps anywhere on it.

@soumyamahunt, this behavior doesn't really fit into our overall [light dismiss guidance](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/dialogs-and-flyouts/flyouts#light-dismiss-behavior) and would be unexpected for users. Typically on Windows, users expect to tap a dedicated close button or use a light dismiss gesture (e.g. tapping outside the UI panel) to dismiss the UI. In this ecosystem, users likely *don't* want teaching tip to close when tapped directly.

Closing the issue because this isn't a supported scenario.
