### ISSUE TITLE
UWP MediaElement Stop and Start called after each other will stop video

### ISSUE THREAD

**Issue by aosyatnik** [microsoft/microsoft-ui-xaml#1975]
**Describe the bug**
I created a minimal reproducible scenario here:
https://github.com/aosyatnik/UWP_StartStopVideo_Issue

In short, when you call `Stop` and `Play` of `MediaElement` one after another, video won't be played even if you called the `Play` method.

**Steps to reproduce the bug**
1. Run application.
2. Click "Stop and start" button. It will load one of a random video among 3 available videos.
3. Click the button again. If you are lucky and the next video is the same video it will be played. If the next video is another video it won't be played.

**Expected behavior**
The video should be played regardless if it's the same video or another video. Stop and Play calls should not break video playing.

Again if the last call is `Play`, the video must play regardless of what was called before.

**Screenshots**
Check repo.

**Version Info**
VS 2019.
UAP,Version=10.0.18362.0

NuGet package version: 
Microsoft.NETCore.UniversalWindowsPlatform
6.2.9

**Comment by tesar-tech** [comment]
I don't think it is related to winUI. MediaElement is not part of WinUI.  (it's from `Windows.UI.XAML` namespace).

Anyway expected behavior is not correct. Because it has this timeline: Button Click  -> Video is stopped -> Video is played -> `Video_MediaOpened` is called and it will stop the video (Autoplay is set to false). That is the reason, why your workaround 1 works. 

It will not stop the same video, because `VideoPath` is not changed and will not fire `Video_MediaOpened`

**Comment by Austin-Lamb** [comment]
@aosyatnik - do you see the same with MediaPlayerElement?  MediaElement is deprecated and has been replaced with MediaPlayerElement.

**Comment by aosyatnik** [comment]
Hi, @Austin-Lamb , sorry for the long reply. I can not reproduce this issue with `MediaPlayerElement`. Just pushed new changes. Thanks.
