### ISSUE TITLE
NumberBox isn't supporting context menu operations

### ISSUE THREAD

**Issue by YuliKl** [microsoft/microsoft-ui-xaml#1978]
**Describe the bug**

**Steps to reproduce the bug**

1. Launch XAML Controls Gallery.
2. Activate AutomationProperties from All Controls Page.
3. Right Click on text box present beside Font Size of texts text box and try to perform Cut/Copy etc operation.
4. Switch to the NumberBox page and attempt a Cut operation.

**Expected behavior**

Users should be able to perform all the context menu operations.

**Screenshots**

![image](https://user-images.githubusercontent.com/13142665/74569775-10606a00-4f30-11ea-847a-d2bb605005d7.png)

**Version Info**

Xaml Controls Gallery v 1.2.12.0

**Additional context**

Copied from [internal bug](https://microsoft.visualstudio.com/OS/_workitems/edit/24690336)

**Comment by StephenLPeters** [comment]
@teap fyi

**Comment by teaP** [comment]
The issue here is that right-clicking to bring up the context menu causes loss of focus, which causes validation to run, which deselects the text in UpdateTextToValue():

```
// This places the caret at the end of the text.
textBox.Select(static_cast<int32_t>(newText.size()), 0);
```

The point of this line is to avoid the caret moving to the front of the control text when using the up/down arrows, so the right fix for this issue is to simply move this line into a more scoped location, at the end of StepValue(), which is when it is actually needed.

**Comment by Felix-Dev** [comment]
I would like to take a look at this if no one currently works on it.

**Comment by teaP** [comment]
> I would like to take a look at this if no one currently works on it.

Certainly! :)
