### ISSUE TITLE
NavigationView TogglePaneTopPadding issue

### ISSUE THREAD

**Issue by aarefievit** [Microsoft/microsoft-ui-xaml#2]
My page xaml
`<Page x:Class="WinUITestApp.MainPage"
      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      xmlns:controls="using:Microsoft.UI.Xaml.Controls">
    <controls:NavigationView AlwaysShowHeader="True"
                             Header="Header"
                             IsBackButtonVisible="Visible" />
</Page>`

My code for title bar

`var coreTitleBar = CoreApplication.GetCurrentView().TitleBar;
   coreTitleBar.ExtendViewIntoTitleBar = true;`

![image](https://user-images.githubusercontent.com/22373380/45863678-a8384380-bd90-11e8-99e7-8e236b670eed.png)

Change NavigationView to Windows.UI...

![image](https://user-images.githubusercontent.com/22373380/45864073-3a8d1700-bd92-11e8-895a-844348c5d466.png)

**Comment by YuliKl** [comment]
Thank you for reporting this issue. What you're seeing in your first screenshot is by design, and will soon be updated in the Windows.UI namespace as well. When extending into the title bar, your app content gets drawn to the top of the window, but there's still a transparent title bar component that physically overlays your app window. As a result, users won't be able to click on your (disabled in the second screenshot) back button, were it to become enabled. To improve this user interaction, we automatically move NavigationView's components (but not its background color) down from the top of the window. This way, all buttons remain interactive without additional work by the app author.
