### ISSUE TITLE
leverage C++ modules support recently added to Winrt/C++ to improve build times

### ISSUE THREAD

**Issue by ranjeshj** [microsoft/microsoft-ui-xaml#2012]
https://github.com/microsoft/cppwinrt/pull/495 added support for C++ modules as an alternative to precompiled headers. This can help reduce build times and improve incremental build times.

**Comment by sylveon** [comment]
At the moment, it does not improve incremental build times, it actually worsens them because the entire module needs to be regenerated, which is more expensive than regenerating a PCH. https://github.com/microsoft/cppwinrt/pull/953 (which I plan to look at again soon) would make incremental builds faster by splitting the cppwinrt modules into partitions (so the entirety of `Windows.*` does not need to be rebuilt for a change to `Contoso.*`).
