### ISSUE TITLE
Rotated text blurring inside of viewbox

### ISSUE THREAD

**Issue by aosyatnik** [microsoft/microsoft-ui-xaml#2039]
**Describe the bug**
I want to share with you one of the controls, that was developed for one of my projects. It's some kind of textblock, that is animated and can be pairwise scaled with another textblock. Check the video how it updates with 0 rotation:
![img](https://github.com/aosyatnik/UWP_IssueBlurringTextInViewBox/blob/master/Images/pairwise-scalling.gif?raw=true)

I tried to reduce source code as much as possible, but keep all important features. Textblocks should be scaled smooth(i.e. with animation) and together. You will find `BaseFadeInOutAnimationControl` in repo, this is base class, that is used in other places in my project for pretty opacity animation, but you might be interested only in `FadeInOutTextBlock` and its' `KeepControlsSameSize`. This method makes pair scaling. It calculates the biggest Width between 2 siblings and sets both siblings the biggest width. + each sibling is in `Viewbox` so they are both scaled.

**Steps to reproduce the bug**
Here is repo:
https://github.com/aosyatnik/UWP_IssueBlurringTextInViewBox

1. Run app.
2. Type in Name_A text box next text: 12345678. (Notice 2 textblocks - fine)
3. Type in Name_B text box next text: 12345678. (Notice another 2 textblocks, BUT 1 and 3 textblocks are blurred now):

![bug](https://github.com/aosyatnik/UWP_IssueBlurringTextInViewBox/blob/master/Images/bug.JPG?raw=true "Title")

Or you may try with texts, maybe it will be more clear (yes, it's not very noticeable on this picture, although I can already notice blurred texts, but on the big screen you will notice it):

![bug](https://github.com/aosyatnik/UWP_IssueBlurringTextInViewBox/blob/master/Images/bug2.JPG?raw=true "Title")

So, the first text of pair is always blurred.

4. Now go to MainPage.xaml and change `Angle="270"` to `Angle="0"`. Notice, that all 4 textblocks are fine and not blurred.

----------

I have an assumption, that it could be caused by the animation of Width, but I'm not 100% sure.

**Expected behavior**
Texts should not be blurred, when they are rotated.

**Version Info**
Target version: Windows 10, version 1903
Min version: Windows 10, version 1809

NuGet package version: 
UAP,Version=10.0.18362.0
Microsoft.UI.Xaml.Markup 10.0.0.0

**Comment by codendone** [comment]
Part of the problem here is that LayoutTransformControl sets UseLayoutRounding=false.  This means the elements, including the TextBlocks in use here, aren't necessarily pixel-aligned by layout.  If a TextBlock is not pixel aligned, each pixel of the rendered texture for the text gets blended across multiple pixels, making it blurry.  With layout rounding off, each TextBlock can end up with a different sub-pixel alignment, resulting in more or less blur.

By setting UseLayoutRounding=true on the LayoutTransformControl, I see a more consistent level of blur.  The Viewbox container of these textblocks also results in the elements not being pixel-aligned, due to the scale transform it applies.  Replacing that Viewbox with a Grid, for the purposes of testing, shows that just the UseLayoutRounding=true is sufficient.

When there isn't anything causing a TextBlock to be rotated, XAML does "baseline pixel snapping" to align the text so its rendered texture will land on a whole pixel to avoid the blur and still position the text appropriately.  This is only done when there isn't rotation involved, since rotation is usually short-lived and will usually already require blending which will add some blur.

At the current time, the best recommendation is to have UseLayoutRounding=true and avoid Viewbox where possible.
