### ISSUE TITLE
Question: Can we get the default corner radius of checkboxes in ListViewItem to rounded, or have a property to set?

### ISSUE THREAD

**Issue by hjohnson12** [microsoft/microsoft-ui-xaml#2067]
Hi Team!

So a feature I'm currently working on a feature in my UWP application for tag selection. I was hoping to be able to set the corner radius of the Check-boxes inside of the ListViewItems to the same that I have for my tags beside it but I cannot find how to do so and it seems as though it's not supported 🤔  

**Example:**
![image](https://user-images.githubusercontent.com/20372914/75941470-ce0ab880-5e5d-11ea-8959-3a88fb7f4d36.png)

I was checking this page, [ListViewItem Class](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.listviewitem), and this page [ListViewItemPresenter Class](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.primitives.listviewitempresenter), as well as the default ListView API page for a property I could set for the CheckBox Corner Radius, but I only found for brushes and such. 

**Main Question:** I'm mainly wanting to see if we're able to get those to either a default corner radius, or if there is a property I'm missing that could achieve this without having to add in my own custom checkbox to the data template and such? 

Thank you for your time :)

**Comment by hjohnson12** [comment]
Also here is where the XAML for my ListView is from the above image: [ListView from example](https://github.com/hjohnson12/Kanban-Tasker/blob/ebe331c5d70021caa4066c117777aafd2ba6ff9b/KanbanTasker/Views/TagSelectorDialog.xaml#L188)

**Comment by Felix-Dev** [comment]
Currently, you probably have to add your own checkbox look (for example via the DataTemplate). By default, ListViewItem's use a [ListViewItemPresenter](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/item-containers-templates#listviewitempresenter) which displays the checkbox and does not expose a corner radius/checkbox visual property. You could use the `ListViewItemExpandedStyle` which contains the UI to display the checkbox, however, you would have to create a hard-copy of the style and then modify it which should be avoided if possible. You will also lose the benefits provided by the `ListViewItemPresenter`.

I created an own selection visual in a project of mine in the past and iirc I also had to use my own selection logic because I found no way to remove the checkbox visual (using ListViewItemPresenter) you get when setting the selection mode to multiple. That said, I wasn't happy with the out-of-the.box selection logic so I had to provide my own logic anyway. Given this...it's probably best to just use the default selection visual for now until better customization has been added.

A new corner radius resource could be added to change the corner radius of the default selection visual. It might also be worth thinking about providing a property which developers can use to provide their own selection visual. Something like WPF's [FocusVisualStyle](https://docs.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement.focusvisualstyle?view=netframework-4.8). This should be in its own API proposal though.

**Comment by ranjeshj** [comment]
@Felix-Dev  SelectionCheckMarkVisualEnabled set to false showing the check box looks like a bug.

There is also a SelectionCheckMarkVisualEnabled property on ListView which seems to disable showing the check box. 

@chigy Should checkbox have rounded corners ?

**Comment by Felix-Dev** [comment]
@ranjeshj 
> There is also a SelectionCheckMarkVisualEnabled property on ListView which seems to disable showing the check box.

Did you mean [ListViewBase.IsMultiSelectCheckBoxEnabled](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.listviewbase.ismultiselectcheckboxenabled#Windows_UI_Xaml_Controls_ListViewBase_IsMultiSelectCheckBoxEnabled)? Yes, that one works. @hjohnson12 Seems like you can use this porperty to hide the default selection visual and provide your own if the customization options available are not enough.

**Comment by ranjeshj** [comment]
> @ranjeshj
> 
> > There is also a SelectionCheckMarkVisualEnabled property on ListView which seems to disable showing the check box.
> 
> Did you mean [ListViewBase.IsMultiSelectCheckBoxEnabled](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.listviewbase.ismultiselectcheckboxenabled#Windows_UI_Xaml_Controls_ListViewBase_IsMultiSelectCheckBoxEnabled)? Yes, that one works. @hjohnson12 Seems like you can use this porperty to hide the default selection visual and provide your own if the customization options available are not enough.

Yep. That's the one. Fixed my comment. Thanks.

**Comment by hjohnson12** [comment]
> @ranjeshj
> 
> > There is also a SelectionCheckMarkVisualEnabled property on ListView which seems to disable showing the check box.
> 
> Did you mean [ListViewBase.IsMultiSelectCheckBoxEnabled](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.listviewbase.ismultiselectcheckboxenabled#Windows_UI_Xaml_Controls_ListViewBase_IsMultiSelectCheckBoxEnabled)? Yes, that one works. @hjohnson12 Seems like you can use this porperty to hide the default selection visual and provide your own if the customization options available are not enough.

@Felix-Dev @ranjeshj Thanks for the responses! I'll give the *IsMultiSelectCheckBoxEnabled* a try out / the template and go from there! 😁

Per the default corner radius or separate property possibility, it would be great for future cases since most of the controls have defaulted to either **2px** or **4px** CornerRadius and the standalone CheckBox is already at **2px**.  I have no idea how frequent this comes up though with other people though!

**Comment by chingucoding** [comment]
I think we should probably add a themeresource, e.g. "ListViewItemCheckboxCornerRadius" that developers could use to set the corner radius of the CheckBoxes the ListView renders.

Of course this would only make sense, if this is a direction design would be fine with. @chigy FYI.

@ranjeshj What is your opinion on adding an additional resource here?

**Comment by ranjeshj** [comment]
Sounds good. Do we need to expose one for CheckBox also ? @chigy thoughts ?

**Comment by Felix-Dev** [comment]
@ranjeshj @chingucoding Instead of introducing a new resource, why not simply use the `ControlCornerRadius` like the default CheckBox style already does? See https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/CheckBox/CheckBox_themeresources.xaml#L297

That way, this can be set once and the checkboxes all have the same radius no matter if they are the ListViewItem selection checkbox or a standalone checkbox control. Otherwise, if we introduce a new resource, then the developer uses `ControlCornerRadius` to set the corner radius of checkboxes and then *also* has to use another resource to make the ListViewItem selection checkbox match the app's checkbox look. I don't think adding a new resource is worth the confusion it might add and the developer should always be able to set a unique checkbox corner radius for ListViewItems using the 
```
<ListView.Resources>
   <CornerRadius x:Key="ControlCornerRadius">x,y,w,z</CornerRadius>
</ListView.Resources>
``` syntax.

**Comment by mdtauk** [comment]
If there are Control Specific brush resources, the same should apply to CornerRadius.  And by default the specific brush value can point to the generic ControlCornerRadius value.

**Comment by chigy** [comment]
We already have an item tracking this work. We cannot do this until WinUI3 so it is on our backlog.
https://github.com/microsoft/microsoft-ui-xaml/issues/1096

**Comment by chigy** [comment]
> Sounds good. Do we need to expose one for CheckBox also ? @chigy thoughts ?

@ranjeshj 
We already have an item tracking this work. We cannot do this until WinUI3 so it is on our backlog.
https://github.com/microsoft/microsoft-ui-xaml/issues/1096
