### ISSUE TITLE
Storyboard animations cause some elements to be drawn at (very) low quality

### ISSUE THREAD

**Issue by benstevens48** [microsoft/microsoft-ui-xaml#2080]
**Describe the bug**
I've noticed a couple of instances where Storyboard animations cause some elements to be drawn at (very) low quality, which seems especially to occur if CompositionDrawingSurface has been used anywhere.

One example is animating the RenderTransform scale factor from 0.1 to 1, applied to some text which had a shadow applied using the composition layer (e.g. using DropShadowPanel from the community toolkit). In this case it wasn't just the shadow that didn't work - the whole text was completely blurred until the animation finished.

Another example includes a situation where the thing that ends up being blurred want' even animated. I created a custom brush derived from XamlCompositionBrushBase to draw a chequerboard background (by tiling a small CompositionDrawingSurface consisting of 4 squares). This in itself worked fine. But then I applied a Storyboard animation to an element to move it over the top of this background (the background stayed still). This cause the background to become blurred (sometimes very blurred) even though the background was completely static.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| November 2019 Update (18363)  | Yes   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |   Yes   |

**Comment by JohnnyWestlake** [comment]
Re: the text rendering thing, this is actually an intentional performance choice - re-rendering can be performance intensive and needs to be done on the UI thread, so in the case of scale changes re-rendering is typically done after the scale has finished to prevent UI thread hitches during animation. (I believe there's some sort of threshold with slightly different behaviour that happens only for minor scale changes like 10% either way, but won't be applicable for your case.)

One way to do avoid this is to actually do a scale animation at the composition layer - this always renders at the original scale - so for your case you won't blurred text, though keep in mind once you go over 100% scale it will never re-render, the scale will still be the 100% scaled image, just stretched.

If you're targeting v10.0.17763.0 as MinVersion, `UIElement.Scale` and `UIElement.Scale` transition are easy ways of using composition for animation without having to create composition animations yourself. 

Setting BitmapCache on the FrameworkElement is another choice but not massively recommended at this point.

If targeting v10.0.18362.0, `CompositionSurfaceBrush.SnapToPixels` property might be useful for the second.

**Comment by benstevens48** [comment]
Hmm, this isn't ideal. I think that text scaling animations can be done in HTML fine (don't have time to test right now). 

Maybe the WinUI team can have a look at improving the situation?

I'm not sure what the rendering needs to be done on the UI thread - is that really correct?

Thanks for the tip about using composition animation. I'm actually animating a more complex element, so that's not really practical. I guess I could try to get the storyboard animation to do the initial render at 100% (and somewhow hiding it from view) scale before dropping to 1% scale then going back to 100%. I don't know if this would work though.

**Comment by JohnnyWestlake** [comment]
Regarding UI thread rendering - because the intial scale transform causes the element to have it's actual render-pass render at 0.1 scale, after the animation is completed (and has been bitmap scaled to 1.0 scale, which makes it blurry), it actually needs to be properly rendered again at 1.0 to have perfect scale. And everything in the XAML layer is rendered on the UI thread.


Composition animations work perfectly fine for complex elements - XAML storyboards essentially use composition layer animation underneath for the last few builds of Windows 10, just with extra foibles on top, like automatically re-rendering at different scale, and the ability to target multiple elements in a single storyboard. (In that regard, CompositionAnimations are closer to individual animation timelines than the entire storyboard object)

In code, you could trigger one like so:

```
        public static void StartScaleAnimation(FrameworkElement target, float from, float to)
        {
            Visual v = ElementCompositionPreview.GetElementVisual(target);

            // Sets the centre point of the scale to be the centre of the object. 
            var c = v.Compositor.CreateExpressionAnimation();
            c.Target = nameof(Visual.CenterPoint);
            c.Expression = "(Vector3(this.Target.Size.X * 0.5f, this.Target.Size.Y * 0.5f, 0f))";
            v.StartAnimationGroup(c);

            // Scale animation
            var t = v.Compositor.CreateVector3KeyFrameAnimation();
            t.Target = nameof(Visual.Scale);
            t.InsertKeyFrame(0, new Vector3(from, from, 0));
            t.InsertKeyFrame(1, new Vector3(to, to, 0));
            t.Duration = TimeSpan.FromSeconds(0.6);

            // Opacity animation
            var o = v.Compositor.CreateScalarKeyFrameAnimation();
            o.Target = nameof(Visual.Opacity);
            o.InsertKeyFrame(0, 0);
            o.InsertKeyFrame(1, 1);
            o.Duration = TimeSpan.FromSeconds(0.2);

            // Create and start the group
            var g = v.Compositor.CreateAnimationGroup();
            g.Add(t);
            g.Add(o);

            v.StartAnimationGroup(g);
        }
```

It's worth noting that CompositionAnimations have a default easing function applied to all KeyFrames if you don't specify one, unlike XAML which uses linear interpolation by default.

**Comment by codendone** [comment]
A few additional comments on top of the great responses from @JohnnyWestlake:

1. If you want to stick with Storyboards, sometimes developers will use a short keyframe at the beginning of the animation which has the target scale value so XAML will render at that scale value, and then have the next keyframe jump to the small value and animate up from there.  You likely will need to include an Opacity animation as well to ensure the element doesn't show as full-size on screen for that first frame.
2. We'd eventually like to deprecate Storyboard animations entirely, but we'll need to enable .xaml markup support for Composition animations before we do that.  And we'll likely need to determine how to handle rasterization scale of animated elements by then.
3. We've talked about moving text rendering off the UI thread, and I suspect this will eventually happen in some form.  There are some challenges to be able to do this efficiently, since needing to lock the same structures which the UI thread uses can have performance consequences, and duplicating the structures to avoid locks has different performance consequences.  We've done some investigation into improvements here, and I expect this will be an area we continue to look at, but we're not likely to get to this in the next two years.

**Comment by benstevens48** [comment]
Thanks for the replay @codendone , but did you see the second issue in my original comment
> Another example includes a situation where the thing that ends up being blurred want' even animated. I created a custom brush derived from XamlCompositionBrushBase to draw a chequerboard background (by tiling a small CompositionDrawingSurface consisting of 4 squares). This in itself worked fine. But then I applied a Storyboard animation to an element to move it over the top of this background (the background stayed still). This cause the background to become blurred (sometimes very blurred) even though the background was completely static.

Any idea why that might happen?

**Comment by codendone** [comment]
@benstevens48 That sounds like a Composition bug.  Frequently in cases like this you can repro the problem with anything that causes a redraw, like moving the element on a timer or based on pointer input, or even by dragging some other app over top of this part of the app so DWM.exe needs to recompose it.

**Comment by benstevens48** [comment]
@codendone Shall I open a separate issue for it? Or are you saying the issue is at a lower level than WinUI?

**Comment by michael-hawker** [comment]
@codendone FYI we do have wrappers for XAML around the Composition animations in the Toolkit already [here](https://docs.microsoft.com/en-us/windows/communitytoolkit/animations/compositionanimations) that we use mostly for Implicit Animations, but can be of course created in markup wherever needed.

Is there a current issue tracking the proposal for this future work to replace Storyboards?

**Comment by codendone** [comment]
@benstevens48 If you could log a separate issue for that XamlCompositionBrushBase behavior, that would be great to help track it.  We'll need the Composition team to investigate this issue.  Does the blur ever fix itself, or does it stay bad?  If you take a screenshot when in this state, does the screenshot look correct?  (This sometimes happens when the compositor has an issue in incremental rendering -- the screenshot creates a complete render.)

@michael-hawker We haven't yet posted an issue for a proposal or intent to replace Storyboards.  Feel free to log a proposal or discussion if you'd like to have something to track.  A replacement won't happen until sometime after WinUI 3.0.
