### ISSUE TITLE
XAML-implemented delegates should implement IAgileObject

### ISSUE THREAD

**Issue by JulianSelman** [microsoft/microsoft-ui-xaml#2090]
Because delegates (such as INPC-listeners) do not implement IAgileObject and are also not marshalable (do not implement IMarshal), they go through a slow code path when they are attached to a C++/WinRT event and are eventually smuggled by the runtime as it runs out of marshaling strategies.

As XAML delegates are going through this code path anyway, the right thing to do here is to assert these delegates as agile, by implementing IAgileObject.  Not doing so can slow down a single event attach by upwards of 100 ms in some scenarios.

**Comment by StephenLPeters** [comment]
@kennykerr is this something that we should be doing in WinUI at our construction point, something our deligate implementation should be changed to implement, or a change that can be made in cppwinrt?  @MikeHillberg @jevansaks either of you have thoughts on the right place to make this fix?

**Comment by kennykerr** [comment]
The fix is to implement `IAgileObject` on the delegates Xaml itself creates and passes to callers of the Xaml API. This is already the case for delegates produced by C++/WinRT (and thus those parts of Xaml implemented with C++/WinRT). This is not the case for Xaml delegates created with WRL or by some other means. For example, Xaml's implementation of `IPropertyChangedEventHandler`.
