### ISSUE TITLE
NavigationViewItems ignore Foreground property when in Top mode

### ISSUE THREAD

**Issue by YuliKl** [microsoft/microsoft-ui-xaml#2103]
**Describe the bug**

Setting the Foreground property of a NavigationViewItem has no effect when its parent NavigationView is in Top display mode.

**Steps to reproduce the bug**

Create simple repro app.

```xaml
<muxc:NavigationView PaneDisplayMode="Top" x:Name="TestNavigationView">
    <muxc:NavigationView.MenuItems>
        <muxc:NavigationViewItem Icon="Home" Tag="Home" Content="Home" Foreground="Purple"/>
    </muxc:NavigationView.MenuItems>
</muxc:NavigationView>
```

**Expected behavior**

Icon and "Home" text foreground should be Purple.

**Screenshots**

![image](https://user-images.githubusercontent.com/13142665/76566882-f0f32900-646a-11ea-8b79-3dafa6c1cffb.png)

**Version Info**

NuGet package version: 

2.4.0-prerelease.200203002

**Additional context**

Issue ported from [internal bug](https://microsoft.visualstudio.com/OS/_workitems/edit/25474707) and originally reported by a customer on https://docs.microsoft.com/answers/questions/4461/uwp-navigationview-items-foreground-color-not-work.html

The problem does not repro when NavigationView is in Left / Auto display mode.

**Comment by chingucoding** [comment]
I think the reason for this bug is the following line in the NavigationViewPresenter style for DisplayModeTop:

https://github.com/microsoft/microsoft-ui-xaml/blob/0db781759437ca8580501649bc00ca1dc5f043be/dev/NavigationView/NavigationView_rs1_themeresources.xaml#L954

The corresponding for DisplayMode Left does not explicitly set the ForeGround property.
