### ISSUE TITLE
Image memory leak

### ISSUE THREAD

**Issue by aosyatnik** [microsoft/microsoft-ui-xaml#2190]
**Describe the bug**
Here is the reproducible repo: https://github.com/aosyatnik/UWP_MemoryLeakWithImage

Before you try to understand memory leak I want to try to explain how I got to this memory leak. I wanted to have some control, that will switch images. Something like an emulation of gif.
I wanted some image to be shown for some time, after that, another image should be shown. Also, I wanted to implement some transition animations, but in this example, this doesn't really matter. 

So, I created `BackgroundImage` and `ForegroundImage` and added `DispatcherTimer _imageTimer`. When both background and foreground were ready, timer starts and the image is shown for 1 second. This was looking like this:

![without_previous_file](https://user-images.githubusercontent.com/8158404/77910288-326b3d00-728f-11ea-9e0a-114c6738f131.gif)

I didn't like, that there is a white blink when an image is loading. So I decided to add a so-called "previous" file. This is an image, that was before. And it kind of worked (although foreground image was still blinking background image was shown fine and I was happy even with this):

![with_previous_file](https://user-images.githubusercontent.com/8158404/77910348-4a42c100-728f-11ea-89d7-dd301f99442d.gif)

**Steps to reproduce the bug**
If you open `MainViewModel.cs` and change this code:
`public OverlayBackground OverlayBackground { get; set; } = OverlayBackground.fx;`
into this code:
`public OverlayBackground OverlayBackground { get; set; } = OverlayBackground.black;`

This will change background into solid color. Should work like this:
![with_black_background](https://user-images.githubusercontent.com/8158404/77910642-c2a98200-728f-11ea-9a55-2ddda0d54285.gif)

And now check Process Memory, when background image is visible(fx) it's ok:
![normal_memory](https://user-images.githubusercontent.com/8158404/77910662-cdfcad80-728f-11ea-9f6f-97d59fdaba28.JPG)

But as soon as background image is hidden (black background) it's raising continuously:
![memory_leak](https://user-images.githubusercontent.com/8158404/77910744-f08ec680-728f-11ea-8839-45662ab4da28.JPG)

P.S. even if I work with Opacity instead of Visibility of background image it still creates a memory leak.
P.S. P.S. I tried just with "foreground" image, it's working fine (no memory leak), but as soon as I have this "previous" file it's not working well anymore. So the whole example should be tested.
P.S. P.S. P.S. workaround this issue is in repo as well.

**Expected behavior**
Well, no memory leak I guess :)

**Version Info**
Target version: Windows 10, version 1903
Min version: Windows 10, version 1803

**Comment by codendone** [comment]
What you're seeing here is the garbage collector.  The size of XAML objects isn't known to the GC, and the garbage collection walk for XAML objects is expensive, so the GC delays attempts to collect XAML objects as long as possible.  This can result in significant memory usage, particularly when the XAML objects involved hold on to a lot of memory (in this case, image data including the contents of the image files).  If you add a call to System.GC.Collect() at the end of your Image_Ended timer callback function, then the memory use stays stable.

Forcing garbage collection regularly is likely not a solution you want, though.  It would be better to avoid a build-up of objects which need to be collected.

One potential option is to limit to a single BitmapImage per file, such as by changing your File class to this and then using GetBitmapImage() in the places that want the image:

```
    public class File
    {
        public string LocalPath;
        private BitmapImage bitmapImage;
        public BitmapImage GetBitmapImage(Uri baseUri)
        {
            if (bitmapImage == null)
            {
                var uri = new Uri(baseUri, LocalPath);
                bitmapImage = new BitmapImage(uri);
            }
            return bitmapImage;
        }
    }
```

Using this in your sample will even help if you don't keep cycling through a few images, since this will share a single BitmapImage on the ForegroundImage/BackgroundImage elements (and the Previous* elements).

But if you're not cycling through a few images, you'll likely need to do even more.  You could avoid creating lots of XAML objects by instead swapping out the Uri on the BitmapImage, such as this:

```
    ((BitmapImage)(BackgroundImage.Source)).UriSource = uri;
```

If you have the Previous{Foreground/Background}Image elements in use, you might want to swap a couple of BitmapImage objects around, so you can simply reassign the current BitmapImage into the previous one so that the previous image doesn't need to reload due to its UriSource changing.  In other words, something like this:

```
    BitmapImage currentImage;
    BitmapImage previousImage;

    // when switching to new image:
    PreviousBackgroundImage.Source = currentImage;
    PreviousForegroundImage.Source = currentImage;

    var tempImage = previousImage;
    previousImage = currentImage;
    currentImage = previousImage;

    currentImage.UriSource = uri;
    BackgroundImage.Source = currentImage;
    ForegroundImage.Source = currentImage;
```

**Comment by aosyatnik** [comment]
Hi, @codendone . Thank you for your detailed answer. I have one more question. What if I want to use not only images, but also video files (via `MediaPlayerElement`). I assume I will need to use Stream, right? Something like this:

```
public class File
    {
        public string LocalPath;
        public IRandomAccessStream Stream; // Create it from local path.
    }
```

```
BackgroundVideo.Source = MediaSource.CreateFromStream(selectedFile.Stream);
```
Will it create any performance issue?

P.S. I can create a sample code if you need.

**Comment by codendone** [comment]
For MediaPlayerElement, I believe it will be fine and possibly more efficient to just use the Uri.  You are more in control of the memory there, with the underlying MediaPlayer being updated as soon as the Source changes.

Similar to images, you may want to pass around the underlying MediaPlayer if/when transitioning the media from current to the Previous elements.  In addition to avoiding the cost of reloading the media, this is likely necessary to prevent the video from starting over.

Another option to consider to avoid the video starting over is to not move the media or image from current* elements to Previous* elements at all, and instead just swap which set of elements are currently on top.  For example:
```
            <Grid x:Name="PreviousImageControl">
                ...
            </Grid>
            <Grid x:Name="ImageControl">
                ...
            </Grid>

        void SwitchDrawOrder()
        {
            if (Canvas.GetZIndex(PreviousImageControl) != 1)
                Canvas.SetZIndex(PreviousImageControl, 1); // move this on top
            else
                Canvas.SetZIndex(PreviousImageControl, 0); // move this to the bottom
        }   
```
Call SwitchDrawOrder() each time you want to move the current element down.  Then just update the image/media on whichever is now on top.

(Note: If you have more elements in the same container panel as the elements above, then you may need to set Canvas.ZIndex on those as well to ensure the ZIndex values provide the draw order you want.)
