### ISSUE TITLE
NavigationView Pane does not close after clicking on an item

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#2244]
**Describe the bug**
When the navigationview is in the compact mode and it is expanded using hamburger menu and an item is clicked. The navigation pane is not getting closed and it stays open. 

**Steps to reproduce the bug**

1. Reduce the windows width so as to go to medium or small mode as described [here](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview#auto)
2. Open the pane using hamburger menu
3. Click on any item
4. Pane does not close

**Expected behavior**

The pane should close

**Screenshots**

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.4.0-prerelease.200322001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | Yes   |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        | Yes   |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by Felix-Dev** [comment]
Additional info: It works fine on Microsoft.UI.Xaml 2.4.0-prerelease.200322001 and Windows 10 18363:

![navview_itemclick](https://user-images.githubusercontent.com/1398851/78610934-2a4e6700-7866-11ea-8305-f84d1a1bdc11.gif)

**Comment by harvinders** [comment]
@Felix-Dev Interesting, I use Windows Template Studio, let me try to create a sample repo app. I can't imagine that I managed to somehow enable this behaviour.

**Comment by harvinders** [comment]
I created a sample app and I can confirm it works. There must be something in my app.

**Comment by harvinders** [comment]
I made a mistake with my previous comments, I have uploaded a repo app [here](https://github.com/harvinders/App6).

**Comment by Felix-Dev** [comment]
@harvinders I get the following screen why trying to access your repro app above:
![image](https://user-images.githubusercontent.com/1398851/78656585-e8eea380-78c7-11ea-9170-ed7adcf12d83.png)
(https://github.com/harvinders/App6)

**Comment by harvinders** [comment]
@Felix-Dev 
Ah, it was private, I have made it public now. Please have a look now.

**Comment by Felix-Dev** [comment]
@harvinders Can confirm this is a new issue introduced by the newest preview (Microsoft.UI.Xaml 2.4.0-prerelease.200322001). Works fine on WinUI 2.3 and older 2.4 preview versions.

![navview_panedismiss_issue](https://user-images.githubusercontent.com/1398851/78667141-b600db80-78d8-11ea-82d0-85935d635401.gif)

In your case, pane dismiss also doesn't work for the other menu items because of the 
```xml
SelectedItem="{x:Bind ViewModel.Selected, Mode=OneWay}"
```
line in ShellPage.xaml for the NavigationView. If you remove this line, pane dismiss works for the other items (this code works fine on older WinUI versions). Settings item still broke though. 

There have been at least two changes to the NavigationView between the current and previous 2.4 WinUI preview version. From the looks of it, the buggy code probably sneaked into WinUI in one of those.

**Comment by Felix-Dev** [comment]
Further inspections show this bug was introduced in commit 5d444b6 (Hierarchical Navigation View). @ojhad for your attention.
