### ISSUE TITLE
Add a bit of padding to NavigationViewItem to avoid occluding expand/collapse chevron

### ISSUE THREAD

**Issue by ranjeshj** [microsoft/microsoft-ui-xaml#2287]
Scrollbars should not occlude the expand collapse chevron.

![navview](https://user-images.githubusercontent.com/28935693/79243035-f1942c00-7e29-11ea-863b-aa533d705846.jpg)

**Comment by Felix-Dev** [comment]
I took a look at this and I'm having a question here. This is the current XAML code for the NaigationViewItem in left mode (content and chevron):

```xml
<ContentPresenter x:Name="ContentPresenter"
    Grid.Column="1"
    Margin="0,0,16,0"/>

<Grid x:Name="ExpandCollapseChevron"
    Grid.Column="2"
    HorizontalAlignment="Right"
    Width="40"
    Margin="-16,0,0,0">
    <TextBlock
        Width="12" Height="12"
        Text="{StaticResource NavigationViewItemExpandedGlyph}">
    </TextBlock>
</Grid>
```
Why the width of 40 and the left margin of -16 for the expandCollapseChevron? 

In my experimental code, I decided to use the same right margin for the chevron which is used for the content (16) and only set the width of the parent grid of the chevron to 12 and no left margin:

```xml
<ContentPresenter x:Name="ContentPresenter"
    Grid.Column="1"
    Margin="0,0,16,0"
    Background="Blue"/>
                                
<Grid x:Name="ExpandCollapseChevron"
    Grid.Column="2"
    HorizontalAlignment="Right"
    Margin="0,0,16,0"                
    Background="Red">
    <TextBlock
        Width="12" Height="12"
    </TextBlock>
</Grid>
```

As you can see, both the ContentPresenter and the expandCollapseChevron grid now use the same right margin (16). This gives the following result (with background colored for better visibility):
![image](https://user-images.githubusercontent.com/1398851/79258673-cb9f7380-7e8b-11ea-863b-708def3f4222.png)

and with scrollbar extended:
![image](https://user-images.githubusercontent.com/1398851/79258742-e671e800-7e8b-11ea-9c5a-7a9583aa2ffc.png)

Is this a possible solution or do we have to work with the current XAML which uses a left margin of -16 and a width of 40 for the chevron grid?

**Comment by ranjeshj** [comment]
@ojhad for the negative margin question.

**Comment by ranjeshj** [comment]
The entire chevron and hit target associated with it should move so that it is offset from the expanded scrollbar by 4 pixels. Can you share a picture of that with and without the scrollbar. This looks like an issue everywhere because the ScrollBar always seems to occlude the content. The problem with moving the chevron is that when there is no scrollbar, the chevron is going to look too far from the right.

**Comment by Felix-Dev** [comment]
@ranjeshj Using a margin of 16 (scrollbar thickness) + 4 (padding) = 20 gives the following images (margin the same for the content presenter and the chevron):

![image](https://user-images.githubusercontent.com/1398851/79275168-fdbdcf00-7ea5-11ea-86c2-1c006d9e7466.png)

![image](https://user-images.githubusercontent.com/1398851/79275203-0d3d1800-7ea6-11ea-93d2-53c392a87d4c.png)

![image](https://user-images.githubusercontent.com/1398851/79274984-ac154480-7ea5-11ea-9a0d-2c6e9a9cec77.png)

![image](https://user-images.githubusercontent.com/1398851/79275016-ba636080-7ea5-11ea-8e9c-71fff9a1a773.png)

As you said, it's also a problem for the compact mode with pane collapsed:
![image](https://user-images.githubusercontent.com/1398851/79273961-162cea00-7ea4-11ea-8bb8-a2b689e8ea4d.png)

**Comment by widersky** [comment]
Scroll bars needs visual overhaul IMO to be less distracting at all. And, of course, rounded :)

**Comment by ranjeshj** [comment]
@widersky  - I think that was already proposed [here](https://github.com/microsoft/microsoft-ui-xaml/issues/987) atleast the rounded part. 

@Felix-Dev, can you also add a picture without the indicator (not scrollable at all). I think the sliver will just go away in that case. 
@chigy do the pictures look reasonable to make this update ?

**Comment by Felix-Dev** [comment]
@ranjeshj
![image](https://user-images.githubusercontent.com/1398851/79336345-defe1d80-7f23-11ea-84d0-0f48021fe823.png)

**Comment by chigy** [comment]
> @ranjeshj
> ![image](https://user-images.githubusercontent.com/1398851/79336345-defe1d80-7f23-11ea-84d0-0f48021fe823.png)

@Felix-Dev , could you show the entire list not just snapshot?

**Comment by Felix-Dev** [comment]
@chigy 
![image](https://user-images.githubusercontent.com/1398851/79362445-e5ea5780-7f46-11ea-8b21-dc98eacd6df3.png)

Let me know if you need more images.

**Comment by chigy** [comment]
@Felix-Dev , is this update something we can run and try out? Hard to figure out the experience with image alone.

**Comment by Felix-Dev** [comment]
@chigy I uploaded my current code in a branch of my WinUI fork [here](https://github.com/Felix-Dev/microsoft-ui-xaml/tree/user/Felix-Dev/navviewitem-padding). You can try to compile that branch (or ask the team to do that) and see the current padding live. Unfortunately, I could not create an app package of the WinUI TestApp, which I've been showing in all the pictures above, and upload that on Github. The images are taken from the [NavigationView] page and the sub page [Hierarchical NavigationView Markup Test].

Below you see the entire page in action:
![image](https://user-images.githubusercontent.com/1398851/79477685-c87ec180-800a-11ea-9cd4-c46f31e1febb.png)

![image](https://user-images.githubusercontent.com/1398851/79477734-da606480-800a-11ea-9716-e7ec8383517d.png)

![image](https://user-images.githubusercontent.com/1398851/79477805-f19f5200-800a-11ea-818f-1910ecb6ac0b.png)

**Comment by chigy** [comment]
@Felix-Dev , thank you for that. Please go ahead with the value you have in the image.

**Comment by Felix-Dev** [comment]
> Why the width of 40 and the left margin of -16 for the expandCollapseChevron?

That question has been resolved (just as an information).

**Comment by ojhad** [comment]
> Why the width of 40 and the left margin of -16 for the expandCollapseChevron?
> 

Apologies for the delayed response.

The chevron is considered a separate hit target. It is a way of expanding an item without having to select the item itself. This is why I gave it a width of 40, to allow for a larger hit target.
I don't think we want to be reducing that hit target to only the size of the chevron. It might frustrate some users who will specifically only want to hit the chevron.

The negative margin was a way to visually move this hit target, otherwise there was too much space being displayed between the item content and the chevron.

**Comment by Felix-Dev** [comment]
@ojhad Agree. In my initial testing (using the MUXControlsTestApp) clicking *everywhere* on the NavigationViewItem expanded/collapsed the chevron which is why I was wondering about the separate hit target. However, there are scenarios where clicking the NavigationViewItem only selects the item and to expand the item, the chevron hit area has to be clicked. In this case, a hit target width of 40 makes a lot of sense.

I will work with the negative margin and the width of 40 when updating the resource values to prevent the chevron from being occluded by the extended scrollbar.

**Comment by Felix-Dev** [comment]
@chigy Sorry to bother you again but since I'm now working with the original settings (negative margin and hit test area of 40px) I would feel better if you could quickly look over the padding solution below to see if it still conforms with the desired design. 
I'm adding a padding of 6px to the right for the chevron hit test area to get a 4px padding between the actual chevron and the extended scrollbar. This matches the visuals I showed in the previous posts. (Currently, there are 14px to the right of the actual chevron symbol so an an extended scrollbar of 16px occludes 2px of it. In order to get the desired 4px padding between chevron symbol and extended scrollbar, I thus add a padding of 6px to the right of the chevron's hit area.) Sample images below:

![image](https://user-images.githubusercontent.com/1398851/80279353-6d7d5680-86fd-11ea-8760-b010900f943e.png)

![image](https://user-images.githubusercontent.com/1398851/80279361-779f5500-86fd-11ea-8743-6c8c5cc64036.png)

The image below shows the hitbox area of the chevron in red (note the 2px padding between chevron hit area and shrunk scrollbar):

![image](https://user-images.githubusercontent.com/1398851/80278415-4b340a80-86f6-11ea-9f26-d83c333166ee.png)

A WinUI Github fork with that change is [here](https://github.com/Felix-Dev/microsoft-ui-xaml/tree/user/Felix-Dev/navviewitem-padding-6px).

Question: Should the ContentPresenter of the NavigationViewItem also get a 4px padding to the right between it and the expanded scrollviewer? (In the images of my earlier posts, the ContentPresenter also had this padding added to make it's text "edge" align visually with the chevron smybol.) Currently, the ContentPresenter has a padding of 16 which is just enough to not be partially occluded by the extended scrollbar.

Below are images showcasing the increased padding by 4px for a total of 20px (16px + 4px) for the ContentPresenter (the padding between ContentPresenter and chevron is unchanged):

![image](https://user-images.githubusercontent.com/1398851/80287394-afc08b00-8731-11ea-8d05-8e7a90e2b6fe.png)

![image](https://user-images.githubusercontent.com/1398851/80287403-bb13b680-8731-11ea-95aa-6d3bb6cb343e.png)

A WinUI Github fork with that change included is [here](https://github.com/Felix-Dev/microsoft-ui-xaml/tree/user/Felix-Dev/navviewitem-padding-6px-with-contentpresenter-alignment).

**Comment by chigy** [comment]
@Felix-Dev , sorry but I am not quite sure exactly what you are asking. Are you asking if the chevron should be moved additional 4px to the left? Also, you are asking if the hit target should be shrunk by 4px so that it doesn't overlap the expanded scrollbar?

I am not too worried about hit target overlapping or not since the experience is likely not going to be impacted either way, however things I am curious about is if the chevron hit target is at least 40x40px and also if the hit target is overlapping of the space where mouse hover in that area makes the scrollbar to expand or not.

**Comment by Felix-Dev** [comment]
@chigy One question I had is if I should also add 4 additional pixel as padding to the NavigationViewItem's ContentPresenter to align it visually with the chevron. (That's the difference in the images above. In the first three images the chevron and the navviewitem content are not aligned visually to the right (text goes a bit more to the right until cut off). In the last two images, chevron and content is visually aligned.)

As for the hit test area of the chevron: Yes, it is still 40x40px wide. 
It also does overlap with the space where mouse hover expands the scrollbar. See this gif:
![navview-chevron-scrollbar-overlap](https://user-images.githubusercontent.com/1398851/80398081-64d08000-88b7-11ea-9332-a7842d507d99.gif)

Should this be changed? If yes, I will need to add some more padding to the chevron's hit area (and then the question is again if I should add that padding to the content presenter as well to visually align chevron and NavigationViewItem content.)

**Comment by chigy** [comment]
@Felix-Dev , yes, please visually align the chevron and the NavigationViewItem's _ContentPresenter_ as you suggest. Unfortunate about the hover overlapping but I don't think there is a feasible option without making the visual to be less optimal, so please keep it be.

**Comment by rcohn** [comment]
Hello @ranjeshj  and @Felix-Dev  -

I'm trying to solve a problem in which for some cases clicking on the expand/collapse NavigationViewItem chevron in my app does not get recognized.  Ie, for these cases, my NavigationViewItem does not get a PointerPressed event until I click closer to the item text content (to the left of the chevron), and then I can expand/collapse the item.

I've been trying to come up with a simple app that demonstrates this, but so far the simple apps all work as expected!

Anyway, I've been trying to understand your ContentProvider code above.  It appears that you can control where the chevron appears and other properties of the chevron with this provider.  But I don't understand how the content (the leftmost image + text) can be separate from the chevron; I thought those were all part of the same NavigationViewItem.  Can you explain how this is designed or at least point me to some sample code showing a working example (such as the MUXControlsTestApp).

I may be looking for a solution that is a workaround for my own faulty implementation and maybe that's the wrong approach, but at the moment moving the chevron to the left seems to be a possible solution.

Your help would be much appreciated.

Thank you.

**Comment by ranjeshj** [comment]
@rcohn you can look at https://github.com/microsoft/WinUI-Gallery for samples/usage. There is also the WinUI 2 Gallery and WinUI 3 Gallery apps in the store to try them out.
