### ISSUE TITLE
Connected animation break down the app without exception

### ISSUE THREAD

**Issue by h82258652** [microsoft/microsoft-ui-xaml#2296]
**Describe the bug**

With some conditions, the connected animation will break down the app without any exceptions.

**Steps to reproduce the bug**

1. The animation source is an Image control and the source is a gif image.
2. The animation target opacity property set to zero.
3. During the connected animation, set source opacity property to zero.

**Expected behavior**

The connected animation should work and the app will not break down.

**Version Info**

Windows 10 Home 18362.720
18362 SDK

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            | Yes  |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

The source code is here: https://github.com/h82258652/ConnectedAnimationServiceBugDemo

**Comment by codendone** [comment]
Thanks for minimal repro!  This issue recently popped up in our crash data ([internal link](https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/19224095/
)).  As you found, the problem is that if the source or target element isn't visible on the next frame (such as due to Opacity=0), then Connected Animations try to no-op but leave some incorrect state which results in an uncatchable crash.  This is a bug, which we can fix in WinUI 3.

The workaround is to ensure the elements stay visible, or to avoid starting a Connected Animation which would end up being a no-op.

**Comment by bpulliam** [comment]
If you are still seeing this issue, please let us know.  Thanks!
