### ISSUE TITLE
Question: latest ProgressRing version and future development

### ISSUE THREAD

**Issue by jp-weber** [microsoft/microsoft-ui-xaml#2340]
Due to the latest changes in the preview there are breaking changes. So setting values for progress is no longer possible. My question here would be whether there are plans for further development in this regard, or whether setting progress values for the element in the long term is no longer necessary.

**Comment by ranjeshj** [comment]
@jp-weber, the early pre-release versions had the determinate part but we decide to pull it out since there were some open questions regarding the visuals and compatibility with the version of the same control in Windows.UI.Xaml. In WinUI3, this will replace the Windows.UI.Xaml.ProgressRing so it has to be compatible with the inbox control in order to avoid breaking apps that move to WinUI3. We are working towards resolving the issues with the determinate part. @MarissaMatt as FYI.

**Comment by jp-weber** [comment]
Thank you very much for the explanation. Then I am really looking forward to the coming versions 😀

**Comment by chingucoding** [comment]
@jp-weber With #2584, the determinate mode for the ProgressRing was added back again (now with lottie animations!).

**Comment by jp-weber** [comment]
@chingucoding  Oh great, thanks for the hint😃 Then I am looking forward to the next pre release.
