### ISSUE TITLE
Don't require targetversion to be latest for Class Libraries

### ISSUE THREAD

**Issue by dotMorten** [microsoft/microsoft-ui-xaml#2397]
**Describe the bug**
When building a class library, the target version should not matter, as long as it's at least minversion. That check should only apply to app projects.

This check is done here and should have a condition for class libraries to ignore it (or check that target is at least minversion):
https://github.com/microsoft/microsoft-ui-xaml/blob/8f8cd0fe32754cfcd83dafb2fc8539703b6aec26/build/NuSpecs/MUXControls-Nuget-Common.targets#L16-L18

**Steps to reproduce the bug**
1. Create a .NET Class Library and set target version to 17134.
2. Add WinUI nuget package.
3. Build

**Expected behavior**
Build succeeds

**Actual behavior**
Build error:
```
C:\Users\username\.nuget\packages\microsoft.ui.xaml\2.3.191211002\buildTransitive\Common.targets(16,5): error : Microsoft.UI.
Xaml nuget package requires TargetPlatformVersion >= 10.0.18362.0 (current project is 17134) [E:\src\myclasslibrary.csproj]
```

**Version Info**
2.3.191211002

**Comment by ranjeshj** [comment]
@jevansaks @llongley any ideas why 19H1 is required ?

**Comment by jevansaks** [comment]
Agree that the check for class libraries could be different. This check is serving two purposes:
1. For apps, it makes sure that you are running against a version high enough that we won't get "quirked" behavior from OS XAML.
2. For apps and class libraries, it's trying to avoid a confusing error message down the line because the WinUI WinMDs reference types in the Windows SDK that weren't introduced until later versions of Windows.

Now for class libraries the #2 check still needs to be there, but perhaps the Windows SDK we require can be lowered?

I think if someone can suggest a fix here that covers all the various project types we would be happy to accept it.

@dotMorten is there a challenge in having your class library target the 18362 SDK?

**Comment by dotMorten** [comment]
> is there a challenge in having your class library target the 18362 SDK?

I prefer keeping min and max version the same. This to avoid having to ensure we don't call APIs that aren't supported on that platform. If I don't need the latest features, why enable them?

I don't really get your second point. Why is it confusing to not see APIs that you can't call on the version you're targeting?

**Comment by jevansaks** [comment]
The problem is that the WinUI metadata has types it references that weren't introduced until a later version of the Windows SDK. You will get a bizarre compiler error about not being able to resolve types if you disable the check and target too old of a Windows SDK.

**Comment by dotMorten** [comment]
I’m ok with closing this
