### ISSUE TITLE
SplitView placement right + displayMode CompactOverlay doesn't work

### ISSUE THREAD

**Issue by StephenLPeters** [microsoft/microsoft-ui-xaml#2410]
in the Xaml Controls Gallery Split View page set the placement to right and the display mode to CompactOverlay and notice that the content is clipped.  Its possible this is a XCG bug, since changing the OpenPaneLength and CompactPaneLength can reveal the content if the correct settings are chosen.

**Comment by shaheedmalik** [comment]
#2392

**Comment by ranjeshj** [comment]
#2392 looks related but this could be another similar issue in the style.

**Comment by chingucoding** [comment]
I think this is an issue with the XAML Controls Gallery. The content inside the pane has a lot of right padding. Since the content gets positioned to the left of the right border, by "coincidence" we show essentially nothing. If we have content in there that has no right padding, and instead content, there won't be this lack of content.

**Comment by chingucoding** [comment]
@StephenLPeters @stmoy Should we close this issue since this is an issue with the XCG SplitView sample which is also being tracked by https://github.com/microsoft/Xaml-Controls-Gallery/issues/322?

**Comment by StephenLPeters** [comment]
Sure, sounds good.
