### ISSUE TITLE
TeachingTip buttons are not following CornerRadius guidelines

### ISSUE THREAD

**Issue by JuanMejiaVelez** [microsoft/microsoft-ui-xaml#2411]
**Describe the bug**

As part of the recent Fluent UI guidelines most controls on windows have CornerRadius values set so that they are rounded. Button is one of such control, although the buttons that are shown in the UI for Teaching tip are not following this.

**Steps to reproduce the bug**

1. Create a new UWP app
2. Add a teaching tip to the page and make it visible.

`<muxc:TeachingTip x:Name="SampleTeachingTip"
                        PreferredPlacement="Auto"
                        ActionButtonContent="Apply"
                        CloseButtonContent="Close"
                        Title="This is teaching tip"
                        Content="This is the content"
                        IsLightDismissEnabled="False">
        
 </muxc:TeachingTip>`

**Expected behavior**

Buttons are rendered with rounded corners

**Screenshots**

![image](https://user-images.githubusercontent.com/13546698/81355497-93064a80-9083-11ea-86f9-86778a63fa74.png)

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml 2.4.0-prerelease.200506001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19041.21)              | Yes   |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by ranjeshj** [comment]
Looks like some of the buttons don't get rounded corners, especially in popups/dialogs.

**Comment by robloo** [comment]
Related to #1345

**Comment by mdtauk** [comment]
Do they not use the default control templates?

**Comment by robloo** [comment]
This issue is present in the latest version of the XAML controls gallery as well.

![image](https://user-images.githubusercontent.com/17993847/81502869-acd7a580-92ae-11ea-87e2-9976af7c77a2.png)

**Comment by robloo** [comment]
I took a look at the XAML: https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/TeachingTip/TeachingTip.xaml

I don't know the control at all, but it looks like the problem is here:

https://github.com/microsoft/microsoft-ui-xaml/blob/9b99426c9c2846468f1f420b595273b1631072ec/dev/TeachingTip/TeachingTip.xaml#L574

and

https://github.com/microsoft/microsoft-ui-xaml/blob/9b99426c9c2846468f1f420b595273b1631072ec/dev/TeachingTip/TeachingTip.xaml#L580

Both `ActionButtonStyle` and `CloseButtonStyle` are not defined in XAML from what I can see -- so don't know where to go to fix this. These may be copy/pasted from the ContentDialog. Someone with knowledge of the control will have to say how to update these two styles to respect the corner radius (or base on the latest button style with rounded corners).

**Comment by chingucoding** [comment]
Yes the problem are those two styles, which are probably "empty" (and might contain corner radius = 0 because of that).

A way we could fix this is adding the following line (in case of ActionButton, other buttons are similiar):

```xaml
        <Setter Property="ActionButtonStyle" Value="{ThemeResource DefaultButtonStyle}" />
```

I am not sure though if there would be side effects if we do this. 

Also what is a bit confusing, is that there are properties on the TeachingTip control for those, but yet we are binding the button styles using `TemplateBinding`. Shouldn't we use the template properties instead?

**Comment by robloo** [comment]
@chingucoding Good catch, I hadn't checked and these are dependency properties of the control so they can be re-styled without retemplating.

This means the code should be "Binding" instead of "TemplateBinding" -- this is a bug. Then the default value of the DP should be the standard DefaultButtonStyle. We shouldn't create new styles for these buttons. They are supposed to look like normal buttons in this case from what I see.

**Comment by chingucoding** [comment]
@ranjeshj Shouldn't we expose the ActionButtonStyle and CloseButtonStyle in the template settings? Currently there are these properties on the TeachingTip class, but they are not used at all. Shouldn't those do something?

**Comment by ranjeshj** [comment]
@StephenLPeters as FYI.

**Comment by mdtauk** [comment]
> @ranjeshj Shouldn't we expose the ActionButtonStyle and CloseButtonStyle in the template settings? Currently there are these properties on the TeachingTip class, but they are not used at all. Shouldn't those do something?
>

I would suggest every control that contains templated parts or sub controls - should expose any styles of templates to the control proper.

**Comment by ranjeshj** [comment]
TemplateSettings are usually readonly. If the control has these style properties already, I would expect it to be wired up to the template. If we did not have these properties, one option could be use theme resources like we use for brushes.
