### ISSUE TITLE
AppBarButton CornerRadius is not properly applied to the background bottom corners

### ISSUE THREAD

**Issue by ivanicin** [microsoft/microsoft-ui-xaml#2423]
**Describe the bug**
The border is always painted properly. However the background is not - at the top it is clipped by rounded corners but at the bottom it goes beyond the rounded corners (unless the CommandBar is expanded).

Just setting the background and cornerradius will result in this:                 
`<AppBarButton Icon="Add"  Background="{ThemeResource SystemAccentColor}" Foreground="White" CornerRadius="8"/>`

**Steps to reproduce the bug**

1. Just use the code above

**Expected behavior**
The rounded corners should be proper

**Screenshots**

**Version Info**

NuGet package version: 
2.4.0

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes  |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by chingucoding** [comment]
I think this is more an issue with how the commandbar renders the AppBarButtons. What it does is render them at full height, but cut them off, resulting in the behavior outlined. 

While generally it is discouraged to apply cornerradius in that case (T-rule: Don't round corners that are at two elements touching each other and forming a T with their borders), this is still a bug.

The only way we probably can fix this is to change the rendering behavior of CommandBar and the included AppBarButtons.

**Comment by ivanicin** [comment]
@chingucoding while I agree with you, please note that corner radius renders border properly (if set). So it should be technically possible and fairly easy to have a proper behavior.

Also that design rule interpretation is hard to agree with as there are no borders visible in the default template, so there are no T lines in the default state. If you decide to accent one control this way it can't be against any guideline.

**Comment by chingucoding** [comment]
> @chingucoding while I agree with you, please note that corner radius renders border properly (if set). So it should be technically possible and fairly easy to have a proper behavior, this rather seems like an omission in implementation than some technical problem that has caused this.

The problem is that the reveal border is rendered on a different part of the control than the background, hence the clipping issues. Also I assume that you only experience this issue inside a commandbar? Just having that button without a commandbar works just fine on my machine, so maybe you could update your issue description to reflect the exact scenario where you encounter this clipping issue.




> Also that design rule interpretation is hard to agree with as there are no borders visible in the default template, so there are no T lines in the default state. If you decide to accent one control this way it can't be against any guideline.

The T-Rule is not about visible borders (e.g. 1px red) but more about the concept of control borders. If you put two elements exactly next to each other, they would share a border (and form a T with their, and in that case corner radius should be avoided. In the default state, that is indeed not a problem, but I couldn't repo the bug in the "standalone" state. In the case of commandbar it's a bit difficult since there is a small gap, so maybe I am wrong with "you shouldn't use corner radius".

**Comment by ivanicin** [comment]
> The problem is that the reveal border is rendered on a different part of the control than the background, hence the clipping issues. Also I assume that you only experience this issue inside a commandbar? Just having that button without a commandbar works just fine on my machine, so maybe you could update your issue description to reflect the exact scenario where you encounter this clipping issue.

I have mentioned CommandBar in the description, I would assume it is enough, also to confirm that it is required to reproduce the issue.

I am not talking just about the reveal border but also setting the border itself. It works with the corner radius when it is set. Obviously it is a different element than the background but technically there can't be huge differences to achieve the proper implementation.

**Comment by chingucoding** [comment]
> I have mentioned CommandBar in the description, I would assume it is enough, also to confirm that it is required to reproduce the issue.

I assumed that the behavior was inherently broken, not only in CommandBar since you only said it works in the expanded CommandBar.

> I am not talking just about the reveal border but also setting the border itself. It works with the corner radius when it is set. Obviously it is a different element than the background but technically there can't be huge differences to achieve the proper implementation.

Oh right I see. Yes that's strange. Having looked at the template quickly, the wiring of the binding mostly seems correct. Someone probably has to take a close look where exactly is rendered what.

**Comment by ranjeshj** [comment]
Can you please share some pictures ? That would really help understand the issue at hand. Thanks!

**Comment by ivanicin** [comment]
> 
> 
> Can you please share some pictures ? That would really help understand the issue at hand. Thanks! @chigy as FYI

![screenshot](https://user-images.githubusercontent.com/20874207/81612834-bdd30480-93dd-11ea-8f92-f72310141188.png)
Sure, I omitted to add it to the original post by mistake.

**Comment by chigy** [comment]
@ivanicin , per rounding [corner guideline](https://docs.microsoft.com/en-us/windows/uwp/design/style/rounded-corner), we do not round corners of appbar buttons that are used inside command bar. This is because we do not want to show an awkward gap between the items when the items are next to each other, thus we do not round list and grid items. 

I wonder why you decided to round the corner here? What outcome are you trying to achieve with it so I can understand if it is a scenario we should be fully supporting? Please note that we do not support every rounded corner case because we want them to be meaningful. We currently do not fully support very round corner like you show here. It will likely not look good with keyboard focus overlaid on top if it. It is also mentioned int he guidance.

**Comment by ivanicin** [comment]
> 
> 
> @ivanicin , Thanks! Per rounding [corner guideline](https://docs.microsoft.com/en-us/windows/uwp/design/style/rounded-corner), we do not round corners of appbar buttons that are used inside command bar. This is because we do not want to show an awkward gap between the items when the items are next to each other, thus we do not round list and grid items.
> 
> I wonder why you decided to round the corner here? What outcome are you trying to achieve with it so I can understand if it is a scenario we should be fully supporting? Please note that we do not support every rounded corner case because we want them to be meaningful. We currently do not fully support very round corner like you show here. It will likely not look good with keyboard focus overlaid on top if it. It is also mentioned int he guidance.

First there is no need to discuss whether this is the bug or not, it is. If the background and border act differently on corner radius one of those is wrong, which one is right we can discuss on that, though at least for me it is more than obvious.

Second, I don't see the point of the question why I need some specific style. Microsoft went from Windows Forms to WPF and XAML exactly because any style is legitimate. You may put some guidelines but one may or may not respect them (and I even respect it, but really don't want to talk on this topic).

Third, asking why one would need to accent one button is something that can hardly be accepted as legitimate question more than why one uses a button. For example below this form that I use the 'Comment' button is accented, and this form appears in literary million forms of UI design.

Fourth, that particular guideline you try to relate to cannot be applied on this case. First CommandBar has space between the buttons so this can't be applied. Second AppBarButton is transparent so even if those controls touched each other this can't be applied.

**Comment by chigy** [comment]
@ivanicin , I apologize for tardiness in response. Your comment just came as we were heads down for //Build prep, etc., vacation, and other project that took my time, I just had time to sit down to reproduce your issue.

_First_
I applied your code snippet and I am not seeing the issue. Maybe I'm doing something wrong. @ranjeshj FYI.

![image](https://user-images.githubusercontent.com/22958680/83820923-c936ea00-a682-11ea-8750-cd5467092a58.png)

_Second_
You are right, we can provide guidance and one may not respect them. And I think it is healthy and we respect that. However we also do not have infinite resources to fix issues and we do take what we guide people to do as one of the ways to prioritize our work.

_Third_
Apologize if there was a miscommunication, but I was not questioning use of accent color.

_Forth_
Fair enough. Whether legitimately or not, we do design CommandBar and CommandBarFlyout to be as close to the design as possible. CommandBarFlyout, because it is a flyout, does have the gap issue so thus this was not applied to CommandBar either.

Thank you very much for sharing the early concept and working with us.

**Comment by ivanicin** [comment]
@chigy I agree with your points, good to know that we are on the same line. As we've talked about the design I am more likely to apply some different designs (though again they might have different issues to work with: https://github.com/microsoft/microsoft-ui-xaml/issues/2552 ), but no matter of that this remains as a bug and I've insisted exactly on that this is the bug question, not the design question.

I've tried to reproduce it again and it is still reproducible with latest stable version of WinUI. If you are using some development version and it is fixed there, that is a good news.

I am using just the code above with usual boilerplate, but in the case it is needed to reproduce, here is a complete page:

```
    <Grid>
        <CommandBar>
            <AppBarButton Icon="Add" Background="{ThemeResource SystemAccentColor}" Foreground="White" CornerRadius="8"/>
            <AppBarButton Icon="Add"/>
        </CommandBar>
    </Grid>
```
