### ISSUE TITLE
GridView not visible in GUI when Visibility of first GridViewItem is set to collapsed

### ISSUE THREAD

**Issue by SynChLa** [microsoft/microsoft-ui-xaml#2444]
**Describe the bug**
I am currently struggling with a bug or an unexpected default behaviour of the GridView in Cpp/WinRT. A minimal working example is given below. This code does not show the GridView at all.

**Steps to reproduce the bug**
XAML:
```XAML
<Page
    x:Class="GridViewTest.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:GridViewTest"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <Grid>
        <GridView x:Name="PartGrid" Loading="initGrid" Loaded="initGridGeometry" HorizontalAlignment="Center" VerticalAlignment="Center">
            <GridView.ItemTemplate>
                <DataTemplate>
                    <Rectangle Margin="20" Fill="Black"/>
                </DataTemplate>
            </GridView.ItemTemplate>
        </GridView>
    </Grid>
</Page>
```

Cpp-Header:
```Cpp
#pragma once

#include "MainPage.g.h"

namespace winrt::GridViewTest::implementation
{
  struct MainPage : MainPageT<MainPage>
  {
    MainPage();
    void initGrid(Windows::UI::Xaml::FrameworkElement const& sender, Windows::Foundation::IInspectable const& args);
    void initGridGeometry(winrt::Windows::Foundation::IInspectable const& sender, winrt::Windows::UI::Xaml::RoutedEventArgs const& e);
  private:
    const size_t numRows = 2;
    const size_t numCols = 2;
    std::vector<bool> gridVisibility = { false, true, true , true };
  };
}

namespace winrt::GridViewTest::factory_implementation
{
    struct MainPage : MainPageT<MainPage, implementation::MainPage>
    {
    };
}
```
Cpp-Code:
```Cpp
#include "pch.h"
#include "MainPage.h"
#include "MainPage.g.cpp"

using namespace winrt;
using namespace Windows::UI::Xaml;

namespace winrt::GridViewTest::implementation
{
  MainPage::MainPage()
  {
      InitializeComponent();
  }

  void MainPage::initGrid(FrameworkElement const& sender, IInspectable const& args)
  {
    std::vector<IInspectable> elements(numRows * numCols);
    auto partGridElements = single_threaded_observable_vector<IInspectable>(std::move(elements));
    PartGrid().ItemsSource(partGridElements);
    PartGrid().UpdateLayout(); // needed to initialize ItemsWrapGrid?
  }

  void MainPage::initGridGeometry(IInspectable const& sender, RoutedEventArgs const& e)
  {
    auto geom = PartGrid().ItemsPanelRoot().as<Controls::ItemsWrapGrid>();
    if (geom)
    {
      //define geometry: rows/cols
      geom.MaximumRowsOrColumns(numCols);
      geom.Orientation(Controls::Orientation::Horizontal);

      //define geometry: make grid elements invisible
      uint32_t k = 0;
      for (uint32_t i = 0; i < numRows; ++i)
      {
        for (uint32_t j = 0; j < numCols; ++j)
        {
          auto item = PartGrid().ContainerFromIndex(k).as<Controls::GridViewItem>();
          if (item)
          {
            if (!gridVisibility[k])
              item.Visibility(Visibility::Collapsed);
          }
          ++k;
        }
      }
    }
  }
}
```

**Expected behavior**
The idea is to be able to collapse some of the grid elements to create different patterns on this GridView. If one changes the vector `gridVisibility = { false, true, true , true };` to `gridVisibility = { true, false, true , true };` everything works perfectly and the corresponding grid element is collapsed. It seems that anytime the first GridViewItem is not visible, the whole grid disappears. Any help or suggestions would be highly appreciated. Thanks in advance!

**Version Info**

NuGet package version: 
Microsoft.Windows.CppWinRT 2.0.200316.3

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |  Yes   |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by ranjeshj** [comment]
@SynChLa  
you should not have to call UpdateLayout on initGrid.
You can also set the ItemsWrapGrid properties in Markup
```
<GridView.ItemsPanel>
   <ItemsPanelTemplate>
       <ItemsWrapGrid Orientation=.. MaxRowsOrColumns=..  />
```

The issue is that you are trying to set the visibility of the container. ContainerContentChanging might be a better event to handle that because that will get called when containers are recycled.

Depending on what you are trying to achieve ItemsRepeater might provide you a simpler option because there is no container as part of it, so you can just bind the visibility to the data in that case or use the ElementPrepared event.

**Comment by SynChLa** [comment]
@ranjeshj 
Thank you for the quick response. The number of columns and rows and the GridViewItem visibility are set flexible (by a user/file/server) during execution time. Therefore i can not define this information in XAML. As far as I understood your answer, you are suggesting a work around? Could you present further details on this? What should be handled on ContainerContentChanging? Does an ItemsRepeater offer the same functionality as a GridView. Can I set the number of rows/columns? It is essential that there are invisible (non-select able) grid elements between visible ones in a grid with defined number of rows and columns. Additionally scrolling in the grid is required.

In any case I would like to now if this is a bug or the expected default behavior.

**Comment by ranjeshj** [comment]
The likely reason why you are seeing thing disappear is because you are setting visibility during initialize which gets called once, but the GridView recycles its GridViewItems, so it will not stay up to date when items are recycled. You will also need to set the visibility of GridViewItems in ContainerContentChanging event which gets called during recycling.

ItemsRepeater is more of a building block so it does not provide all the features of GridView, so it depends on what you need. UniformGridLayout has a MaxRowsOrColumns which might be what you need to use with ItemsRepeater. ItemsRepeater does not support selection out of the box, so you will have to do some work there.

**Comment by SynChLa** [comment]
@ranjeshj 
I just added the ContainerContentChanging event. The behavior does not change and the problem remains. 

Please note that the solution stated in the beginning works in all cases except those where the first item is set to collapsed. To me this definitely looks like a bug or an unexpected default behavior.

If possible i would like to stick with the GridView instead of implementing a separate solution. Otherwise i would basically just reimplement the GridView functionality by hand without knowing if this actually solves the problem.

So the questions remains: Is the GridView intended to behave like this or not?

**Comment by ranjeshj** [comment]
Just tried the repro. The issue seems to be that you set visibility of the first item to false. ItemsWrapGrid uses the size of the first item to size all its items. Can you try setting  ItemsWrapGrid.ItemWidth/Height properties so that ItemsWrapGrid uses that to size its items instead of the first item ?

**Comment by SynChLa** [comment]
@ranjeshj 
Thank you for the repro. I just tested your suggestion. Setting the ItemsWrapGrid.ItemWidth/Height in XAML does not work for me. But if I set it in the the Cpp Code it works. I just added the lines:
`geom.ItemHeight(60);`
`geom.ItemWidth(60);`
Of course I will have to add an extra resource in XAML to make the size settable there. Your suggestion will work for me as a work around. Thank you very much!

However i am still unsure if this default behavior is reasonable. Fixing the item size will work for me, but may not always be a possible solution. Maybe you can decide on that and close the issue if you don't think further work is necessary.

**Comment by ranjeshj** [comment]
@SynChLa glad to hear that worked. ItemsWrapGrid sizing all its items based on the first item's size (by default) when ItemWidth/ItemHeight is not provided is by design.

Looking at the documentation for ItemsWrapGrid, that information is not clear. @anawishnoff can you please help update the docs here ?
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.itemswrapgrid?view=winrt-19041

If your ItemWidth/ItemHeight is only available at runtime, setting it in code seems reasonable. If it is a constant or a resource, then setting it from markup should give you the same behavior.
