### ISSUE TITLE
WinUI3 Desktop App with extended client area

### ISSUE THREAD

**Issue by Rodricula** [microsoft/microsoft-ui-xaml#2530]
Hello,

Experimenting with the preview 1 of WinUI3 in a Win32 context, I realized that the application uses the standard hwnd titlebar. Is it (or will it be) possible to use the UWP style titlebar in Win32 so that one can extend the client area all over the titlebar (for stuff like browser tabs as in Edge or the back-arrow-control?)

Thanks in Advance!

**Comment by ShankarBUS** [comment]
Would be better if some tool like **WindowChrome** (available in WPF) is provided

**Comment by MikeHillberg** [comment]
This won't be supported for Desktop apps in the first release of WinUI3.

Part of having a custom title bar is that you still be able to grab it with a mouse and drag the window around. You can do this with WinUI in a UWP (CoreWindow) app by using [Window.SetTitleBar](https://docs.microsoft.com/uwp/api/Windows.UI.Xaml.Window.SetTitleBar) to identify the drag element. That's disabled now for WinUI3 running in a Desktop app, and won't be reenabled yet in 3.0. The technical difficulty is that the window dragging is handled inside the system, and with V3 WinUI is a standard framework instead of part of the OS.

**Comment by Rodricula** [comment]
Okay, thanks for the info.
