### ISSUE TITLE
Invalid link in documentation 

### ISSUE THREAD

**Issue by ibonhub** [microsoft/microsoft-ui-xaml#2543]
**Describe the bug**

Invalid link in documentation "Introduction to Windows app design"

**Steps to reproduce the bug**

1. Go to https://docs.microsoft.com/en-us/windows/uwp/design/basics/design-and-ui-intro
2. Click on ' Guidelines for tile and icon assets.'
![image](https://user-images.githubusercontent.com/65885231/82781891-b262ed00-9e63-11ea-9dd9-3db0167d0f3c.png)

3. Get the error 404.
![image](https://user-images.githubusercontent.com/65885231/82781947-d7eff680-9e63-11ea-9338-c6be994c5bde.png)

**Comment by Felix-Dev** [comment]
@ibonhub I created a PR [here](https://github.com/MicrosoftDocs/windows-uwp/pull/2483) to fix this. 

Please note that this is wrong repo, UWP documentation issues (especially issues like broken links) should be posted in the [UWP Documentation repo](https://github.com/MicrosoftDocs/windows-uwp). Also note that from my experience, creating a PR fixing this issue instead of just creating an issue on Github will definitely see the fix land into the official UWP documentation much faster. The Windows Docs team made it really easy to create such PRs by including an [Edit] button in the documenation:
![image](https://user-images.githubusercontent.com/1398851/82797205-0e833c80-9e77-11ea-95fe-ff890453cd2c.png)

**Comment by Felix-Dev** [comment]
@ibonhub The PR just got merged, the link is working again.
