### ISSUE TITLE
when "automatically hide scroll bars" is off in Windows, the content isn't pushed

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/microsoft-ui-xaml#2566]
**Describe the bug**

when "automatically hide scroll bars" is off in Windows, the content isn't pushed and can make things tight

**Steps to reproduce the bug**

1. Enable "Automatically hide scroll bars in Windows"

**Expected behavior**

**Actual behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/51363864/82359087-c87b4280-9a4a-11ea-8bb7-881b6eb6fe68.png)
![image](https://user-images.githubusercontent.com/51363864/82359193-efd20f80-9a4a-11ea-8961-f68d2ada0904.png)

**Version Info**

Gallery version (found on Settings page): 

1.2.15.0

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [x] May 2020 Update
- [x] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by ranjeshj** [comment]
Yes. This was designed to behave this way. I'm not a huge fan of the overlapping either. The question is should scrollbars take layout space. Currently it does not. If it took layout space and the view is not scrollable, we would still end up taking that extra space which would look weird. @RBrid as FYI since we are talking about scrollbars.

**Comment by Poopooracoocoo** [comment]
@ranjeshj honestly hate "conscious scrollbars". they don't even shrink upon overscroll either (which i've filed an issue for). super annoying after using apple devices for a while. the old edge and ie do it too. 

>If it took layout space and the view is not scrollable, we would still end up taking that extra space which would look weird.

what does that even mean? if something cannot be scrolled, why is there a scrollbar??

**Comment by ranjeshj** [comment]
Lets say that if the view is not scrollable then no scrollbar will be shown and the content takes up all the space. Now some content is added (or you expanded something) which makes is scrollable. Now we have to show a scrollbar and we want it to take layout space (not overlap), so we have to run layout and move things around to make space for that scrollbar. 
The way I was thinking of avoiding that is to have the layout space set aside for the scrollbar always. When the view is not scrollable, the scrollbar would not show but that space is still set aside for the scrollbar so that when it shows up it does not end up changing the layout of the content.

**Comment by Poopooracoocoo** [comment]
what happened before "conscious scrollbars"? Did scrollbars always take the layout space, even when not shown?
