### ISSUE TITLE
When TreeViewNode.Children and IsExpanded change, HasUnrealizedChildren would not change

### ISSUE THREAD

**Issue by zhuxb711** [microsoft/microsoft-ui-xaml#2575]
**Describe the bug**

When the number in TreeViewNode.Children is not 0 and IsExpand = true, HasUnrealizedChildren will not automatically become false.

When the number in TreeViewNode.Children is 0 and IsExpand = false, HasUnrealizedChildren will not automatically become true.

#### This violates HasUnrealizedChilren's explanation: "Gets or sets a value that indicates whether the current node has child items that haven't been shown."

**Steps to reproduce the bug**

**Expected behavior**

**Screenshots**

**Version Info**

NuGet package version: Microsoft.UI.Xaml  v2.4.2

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by chingucoding** [comment]
> When the number in TreeViewNode.Children is not 0 and IsExpand = true, HasUnrealizedChildren will not automatically become false.

I am not sure if this is necessary since in that case, I would assume that HasUnrealizedChildren does not serve much purpose.

> When the number in TreeViewNode.Children is 0 and IsExpand = false, HasUnrealizedChildren will not automatically become true.

Automatically setting HasUnrealizedChildren to true when a node has no children and is not expanded would break a lot of applications. The idea behind `HasUnrealizedChildren` is that you can indicate that a node has children without actually having to render them. 

This allows to virtualize items, for example if you create a TreeView of folders on your hard drive. Without the `HasUnrealizedChildren` flag, you would need to scan the whole hard drive and build the complete tree. With that flag, you can just indicate that a node has children, and if it expands render those items.

In my opinion, the TreeView control shouldn't interfere much with the `HasUnrealizedChildren` flag since it is designed to allow developers to tell the treeview when a TreeViewNode can be expanded despite it currently not having any children.

**Comment by carmineos** [comment]
Somehow related to https://github.com/microsoft/microsoft-ui-xaml/issues/2338 ?

**Comment by chingucoding** [comment]
Yes this touches the same API, but I think the proper fix for #2338 would be to have the GlyphOpacity to be 1 if HasUnrealizedChildren is true, and not setting the HasUnrealizedChildren flag in some cases without the developers consent.
