### ISSUE TITLE
[DEBUG] error.cpp not found

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#2613]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1063908/debug-errorcpp-not-found.html)._

---
This error occurs when I try to debug issues with a UWP application. It makes my workflow nearly impossible and is extremely frustrating. Repair install does not fix the problem. I am running the latest Windows Insider fast ring build (19640.)

---
#### Visual Studio Feedback System on 6/3/2020, 07:26 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by StephenLPeters** [comment]
This looks like a symbol/source loading issue to me.

**Comment by Kikanye** [comment]
@vsfeedback Is there a way to work around this issue in the mean time? I am having the same issue developing with Xamarin.UWP, and I am unable to tell what is causing this, I don't even know if it is hitting a breakpoint.

**Comment by JeanRoca** [comment]
Hey @Kikanye thanks for letting us know. Would you be able to provide us with a repro so we can better understand the issue?

**Comment by jasper-zanjani** [comment]
This has started coming up for me when attempting to run even the default WinUI on Desktop or WinUI on UWP template applications

**Comment by jasper-zanjani** [comment]
I've tried repairing and uninstalling/reinstalling Visual Studio and running `sfc /scannow` (no errors). Currently I am able to run solutions that are provided by other people, but starting a new project with a GUI framework doesn't work for me. This includes the normal Blank UWP app and both the Desktop and UWP Blank App templates from the WinUI 3 Templates extension.

Currently, attempting to run the WinUI template Desktop app without any changes results in an unhandled exception. In the call stack 
```
Unhandled exception at 0x75FB583E (combase.dll) in New-WinUI-Win32.exe: 0xC0000602:  A fail fast exception occurred. Exception handlers will not be invoked and the process will be terminated immediately.
```
The call stack:

![image](https://user-images.githubusercontent.com/8889926/107532210-a488ff80-6b8b-11eb-8d45-128dbeecb30b.png)

At this point Visual Studio is asking me to find error.cpp, I guess because it wants me to provide the code to handle the exception.
![image](https://user-images.githubusercontent.com/8889926/107532339-cd10f980-6b8b-11eb-993f-891fb957c7a4.png)

**Comment by JeanRoca** [comment]
@jasper-zanjani it looks like this issue will be fixed with the next WinUI 3 preview. Please let us know if you are still experiencing it once it releases.
