### ISSUE TITLE
Question: Acrylic not working on Windows 10 2004

### ISSUE THREAD

**Issue by DavidZhang73** [microsoft/microsoft-ui-xaml#2737]
### Basic information

I have just updated my Windows 10 to 2004 (19041.330).

This is a i7 7700HQ, GTX1060 laptop with Intel GPU driver(27.20.100.8280) and NVIDIA GPU driver(446.14).

#### On my computer

The Acrylic tab in _XAML Controls Gallery_ app looks like

![Acrylic tab](https://user-images.githubusercontent.com/33928385/85421230-c6a32280-b5a6-11ea-9a0a-820cf6a62455.png)

And the start menu, all UWP applications that uses acrylic are not working correctly.

![Start menu](https://user-images.githubusercontent.com/33928385/85421338-e5a1b480-b5a6-11ea-8251-ab5d889d9fdd.png)

![Windows terminal](https://user-images.githubusercontent.com/33928385/85421201-bbe88d80-b5a6-11ea-924e-6281e88b9e7f.png)

![Calculator](https://user-images.githubusercontent.com/33928385/85421149-aa9f8100-b5a6-11ea-8513-0a3c520c33a8.png)

However, the taskbar does work well.

![taskbar](https://user-images.githubusercontent.com/33928385/85421415-f9e5b180-b5a6-11ea-843f-1a7146b445ab.png)

#### Online reports

There are some related online reports,

1. [Acrylic transparency not working](https://github.com/microsoft/terminal/issues/1414)
2. [Acrylic Effects Not Working On Windows 10 Virtual Installation](https://www.kapilarya.com/fix-acrylic-effects-not-working-on-windows-10-virtual-installation)
3. [Windows10任务栏透明的小研究](https://huanx9.github.io/2020/02/06/dwm/)

### What I have tried

1. Turn on and off Settings app > Personalization > Colors > Transparency effects, and reboot several times(including first shutdown then boot). ![Snipaste_2020-06-23_23-19-45](https://user-images.githubusercontent.com/33928385/85422321-0d454c80-b5a8-11ea-8908-b09c9df7627f.png)

2. Reinstall(update) Intel and NVIDIA GPU drivers.
3. Apply and unapply the following Windows Registry
```
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced]
"UseOLEDTaskbarTransparency"=dword:00000001
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm]
"ForceEffectMode"=dword:00000001
```

### My guess

I am pretty sure that, no long ago, Acrylic works fine, but I could not remember when it broke.

According to the  [Doc on usability-and-adaptability](https://docs.microsoft.com/en-us/windows/uwp/design/style/acrylic#usability-and-adaptability). The system needs to satisfy the following requirements

1. When the user turns off transparency in Settings > Personalization > Color, which I have tried several times.
2. When Battery Saver mode is activated, which I am pretty sure that I am not in saver mode.
3. When the app runs on low-end hardware. Since Windows 7 needs to run winsat to determine whether aero effect can be applied, so I also run, and the score is 8.5, however, nothing has changed to the issue.

After a week of searching and experiments, I can still **not** find any useful information. Could anyone here help me out?

Sorry if this question is out of the range for this repo.

**Comment by StephenLPeters** [comment]
@DavidZhang73  Have you checked the Transparency Setting in Ease of Access > Display?  I think it is the same setting exposed in multiple places, but I think its worth a try.

@codendone and @stevewri FYI.

**Comment by DavidZhang73** [comment]
@StephenLPeters Thanks for your reply. I am pretty sure that Transparency Setting is on.

![Transparency Setting](https://user-images.githubusercontent.com/33928385/85551816-f4df3b80-b654-11ea-9029-2b872b3a3ca0.png)

**Comment by arcadepro** [comment]
Try changing the colour range in the driver control panel to limited then back to full rgb. Or pick some low resolution and revert back.

Performing this dance fixes it on Nvidia for me. I'm not sure of the exact remedy as I've just been experimenting with it today. I also don't think it's limited to build 2004 since I had it in prior builds and just disabled transparency rather than have the inconsistency.

The problem seems to be that the acrylic texture is not loading? or perhaps it's failing to enumerate the correct texture format due to incorrect color data being returned? When this bug occurs the taskbar IS transparent but doesn't have the textured milky appearance like it's supposed to have. (action center and other apps are untextured during this bug; as if transparency is disabled)

**Comment by DavidZhang73** [comment]
@arcadepro It really works for me!!! Thanks a lot!!!

So, the solution is indeed change the color range in the driver control panel to full and reboot. In my case, I do not have color range setting in Nvidia Control Panel, but I found an similar one in Intel Graphic Control Panel called Input Range (in Chinese 输入范围). I change it to full (in Chinese 全) and reboot, it works.

![Snipaste_2020-06-27_12-37-03](https://user-images.githubusercontent.com/33928385/85914682-f6864a80-b872-11ea-8980-f353dadfb815.png)

Thanks again!!!

**Comment by Jehoel** [comment]
@arcadepro I'm running NVIDIA cards too, but I don't see any setting in NVIDIA's control panel named "Color range" and nothing named "Limited" or "Full RGB" - can you share a screenshot?

This is what I see:

![image](https://user-images.githubusercontent.com/1693078/98166822-e0ca0700-1e9c-11eb-9d06-4e9af1fbafe1.png)

**Comment by arcadepro** [comment]
Look in the Change Resolution menu. Scroll down. There should be 4 boxes that allow you to change Nvidia colour settings.

**Comment by Jehoel** [comment]
@arcadepro  I tried that just now but unfortunately it did not work for me at all.

**Comment by arcadepro** [comment]
As a belated follow-up to this you could try disabling the blur effect on the windows log in screen. Either using regedit or the app Winaero Tweaker. For some reason on my system it works as an inverse toggle. i.e. if logon screen blur is on, all other blur is off. Possibly a broken Windows setting somewhere since this installation is an in place upgrade over a day one Windows 7 build. I'll do a clean install someday.

**Comment by Jehoel** [comment]
@arcadepro Interesting. I set a Group Policy on my machine to disable the login-screen background (because I hate caves...) and just show a plain solid colour - but the GP is always consistent, whereas the acrylic/transparency-effects are temperamental.

**However**, my boss tentatively approved my request for an MSDN Subscription (bloody $6000 for the first year and $2600/yr every year for life afterwards...), but because it includes _complimentary support_ if that goes through then I'll gladly file a Professional (with a capital P) support ticket with MSFT for them to get to the bottom of this - and if they confirm it's a bug I get my support credit back! :D

**Comment by rodjdowdall** [comment]
If you have something like Lenovo Display Optimizier installed, try uninstalling it.  This fixed the issue on my Lenovo Laptop.

**Comment by Jehoel** [comment]
Posting a follow-up of my own... I believe the problem was, of all things, my Intel Optane 905p PCI-Express SSD.

From what I can tell, there was some PCI-Express _bus weirdness_ caused by the Optane SSD that caused all manner of subtle performance effects (but no visible glitching). This happened on three different motherboards (two X-99 motherboards, and a Z-490 mobo) and with both NVIDIA GeForce and AMD Radeon graphics cards - this was truly strange, After removing the Optane SSD and replacing it with a "normal" 1TB M.2 SSD (which are now within 90% of the performance of the 905p but with 10% of the price!) things seem okay now.

Truly weird.

**Comment by ca0t** [comment]
update to 22518.1000 version fix this bug
