### ISSUE TITLE
MUXControlsInnerLoop solution fails to build

### ISSUE THREAD

**Issue by yoshiask** [microsoft/microsoft-ui-xaml#2766]
**Describe the bug**
The MUXControls solution builds successfully, and the test app deploys and runs properly. However, the MUXControlsInnerLoop solution fails to build with the following errors:
```
1>\microsoft-ui-xaml\BuildOutput\Debug\x64\Microsoft.UI.Xaml\XamlMetadataProviderGenerated.cpp(424,1): error C2872: 'ElementFactoryGetArgs': ambiguous symbol
1>\microsoft-ui-xaml\BuildOutput\Debug\x64\Microsoft.UI.Xaml\XamlMetadataProviderGenerated.cpp(425,1): error C2872: 'ElementFactoryGetArgs': ambiguous symbol
1>\microsoft-ui-xaml\BuildOutput\Debug\x64\Microsoft.UI.Xaml\XamlMetadataProviderGenerated.cpp(432,1): error C2872: 'ElementFactoryGetArgs': ambiguous symbol
1>\microsoft-ui-xaml\BuildOutput\Debug\x64\Microsoft.UI.Xaml\XamlMetadataProviderGenerated.cpp(433,1): error C2872: 'ElementFactoryGetArgs': ambiguous symbol
1>\microsoft-ui-xaml\BuildOutput\Debug\x64\Microsoft.UI.Xaml\XamlMetadataProviderGenerated.cpp(461,1): error C2872: 'ElementFactoryRecycleArgs': ambiguous symbol
1>\microsoft-ui-xaml\BuildOutput\Debug\x64\Microsoft.UI.Xaml\XamlMetadataProviderGenerated.cpp(462,1): error C2872: 'ElementFactoryRecycleArgs': ambiguous symbol
1>\microsoft-ui-xaml\BuildOutput\Debug\x64\Microsoft.UI.Xaml\XamlMetadataProviderGenerated.cpp(469,1): error C2872: 'ElementFactoryRecycleArgs': ambiguous symbol
1>\microsoft-ui-xaml\BuildOutput\Debug\x64\Microsoft.UI.Xaml\XamlMetadataProviderGenerated.cpp(470,1): error C2872: 'ElementFactoryRecycleArgs': ambiguous symbol
```

**Steps to reproduce the bug**
1. Clone this repo (commit 865e4fcc00e8649baeaec1ba7daeca398671aa72)
2. Open the MUXControls solution and build it.
3. Deploy the MUXControlsTestApp project.
4. Open the MUXControlsInnerLoop solution and build it. Observe that it fails.

**Expected behavior**
MUXControlsInnerLoop should build successfully on a fresh clone if the MUXControls solution builds successfully.

**Version Info**
Commit 865e4fcc00e8649baeaec1ba7daeca398671aa72

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               | N/A |
| Surface Hub        | N/A |
| IoT                | N/A |

**Additional context**

**Comment by chingucoding** [comment]
Cleaning the solution and then building the inner loop works fine. I think the issue is that the generated file from the "normal" loop contains all types, however when the inner loop does not rebuild the "XamlMetadataProviderGenerated.cpp" file. The newly generated inner loop file does not contain those types anymore (unless one of the projects included is the ItemsRepeater).

What surprises me is that we are getting error C2872 here, I would have expected the error be along the lines of missing types.

The general issue here is that inner loop builds and complete builds don't work well simultaneously. When switching solutions, you need to clean everytime to make sure that you are not loading some build artifacts from the other build. Maybe this is something we can improve or should at least point out in the documentation. @ranjeshj @kmahone thoughts?

**Comment by yoshiask** [comment]
I cleaned the InnerLoop solution and now both solutions fail with the same errors

**Comment by yoshiask** [comment]
Cleaning the MUXControlsInnerLoop doesn't fix the issue. I also tried cleaning the MUXControls solution, and now that one fails with a similar issue.
Also, I made a VM and cloned the repo again, this time only building the MUXControlsInnerLoop solution, and it worked as expected.

**Comment by chingucoding** [comment]
Maybe the MSBUILD clean step doesn't work correctly in this configuration. Can you try deleting the "BuildOutput" folder? That definitely removes all previously built artifacts.

**Comment by kmahone** [comment]
I agree that the documentation should be improved here. The MUXControlsInnerLoop.sln is a little bit of a hack. The issue is that it is identical to MUXControls.sln, just with various pieces optionally removed. So they share the same build output locations (including objs, temporary files, generated files, etc.). So before using MUXControlsInnerLoop.sln, it definitely makes sense to fully clean the repo (e.g. with 'git clean -dfx', or just by deleting the BuildOutput directory.

**Comment by yoshiask** [comment]
Deleting the BuildOutput folder fixes both solutions! It would be great if the docs included this, at least until both solutions play nicer together. I'll open a PR to add this to the developer guide.
