### ISSUE TITLE
Discussion: WinUI Performance comparison between C# & C++

### ISSUE THREAD

**Issue by jeganrajm** [microsoft/microsoft-ui-xaml#2851]
Comparing the performance in WinUI to create component
# Discussion: WinUI Performance comparison between C# & C++

While comparing the simple "for loop" between C# and C++ there is vast difference in performance.

For Eg:
## WinUI C# for loop

`List<string> stringCollection = new List<string>();
for (int i = 0; i < 100000; i++)
{
     stringCollection.Add("item");
}`

or **foreach loop**

`foreach (var item in stringCollection)
{
}`
took  0.002 sec

## but in WinUI C++

`
IVector<hstring> stringCollection= winrt::single_threaded_vector<hstring>();
for (int i = 0; i < 100000; i++)
 {
       stringCollection.Append(L"item");
}`

or 
`for (auto item : stringCollection)
{
}`

took 0.2395 sec  (IVector or IObservableVector have same performance.)

It looks C++ performance is low compared to C#. So, which one will be good choice for creating component in WinUI based on performance and memory consumption.

## Related Links
https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/collections

**Comment by MarkIngramUK** [comment]
In release builds I would expect the compiler to realise you're doing nothing with `item` and discard the whole of that loop. Could you link to a full repro (Godbolt link?) to try it out?

**Comment by StephenLPeters** [comment]
@Austin-Lamb FYI

**Comment by riverar** [comment]
What does this have to do with WinUI?

**Comment by sylveon** [comment]
You're paying the cost of marshalling for no good reason. Use std::vector directly, and only use single_threaded_vector when you need to pass it to WinUI, since single_threaded_vector wraps around a std::vector anyways.

Sidenote, but to make the initial fill faster, call .reserve before adding your 10000 items.

**Comment by jeganrajm** [comment]
> In release builds I would expect the compiler to realise you're doing nothing with `item` and discard the whole of that loop. Could you link to a full repro (Godbolt link?) to try it out?

You can find the sample which in tried below
[WinUI C#.zip](https://github.com/microsoft/microsoft-ui-xaml/files/4911894/WinUI.C.zip)
[WinUI Cpp.zip](https://github.com/microsoft/microsoft-ui-xaml/files/4911895/WinUI.Cpp.zip)

**Comment by kennykerr** [comment]
As @sylveon pointed out, this is not a meaningful comparison. And as @riverar notes, this has nothing to do with WinUI. If you gave both C# and C++ a WinRT `IVector<hstring>` you will find that the C++ version outperforms the C# version by a very considerable margin. I [wrote about this](https://kennykerr.ca/2015/04/13/modern-c-as-a-better-compiler/) a few years back. 

But here you're comparing a native C# list with a COM interface. The C# version will obviously outperform the C++ example because the C# version is inlined whereas the COM interface can never be inlined (no matter the language). A better comparison would be a C# `List` and C++ `std::vector`. 

If you are looking for the best possible performance for COM/WinRT/WinUI, C++ outperforms C# every time.

**Comment by Jaiganeshkumaran** [comment]
@jeganrajm Pass item by const& like this auto const& item : stringCollection

**Comment by sylveon** [comment]
This doesn't make a difference, because when enumerating a WinRT collection, you always get the item "by value", the `auto item` version will move the hstring, not copy.

**Comment by Jaiganeshkumaran** [comment]
Won't it call AddRef and Release?

**Comment by sylveon** [comment]
No, this is an hstring. As for reference types, this still holds, because AddRef is called for copies, but the type is moved here.
