### ISSUE TITLE
👩‍💻📞 July WinUI Community Call (July 15, 2020)

### ISSUE THREAD

**Issue by anawishnoff** [microsoft/microsoft-ui-xaml#2867]
Hello everyone! We'll be hosting our monthly WinUI Community Call next week on Wednesday, July 15! We've got exciting guest speakers joining us and important updates to share, so make sure to tune in. 

Watch live on YouTube: https://youtu.be/lcnqqkYggCw

----------------------------------------------------------------------------------------------------------------------------------------------

### Details
Date: July 15, 2020
Time: 16:00-17:00 UTC (9:00-10:00am Pacific)

Anyone and everyone is welcome - no pre-registration is required.
This will be an informal interactive live stream directly with members of our engineering team.

### Format
In this community call we'll be welcoming two guests from related teams here at Microsoft.

At the end of every community call we have a Q&A session where our team answers your questions about all things WinUI. 
**Ask your questions in the comments of this issue!** If any questions come up during the call, you can ask them live in the comments as well. 

### Agenda
Intro, Updates on WinUI 3
Guest Spotlight: Project Reunion and WinUI
Guest Spotlight: The WPF Roadmap for 2020-2021
Q&A

**Comment by StefanKoell** [comment]
I have a couple of questions regarding WinUI and WPF:
* will there be a way to pull in individual WinUI controls without applying the style to the whole application? the reason I ask this is, that I am also dependent on 3rd party UI controls (e.g. docking library) and applying styles on a global scope would mess with their styles.
* will render performance be addressed in WPF at some point?
* I understand that there are many PRs already for WPF but there's no real activity in reviewing/merging them. When will the WPF repo finally pick up some traction?

**Comment by Felix-Dev** [comment]
@StefanKoell 
> will render performance be addressed in WPF at some point?
I understand that there are many PRs already for WPF but there's no real activity in reviewing/merging them. When will the WPF repo finally pick up some traction?

These questions should be best asked in the WPF repository. WInUI is not WPF.

**Comment by mdtauk** [comment]
@Felix-Dev  Look at the Agenda, WPF will be discussed.

>Agenda
>Intro, Updates on WinUI 3
>Guest Spotlight: Project Reunion and WinUI
>**Guest Spotlight: The future of WPF**

**Comment by Felix-Dev** [comment]
@mdtauk Ahahaha, in that case, disregard what I just said here.

**Comment by StefanKoell** [comment]
I have one more question about WPF (and other platforms/frameworks): will there be native SVG support at some point. This is a de-facto standard and even Xcode 12 has now native SVG support which just works...

**Comment by niels9001** [comment]
What updates are there, related to:

- Customizing the window: the ability to create borderless (and transparent) windows (#1247)
- Acrylic support in 3.0 or 3.1 (#2236)

**Comment by pjmlp** [comment]
Regarding the future of WPF, what are the transition plans to eventually get us to move into WinUI?

As mentioned on a few other threads, the effect shaders and System.Windows.Media.Media3D is something I care about, specially since they allow for quick 3D visualizations in .NET without having to go down the C++ coding route (regardless how it is being advertised as being plus for WinUI), or to depend on a full blown .NET friendly game engine.

Then another reason to stay with WPF is the tooling available to us via Blend and graphical visualizations.

So whatever the roadmap for WPF might be, if migrating WPF applications to WinUI is part of the plan, it shouldn't be at the expense of losing features and having to rewrite code from scratch with lesser tooling, because that is how you keep people using older stacks.

Now one thing that would be great after all these years, would be some way to finally use INotifyPropertyChanged  without property handling boilerplate or relying on external MVVM third party frameworks.

**Comment by Bohdan-dotcom** [comment]
Will there be any possibility in the next update of the **21H1** function that **Windows 10** will be really super efficient in booting the system and shutting down the system as well as in the operation of this system which I would ask for in this update.

**Comment by Pinox** [comment]
would luv to hear some comments from MS regarding this thread :
https://github.com/microsoft/ProjectReunion/issues/105

**Comment by LanceMcCarthy** [comment]
I think the decision to decouple WinRT from .NET5 was a good idea. By having the [C#/WinRT toolchain](https://docs.microsoft.com/en-us/windows/uwp/csharp-winrt/) outside of the .NET5 lifecycle, it _should_ allow us to have .NET5/NS21 support in our UWP-WinRT apps without waiting for the .NET5 team to include support for things.

My main question for Kevin and team are: 
* What is the status of C#/WinRT and how does it currently play into UWP-WinRt apps using .NET5/NS21? (_in terms of WinUI3 and UWP-WPF apps, it makes sense, but I'm unclear on how this works for UWP-WinRT apps_).
* What does such a project structure look like, does it mean setting a MinSDK/TargetSDK and add a NuGet package (ala WinUI2 style)

I completely understand the need to not over-promise something that might not make it in time for release X. A headnod that UWP-WinRT is not on the chopping block (Felix-Dev has a nice post in the thread @Pinox linked to) should be enough for many devs to keep investing in their UWP-WinRT apps (instead of ditching it in favor of a UWP-WPF app).

**Comment by mveril** [comment]
What is the procedure to create a WinUI3 controls library targeting .NET UWP and .Net Desktop at the same time ?

**Comment by Xarlot** [comment]
Do you have any timeframe for fixing performance issues with marshaling?

Do you have any plans for better 3d party vendor support? For now, we cant use XAML direct for custom properties, we cant create our own descendants for a lot of controls and mechanisms (for example virtualization) so we cant provide our users better experience than standard control. 

Do you have any plans to improve the XAML engine?
The lack of type descriptors makes it impossible to define simple things in XAML.
The lack of triggers or the same mechanisms like CSS styles in Avalonia that allow 3d party devs define logic on the style level makes 3d party XAML harder to read, maintain, and customize. The VisualStateManager defines its content in templates so it could not be inherited and overridden by the end-user. End-user forced to copy, paste, and maintain giant templates with custom logic and its dependencies. We struggled with this a lot in the Silverlight era.
3d party vendors need the ability to define custom themes like in WPF, not only predefined fluent.

**Comment by michael-hawker** [comment]
> What is the procedure to create a WinUI3 controls library targeting .NET UWP and .Net Desktop at the same time ?

@mveril this is kind of in limbo right now until WinUI3 UWP supports .NET 5 as otherwise you have to target both .NET 5 and .NET Native for the library to function in both environments.

For now, with the Windows Community Toolkit Preview for WinUI, we decided to just support .NET 5 for the Desktop support banking on .NET 5 support to come eventually for UWP (as then the library should just work).

So, ideally you should just make a WinUI 3 control library and target .NET 5, but if you want something that works with both Desktop and UWP for the current Previews, you'll have to multi-target the library.

**Comment by stevenbrix** [comment]
> So, ideally you should just make a WinUI 3 control library and target .NET 5, but if you want something that works with both Desktop and UWP for the current Previews, you'll have to multi-target the library.

@mveril and to piggy back on what @michael-hawker said, you'll have to use https://github.com/novotnyllc/MSBuildSdkExtras in order to do that with Desktop and UWP in their current state

**Comment by AathifMahir** [comment]
My question is any plans on making project Reunion as native windows app UI library or It's going to co-exist with all lagacy stuffs.

**Comment by StefanKoell** [comment]
What about true ARM64 support in WPF? I've read that there are plans for this but more details and a timeline would be interesting.

**Comment by jamesmcroft** [comment]
Follow up from the last call, will there ever be a time when we see WinUI being a choice for 2D UI in 3D mixed reality experiences on HoloLens or WMR devices?

Also, will WinUI bring better windowing API support for positioning multiple windows of a single 2D app running mixed reality?

**Comment by riverar** [comment]
Q: Where is the WinUI 3 dev status document shown [during the February WinUI Community Call](https://youtu.be/tasbSc3771A?t=831)? Developers still have no idea what's truly landing in WinUI 3 and we're inching closer to preview go-live.

![image](https://user-images.githubusercontent.com/475132/87458074-42005e80-c5be-11ea-9239-529f37938e68.png)

**Comment by riverar** [comment]
Q: What's the current commitment for WPF support? Are we talking about supporting the scenario in which developers can add _both_ a WPF and WinUI XAML file to a project and the solution will build? Or will developers have to pick and choose? Or some other scheme?

**Comment by terrycox** [comment]
Any news on file / folder pickers?

**Comment by terrycox** [comment]
Can you discuss the level of coordination your team has with the  WinRT and .NET5 efforts?

**Comment by Symbai** [comment]
Q: Will the desktop support for WinUI be a true and native support, completely decoupled from any UWP related stuff? Or will be something like the XAML Island which hosts UWP stuff in our desktop applications and comes with lots of issues and limitations?

Q: Any news about an updated MediaPlayer for desktop applications? For a long time we only had the Windows Media Player as a control. Then we got the very limited and buggy MediaPlayerElement through XAML Island which is quite unsupported, i.e. reported bugs remain unfixed for over a year now.

**Comment by terrycox** [comment]
For Eve: How do the WinRT Projection packages fit into Project Reunion?

**Comment by ranjeshj** [comment]
> * will there be a way to pull in individual WinUI controls without applying the style to the whole application? the reason I ask this is, that I am also dependent on 3rd party UI controls (e.g. docking library) and applying styles on a global scope would mess with their styles.

@StefanKoell could you open an issue so we can track this need. Thanks
