### ISSUE TITLE
WinUI 3 UWP Preview2 - ObservableCollection (INotifyCollectionChanged) does not work

### ISSUE THREAD

**Issue by AlexanderEgorov** [microsoft/microsoft-ui-xaml#2929]
**WinUI 3 Preview 2** announced that **INotifyCollectionChanged** and **INotifyPropertyChanged** should now work, but it does not in a project created for **UWP**. I have attached a simple sample to demonstrate this issue.

[App1.zip](https://github.com/microsoft/microsoft-ui-xaml/files/4931323/App1.zip)

**Steps to reproduce the bug**
1. Run the attached sample
2. Click on "Add New Item" - nothing happens (ItemsControl and ListBox don't show a new item)

**NuGet package version:** 
Microsoft.WinUI.3.0.0-preview2.200713.0
Microsoft.NETCore.UniversalWindowsPlatform.6.2.10

**Comment by spydacarnage** [comment]
I've tried the simplest of tests in both Desktop and UWP, and can confirm the same.  This is the code I used:
```xaml
    <StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
		<ListView x:Name="Items" ItemsSource="{x:Bind Strings, Mode=OneWay}" Margin="5">
			
		</ListView>
        <Button x:Name="myButton" Click="myButton_Click">Click Me</Button>
    </StackPanel>
```

Code behind:
```csharp
	public sealed partial class MainWindow : Window
	{
		public ObservableCollection<string> Strings { get; set; } = new()
		{
			"Apple",
			"Banana",
			"Cherry"
		};

		public MainWindow()
		{
			this.InitializeComponent();
			Strings.CollectionChanged += (s, e) => Debug.WriteLine($"{e.Action} at index {e.NewStartingIndex}");
		}

		private void myButton_Click(object sender, RoutedEventArgs e)
		{
			Strings.Add("Damson");
			myButton.Content = "Clicked";
		}
	}
```
(the class in the UWP version was `MainPage : Page`, but otherwise identical)

In both versions, when the button is pressed, a debug entry of "Add at index 3" is written, but then it only appears in the Desktop version.

I've checked the MainPage.g.cs vs MainWindow.g.cs, and there are only 3 (non-name-related differences):
1. UWP uses System.WeakReference instead of WinRT.WeakReference  (as announced in the known issues list)
2. UWP uses (T)object instead of object.As<T>() for casting.
3. In GetBindingConnector, UWP uses the Loading event instead of the Activated event to set of the initial bindings, and then runs a SetDataTemplateComponent() method (which Desktop doesn't do at all).

I've not really delved into these files in much detail before, so I'm not sure if that's any help or not

**Comment by ranjeshj** [comment]
@AlexanderEgorov  The fix in Preview2 is specific to Win32 desktop apps and was fixed through the CS/WinRT projections which is not used for UWP apps. UWP apps still need a workaround. You can see the details of the issue and the workaround in the Xaml Controls Gallery app [here](https://github.com/microsoft/Xaml-Controls-Gallery/blob/winui3preview/XamlControlsGallery/CollectionsInterop.cs). 

The issue is that .net collections are tightly coupled to Windows.UI.Xaml* types unfortunately.

@stevenbrix as FYI

**Comment by spydacarnage** [comment]
Thanks - that workaround works great :-)
