### ISSUE TITLE
Question: How to change display name on the desktop app from 'WinUI Desktop' to the actual display name or something else?

### ISSUE THREAD

**Issue by abhi-msft** [microsoft/microsoft-ui-xaml#2961]
I am using Win UI 3 Desktop template and I always see display name as 'WinUI Desktop' irrespective of what I have in manifest file.
Can any one suggest a way or workaround?

![image](https://user-images.githubusercontent.com/52011872/88022945-06e1bc00-cae5-11ea-8f48-c4674d3d3ce2.png)

**Comment by WamWooWam** [comment]
You need to set the `Title` property of your `Window` class. The title doesn't depend on any part of the app package under Win32

**Comment by StephenLPeters** [comment]
I think @WamWooWam is correct, however this is not exposed to markup and needs to be set from codebehind.

**Comment by michael-hawker** [comment]
@StephenLPeters should this be exposed in XAML? If packaged apps have a manifest and the original title from folks coming from UWP was there should it look there? Or will UWP folks have to change their code to adapt here, is that expected?

**Comment by StephenLPeters** [comment]
uhm, I'm not sure, @MikeHillberg @Austin-Lamb and @marb2000 thoughts?

**Comment by abhi-msft** [comment]
@WamWooWam : Thank you, it worked and will work as a work around. But I feel it should be set for packaged apps based on manifest file.

**Comment by michael-hawker** [comment]
Great point @abhi-msft, the manifest for a packaged app should be the source of truth for icons and stuff too. It'd be good to know how this is supposed to work in both environments.

**Comment by StephenLPeters** [comment]
Another good point. @Austin-Lamb @marb2000

**Comment by jtbrower** [comment]
@abhi-msft I found that for many reasons it was easier for me to just completely remove the Win32 titlebar and border and add my own custom implementation in XAML.  It's much easier to control all of the content, but turned out to be most important when it came to handling DPI changed events.  There is a potential issue that I have not reported yet, but it has been on my TODO to consider reporting it.  

Let's say that you want to provide a Window implementation that emulates WPF's SizeToContent feature.  With this feature, it provides the client area with the exact space it needs to render and no more.  This is a critically important feature when you want to show Window's that are borderless and have a transparent background.  If however, you leave the win32 non-client area intact (TitleBar) and a DPI change occurs, a DPI aware application will automatically scale the titlebar area.  When that area is scaled it either takes away from, or adds more space to, the client's area.  If you SizeToContent its obvious because the content will either not have enough space to render or there will be slightly too much because the Win32 TitleBar either steals space from it or adds back to it.  

That's not the problem though.  The problem occurs when I reacted to the DPI changed event by scaling down or up the size of the Window to assure the space was just right.  Now, if you try to drag a Window from one DPI to another (let's say one monitor is scaled at 150% and the other normal), if done "just right" this will cause an infinite recursion of DPI Changed events.  I think the resizing of the Window during the DPI Changed event can cause it to resize such that the majority of the Window ends up back on the DPI that it was on before the event fired.  Then the event fires again, the code reacts by resizing the Window and forever and so on.  It will actually lock the entire application along with Visual Studio.  The only way to regain control of your computer is to kill the process.

So, I removed the Titlebar all-together and that problem no longer occurs.  Plus I can add my own icon, text, colors and etc.  I think the Window should be completely look-less so I designed some classes https://github.com/jtbrower/WinUI that can help others until WinUI has these features built-in someday.  

I have been pretty busy trying to keep up and have yet to report the infinite DPI issue because I am not really sure whos problem that is anyway?  I tried my best to blame myself but I just couldn't find a way to change the Window size and guarantee that this infinite recursion wouldn't be hit.  You have to drag the window across the DPI change just slow enough to cause its tantrum.

One of the features I still need to code is how to have slightly rounded corners where the rounded off region is completely transparent.  I look forward to figuring that one out so I can try porting over more of my application.  It seems that many people are looking for this, but nobody has publicly shared how to do it yet.  If I figure it out you will be able to find it at the link I mentioned above.

**Comment by marb2000** [comment]
I'm revisiting old issues and cleaning up a little the Windowing area in WinUI 3. 

@abhi-msft and @michael-hawker, I got your request. Today, in Preview 4, **it's possible to change the title of a Window setting up the Title property in the code-behind, and the icon can be changed using Win32 APIs** (I wrote a sample in #4056). However, it doesn't honor the app package properties. This is a new feature to me, given it's a new behavior for a Win32 app. IMO, if the Window doesn't have a Title and Icon set, it should use the app package one. There is a workstream in Project Reunion that is creating a library for setting these properties properly, so let's send this feedback to them. I already did it internally.  

I'm closing this question. Feel free to open a feature request if you want to or open again if you have more questions.

**Comment by michael-hawker** [comment]
Thanks @marb2000 is there a corresponding Reunion issue open tracking the workstream you mentioned we can link to on GitHub?

**Comment by jarno9981** [comment]
@marb2000  for the icon it this works for me latest WinUi AppSdk `
        var hWnd = WinRT.Interop.WindowNative.GetWindowHandle(this);
        WindowId windowId = Win32Interop.GetWindowIdFromWindow(hWnd);
        appWindow = AppWindow.GetFromWindowId(windowId);
        appWindow.SetIcon("Logo.ico");`

**Comment by jarno9981** [comment]
logo.ico has the be in the root
