### ISSUE TITLE
VS reports warning "WMC9999: Type universe cannot resolve assembly" from xaml compiler

### ISSUE THREAD

**Issue by huoyaoyuan** [microsoft/microsoft-ui-xaml#3019]
**Version used:**
Visual Studio 16.7 Preview 6
WinUI 3 Preview 2
.NET 5 SDK Preview 7 (x64 only)

**Reproduce:**
It doesn't reproduce for templated project, but reproduces for my simple scaffold project.
There's warning `WMC9999: Type universe cannot resolve assembly: WinRT.Runtime, Culture=neutral, PublicKeyToken=null.` for every xaml file shown in VS error list window, but not in VS build output.

It seems to be caused by setting `<BaseIntermediateOutputPath>` in `Directory.Build.props`, but I cannot eliminate the warning completely by commenting it out.

The attachment is reproduction project.

[WMC9999repro.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5006771/WMC9999repro.zip)

**Comment by huoyaoyuan** [comment]
I did a `git clean` when uploading the reproduction. Then, when I compile it for the first time, the warning is not fully shown up. Restarting VS and building for a second time may be required to reproduce.

`NoWarn` cannot suppress the warning. The application runs well.

**Comment by ranjeshj** [comment]
@huoyaoyuan Is it an intellisense warning ? You can filter out build/intellisense warnings in the error window. NoWarn does not affect intellisense warnings.

**Comment by huoyaoyuan** [comment]
> Is it an intellisense warning ?

@ranjeshj No, it goes under build category.

More information: after I changed the content of `MainWindow.xaml` (replacing with an empty `NavigationView`), the warning pointing it disappears. The warning pointing `App.xaml` is still present.

**Comment by ranjeshj** [comment]
@fabiant3 @stevenbrix as FYI.

**Comment by jtbrower** [comment]
I may as well add that I have been seeing this warning since preview version 1 as well as the other two in this screenshot.  I hadn't reported them yet because I have been using .Net 5.0 preview 7 with WinUI and as we know, that's not the currently supported version.  Since there doesn't seem to be a way to have side-by-side installations of previews of .Net (that I am aware of) I didn't take the time to uninstall, roll back and then revert the process when I was done.  Thanks to @huoyaoyuan for reporting it.  You can find a project that replicates the warnings at https://github.com/jtbrower/WinUI .

![image](https://user-images.githubusercontent.com/3423706/89472480-2bc16a80-d746-11ea-864d-5cf35a8b671e.png)

**Comment by huoyaoyuan** [comment]
Looks to be solved in preview 3.
