### ISSUE TITLE
Question: ToolBar, TabControl, HeaderedContentControl, DataGrid => Types not available in Microsoft.UI.Xaml.Controls

### ISSUE THREAD

**Issue by VijayanRamachandran** [microsoft/microsoft-ui-xaml#3036]
Hi,

I am currently doing some prototypes migrating custom controls available in our end from WPF to WinUI.

During prototype I noticed that, in our end there are some WPF custom controls inheriting ( or using )
from ToolBar, TabControl, HeaderedContentControl, DataGrid ( available in System.Windows.Controls ) and when we try to migrate those custom controls to WinUI then ScrollViewer, TextBlock and TickBar control types are not available in Microsoft.UI.Xaml.Controls.

These implementations will be available soon from your end in near WinUI Preview release ?

I am using right now
VS => Version 16.7.0 Preview 5.0
.Net SDK => dotnet-sdk-5.0.100-preview.4.20268.1-win-x64 / dotnet-sdk-5.0.100-preview.4.20268.1-win-x86

Thanks in advance.

**Comment by Felix-Dev** [comment]
You can use WinUI's [TabView](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/tab-view) control instead of WPF's TabControl. Fot the ToolBar control, you could use the [CommandBar](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/app-bars) control.

You will find controls like DataGrid and HeaderedContentControl in the [Windows Coomunity Toolkit](https://docs.microsoft.com/en-us/windows/communitytoolkit/). 

Controls like the DataGrid are [on the mind of the team](https://github.com/microsoft/microsoft-ui-xaml/issues/1500) though the WinUI team has not yet committed itself to a specific WinUI version (so it might arrive only arrive post WinUI 3.0).

**Comment by robloo** [comment]
Don't forget `Pivot` was the original replacement for TabControl. Pivot has some issues like it can't hide tabs though. The UI will have to be redesigned in this area migrating from WPF to WinUI.

**Comment by robloo** [comment]
Also, I did a comparison of controls between WPF/UWP right now this still applies for the most part with WinUI. Some (like DataGrid) are available in the community toolkit which does have a WinUI preview as well.

https://github.com/robloo/PublicDocs/blob/master/UWPvsWPF.md#Controls

**Comment by robloo** [comment]
For HeaderedContentControl, a `Header` property has been added to most controls instead.

**Comment by StephenLPeters** [comment]
We have similar controls available in Winui or the Windows Community toolkit.

TabControl -> TabView/Top Navigation View
ToolBar -> CommandBar
DataGrid -> published in the Windows Community Toolkit
HeaderedContentControl -> published in the Windows Community Toolkit

If these are not sufficient we'd like to know why.
