### ISSUE TITLE
Expose `ICoreWebView2` in WinUI3

### ISSUE THREAD

**Issue by AnFunctionArray** [microsoft/microsoft-ui-xaml#3112]
## Summary
Allow something like `QueryInterface` from `Microsoft::UI::Xaml::Controls::IWebView2` to `ICoreWebView2`.

## Rationale
Features like `PostWebMessage` doesn't seem to be available under `Microsoft::UI::Xaml::Controls::IWebView2`, there only seem to be an option to add a handler for `WebMessageReceived`. I'm sure there are other features missing from it but those are of the top of my head and also what I need to implement my WebGPU application with UWP shell.

**Comment by codendone** [comment]
What you describe is indeed the plan. Quoting my comment in #3013:

> The work to expose the CoreWebView2 WinRT APIs with its full capabilities is starting now ([internal task](https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/27381901)). And, we have another more specific task to ensure NewWindowRequested works ([internal task](https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/21173937)).

The change will add a WebView2.CoreWebView2 property, which will return the CoreWebView2 WinRT object.

**Comment by bsld** [comment]
@codendone Thanks. I had an idea though - why not just allow `WebView2` to be queried for `CoreWebView2` directly instead of adding additional property.

**Comment by codendone** [comment]
`WebView2` is a subclass of FrameworkElement, so it can't also be a `CoreWebView2`. Hypothetically we could manually have QueryInterface to get to the `CoreWebView2` object, but that would break COM rules since you wouldn't be able to QueryInterface from that object (implemented in the Edge WebView2 Runtime) back to `WebView2`.  Since WinRT also wouldn't be aware of this extra ability, developers would need to go out of their way to do the QueryInterface cast.

Because of all that, the property is more straightforward/correct and also provides more visibility to the extra APIs on `CoreWebView2`.

**Comment by krschau** [comment]
This is is now. Closing.
https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.webview2.corewebview2?view=winui-3.0
