### ISSUE TITLE
Proposal: Redesigned Windows File Explorer

### ISSUE THREAD

**Issue by mcarthur-cpt** [microsoft/microsoft-ui-xaml#3198]
While a lot of the UI's present in Windows are being redesigned the File Explorer has basically stayed the same(more or less). Wouldn't WinUI  look better or a Fluent based one.
![WinUI File Explorer](https://user-images.githubusercontent.com/69404152/91239291-6b74e400-e73f-11ea-95b0-f97eb9e865fd.png)

**Comment by AzAgarampur** [comment]
This is something up to the shell team at Windows, so the folks at WinUI probably can't do anything about it.

Let's ignore that for a moment - File Explorer will probably not use XAML controls because of their runtime overhead and dependencies for Direct3D, Direct2D, DirectComposition, etc. Also, they are all GPU-intensive frameworks. For something like File Explorer, when listing thousands of files with all their thumbnails, using XAML controls would be incredibly inefficient, slow, and will probably lag the entire system due to high CPU, GPU and memory usage. Using GDI (like it is at the moment) is the best choice and File Explorer probably won't change to any other graphics framework.

This also explain why Microsoft decided to create dark theme common controls to use in dark mode File Explorer, rather than switch to dark theme XAML controls.

**Comment by shaheedmalik** [comment]
> This also explain why Microsoft decided to create dark theme common controls to use in dark mode File Explorer, rather than switch to dark theme XAML controls.

This happened because the feedback was misinterpreted.  People wanted dark mode for all apps but for some reason they thought they wanted it just for Explorer.

**Comment by mcarthur-cpt** [comment]
If they can't make XAML controls the default then maybe as an optional extra for people with high end graphics.

**Comment by YuliKl** [comment]
Thank you for the the proposal @mcarthur-cpt. The WinUI team does not own the File Explorer app, so this work would be outside our scope.
