### ISSUE TITLE
Is setting environment variables allowed in WinUI3 Desktop app? (Error: Requested registry access is not allowed)

### ISSUE THREAD

**Issue by abhi-msft** [microsoft/microsoft-ui-xaml#3221]
**Is setting environment variables allowed in WinUI3 Desktop app?**

I am seeing '**Requested registry access is not allowed**' error with Stack Trace :
at Internal.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   at System.Environment.OpenEnvironmentKeyIfExists(Boolean fromMachine, Boolean writable)
   at System.Environment.SetEnvironmentVariableFromRegistry(String variable, String value, Boolean fromMachine)
   at System.Environment.SetEnvironmentVariable(String variable, String value, EnvironmentVariableTarget target)

**Comment by StephenLPeters** [comment]
Administrator access is not currently supported so if your environment variable accesses a part of the registry that requires it you wont be able to. Otherwise it should work.

**Comment by abhi-msft** [comment]
I am trying to add a simple environment variable which is resulting in error.

**Comment by abhi-msft** [comment]
If it doesn't work, do we have any alternative?

**Comment by StephenLPeters** [comment]
@stevenbrix @Austin-Lamb or @JesseCol fyi?

**Comment by Austin-Lamb** [comment]
@abhi-msft - This is unrelated to WinUI - which is just a UI framework, so most likely the security restriction you're experiencing is due to the security container that Desktop Bridge apps (aka MSIX) are put in.  See here for more details: https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-behind-the-scenes

I'm going to close this issue since it's not something that the UI framework can address.
