### ISSUE TITLE
ColorPicker Tooltip doesn't disappear when focused

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/microsoft-ui-xaml#3237]
**Describe the bug**
When using the ColorPicker, the tooltip doesn't disappear unless the user clicks somewhere else that takes focus. This causes the tooltip to overlay itself when scrolling. This can be seen pretty easily in the Control Gallery Sample.

![image](https://user-images.githubusercontent.com/24302614/92161184-18f19280-ede5-11ea-9005-bcb6d65b70cd.png)

**Steps to reproduce the bug**
1. Go to control gallery sample for ColorPicker
2. Click and drag on the color picker to cause tooltip to appear
3. Scroll with mouse wheel
4. Note: Tooltip is now obscuring other parts of the page.

A similar issue appears if you later also give ColorPicker focus again and then scroll, as it seems whenever ColorPicker has focus it displays the Tooltip.

**Expected behavior**
The tooltip should disappear after a short time after the user has finished manipulating the selection.

**Version Info**
Controls Gallery Package

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |  Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
@kikisaints I think we could probably do something with effectiveViewPortChanged to fix this but some thought would need to go into the desired behavior.

**Comment by Felix-Dev** [comment]
@StephenLPeters What speaks against collapsing the tooltip as soon as the user starts scrolling? The tooltip wouldn't be aligned with the "actual" color picker (the circle users can drag around the color panel to select a color) any longer and it rapidly starts to look visually unpleasing.

**Comment by StephenLPeters** [comment]
I think the options are either close the tip or move it with the color spectrum. you are right we wouldn't want it to be misaligned (as it is currently)

**Comment by chingucoding** [comment]
I think closing the tooltip makes more sense, otherwise we would need to check when the colorspectrum is actually visible on screen and didn't get occluded by something else as part of scrolling.

**Comment by StephenLPeters** [comment]
> I think closing the tooltip makes more sense, otherwise we would need to check when the colorspectrum is actually visible on screen and didn't get occluded by something else as part of scrolling.

EffectiveViewportChanged lets us do just that though

**Comment by chingucoding** [comment]
That's true yes. Should we follow the TeachingTip behavior in this case? A persistent ToolTip like in this case seems is quite similar to a TeachingTip in this regard.

**Comment by Felix-Dev** [comment]
I implemented my suggestion outlined above in WInUI for better visualization:

![colorpicker-example](https://user-images.githubusercontent.com/1398851/92311242-abe12700-efb5-11ea-9b96-69b9c633180c.gif)

The tooltip got a default show duration time of 5 seconds (meant to match UWP's default tooltip duration time). Changing the position of the circle either by mouse/touch or keyboard will show the tooltip and the tooltip will be hidden of no movement changement has been registered for 5 seconds.

When the user scrolls, the tooltip is hidden. As written above, since we should hide the tooltip anyway if no change happens after some time, there is little reason for us to preserve the tooltip when the user scrolls. A scrolling user is most likely directinging their focus *away* from the colorpicker (if they interacted with it prior to the scrolling) and thus the overlay nature of the tooltip will cuase visual inconveniences if the user scrolls reasonably fast. As the tooltip would disappear after five seconds anyway (since the user is now likely interacting with other UI elements after their scrolling) we prevent the visual inconveniences by hiding it directly.

(The current behavior f showing the tooltip of focus received and hiding it on focus lost remains unchanged.)

Honestly, I think this is looking quite good.

**Comment by Felix-Dev** [comment]
@StephenLPeters Your thoughts on the suggestion above (see the GIF)?

**Comment by Felix-Dev** [comment]
@StephenLPeters Friendly ping.

**Comment by michael-hawker** [comment]
@Felix-Dev looks good to me as the OP. 🦙❤

**Comment by michael-hawker** [comment]
@Felix-Dev I thought I remember seeing a PR for something like this? Did it not get linked or am I thinking of something else?

**Comment by Poopooracoocoo** [comment]
@StephenLPeters ping

**Comment by asklar** [comment]
@Felix-Dev did you send a PR for this yet? if not, can you do so?
