### ISSUE TITLE
When you go to a sample page from the search, the navigationview should close (if it is in compact mode)

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/microsoft-ui-xaml#3241]
Repro:
1. Open Xaml Controls Gallery so primary navigation is in LeftCompact mode
2. Search for Button and chose this page from the ASB dropdown

Actual behavior: XCG navigates to another page but NavigationView pane remains open.
Expected: XCG navigates and also closes the pane.

**Comment by chingucoding** [comment]
I would like to look into this. For clarification, when the pane was opened using the hamburger button, and the user clicks inside the search and then clicks outside of it, should the pane stay open? I would say yes, however that would increase complexity here I think.

**Comment by Poopooracoocoo** [comment]
^i don't think the pane is supposed to stay open in that situation

**Comment by Felix-Dev** [comment]
@chingucoding The pane is light-dismissable in minimal/compact mode so it should close if the developer clicks outside the pane.

**Comment by chingucoding** [comment]
No I mean, what if you click inside the pane, but outside the AutoSuggestBox?

**Comment by Poopooracoocoo** [comment]
i'd expect the pane to stay open if you're clicking on it

**Comment by Felix-Dev** [comment]
I would say the same behavior as can be seen today then? (I.e. close if a NavigationViewItem is selected and stay open if no interactive UI is clicked on the pane surface).

**Comment by Felix-Dev** [comment]
@Poopooracoocoo Point 4 ("if it's navigating to a page the pane should close") is problematic in the following sense:

![navview-pane](https://user-images.githubusercontent.com/1398851/92183365-71a94580-ee4e-11ea-860a-b5d9096484ae.gif)

So if you click a top-level NavigationView item, the pane shouldn't close as can be seen in the XCG gif since the user might want to select one of its children. The pane definitely should close if the selected menu item has no children.

**Comment by chingucoding** [comment]
That makes sense, thanks @Felix-Dev and @Poopooracoocoo . @YuliKl Do you agree with our assessments?
