### ISSUE TITLE
Proposal: Add ColorPicker Architecture Docs

### ISSUE THREAD

**Issue by robloo** [microsoft/microsoft-ui-xaml#3242]
# Proposal: Add ColorPicker Architecture Docs

## Summary

Just like NavigationView, add some docs explaining how the ColorPicker works internally.

## Rationale

As previously discussed, docs help contributors and those that need to make changes in the future.

## Important Notes

I have a draft already started and will open a PR to commit it myself.

**Comment by chingucoding** [comment]
I think a separate proposal for this is not necessary, if you want to work or are starting to work on the documentation for a specific control, it is better to comment on the existing thread regarding the architecture documentation: #2812

**Comment by robloo** [comment]
Even small issues like this are necessary just to communicate things are being worked on in my opinion.

**Comment by chingucoding** [comment]
In my opinion, leaving a comment saying "I would like to work on the ColorPicker documentation" is enough, especially since I probably would look at that thread for any updates and wouldn't expect a separate issue to be opened for each control.

**Comment by Felix-Dev** [comment]
@robloo @chingucoding I think leaving a short note on the original thread #2812 - which covers adding documentation for *all* WinUI controls - would be more than fine. I.e. if I were to start working on documentation for control X, I would write something like "Chingucoding, Ranjesh (as mentions) I would like to work on the architecture docs for the control X, if you don't mind."

That would clearly communicate with other contributors interested in helping out in that area. 

Instead of creating a new (tracking) proposal for each control, let's instead keep track of the architectural documentation state which is
* already done
* currently being worked on (perhaps including by whom)

in the opening post of issue #2812. We could list both the controls already with documentation in place and controls currently being worked on (including listing the "assignee" next to them). These lists can be maintained by both the thread author (@chingucoding), or, if he should be unavailable, by the WinUI team (which can also edit posts). That way, we always have the current state of that broad work item easily visible right at the top of that issue instead of being tracked, potentially, in multiple different issues at a time.

@robloo @chingucoding Would you be fine with that?

**Comment by chingucoding** [comment]
That sounds like a good idea @Felix-Dev . I've added a table at the top of the proposal showing the status of WIPs and finished controls.

**Comment by robloo** [comment]
Thats fine its just a different way of managing things. With large projects communication is key. It's also sometimes good to have a request/bug-report to close with a corresponding PR for tracking purposes.
