### ISSUE TITLE
ArgumentException when TabViewItem.Header is null or empty string

### ISSUE THREAD

**Issue by huoyaoyuan** [microsoft/microsoft-ui-xaml#3329]
**Describe the bug**
`ArgumentException` when a `TabViewItem` with empty or null `Header` displayed.

**Steps to reproduce the bug**
```xaml
<TabView>
    <TabViewItem Header="">
        <TextBlock Text="123" />
    <TabViewItem>
<TabView>
```

or

```xaml
<TabView>
    <TabViewItem Header="{x:Null}">
        <TextBlock Text="123" />
    <TabViewItem>
<TabView>
```

or

```xaml
<TabView>
    <TabViewItem>
        <TextBlock Text="123" />
    <TabViewItem>
<TabView>
```
*Does not reproduce* if `TabViewItem.Content` is not set, or set to a string instead of a control.

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml 2.4.3
Microsoft.UI.Xaml.2.5.0-prerelease.200923002
Microsoft.WinUI 3.0.0-preview2.200713.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by Felix-Dev** [comment]
It is worth pointing out the crash only happens when the TabViewItem is selected. A TabViewItem with an empty header  ("" or null) and an UIElement as its content will not crash the app as long as its not selected. 

The reason why such a TabViewItem will crash the app is the following I believe: The TabViewItem uses a `ContentPresenter` to represent its header. Yet, if no header is spcified, the TabViewItem's header ContentPresenter consumes the TabViewItem's `Content` property. We are seeing the effect of values automatically propagating down in the control template: 
> If the ContentPresenter is in the ControlTemplate of a ContentControl, the ContentPresenter behavior will implicitly bind to the ContentTemplate and Content properties of the templated ContentControl.

In other words, if the TabViewItem's content is a FrameworkElement (a panel, control, etc...) then that element now has a parent - the TabViewItem's header ContentPresenter.

Now, if we select such a TabViewItem, we update the TabView's tab content ContentPresenter to the content of the TabViewItem: https://github.com/microsoft/microsoft-ui-xaml/blob/7c3ba16da9e273c73169c062cc803868695fa864/dev/TabView/TabView.cpp#L757

However, the TabViewItem's content is a FrameworkElement and already has a parent. And every UIElement can only have at most one parent at at given time. As such, we are trying give the TabViewItem's Content yet another parent (this time: The TabView's tab content ContentPresenter), however, this is not allowed. As a result, the app crashes.

This also explains why it works fine if the TabViewItem's content is a primitive type: In this case, both he TabViewItem's ContentPresenter and the TabView's ContentPresenter will wrap the primitive type and as such we don't have a situation where an UIElement gets assigned two parents.

Looking at a possible solution, I think we should consider preventing the down-level propagation of the TabViewItem's Content to its internal Header ContentPresenter. That ContentPresenter is only meant for the header. It is not meant to be populated by the TabViewItem's content. If a header is deliberately being set to empty by a developer, then the TabViewItem's header should be empty, after all.

**Comment by Felix-Dev** [comment]
@huoyaoyuan A workaround for now would be to set the TabViewItem's header to some not-empty value and then use the TabViewItem's Loaded event to set the header to empty.

**Comment by huoyaoyuan** [comment]
@Felix-Dev Thanks for investigation. I found this originally when using `FallbackValue=''` in header binding. Now I have some other thing to show when the VM is null.

**Comment by StephenLPeters** [comment]
Thanks Felix... This behavior of content presenter automatically displaying the "content" property when its template binding resolves to null has caused us pain all over the place, see this conversation with Marcel https://github.com/microsoft/microsoft-ui-xaml/pull/3205#discussion_r485203320.  I think the fix for this is to replace the content presenter in TabViewItem with a border (or some other presenter like element).

@ranjeshj and @MikeHillberg is this content presenter behavior of automatically pulling in the content something we can remove? At least for when there was already a template binding which happened to resolve to null? It feels very strange that if your tab view has no header, the header content presenter will pull in the main page content.

**Comment by Felix-Dev** [comment]
@StephenLPeters Interestingly to me, the `ContentTemplate` property does not cause the same issues here, even though the documentation above states that the ContentTemplate is also automatically pulled in. Yet if we specify no TabViewItem.HeaderTemplate but a TabViewItem.ContentTemplate instead, then the content template is only applied to the TabViewItem's content, as it should:

```xml
<muxc:TabView>
    <muxc:TabView.TabItems>
        <muxc:TabViewItem Header="Tab 1" Content="Tab 1 Content">
            <muxc:TabViewItem.ContentTemplate>
                <DataTemplate>
                    <TextBox Margin="5" Text="ContentTemplate" Foreground="Blue" />
                </DataTemplate>
            </muxc:TabViewItem.ContentTemplate>
        </muxc:TabViewItem>
    </muxc:TabView.TabItems>
</muxc:TabView>
```
![image](https://user-images.githubusercontent.com/1398851/94309584-99388d00-ff78-11ea-9a27-165945e0f81c.png)

The existence of the TabViewItem's `HeaderTemplate` API probably rules out using the `Border` "workaround" mentioned by you (as I'm not seeing a ContentTemplate related API on the Border element) and I'm also not immediately aware of another presenter like element coming with a `ContentTemplate` API outside of the ContentPresenter.

We could use the workaround of moving the ContentPresenter update logic to code-behind and setting the Content property of the TabViewItem's header ContentPresenter to the empty string ("") in the template. Though if we can do it in Xaml that would be a lot better.  Some ideas?

**Comment by StephenLPeters** [comment]
In teaching tip we ended up doing a content presenter who's content is a border, who's content is template bound to the property. that way we could put the foreground on the parent content presenter. I think that same model would work here?

**Comment by Felix-Dev** [comment]
Haaaaaah.....not sure what I was thinking when I mentioned the HeaderTemplate API here. That won't cause problems, since if a customer uses a ContentPresenter in that DataTemplate it won't inherit the Content of the TabViewItem since it's not in the ControlTemplate of the TabViewItem directly.

An additional question now arises: If the header is empty, we still show a tooltip. Looking at the NavigationView, that control shows no tololtip for a menu item with no content, and the empty tooltip does look strange here:
![image](https://user-images.githubusercontent.com/1398851/94321242-5504b700-ff8f-11ea-9e3c-7dd152db40f4.png)

So my suggestion is to be consistent with the NavigationView control here and not show a tooltip when the TabViewItem header is empty.

**Comment by Felix-Dev** [comment]
@StephenLPeters Quick ping in case previous ping got missed (just to make sure you saw my question).

**Comment by StephenLPeters** [comment]
Yes, I think we should never show an empty tool tip, I think removing the tooltip all together is correct. @YuliKl can you confirm?

**Comment by YuliKl** [comment]
> Yes, I think we should never show an empty tool tip, I think removing the tooltip all together is correct. @YuliKl can you confirm?

Agreed!

**Comment by Felix-Dev** [comment]
Excellent, I will soon create a PR then :)

**Comment by Felix-Dev** [comment]
@StephenLPeters One difference here, compared to the mentioned TeachingTip scenario, is that Border.Child expects an UIElment and the TeachingTip.TemplateSettings.IconElement API is an UIElement. However, the TabView.Header property is of type object so if I'm just assigning a simple string as the Header of the TabViewItem, the TabViewItem will display an empty header:
```xml
<TabViewItem Header="Home">
    <TabViewItem.IconSource>
        <SymbolIconSource Symbol="Home"/>
    <TabViewItem.IconSource>
</TabViewItem>
```
![image](https://user-images.githubusercontent.com/1398851/94802049-41ba7700-03e7-11eb-9569-669eb09c8756.png)

As soon as I explicitly specify an UIElmement as the header, then the header will be displayed as expected.

In light of this, I'm not sure if a fix can purely be done in markup. I can't use a ContentPresenter as the Child of the border I will wrap the TabViewItem header into since then I will get the same issue we are already facing today. We might have to use some code-behind here. As mentioned earlier in this conversation one way to to do that would be to set the ContentPresenter's Content to an empty string in the template and move setting the actual header into the existing TabViewItem::OnHeaderPropertyChanged() logic.

**Comment by StephenLPeters** [comment]
That, unfortunately, makes sense.  I think you are right and setting the content presenter's content from code behind makes sense... :(
