### ISSUE TITLE
NavigationView needs some serious attention

### ISSUE THREAD

**Issue by Parth** [microsoft/microsoft-ui-xaml#3340]
I was requested to make this it's own issue, but there are significant bugs in the most recent stable and prerelease versions of NavigationView (which means there's no working NavigationView available).

1. #3131
2. #3290
3. https://github.com/microsoft/microsoft-ui-xaml/issues/3290#issuecomment-699687352

UWP 2.4 (stable) - has bugs
UWP 2.5 (prerelease) - has bugs
UWP 3.0 - [Should not be used for production apps](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/)

Pretty discouraging situation.

**Comment by Felix-Dev** [comment]
@Parth Could you make this issue about the PaneFooter/Settings item being pushed out of the displayed NavigationView pane (starting with WinUI 2.5.0-prerelease.200812001 which introduced new FooterMenuItems APIs and are likely the reason for the change in behavior you are seeing here)? That way, this issue will be easily searchable for other customers encountering the same changed behavior and can be re-directed to this issue instead of opening a new one. It would also help the team with discussing this very issue and possible changes required as well as acting as tracking progress on this issue..

So the issue title could be changed to something like "NavigationView footer area/Settings button are pushed out of view given enough menu items" and then add the details you write on your https://github.com/microsoft/microsoft-ui-xaml/issues/3290#issuecomment-699687352.

Thanks!

**Comment by YuliKl** [comment]
@Parth I'm sorry you're unhappy with NavigationView, but I'm closing this issue as too vague. Please open a new one, as @Felix-Dev suggested, about each specific problem. As written this item is not actionable, and as the PM owner of this control I know first hand that overall NavigationView does receive "serious attention" from the WinUI team and our community. (Thank you for all your work on it, @Felix-Dev!) 

I think some of your frustration with the control is stemming from poor drag-and-drop support. That's understandable, because we did not design NavigationView to support drag-and-drop. The control's primary scenario was to show a "drawer" of destinations within the app. I had not expected the navigation links to be dragged and rearranged or copied by end users. What would be helpful is if you open a feature proposal for NavigationView to support drag-and-drop and use that proposal to explain the scenario(s) in which users would leverage this capability.
