### ISSUE TITLE
WebView2 Proxy Configuration

### ISSUE THREAD

**Issue by standrze** [microsoft/microsoft-ui-xaml#3341]
I would like to a set proxy for my WebView2 control, but I am not sure that you are able to set it. Does anyone know whether that is available right now? Also, it would be nice to have the ability to alter the requests on even NavigationStart, no idea why I can't alter the request. Thank you.

**Comment by codendone** [comment]
There isn't currently an ability to set a proxy, but there are some issues in the Edge WebView2 feedback repo requesting this capability:
* MicrosoftEdge/WebViewFeedback#132
* MicrosoftEdge/WebViewFeedback#193

Altering requests on NavigationStarting will be possible when we fix the event args to expose the RequestHeaders. As a workaround, it should be possible to do this in Preview3 if you listen for myWebView2.CoreWebView2.NavigationStarting rather than using the wrapper NavigationStarting event on the WebView2 element.

**Comment by codendone** [comment]
Closing this issue. Please track via the WebView2 feedback items mentioned above.
