### ISSUE TITLE
LoadedImageSurface fails unexpectedly if local asset not found.

### ISSUE THREAD

**Issue by simeoncran** [microsoft/microsoft-ui-xaml#3357]
**Describe the bug**
If you use LoadedImageSurface::StartLoadFromUri(L"ms-appx://Assets/someasset.jpg") and someasset.jpg is not found, the process crashes.

**Steps to reproduce the bug**
See description.

**Expected behavior**
No crash, but the failure gets reported to the LoadCompleted handler.

**Version Info**
All.

**Comment by codendone** [comment]
The problem is that if the path points to a local file like this, the code assumes that a valid path should have been specified and therefore lets the error returned from ResourceManager bubble out, and that error ends up being fatal since it happens during Tick:

```
Windows_UI_Xaml!CDownloader::CreateUnsecureDownloadRequest
Windows_UI_Xaml!CommonBrowserHost::UnsecureDownload
Windows_UI_Xaml!CCoreServices::ProcessDownloadRequests
Windows_UI_Xaml!CCoreServices::SubmitPrimitiveCompositionCommands
Windows_UI_Xaml!CCoreServices::NWDrawTree
Windows_UI_Xaml!CCoreServices::NWDrawMainTree
Windows_UI_Xaml!CWindowRenderTarget::Draw
Windows_UI_Xaml!CXcpBrowserHost::OnTick
Windows_UI_Xaml!CXcpDispatcher::Tick
```

Even if it is reasonable for an app to not use "ms-appx:///" to point to missing files, this should at least produce a better error message to make the failure easier to understand.  Having LoadedImageSurface expose the error with an event would be even better.
