### ISSUE TITLE
ItemsReperater with Binding in ItemTemplate throws exception on vertical scrolling

### ISSUE THREAD

**Issue by zed220** [microsoft/microsoft-ui-xaml#3377]
**Describe the bug**
ItemsRepeater with Binding in ItemTemplate throws exception on vertical scrolling.

**Steps to reproduce the bug**
1. Create a WinUI app for c#.
2. Create a class like following:
```
public class Item : INotifyPropertyChanged {
    public int Id { get; set; }
    public event PropertyChangedEventHandler PropertyChanged;
}
```
3. Create xaml:
```
<ScrollViewer>
	<ItemsRepeater ItemsSource="{x:Bind Items}">
		<ItemsRepeater.ItemTemplate>
			<DataTemplate x:DataType="local:Item">
				<TextBlock Text="{Binding Id}" />
			</DataTemplate>
		</ItemsRepeater.ItemTemplate>
	</ItemsRepeater>
</ScrollViewer>
```

4. Make a source with 1000+ items for the ItemsReperater.
5. Run.
6. Scroll to about 1000 lines with the mouse wheel.
7. See an exception.

**Expected behavior**
Scrolling works fine.

**Version Info**
3.0.0-preview2.200713.0
NuGet package version:
[Microsoft.WinUI 3.0.0-preview2.200713.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| No | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2020 Update (19041)            | Yes   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               | No |
| Surface Hub        | <No |
| IoT                | No |

**Additional context**
I have attached an example what illustrates this behavior.

[App11.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5334083/App11.zip)

**Comment by StephenLPeters** [comment]
@ranjeshj FYI

**Comment by ranjeshj** [comment]
This might be related to the effective viewport issue in Winui3

**Comment by BorzillaR** [comment]
The issue is reproduced in Preview 3.

![image](https://user-images.githubusercontent.com/23479280/99628007-5eb61280-2a46-11eb-8704-8a40ff4103b5.png)

Call stack:

` 	KernelBase.dll!CompareStringOrdinalCounted()	Unknown
 	KernelBase.dll!_CompareStringOrdinal@20()	Unknown
 	combase.dll!WindowsCompareStringOrdinal(HSTRING__ * string1, HSTRING__ * string2, int * result) Line 377	C++
 	Microsoft.ui.xaml.dll!0a2b577c()	Unknown
 	Microsoft.ui.xaml.dll![Frames below may be incorrect and/or missing, no symbols loaded for Microsoft.ui.xaml.dll]	Unknown
 	Microsoft.ui.xaml.dll!0a080d0d()	Unknown
 	Microsoft.ui.xaml.dll!09ea14e7()	Unknown
 	Microsoft.ui.xaml.dll!09dc17d3()	Unknown
 	Microsoft.UI.Xaml.Controls.dll!19efd7d4()	Unknown
 	Microsoft.UI.Xaml.Controls.dll!19d8ab2b()	Unknown
 	Microsoft.ui.xaml.dll!09d9aa7d()	Unknown
 	Microsoft.ui.xaml.dll!09e4f5db()	Unknown
 	Microsoft.UI.Xaml.Controls.dll!19d45ef1()	Unknown
 	Microsoft.UI.Xaml.Controls.dll!19ceea6c()	Unknown
 	Microsoft.UI.Xaml.Controls.dll!19d2b28c()	Unknown
 	Microsoft.UI.Xaml.Controls.dll!19ce8392()	Unknown
 	Microsoft.UI.Xaml.Controls.dll!19ce6494()	Unknown
 	Microsoft.UI.Xaml.Controls.dll!19cec7df()	Unknown
 	Microsoft.UI.Xaml.Controls.dll!19cee13b()	Unknown
 	Microsoft.UI.Xaml.Controls.dll!19ce54e7()	Unknown
 	Microsoft.UI.Xaml.Controls.dll!19ce9e67()	Unknown
 	Microsoft.ui.xaml.dll!09f3b415()	Unknown
 	Microsoft.ui.xaml.dll!09db8bfb()	Unknown
 	Microsoft.ui.xaml.dll!0a25d15f()	Unknown
 	Microsoft.ui.xaml.dll!09d9877b()	Unknown
 	Microsoft.ui.xaml.dll!09dd4815()	Unknown
 	Microsoft.ui.xaml.dll!09d95323()	Unknown
 	Microsoft.ui.xaml.dll!09d95392()	Unknown
 	Microsoft.ui.xaml.dll!09d95392()	Unknown
 	Microsoft.ui.xaml.dll!09d95392()	Unknown
 	Microsoft.ui.xaml.dll!09d95392()	Unknown
 	Microsoft.ui.xaml.dll!09d95392()	Unknown
 	Microsoft.ui.xaml.dll!09d95392()	Unknown
 	Microsoft.ui.xaml.dll!09d95392()	Unknown
 	Microsoft.ui.xaml.dll!09d95392()	Unknown
 	Microsoft.ui.xaml.dll!09d95392()	Unknown
 	Microsoft.ui.xaml.dll!09d95392()	Unknown
 	Microsoft.ui.xaml.dll!09e13897()	Unknown
 	Microsoft.ui.xaml.dll!09e12c3d()	Unknown
 	Microsoft.ui.xaml.dll!09db4e0f()	Unknown
 	Microsoft.ui.xaml.dll!09db4c32()	Unknown
 	Microsoft.ui.xaml.dll!09db4a30()	Unknown
 	Microsoft.ui.xaml.dll!09db49aa()	Unknown
 	Microsoft.ui.xaml.dll!09db48ab()	Unknown
 	Microsoft.ui.xaml.dll!09f10a63()	Unknown
 	Microsoft.ui.xaml.dll!09f108fe()	Unknown
 	CoreMessagingXP.dll!Microsoft::WRL::Details::DelegateArgTraits<long ( Windows::Foundation::ITypedEventHandler_impl<struct Windows::Foundation::Internal::AggregateType<class Microsoft::System::DispatcherQueueTimer *,struct Microsoft::System::IDispatcherQueueTimer *>,struct IInspectable *>::*)(struct Microsoft::System::IDispatcherQueueTimer *,struct IInspectable *)>::DelegateInvokeHelper<struct Microsoft::WRL::Implements<struct Microsoft::WRL::RuntimeClassFlags<2>,struct Windows::Foundation::ITypedEventHandler<class Microsoft::System::DispatcherQueueTimer *,struct IInspectable *>,class Microsoft::WRL::FtmBase>,class <lambda_74c1b97b1c2a05a0aae7d9f4d55c50cf>,-1,struct Microsoft::System::IDispatcherQueueTimer *,struct IInspectable *>::Invoke(struct Microsoft::System::IDispatcherQueueTimer *,struct IInspectable *)	Unknown
 	CoreMessagingXP.dll!Microsoft::WRL::InvokeTraits<-2>::InvokeDelegates<class <lambda_2ae92d1256ada6b651b55d5dab7f510d>,struct Windows::Foundation::ITypedEventHandler<class Microsoft::System::DispatcherQueueTimer *,struct IInspectable *> >(class <lambda_2ae92d1256ada6b651b55d5dab7f510d>,class Microsoft::WRL::Details::EventTargetArray *,class Microsoft::WRL::EventSource<struct Windows::Foundation::ITypedEventHandler<class Microsoft::System::DispatcherQueueTimer *,struct IInspectable *>,struct Microsoft::WRL::InvokeModeOptions<-2> > *)	Unknown
 	CoreMessagingXP.dll!Microsoft::WRL::EventSource<struct Windows::Foundation::ITypedEventHandler<class Microsoft::System::DispatcherQueue *,struct IInspectable *>,struct Microsoft::WRL::InvokeModeOptions<-2> >::InvokeAll<class Microsoft::System::DispatcherQueue *,std::nullptr_t>(class Microsoft::System::DispatcherQueue *,std::nullptr_t)	Unknown
 	CoreMessagingXP.dll!Microsoft::System::DispatcherQueueTimer::TimerCallback(void *)	Unknown
 	CoreMessagingXP.dll!CFlat::SehSafe::Execute<<lambda_e16aea3717fc5beac95aa2e513a8f395>>()	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::ActionCallback::ImportAdapter$(class CFlat::Box$1<struct CFlat::FunctionPointerAndUserData$1<long (*)(void *)> > *)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Support::ActivationContext::CallbackWithActivationContext(class Microsoft::CoreUI::Dispatch::Timeout *,struct System::UIntPtr)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::TimeoutManager::Callback_OnDispatch(void)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::Dispatcher::Callback_DispatchNextItem(void)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::Dispatcher::Callback_DispatchLoop(enum Microsoft::CoreUI::Dispatch::RunnablePriorityMask)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::EventLoop::Callback_RunCoreLoop(enum Microsoft::CoreUI::Dispatch::RunMode)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::SystemCoreMessagingEventLoopBridge::Callback_OnSystemDispatch(enum Microsoft::CoreUI::Dispatch::SystemCoreMessaging$GroupPriority,struct CFlat::Ref<struct System::IntPtr>)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::SystemCoreMessaging::Callback_OnGroupDispatch(enum Microsoft::CoreUI::Dispatch::SystemCoreMessaging$GroupPriority,struct CFlat::Ref<struct System::IntPtr>)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::SystemCoreMessaging::NoContext_GroupDispatchHandler(enum Microsoft::CoreUI::Dispatch::SystemCoreMessaging$GroupPriority,void *)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::SystemCoreMessaging::NoContext_HighPriorityDispatchHandler(void *)	Unknown
 	CoreMessaging.dll!Microsoft__CoreUI__DispatchGroupHandler$CallbackThunk(class System::Delegate *)	Unknown
 	CoreMessaging.dll!System::Action::Invoke(void)	Unknown
 	CoreMessaging.dll!Microsoft::CoreUI::Dispatch::Dispatcher::DispatchNextItem(void)	Unknown
 	CoreMessaging.dll!Microsoft::CoreUI::Dispatch::Dispatcher::Callback_DispatchLoop(struct Microsoft::CoreUI::Dispatch::RunnablePriorityMask)	Unknown
 	CoreMessaging.dll!Microsoft::CoreUI::Dispatch::EventLoop::Callback_RunCoreLoop(struct Microsoft::CoreUI::Dispatch::RunMode,bool,bool &)	Unknown
 	CoreMessaging.dll!Microsoft::CoreUI::Dispatch::UserAdapterBase::DrainCoreMessagingQueue(struct Microsoft::CoreUI::Dispatch::UserAdapterBase__UserPriority,bool,struct System::IntPtr &)	Unknown
 	CoreMessaging.dll!Microsoft::CoreUI::Dispatch::UserAdapter::OnUserDispatch(bool,struct Microsoft::CoreUI::Dispatch::UserAdapterBase__UserPriority,struct System::IntPtr &)	Unknown
 	CoreMessaging.dll!Microsoft::CoreUI::Dispatch::UserAdapter::OnUserDispatchRaw(struct System::IntPtr,struct Microsoft::CoreUI::Dispatch::UserAdapterBase__UserPriority,bool,struct System::IntPtr &)	Unknown
 	CoreMessaging.dll!Microsoft::CoreUI::Dispatch::UserAdapter_DoWork(struct Microsoft::CoreUI::Dispatch::UserData *,struct Microsoft::CoreUI::Dispatch::UserAdapterBase__UserPriority,bool)	Unknown
 	CoreMessaging.dll!Microsoft::CoreUI::Dispatch::UserAdapter_HandleDispatchNotifyMessage(struct HWND__ *,unsigned int,long)	Unknown
 	CoreMessaging.dll!Microsoft::CoreUI::Dispatch::UserAdapter_WindowProc(struct HWND__ *,unsigned int,unsigned int,long)	Unknown
 	user32.dll!__InternalCallWinProc@20()	Unknown
 	user32.dll!UserCallWinProcCheckWow()	Unknown
 	user32.dll!DispatchMessageWorker()	Unknown
 	user32.dll!_DispatchMessageW@4()	Unknown
 	Microsoft.ui.xaml.dll!0a25b849()	Unknown
 	Microsoft.ui.xaml.dll!0a25c014()	Unknown
 	Microsoft.ui.xaml.dll!0a0e14f8()	Unknown
 	[Managed to Native Transition]	
 	Microsoft.WinUI.dll!ABI.Microsoft.UI.Xaml.IApplicationStatics.Microsoft.UI.Xaml.IApplicationStatics.Start(Microsoft.UI.Xaml.ApplicationInitializationCallback callback)	Unknown
 	Microsoft.WinUI.dll!Microsoft.UI.Xaml.Application.Start(Microsoft.UI.Xaml.ApplicationInitializationCallback callback)	Unknown
>	App11.dll!App11.Program.Main(string[] args) Line 26	C#
 	[Native to Managed Transition]	
 	[Inline Frame] hostpolicy.dll!coreclr_t::execute_assembly(int) Line 89	C++
 	hostpolicy.dll!run_app_for_context(const hostpolicy_context_t & context, int argc, const wchar_t * * argv) Line 246	C++
 	hostpolicy.dll!run_app(const int argc, const wchar_t * * argv) Line 275	C++
 	hostpolicy.dll!corehost_main(const int argc, const wchar_t * * argv) Line 408	C++
 	hostfxr.dll!execute_app(const std::wstring & impl_dll_dir, corehost_init_t * init, const int argc, const wchar_t * * argv) Line 146	C++
 	hostfxr.dll!`anonymous namespace'::read_config_and_execute(const std::wstring & host_command, const host_startup_info_t & host_info, const std::wstring & app_candidate, const std::unordered_map<enum known_options,std::vector<std::wstring,std::allocator<std::wstring>>,known_options_hash,std::equal_to<enum known_options>,std::allocator<std::pair<enum known_options const ,std::vector<std::wstring,std::allocator<std::wstring>>>>> & opts, int new_argc, const wchar_t * * new_argv, host_mode_t mode, wchar_t * out_buffer, int buffer_size, int * required_buffer_size) Line 521	C++
 	hostfxr.dll!fx_muxer_t::handle_exec_host_command(const std::wstring & host_command, const host_startup_info_t & host_info, const std::wstring & app_candidate, const std::unordered_map<enum known_options,std::vector<std::wstring,std::allocator<std::wstring>>,known_options_hash,std::equal_to<enum known_options>,std::allocator<std::pair<enum known_options const ,std::vector<std::wstring,std::allocator<std::wstring>>>>> & opts, int argc, const wchar_t * * argv, int argoff, host_mode_t mode, wchar_t * result_buffer, int buffer_size, int * required_buffer_size) Line 1001	C++
 	hostfxr.dll!fx_muxer_t::execute(const std::wstring host_command, const int argc, const wchar_t * * argv, const host_startup_info_t & host_info, wchar_t * result_buffer, int buffer_size, int * required_buffer_size) Line 580	C++
 	hostfxr.dll!hostfxr_main_startupinfo(const int argc, const wchar_t * * argv, const wchar_t * host_path, const wchar_t * dotnet_root, const wchar_t * app_path) Line 50	C++
 	App11.exe!exe_start(const int argc, const wchar_t * * argv) Line 236	C++
 	App11.exe!wmain(const int argc, const wchar_t * * argv) Line 302	C++
 	[Inline Frame] App11.exe!invoke_main() Line 90	C++
 	App11.exe!__scrt_common_main_seh() Line 288	C++
 	kernel32.dll!@BaseThreadInitThunk@12()	Unknown
 	ntdll.dll!__RtlUserThreadStart()	Unknown
 	ntdll.dll!__RtlUserThreadStart@8()	Unknown
`

Sample project for Microsoft.WinUI 3.0.0-preview3.201113.0

[AttachedCollections.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5564714/AttachedCollections.zip)

**Comment by BorzillaR** [comment]
This issue is not reproduced in Preview 4 and can be closed.
