### ISSUE TITLE
FocusManager.GetFocusedElement() always returns null

### ISSUE THREAD

**Issue by alexdi220** [microsoft/microsoft-ui-xaml#3484]
**Describe the bug**
Hi,
the GetFocusedElement method always returns null. How can I get a focused element?

**Steps to reproduce the bug**
Check focused element on TextBox's TextChanged:
~~~ csharp
textBox.TextChanged += (s, e) => Debug.WriteLine($"Focused element: {FocusManager.GetFocusedElement()}");
~~~

**Expected behavior**
The focused element should be null

**Screenshots**

**Version Info**

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview2.200713.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by codendone** [comment]
I think what you're seeing is the expected behavior. The problem is that GetFocusedElement() becomes ambiguous if there is more than one Window, since we don't know which window you want the focused element from. The solution is to pass in the XamlRoot for the desired window, and in this example you can use textBox.XamlRoot if the textBox is in the window you're interested in.

**Comment by alexdi220** [comment]
Thank you for your answer. I already use the GetFocusedElement(XamlRoot) method. But in what cases the GetFocusedElement() returns not null? Otherwise, it seems useless. Also, the WPF has only one method with a focus scope argument and it looks more clear.

**Comment by codendone** [comment]
GetFocusedElement() without a XamlRoot works in a UWP to get the focused element for the CoreWindow on the thread. As you suggest, it might make sense to remove that old API in WinUI3 and require always using the scope version.

**Comment by alexdi220** [comment]
Yes, it would be clearer

**Comment by billhenn** [comment]
I just ran into this since we are porting UWP code over and suddenly the `GetFocusedElement()` method unexpectedly returned null.  I found this thread and if we specify the `XamlRoot` it will return a result.

That being said, can't the original parameterless overload just see which window is currently active and pass its `XamlRoot` to the other overload?  That would make the most sense, instead of having to remove the parameterless overload, or keep it and return null all the time.

**Comment by pratikone** [comment]
we have rolled out support for multiple windows now. you will need to modify the code to call `GetFocusedElement()` with xamlroot.   Read more here : 
https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.input.focusmanager.getfocusedelement?view=windows-app-sdk-1.2#microsoft-ui-xaml-input-focusmanager-getfocusedelement(microsoft-ui-xaml-xamlroot)

**Comment by citelao** [comment]
I've opened [a docs PR](https://github.com/MicrosoftDocs/winrt-api/pull/2463) to note this behavior, since I hit it myself.
