### ISSUE TITLE
Exception on XamlDirect.CreateInstance call

### ISSUE THREAD

**Issue by BorzillaR** [microsoft/microsoft-ui-xaml#3509]
**Describe the bug**

Hello!

When I try to create an IXamlDirectObject the following exception throws.

![image](https://user-images.githubusercontent.com/23479280/97439507-4bc48c80-1937-11eb-9215-fa57fe84efa4.png)

**Version Info**

Windows 10 1903 (OS Build 18362.1082)

**NuGet package version:**

WinUI 3.0.0-preview2.200713.0

**Windows app type:**

| UWP              | Win32            |
| :--------------- | :--------------- |
|| Yes|

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Comment by StephenLPeters** [comment]
@jevansaks I don't know very much about Xaml Direct. I don't know if it is in the Winui 3 radar at all. Can you shed light on what this issue might be or suggest who would be able to?

**Comment by jevansaks** [comment]
@jonthysell was driving this. @MikeHillberg  can probably help though. It's less relevant with WinUI 3 because we're taking the opportunity to flatten the ABI so the vtable/vfptr explosion is contained -- but XAML Direct still allows you to construct objects without immediately faulting in the XAML "peer" objects, so it still can be useful.

**Comment by MikeHillberg** [comment]
We'll need to debug, it might be fixed in the upcoming preview; a lot of the c# projection has been updated.

**Comment by BorzillaR** [comment]
I have checked it on Preview 3. Still reproduced.

**Comment by BorzillaR** [comment]
Seems, it is fixed in Preview 4.
