### ISSUE TITLE
Question: How to get a string resource from code?

### ISSUE THREAD

**Issue by BorzillaR** [microsoft/microsoft-ui-xaml#3589]
I try to use UWP approach to get a resource identified by resource id. 

https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.resources.resourceloader?view=winrt-19041#examples

But I got the following exception.

![image](https://user-images.githubusercontent.com/23479280/98683322-f1cfb800-2375-11eb-850f-1d6af79db04f.png)

What a true way to get the string resource by resource id in WinUI/Desctop applications?

**Comment by ranjeshj** [comment]
@stevenbrix @alwu-msft as FYI

**Comment by alwu-msft** [comment]
@BorzillaR This is a known issue (string resources not being added to the expected resource map) with Preview 2 that will be addressed in Preview 3. In the meantime, you may be able to workaround this by calling [`GetForCurrentView()`](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.resources.resourceloader.getforcurrentview?view=winrt-19041#Windows_ApplicationModel_Resources_ResourceLoader_GetForCurrentView_System_String_) with the project name as an argument; using the example from your project, it would look like `ResourceLoader.GetForCurrentView("Localization").GetString("String1")`.

**Comment by BorzillaR** [comment]
@alwu-msft, thank you!

**Comment by anawishnoff** [comment]
This was fixed in WinUI 3 Preview 3, so I'm going to go ahead and close this issue. Feel free to re-open and let us know if the issue still persists.

**Comment by JosHuybrighs** [comment]
I am not sure how WinUI 3 Preview 3 relates to WinUI 3 Project Reunion 0.8.4 which I am using to build a desktop app, but with 0.8.4 the following still doesn't work:
`var resourceLoader = Windows.ApplicationModel.Resources.ResourceLoader.GetForCurrentView();`

Error:                 
```
System.Runtime.InteropServices.COMException: 'Can't create resourcecontext for threads that don't have a CoreWindow. (0x80073B27)'
(translated from Dutch)
```
The call to GetForCurrentView is done within a 'Page' constructor after InitializeComponent.

What works is:
`var resourceLoader = Windows.ApplicationModel.Resources.ResourceLoader.GetForViewIndependentUse();`

Question: is WinUI 3 Preview 3 (or whatever) still something that exists or is there a WinUI 3 Project Reunion 0.8 Preview x now?

**Comment by evelynwu-msft** [comment]
@JosHuybrighs Since this thread was started, WinUI 3 has become part of Windows App SDK (formerly known as Project Reunion); WinUI 3 Preview 3 is a pretty old release! You're fine to continue using Windows App SDK 0.8.4.

For resource management, Windows App SDK's default mechanism is MRT Core, a lighter-weight version of the OS's built-in MRT (Windows.ApplicationModel.Resources). An overview of MRT Core can be found [here](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/mrtcore/mrtcore-overview), while API documentation is [here](https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.windows.applicationmodel.resources?view=windows-app-sdk-1.0). And this [sample app](https://github.com/microsoft/WindowsAppSDK-Samples/tree/main/Samples/ResourceManagement/cs-winui/winui_desktop_packaged_app) should help you get started; I suspect you would be particularly interested in [these](https://github.com/microsoft/WindowsAppSDK-Samples/blob/1abe6431a40b38526fd8587f4166324b2e20c25a/Samples/ResourceManagement/cs-winui/winui_desktop_packaged_app/App.xaml.cs#L37) [lines](https://github.com/microsoft/WindowsAppSDK-Samples/blob/1abe6431a40b38526fd8587f4166324b2e20c25a/Samples/ResourceManagement/cs-winui/winui_desktop_packaged_app/MainWindow.xaml.cs#L31).
