### ISSUE TITLE
WinUI 3.0 no XAML designer view?

### ISSUE THREAD

**Issue by jixc2008** [microsoft/microsoft-ui-xaml#3656]
I know WinUI 3.0  is in alpha and early days, but I just want to confirm if the designer view is something that exists yet, or if it doesn't.

**Comment by jixc2008** [comment]
I hope to have a XAML designer view similar to WPF to speed up development .

**Comment by anawishnoff** [comment]
Hi @jixc2008, the XAML Designer is currently not supported in WinUI 3 Preview 3. We don't have a guaranteed timeline for this, but we're expecting to look into this after WinUI 3.0 ships.

**Comment by lone-wolf-akela** [comment]
> Hi @jixc2008, the XAML Designer is currently not supported in WinUI 3 Preview 3. We don't have a guaranteed timeline for this, but we're expecting to look into this after WinUI 3.0 ships.

The problem is, in https://docs.microsoft.com/en-us/windows/apps/winui/winui3/ , the line that was saying "no Visual Designer" in preview 2 is now removed in this document for preview 3. This is kind of misleading.

**Comment by anawishnoff** [comment]
@lone-wolf-akela Great point - I believe this got removed because it was lumped together with other developer tools (Intellisense, Hot Reload, etc.) which are now working. I'll go ahead and add this back into the known issues list.

**Comment by vmx17** [comment]
OMG. orz. Is it ok to close? Really? No designer nor Blend support? I've been chasing project reunion to spread knowledge of WindowsForms in C++/WinRT to all over my colleague but this ISSUE stops it. Programmers, should accept any new APIs (yes, I agree) but designers cannot try/prototype/demonstrate without such tools. Delay of such items discourage us to go with...

**Comment by Aaron-Corp00** [comment]
@anawishnoff  Thank you for the information around the Visual Designer. When you have the chance can you detail or link to Microsoft's thought processes around not including a Visual Designer in WinUI 3 v1.0? This is a major regression in functionality compared to all other desktop UI frameworks Microsoft has released over the last 25+ years. On my team this missing feature is causing an internal re-evaluation of the choice to use WinUI 3 for future and current projects. As such we'd like to know if there has been any updates to the timeline around the introduction of a Visual Designer for WinUI 3?

**Comment by JonPerkinsOldGit** [comment]
I have a workaround that I use, and I am not suggesting that it is satisfactory but at least it works. I had a rather complex page to assemble last week so I opened an older WinUI 2.4 (UWP) project and added a new blank page. I was able to do most of the visual assembly here because that platform is supported with the visual designer, and then I just cut and pasted the XAML over to my Reunion 0.8-preview project and was able to finish the final refinements by hand. I think the main issue was that I had to alter a couple of namespace declarations at the top to non-UWP alternatives, but otherwise the XAML is are largely code-compatible.

Having said that, I've written quite a few pages now without the designer and it is less hassle than I thought it would be; I too almost decided not to move up to 3.0 without the designer. I am kind of surprised by the comment further up this page that the team haven't even got around to "looking into this" yet, but that was seven months ago in fairness

**Comment by vmx17** [comment]
Thank you replying my delayed-asking. With the movement of C++/WinRT and Project reunion, I've considered to change compilers FROM OUT OF Microsoft. This is our selfish story.

I'm a member of SI'er company working on medical and industrial fields. We are holding very large and old, complicated, vender-dialect program core. I thought we should shift to brand-new software NOW. Considering the C++/C#/WinRT and  project reunion, now is the best time to preparation. As for medical programs, .Net (core or framework) was sufficient for productivity (DB and Web). Even FA field, .Net core can be adoptable (but FA device companies still supplies 32bit drivers only). As for industrial field, it request performance of C++ because our customer draws more than one million lines in one screen to measure center of gravity, and have to solve NP-hard problems repeatedly.

For example, think of CAD. Do you think it can be separated from desktop? I cannot imagine drawing with fingers and screen- or battery-driven bluetooth keyboard. It use mouse and wired keyboard to input accurate value. This ground is the place where Microsoft can dominate with desktop software. I know changing GUI controls (binary) costs so expensive then I want to move to the newest one, means WinUI3. With the most performance of C++/WinRT, WinUI desktop seems the most suitable solution. But at least, such environment, like VS Code with open source compilers, lacking GUI designer assist is insufficient for official use. To develop XAML code from nothing seems not productive enough.

Timelines. the cost of changing to C++17 (or 20, I prefer) from another company's old one may be equivalent cost to C#/WinRT. Starting from now on, new design (small start because I'll try TDD with VS), evaluate difficulties, train young programmers, hmm... at the time we get WinUI3 or .net 6 (or Windows11, whatever), I want to be able to draw multi-window desktop design.

At the same time, some other person start talking about gcc because Windows seems going to light-weight, like wsl2, and container-based operating system. Is it true?

**Comment by LJ-Court** [comment]
Wait so are there no plans to introduce an xaml designer view for project reunion or is it just not arriving in near future?

**Comment by vmx17** [comment]
I think, by now, we can get XAML Studio and XAML Controls Gallery but they are not "windowing" tool. Are there any other tools useful to develop WinUI3 Desktop? At least, I need some reference or knowledge base.

**Comment by GeorgeKerwood** [comment]
Respectfully jumping on the chain to lobby for, at the very least, some clarity on Microsoft's plan to support a means of visual design for WinUI 3.0. Its lacking currently presents a serious barrier of entry for those of us not gifted with xaml second sight.

**Comment by asouth** [comment]
There should be some warning or note about this in VS to make it clear there is no Designer at the moment for WinUI 3.0, its wasting peoples time unnecessarily.

**Comment by Beji-kun** [comment]
Exist some alternative for XAML desinger for WInUI

**Comment by jonasnordlund** [comment]
> Respectfully jumping on the chain to lobby for, at the very least, some clarity on Microsoft's plan to support a means of visual design for WinUI 3.0. Its lacking currently presents a serious barrier of entry for those of us not gifted with xaml second sight.

Even being fairly seasoned in XAML, this is very important to me to get a continuously updated view of what I'm doing. A 300 row, six level deep XAML tree is awesomely structured for a computer, less so for a human to get a bird's eye view.

**Comment by megastary** [comment]
I wanted to write our new app using WinUI3, but after being stuck for couple days with various things, discovering this tragic information was the last nail in the coffin. Back to the WPF!

**Comment by fourdragons** [comment]
So, I've  really just been wasting hours the past week trying to get this to work? No, I didn't spend all the past week trying to get it to work, just have tried numerous times while I stumbled across different tips/tidbits while exploring UWP/C#. Nothing has worked, even for 0.8. Well, now I know WHY. LOL. Just wasted precious hours. (Not really, I did learn a lot.) Guess I'm stuck using UWP by itself for the foreseeable future.

**Comment by GeorgeKerwood** [comment]
To anyone continuing to follow this thread in hopes of alternatives or designer news may be interested to visit #5917. 

Whether is it specially new to Windows App SDK 1.0.0 or not, I don't know, however VS 2019 is supporting both Hot Reload and Live Visual Tree for WinUI 3.0 xaml. In my opinion resolves the greater part (of course not all) of the no-designer-issue.

**Comment by bugproof** [comment]
Is it just me or there is no intellisense for C++ WinUI3 apps in XAML files?

![image](https://user-images.githubusercontent.com/3116731/160394309-afecd93c-77c2-46b5-92ac-e9ce9465212b.png)

**Comment by arthur-s** [comment]
> Is it just me or there is no intellisense for C++ WinUI3 apps in XAML files?
> 
> ![image](https://user-images.githubusercontent.com/3116731/160394309-afecd93c-77c2-46b5-92ac-e9ce9465212b.png)

same to me

**Comment by TheMR-777** [comment]
> Is it just me or there is no intellisense for C++ WinUI3 apps in XAML files?
> 

Same here mate. Still no IntelliSense support for C++ projects,

**Comment by JonPerkinsOldGit** [comment]
I have become used to writing the XAML purely in the code window (even without the IntelliSense) and then just seeing how it looks when I run it, but I am very disappointed by the three-years-and-counting absence of the XAML designer which disappeared since the discontinuance of UWP. I would prefer to see this reinstated in favor of everything else that the team are looking to add in the next WinApp SDK. That it was missing at v1.0 was a surprise but after all this time it is just sheer failure.

**Comment by a-M1NG** [comment]
> Is it just me or there is no intellisense for C++ WinUI3 apps in XAML files?
> 
> ![image](https://user-images.githubusercontent.com/3116731/160394309-afecd93c-77c2-46b5-92ac-e9ce9465212b.png)

Same problem, I found out that C++/WinRT doesn't support either. However, at about 4:13 [in this video](https://www.bilibili.com/video/BV1eS4y1S7kC/?share_source=copy_web&vd_source=2e7323957527c3af92905aeb9be2d964), the VS2019 used by the video uploader seems to support intellisense

**Comment by GuildOfCalamity** [comment]
Hot-Reload is not a solution for this problem, rarely does it update the app properly.
I understand MS is going x-plat so showing _Windows_ controls might not make sense to everyone, but at least you could use them as placeholders during the UI design phase.
