### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by santhoshkumarmk** [microsoft/microsoft-ui-xaml#3660]
Can i migrate my wpf project to UWP. If possible just me steps.

**Comment by huoyaoyuan** [comment]
WPF and UWP are indeed different technologies. You can bring many parts from WPF, but there's no simple migrations.

View models and utilities are often reusable, with changing the namespace from `System.Windows` to `Windows.UI` or `Windows.UI.Xaml`.

For xaml, the suggestion is to copy from old application block by block. There are certain features not available in UWP xaml, and you need to find their replacements.

**Comment by robloo** [comment]
@santhoshkumarmk There is no step-by-step procedure for going from WPF to UWP or WinUI. WPF is an entirely different framework and things by design dont work the same in all areas. If you are prepared to make some changes it can be done relatively quickly though. If you have a small app it should be little trouble.

An idea of the changes you may need to make is below:

https://github.com/robloo/PublicDocs/blob/master/UWPvsWPF.md

**Comment by StephenLPeters** [comment]
Also keep in mind that with winui3 your winui projects do not need to be UWP if that is what ends up blocking your migration
