### ISSUE TITLE
Add WinUI window to WPF/WinForms

### ISSUE THREAD

**Issue by Marv51** [microsoft/microsoft-ui-xaml#3675]
One of the promoted use-cases of WinUI 3 on the community calls is to modernize existing applications.

Especially interesting to me would be how to add a WinUI 3 window to an existing WPF app. This is a very important scenario.

The WinUI 3 documentation is lacking a "Getting started from WPF/WinForms" page. And trying to get this working on my own has been unsuccessful. 

Please support this.

**Comment by Marv51** [comment]
Is there something out there how to do this? I can't find anything. @anawishnoff do you know?

**Comment by anawishnoff** [comment]
@Marv51 - this is a great question, and I know that this is a gap in our documentation. While WinUI 3 is still in preview, we're recommending creating new WinUI 3 projects rather than adding it to an existing project. This is why there aren't any docs on adding WinUI 3 to an existing app yet.

Our local WinUI 3/Desktop expert @marb2000 may have some more detailed advice here.

**Comment by Marv51** [comment]
Any update on this? @marb2000 or @anawishnoff ?

**Comment by Marv51** [comment]
After looking into this a bit more, it does not seem to me like this is a documentation issue, it seems to not work. I have updated the title and the description.

@ranjeshj  Can you remove the "documentation" label?

**Comment by Marv51** [comment]
Understanding a bit more about how WinUI 3 works. I feel like I should close this issue. 

It is not possible to have WPF/WinForms and WinUI 3 in the same process. If/When XAML-Islands returns then that solves this issue completely. 

I was thinking it would be possible/easier to have a WinUI 3 window in a WPF app without full XAML-Island support, but I think that is not so.

**Comment by emilsteen** [comment]
This info is on the WinUi page on docs.microsoft.com "... or gradually migrate your existing MFC, WinForms, or WPF apps using familiar languages such as ... ".

**Comment by nikeee** [comment]
I've got a WinForms application and I'm trying to create a new window using WinUI. Is it possible now?

If not, is it possible to create a new Win32 app (that has the same API access as a .NET6 WinForms app) that uses WinUI instead?

**Comment by ojhad** [comment]
@marb2000 fyi

**Comment by astramistil** [comment]
Sorry but I'm now totally lost, and I'm sure I'm not the only one.

1- I thought the aim for project reunion was to be able to use any Win32 controls in a WinUI project. Wasn't it?

2- Since WinUI, WinRT and .Net6 are the new standards, should all my new projects be WinUI projects? (I aim at Windows 10-11 only). But there are WPF controls I really want to use that aren't available in WinUI (especially when using a 3rd party library like DevExpress); so what project type do your recommend I use in that case?

3- As I think I understand right now, XAML Islands is not working in .Net6?

Thank you it's quite confusing honestly (so much have changed in .Net in a short amount of time; it seems like reading about Project Reunion/Xaml Islands or looking at videos from 1 or 2 years ago doesn't seem relevant anymore).

**Comment by astramistil** [comment]
Anyone please? @Marv51 , @anawishnoff , @marb2000? Thank you.

**Comment by jonrmorgan99** [comment]
Pretty depressing to read astramistils pleas for some sanity in the WinUI world, nearly three years on from the OP.

The funeral rites on Winforms and WPF have been pronounced repeatedly over the years but there's still lots of us using them daily to get the job done in the dektop world.

MS helpfully made it easy to host WPF controls in WInforms apps and vice versa. Is that one of the design goals  of WinUI or is MS determined to go on trying to persuade us to torch years of development work and move to what looks like a very shaky, now not-so-new framework ? 

Anyone please? @Marv51 , @anawishnoff , @marb2000?
