### ISSUE TITLE
Proposal: make it easier to debug layout cycles

### ISSUE THREAD

**Issue by FrayxRulez** [microsoft/microsoft-ui-xaml#3779]
# Proposal: make it easier to debug layout cycles

I know it's absolutely non-trivial, but I think that in some future WinUI 3.X version this should happen.
At the moment having a large code base it's pretty much impossible to find out where a layout cycle happens without being able to reproduce the issue. I released a update a couple of days ago and I'm just seeing the amount of crashes raising drastically, and I have absolutely no way to find out what's the cause. I can just wait until someone will bother to reach me out somehow to inform me about the problem, hoping that he's actually able to explain me how the issue happened.

**Comment by StephenLPeters** [comment]
I would love this, its definitely not trivial though.

**Comment by StephenLPeters** [comment]
I think framework team owns layout?

**Comment by chrisglein** [comment]
As someone who has debugged more than their fair share of layout cycles, I heartily agree! However... I'm very curious what ideas you have for how that process could be improved. I generally use trace breakpoints as live debugging is worse for layout debugging than aggregate/log style analysis. On a previous framework I worked on I spent a lot of time building layout diagnostics tools only to realize that they were only useful to layout authors, not app/page authors.

So my question is this, what would you like here? And be as specific and needy as possible! :D What would success look like?

**Comment by FrayxRulez** [comment]
Hi @chrisglein, I'm not sure I have some really concrete view, but I think that I would be happy already to have some traces of where the cycle happens, as with a stack overflow.
Just consider a scenario where you have hundreds of xaml files and templated controls. Finding out with SizeChanged/MeasureOverride/ArrangeOverride is causing the problem is going to be a nightmare, even more if you can't reproduce the problem yourself.

Is there any chance that the framework could keep track of the source that triggered the relayout?

**Comment by chrisglein** [comment]
> Is there any chance that the framework could keep track of the source that triggered the relayout?

That seems possible. The layout cycle is detected by tracking a count in the layout manager and when it exceeds some threshold flagging it as a layout cycle. It seems like it'd be possible to use that threshold to trigger a diagnostic mode, let layout run a couple more cycles, and report what was invalidating layout within that window. Maybe even getting really fancy and reporting what layout numbers were changing and what weren't in that time window (as you often get something toggling between two states).

**Comment by MikeHillberg** [comment]
I think the layout-cycle error is raised during layout, when it detects that it's about to run one too many layouts. Maybe one simple thing we could do is raise the error when N-1 layouts have run, and layout is getting invalidated. For example if the problem (or part of the problem) is some code that's setting an element Width, that call to the setter would be on the call stack.

**Comment by michael-hawker** [comment]
I think the main thing missing is that it's not easy to catch where the exception is coming from and so there's no useful stack here of information around which controls are being laid out. If you had a list of the calls, then at least you could maybe see where the cycle is occurring and which controls are involved with the cycle?

We're hitting something in a custom control with a VSM, so it's really hard to understand what particular piece is causing an issue, especially as it's only happening intermittently.

**Comment by FrayxRulez** [comment]
After more than two years I still didn't manage to find the source for mine, as I never even managed to reproduce it on my machine. I just see a _lot_ of them in my crash analytics, but I'm completely blind about this as it's a quite complex piece of software...

**Comment by codendone** [comment]
There are new APIs coming in WinAppSDK 1.5 to improve layout cycle debugging. Here's a short summary (full API docs will be published with the 1.5 release):
* An app may set a new `DebugSettings.LayoutCycleTracingLevel` property to get helpful native debugger output
during a layout cycle crash, or to raise the level/verbosity of logging also included in crash dumps.
* An app may also set a new `DebugSettings.LayoutCycleDebugBreakLevel` property to trigger an attached native debugger
to break in during interesting events leading up to a potential layout cycle crash.

Debugging layout cycles can still be challenging with this new support, but the tracing and DebugBreak support greatly increases the visibility of what is happening during a layout cycle and helps to break in to inspect state to further determine the cause.

I'm closing this proposal as Completed with this new support. We may want additional improvements in the future, but hopefully those will be tweaks on top of these new properties.

Also worth noting is that WinAppSDK 1.5 will include fixes for layout cycles caused by incorrect layout-rounding handling in ScrollBar, Slider, and Progress. (The new LayoutCycle debugging properties were used to track down those issues.) Hopefully those fixes in those core controls will significantly reduce the occurrence of non-trivial layout cycles.

**Comment by codendone** [comment]
@FrayxRulez The fixes made for WinAppSDK were all code changes. However, at least for ScrollBar there is a possible workaround in the app:
> A workaround is available for this issue: Set `UseLayoutRounding = false` on the `VerticalPanningRoot` element in ScrollBars.
>
> One option is to restyle ScrollBar (such as by copying the default ScrollBar style) and set this property on the element in style. The default <Style> block for ScrollBar is rather large, so this might not be the most desirable option.
>
> Another option is to run code using `VisualTreeHelper` to search for the element under the subtree of the given element and set the property on it.

For diagnostics, your approach using `FrameworkElement.SizeChanged` is about as good as you can get for UWP. Replacing the `VerticalPanningRoot` in style with a subclass of Grid so you can monitor and log the MeasureOverride/ArrangeOverride results could be better, if you know the problem is specific to ScrollBar (or do something similar for an appropriate control). (For ScrollBar, if you have horizontal scrolling rather than vertical, then `HorizontalPanningRoot` may also or instead be the one you want.)

**Comment by stevenbrix** [comment]
@codendone after trying out these new properties, it seems somewhat insufficient for collecting information from the wild, as they require having a debugger attached. is there any way xaml could provide a callback for these messages so that the app can log them how they prefer?

also, the docs say that the information will be stored in stowed exceptions, but that doesn't seem to be the case. i created https://github.com/microsoft/microsoft-ui-xaml/issues/9913 to track this
