### ISSUE TITLE
Proposal: Ability to support reorder and drag & drop for specific items only

### ISSUE THREAD

**Issue by knightmeister** [microsoft/microsoft-ui-xaml#381]
# Proposal: Ability to support reorder and drag & drop for specific items only

## Summary
The UWP TreeView exposes only two events for supporting drag and drop, and by extension, reordering. These events are [DragItemsCompleted ](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.treeview.dragitemscompleted)and [DragItemsStarting](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.treeview.dragitemsstarting).

I can prevent a drag operation from starting by setting Cancel = True on the `[DragItemsStarting](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.treeviewdragitemsstartingeventargs)` event.

This isn't flexible enough to support a scenario where I might have items fixed at the start of the tree which are "built in" to the app and not designed to be reordered or moved. My app displays a bunch of inbuilt categories (all, featured, recent, loved, etc) and then user categories/tags. The user categories should be able to be reorganised and dragged/dropped but the hierarchy of the in built items should be preserved.

## Rationale
This feature needs to be added so that developers can implement a more powerful treeview control, which gives better interaction to users who are using the control.

## Functional Requirements

**DragItemsCompleted event**
Add a Cancel and DropTarget property. DropTarget represents the item that the item(s) were dropped on and allows for cancelling the operation.

I think this should be sufficient to cater for both a drag/drop & reorder operation.

**Comment by jevansaks** [comment]
We think this might be possible, @chrisglein  is going to poke around.

**Comment by chrisglein** [comment]
Just to make sure I'm following. You have some situation like this:
![TreeView_PreDrag](https://user-images.githubusercontent.com/26607885/54237077-63d16900-44d2-11e9-9085-6c85b317dd27.png)
You can use `TreeViewDragItemsStartingEventArgs.Cancel=true` to stop your fixed items from being a drag source, and you can use `UIElement.AllowDrop=false` to prevent dropping on top of your fixed item. But there's no way to stop it from being indirectly affected by a reorder due to drag/drop on adjacent items.
So even if you've done the above someone sill still hover over and do this:
![TreeView_MidDrag](https://user-images.githubusercontent.com/26607885/54237304-dcd0c080-44d2-11e9-8bc1-9a1cce777d61.png)
As in the user can drop that item wherever they want and cause the items you meant to be fixed to instead shift around. Am I reading your problem correctly?

Waiting until `DragItemsCompleted` to handle this seems too late, as that while that might enable you to reject an undesirable reorder it, that wouldn't prevent the user from seeing the preview of that drop operation before they release. To prevent that misleading visual feedback you'd need to instead either declare the un-reorderable items up front, or have an interactive handler that decides valid drop options on hover.

Would having a `CanReorder` property set to false on your fixed position items capture your intent here? I'm assuming a property like that would determine whether the item could be picked up, dropped upon, but also affected by adjacent drops.

Your scenario sounds like it has the fixed items at the top, but having them at the bottom of the list is a likely equivalently desirable scenario. But it has some different impact on what "affected by adjacent drops" means. Also I'm not sure what would be the best way to handle intermixed `CanReorder=false` and `true` nodes. So I'm not sure if that's the right way to model this (over separate collections or adjacent TreeViews, for example), but I thought I'd first check if something like `CanReorder` would meet your needs.

**Comment by knightmeister** [comment]
@chrisglein you make a good point about stopping reordering above the fixed part of the tree, which I'd not considered, I'm not sure how this would be best served, perhaps by exposing two properties such as `NodeBefore` and `NodeAfter` in `DragItemsCompleted`.

> and you can use `UIElement.AllowDrop=false` to prevent dropping on top of your fixed item

The `TreeViewNode` element is missing `AllowDrop` property and setting `AllowDrop` on a `TreeViewItem` does not prevent me from dropping an item on it.

> As in the user can drop that item wherever they want and cause the items you meant to be fixed to instead shift around. Am I reading your problem correctly?

Yes; for a requirements list, users should not be able to:
1. reorder fixed items
2. drag the fixed items to be children of their own categories
3. drag their categories into the "fixed" area
4. drag their categories to be children of fixed items

> Waiting until `DragItemsCompleted` to handle this seems too late, as that while that might enable you to reject an undesirable reorder it, that wouldn't prevent the user from seeing the preview of that drop operation before they release. To prevent that misleading visual feedback you'd need to instead either declare the un-reorderable items up front, or have an interactive handler that decides valid drop options on hover.

Agreed.

> Would having a `CanReorder` property set to false on your fixed position items capture your intent here? 

Using a property would be an alternative to events; CanReorder would prevent changing the order of fixed items and presumably also stop it from being dragged into a user defined category. However, it wouldn't stop the adjacent reordering you mentioned, nor would it prevent user categories from being dropped onto the fixed nodes. 

To solve all these requirements, the following should work:

1. Add the CanReorder property to Node/Item as you've suggested. This would resolve item 1 in my requirements list above, and depending on the implementation, possibly item 2.
2. Modify DragItemsCompleted, or add an additional querying event, which exposes `SelectedNode` or similarly named property. `SelectedNode` would be the node that is being hovered over or that the nodes have been dropped on. In conjunction with a `Cancel` property, this would resolve items 2 and 4 in the above requirements list.
3. As mentioned earlier in my reply, adding properties `NodeBefore` and `NodeAfter` would solve item 3 in the requirement list.

**Comment by chrisglein** [comment]
In my head I was thinking `CanReorder`* would control a couple things:
1. Can't be dragged
2. Can't be dropped onto
3. Disallow any drop operation that would change this items position in the list

*CanReorder may be the wrong description of the policy I'm trying to capture here. If you have ideas for better names definitely suggest them.

That 3rd item is where there are interesting edge cases. For example, what if I have this:
```
Item 1
Fixed Item 1
Fixed Item 2
Item 2
Item 3
```
(where Fixed items have CanReorder=false)
I should be able to swap the positions of 2 and 3. That seems clear. But what can I do with 1? What's the promise of CanReorder=false? One way to interpret it is that the fixed items are chunked together. So I'm allowed to do this after dragging Item 2 above Item 1:
```
Item 2
Item 1
Fixed Item 1
Fixed Item 2
Item 3
```
Another is that their index in the list is fixed, so dragging Item 2 above Item 1 is actually a swap:
```
Item 2
Fixed Item 1
Fixed Item 2
Item 1
Item 3
```
If the fixed items were at the top/bottom of the list initially, thinking about your scenario, I don't think you want to be able to drop above/below them respectively. As in in this case you should never be able to get above Fixed Item 1:
```
Fixed Item 1
Fixed Item 2
Item 1
Item 2
Item 3
```
Items at the top of the list can reliably have their indexes stable. But if we're anchored to the bottom and there's removal or grouping (as there is in TreeView), then I think you need to take a higher level interpretation than just 'fixed index'. For example, let's say I start with this:
```
Item 1
Item 2
Item 3
Fixed Item 1
Fixed Item 2
```
And then I drop 3 onto 1:
```
Item 1
- Item 3
Item 2
Fixed Item 1
Fixed Item 2
```
That feels like it's respecting the intent of having those items not reorder... but strictly speaking with respect to their top level index, they were bumped up one item.

Really we can pick any policy here and stick to it, as long as it's documented and well understood. Providing custom hooks in the events would allow more customization of that policy, in case we go it 'wrong' for any developer's scenario. But I think there's probably a core scenario here that we can represent in a more up-front declarative way that avoids needing hands-on events.

To me that's interpreting a CanReorder=false it as follows:
1. Can't be dragged
2. Can't be dropped onto
3. Can only be dropped above if there is an item above and it is CanReorder=true
4. Can only be dropped below if there is an item beow and it is CanReorder=true

Am I missing anything?

**Comment by lukasf** [comment]
> To me that's interpreting a CanReorder=false it as follows:
    Can't be dragged
    Can't be dropped onto
    Can only be dropped above if there is an item above and it is CanReorder=true
    Can only be dropped below if there is an item beow and it is CanReorder=true

If it is so hard to describe what a property does, then it is probably not a good idea to add it. And I think we don't even need that property:

In DragItemsStarting, we can set Cancel=true, if this item should not be moved around. Now we only need a new "hover" event with properties SelectedNodes (the node(s) that are being dragged), DropTarget (if dropping onto a node), and NodeBefore/NodeAfter, plus Cancel property. Or we add those properties to DragItemsCompleted. So in DragItemsStarting we can prevent dragging of locked items. For all allowed items, we can decide if the drop location is valid in the other event, and prevent drop if this is not the case. 

This should fulfill all requirements, and it is flexible and not only tied to this exact scenario. Maybe someone would want to allow reordering of fixed items, but only within the fixed group, or have specific nodes not to be dropped on specific other nodes. This would all be possible with the events, no need to have a "CanReorderForMyVerySpecificAppRequirement" property ;)

I would prefer to have a new "Hover" event, since this would allow the UI to give clues whether the drop location is valid or not. There could be this "not allowed" icon, like we already have it in normal drag+drop operations.

**Comment by jevansaks** [comment]
Does the [DragOver](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.UIElement.DragOver) event do what you need here? Handle it and set args.AllowedOperations = None when dragging on the items in question?

**Comment by knightmeister** [comment]
Apologies for my late reply on this one.

> In my head I was thinking `CanReorder`* would control a couple things:
> 
> 1. Can't be dragged
> 2. Can't be dropped onto
> 3. Disallow any drop operation that would change this items position in the list

> Am I missing anything?
No, I think you've summarized the issue well. I would expect the majority of developers to have fixed items at the top of the tree. As you say, exposing a hook for querying will give the ultimate flexibility.

**Comment by lukasf** [comment]
You are very focues on these fixed items. Think of a file explorer. Some drives might be read-only, others can be written to. Drives cannot be re-orderd, but maybe they can be dragged (copied) into other folders. Think of a music player where you might have folders "favorite artists", "favorite albums". You can re-order inside favorite artists, but you cannot drop an artist into favorite albums.

I can imagine a whole lot of scenarios where only very specific drop/reorder scenarios are valid. I think a UWP solution should be flexible to cover many scenarios, not only one.

**Comment by knightmeister** [comment]
Hi guys, I note this is flagged for "needs follow up" - is it still under consideration? I'm being nagged about implementing this again :)

**Comment by lukasf** [comment]
Please consider this for WinUI 3.0! It is a very common scenario.
