### ISSUE TITLE
Discussion: Make acrylic a priority for WinUI 3 instead of a point 1 release

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/microsoft-ui-xaml#3840]
# Discussion: Make acrylic a priority for WinUI 3 instead of a point 1 release
Back in 2015 and 2016, the Feedback Hub was flooded with transparency related suggestions and so please make acrylic a priority for WinUI 3 instead of saving it for a minor release. When you can update visual styles, why can't you make acrylic come in WinUI 3 and then do other stuff in a minor release? It doesn't even care if it becomes an open-source or not, I just want MS to delay the launch until acrylic becomes available to WinUI 3, without it, it's a shame calling yourself a Fluent framework.

**Comment by mdtauk** [comment]
They mentioned they had started discussing how to achieve Acrylic, and they are looking at a 3.1 release for it - during the December 2020 WinUI Community Call

**Comment by Jaiganeshkumaran** [comment]
@mdtauk I know. What I'm asking it make it a high priority and delay WinUI 3 major launch for it/

**Comment by huoyaoyuan** [comment]
There should some technical difficulty. Acrylic is somehow provided by the OS itself. WinUI 3 need to define the communication between the OS, since the xaml platform is not provided by OS now.

**Comment by shaheedmalik** [comment]
They are stubborn. I don't understand the point of Open Source if they don't listen in the first place. We have been asking them about a faux acryllic or fallback acryllic on every Monthly Call for months. In the amount of time, someone here could've ripped the acrylic from Notepads and implemented. The creator posted himself and told them exactly what he did.

They insist on creating inconsistencies then wonder on why no one uses a feature.

**Comment by ShankarBUS** [comment]
@shaheedmalik,

> In the amount of time, someone here could've ripped the acrylic from Notepads and implemented. The creator posted himself and told them exactly what he did.

Ugh, you guys don't understand what they mean by **"acrylic is not supported in WinUI 3.0"**.

What they actually mean is WinUI 3 has it's own composition APIs (`Microsoft.UI.Composition`) and it doesn't use the `Windows.UI.Composition` APIs.

The `Compositor` provided with `Windows.UI.Composition` namespace has a method called [`Compositor.CreateHostBacdropBrush`](https://docs.microsoft.com/en-us/uwp/api/windows.ui.composition.compositor.createhostbackdropbrush?view=winrt-19041) which is used by UWP and WinUI 2.x `AcrylicBrush` and the `HostBackdropBrush` made by the Notepads dev.

Since the `Windows.UI.Composition.Compositor` comes within the OS, it has full integration with DWM and can get the windows's backdrop.

However the `Microsoft.UI.Composition.Compositor` is provided independent of the OS. So it doesn't have integration with DWM. Thus, the `Compositor.CreateHostBacdropBrush` won't work in WinUI 3 and `AcrylicBrush` is not implemented in WinUI 3.

Are we clear?

**Comment by mdtauk** [comment]
This issue is only here to encourage conflict as I see it.

The WinUI team has said Acrylic (Host Backdrop) _**is**_ a priority, but their approach is not only to enable Acrylic, but future materials and visual effects.

We have brought it up, I have brought it up at the past several WinUI Community Calls - and it is scheduled for the 3.1 release, which is about 4 months after the 3.0 release.

If it were not for all of us being vocal about it, it may not have been given as much priority as it has.

Its pinned for 3.1, so enough with all the criticism and let's just focus on solving the problems that may come up with implementing it.

**Comment by ShankarBUS** [comment]
@mdtauk,

Well, I couldn't agree more.

**Comment by mdtauk** [comment]
In App Acrylic should still work as I understand it, but it does not have access to the background rendering to show the desktop and other windows with the brush.

**Comment by shaheedmalik** [comment]
> @shaheedmalik,
> 
> > In the amount of time, someone here could've ripped the acrylic from Notepads and implemented. The creator posted himself and told them exactly what he did.
> 
> Ugh, you guys don't understand what they mean by **"acrylic is not supported in WinUI 3.0"**.
> 
> What they actually mean is WinUI 3 has it's own composition APIs (`Microsoft.UI.Composition`) and it doesn't use the `Windows.UI.Composition` APIs.
> 
> The `Compositor` provided with `Windows.UI.Composition` namespace has a method called [`Compositor.CreateHostBacdropBrush`](https://docs.microsoft.com/en-us/uwp/api/windows.ui.composition.compositor.createhostbackdropbrush?view=winrt-19041) which is used by UWP and WinUI 2.x `AcrylicBrush` and the `HostBackdropBrush` made by the Notepads dev.
> 
> Since the `Windows.UI.Composition.Compositor` comes within the OS, it has full integration with DWM and can get the windows's backdrop.
> 
> However the `Microsoft.UI.Composition.Compositor` is provided independent of the OS. So it doesn't have integration with DWM. Thus, the `Compositor.CreateHostBacdropBrush` won't work in WinUI 3 and `AcrylicBrush` is not implemented in WinUI 3.
> 
> Are we clear?

I know what the issue is, as I have been one of the ones bringing up host acrylic monthly..

**Comment by Jaiganeshkumaran** [comment]
I believe they have some proprietary logic that's bundled with Windows which they can't simply make it available to the public.

**Comment by ShankarBUS** [comment]
@shaheedmalik,

I was just making it clear for you since you mentioned that the Notepads developer made his own acrylic brush. His method won't work either in WinUI 3. That was what I wanted to say.

@Jaiganeshkumaran, precise.

**Comment by FireCubeStudios** [comment]
pls focus on fixing bugs rather than adding a visual affect as opaque colors can easily be used in meanwhile

**Comment by Jaiganeshkumaran** [comment]
No please focus on adding acrylic first before WinUI 3.0

**Comment by Jaiganeshkumaran** [comment]
Closing as Windows App SDK 1.1 Preview 3 now has Mica and Background Acrylic support for WinUI 3 apps.
