### ISSUE TITLE
PointerWheelChanged event is called only when pressing Ctrl while scrolling

### ISSUE THREAD

**Issue by vadd98** [microsoft/microsoft-ui-xaml#3864]
**Describe the bug**
I'm using the WinUI 3 Preview 3 and I'm trying to implement a method to handle the PointerWheelChanged event of a GridView in order to customize the scrolling behaviour (I'm implementing an horizontal scrolling when rolling the mouse wheel while pressing the Shift key). I noticed that PointerWheelChanged is called only when I roll the wheel while pressing the Ctrl Key, otherwise it is never called. Because of this I can not customize the scrolling behaviour without having to force the user to press Ctrl.
I only used PointerWheelChanged in a GridView, but I think that this behaviour can be common for other controls too.

**Steps to reproduce the bug**
1. Create a GridView
2. Add a method to PointerWheelChanged 

**Expected behavior**
Being able to use PointerWheelChanged without having to force the user to press the Ctrl Key.

**Version Info**
WinUI 3 Preview 3. Windows 10 20H2. Windows Desktop Application. TargetPlatformMinVersion: 10.0.18362.0

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview3.201113.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| No | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes  |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by JanPeter** [comment]
I can confirm the problem with Windows 20H2 build 19042. Seems odd to barely find any docs on how to introduce this scrolling behaviour.

**Comment by ranjeshj** [comment]
@vadd98 GridView has a ScrollViewer in its template which is probably handling the events. You can try hooking to the ScrollViewer' s events or use the AddHandler method to intercept handled events.

**Comment by Ballig** [comment]
I'm having this issue too. I have not been able to get `PointerWheelChangedEvent` to trigger on any element I have tried it on, except when holding down the CTRL key. I have tried using the XAML property to set the event, and I have also used the AddHandler (with `handledEventsToo` set to true). I have tried this on ScrollViewer, Page, StackPanel, TabView, TabViewItem (haven't been able to attach it to a Window element). It will only trigger when the CTRL key is held down.

Maybe or maybe not related, the reason I'm trying to trigger this event is because the mouse wheel is not controlling the scrollbar to begin with.

My element hierarchy is:

1. Window
2. Tabview
3. TabViewItem
4. Page
5. ScrollViewer
6. StackPanel(s)

I have also tried with the ScrollViewer being at item 2. This creates the scrollbar that lets you scroll down as you'd expect, though again the mouse wheel scrolling doesn't work and the PointerWheelChangedEvent will only trigger if CTRL is held down.

**Comment by ranjeshj** [comment]
@RBrid @codendone Is it possible that dmanip is eating these events ?

**Comment by Ballig** [comment]
Related: I think I found out why the mouse wheel scrolling in general isn't working. I have a program running called "X-Mouse Button Control" which I use to disable the side mouse button being used as a back button in Chrome (no other setting in the program is turned on or would be expected to interfere with scrolling). If I shut this program down the mouse wheel scrolling works normally to move the scrollviewer - the PointerWheelChanged event still only triggers with CTRL, however.

"X-Mouse Button Control" doesn't seem to interfere with mouse wheel scrolling in anything else, just WinUI 3 desktop apps. The "XAML Controls Gallery" app scrolls normally even with "X-Mouse Button Control" running, however I don't think that app is made using WinUI 3.

**Comment by nmoschkin** [comment]
I am also having this issue.  I am trying add a bit of custom functionality to a control I am creating that is wrapped in ScrollViewer.

I do not have XMBC installed, or any other such interceptor, that I'm aware of.  So that resolution does not work for me.  

It will work if I press Ctrl, but no other combination of keys or lack thereof.

**Comment by AjaykrishnanR-axon** [comment]
This is funny because I was implementing a zoom where scrolling with control key down triggers the scaling.
