### ISSUE TITLE
Proposal: remove XAML from name

### ISSUE THREAD

**Issue by charlesroddie** [Microsoft/microsoft-ui-xaml#392]
This project is called microsoft-ui-xaml, even though XAML is only an optional way to use it.
Moreover XAML is an optional way to use other Microsoft UI frameworks too (WPF, Xamarin).
So UWP does not imply XAML and XAML does not imply UWP.

This misnaming affects the github name of this project (microsoft-ui-xaml) and also namespaces. "Windows.UI.Xaml" has nothing to do with Xaml. This is confusing to developers as the name suggests a way to interact with markup language.

Use of XAML for marketing purposes ("XAML Islands") is a marketing decision, but use in github project names and in namespaces should be more accurate.

**Comment by contextfree** [comment]
Yes, it's always been really confusing that there's basically no accepted name for this UI framework - calling it "XAML" is doubly confusing for the reasons mentioned in @charlesroddie 's post. (Some people conversely use "UWP" to refer specifically to this XAML framework, which is also wrong/misleading since UWP apps don't necessarily use it) I wish we could all decide on a name for it that doesn't have these problems.

**Comment by contextfree** [comment]
Here's a list of names I've seen used for this framework and what's wrong with them:

- "XAML": You can use controls from this framework in code (or through another framework like React Native built on top of them) without needing XAML; other frameworks like WPF and Silverlight also use XAML 

- "UWP": UWP apps don't have to use this framework; they can be written for example using HTML, game engines like Unity, or even as text-based console apps; conversely XAML Islands allows this framework to be used from a Win32 app instead of a UWP app

- "UWP XAML" - Mix of the problems above

- "Windows XAML" - Same problem with XAML not being required; also, WPF is also "Windows"

- "WinUI" - Unfortunately is just a name for the controls library in this repository and doesn't cover the layout engine, etc. they're built on.

You could say it's just hard to avoid all these problems, but WPF and Silverlight both manage ...

**Comment by jevansaks** [comment]
Great feedback. :) I agree, the terminology in this space is hopelessly confusing. Unfortunately this isn't something we're in a position to change now.
