### ISSUE TITLE
Update roadmap to include more details about 2021 feature status

### ISSUE THREAD

**Issue by Marv51** [microsoft/microsoft-ui-xaml#4006]
On the January Community Call (#3942) there was a clear promise to update the [public roadmap](https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/roadmap.md) document to reflect the current schedule. 

While I'm sure you have some sort of internal work item to track that, maybe this is a good way to track the progress on that.

**Comment by StephenLPeters** [comment]
@anawishnoff FYI

**Comment by Marv51** [comment]
This is even more relevant now that the team has announced a preview 4. Please communicate using the published documents.

**Comment by anawishnoff** [comment]
Thanks @Marv51 - we have been working on this, expect to see an updated roadmap within the next day or two.

**Comment by Marv51** [comment]
Just about 2 weeks after the call and the roadmap has not been updated yet. Please don't forget @anawishnoff

**Comment by anawishnoff** [comment]
@Marv51, we are actively working on this and reviewing it throughout the team - we appreciate your patience!

**Comment by mrlacey** [comment]
This is what was shown on the call

![WinUI3 roadmap including project Reunion release 0.5 in March 2021, release 0.8 in May 2021, and release 1.0 in October 2021](https://user-images.githubusercontent.com/189547/106619950-02549080-6569-11eb-9219-ca82279943c6.png)

When the roadmap is updated, please can it include/confirm the following:

- Will the WinUI3 release that happens as part of Project Reunion 0.5, be the official/GA release of WinUI3 version 3.0? (if not, then what?)
- Will the WInUI3 release that happens as part of Project Reunion 0.8 be identified as WinUI3 version 3.1? (if not, then what?)
- Will the WInUI3 release that happens as part of Project Reunion 1.0 be identified as WinUI3 version 3.3? (if not, then what?)
- When will preview releases of WinUI3 begin shipping?
- What will be the standard/pattern for numbering preview releases?
- Will preview releases be be made available in the same months that stable releases also come out?

**Comment by anawishnoff** [comment]
@Marv51  - happy to report we've published an updated roadmap doc: https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/roadmap.md.

@mrlacey - these are great questions, some of which we are still figuring out ourselves. I'll make sure we share this information as we finalize it.

**Comment by omikhailov** [comment]
Hmm... Do I understand it correct that production-ready version of WinUI 3 for UWP will be available in October? Isn't it too late? For example, WebView2 is already available in Winforms and WPF, but UWP will get it almost one year later as part of WinUI. Plus, there will be Sun Valley update in 21H2 and developers will have to choose between "old" UWP supporting new design and "new" WinUI with old design.

I think that it may make more sense to change focus from Win32 to UWP. In the former case on Build 2021 we will see just announcement of tools which UWP developers cannot use and WPF developers don't hurry to use, while in the latter case it would be release of stable library of controls (maybe even v3.1) that can be used in UWP and is or will be available for thoose Win32 developers, who does not upgrade because of limitations of WinRT and containers.
