### ISSUE TITLE
WinUI version schema sometime can't applied to MinVersion

### ISSUE THREAD

**Issue by licanhua** [microsoft/microsoft-ui-xaml#4008]
Add PackageDependency like below: 
```   <PackageDependency Name="Microsoft.UI.Xaml" MinVersion="2.62101.13002" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" />
```
Run into build error:
error : Error info: error C00CE169: App manifest validation error: The app manifest must be valid as per schema: Line 14, Column 51, Reason: '2.62101.13002' violates pattern constraint of '(0|[1-9][0-9]{0,3}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])(\.(0|[1-9][0-9]{0,3}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])){3}'.

**Comment by jevansaks** [comment]
That version string passes the regex in the error message. I suspect MakeAppx has a bug that it's using different code to validate the string.

Regardless we will legitimately start failing this in WinUI 2.7 if we continue with this scheme for the package versions (because the 2nd component would be 7xxxx > 65535). So we'll need to do something soon. The framework package version doesn't really matter as long as it's always increasing. Maybe we just drop the major version out of the framework package version string and start the version with the minor component? Then the version is Minor.YYMM.DDRRR which will always fit in this scheme.

**Comment by DrusTheAxe** [comment]
Will there be a 2.7 release?

**Comment by StephenLPeters** [comment]
This has been fixed.
