### ISSUE TITLE
CommandBar items should show the label when collapsed if there is no other tooltip

### ISSUE THREAD

**Issue by ivanicin** [microsoft/microsoft-ui-xaml#4022]
**Describe the bug**
`CommandBar `items should show the label as tooltip if there is no other tooltip when the `CommandBar `is collapsed.

**Steps to reproduce the bug**

1. Use the code:
```
            <CommandBar>
                <AppBarButton Label="Test" Icon="Help"/>
            </CommandBar>
```
2. Run the app and place the pointer over 'Test'

**Expected behavior**

The app should show a tooltip 'Test'
**Screenshots**

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.5.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by YuliKl** [comment]
@ivanicin thank you for opening this issue. What you're describing isn't a bug, it's a feature request. We had actually looked into adding this feature several years ago, but our accessibility experts discourage the over-use of tooltips. Tooltips are more of a crutch than an accessible answer and ideally UIs should be restructured in a way to make tooltips unnecessary. 

In your example, the tooltip is not necessary because users are able to press the "..." button to view the label. Furthermore, we [recommend changing the default label position to be on the right](https://docs.microsoft.com/windows/uwp/design/controls-and-patterns/app-bars#button-labels) when practical. With the label always visible, there's no need for either a tooltip or extra user clicks.

Closing this issue. Please feel free to reopen if you disagree.

**Comment by ivanicin** [comment]
@YuliKl I am only user of this package so I can't fight the philosophical standings of the team management.

However I'll try to tell you why what you have mentioned is completely wrong.

What you have said above is the same like the statement 'it is fine that the user interface is accessible by the mouse, why make it accessible with the keyboard?'.

There is no relation in making the user interface discoverable in one way with user interface being discoverable in another way and looking those things as one problem is a lack of the basic knowledge.

The worst thing is that all users will try to discover the user interface by the tooltips as that is what they have done for decades. No one had any experience in discovering the user interface with the more button. Going straight against the previous user experience is something that prevented UWP from success and if you ask why no one uses UWP then it is because of the things like this.

Good luck!
