### ISSUE TITLE
Proposal: Have PropertyChangedEventArgs carry the new property value

### ISSUE THREAD

**Issue by andreinitescu** [Microsoft/microsoft-ui-xaml#405]
### Summary

Currently PropertyChangedEventArgs only has the property name, not the new value. So all listeners must read the value of the sender on the PropertyChanged event handler. 

## Rationale

Having to read the value on every PropertyChanged event listener can be avoided by simply having the PropertyChangedEventArgs carry the new value beside the property name:

```
public class PropertyChangedEventArgs : EventArgs
{
     public virtual string PropertyName { get; }
     public virtual object PropertyValue { get; }
}
```

## Important Notes

Is there a reason why PropertyChangedEventArgs was designed not to carry the value too? Maybe to make it lightweight in case listeners don't need the actual value, but just to know that property changed? 
But I think these cases are far more less than those where the property value is needed and needs to be read....

**Comment by jevansaks** [comment]
I believe the rationale for leaving this out is a few things:
1) It's costly to make callers put the new value in. 
2) If you include the new value then people are likely going to want the old value too, which is potentially even harder/more costly for implementers to include.
3) In cases where the property is value-typed, then the object-typed property will force boxing of the value which is bad for performance.

There's probably more reasons. @MikeHillberg may remember more.

**Comment by MikeHillberg** [comment]
(Note that the Xaml [PropertyChangedEventArgs](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Data.PropertyChangedEventArgs) is special in C#/VB, as there it projects as the [.Net version](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.propertychangedeventargs?view=netframework-4.7.2).)

In general, we've been getting more consistent about not putting convenience APIs on event args that duplicate the same API on the event sender.  Primary motivations being that duplication creates its own confusion, and to save allocations.

**Comment by andreinitescu** [comment]
Thanks for the feedback. 
So I suppose allocation is more costly even when you have 2 or 3 listeners which read a bindable property which require unboxing

**Comment by MikeHillberg** [comment]
Thanks for the proposal!

The APIs you really need to have on event args are those that are temporal; they're only possible in the context of raising the event.  For example, passing the old value on a property changed event really has to be on the args, because it's not on the sender anymore.  Once you reduce the args to that, a lot of (most?) events don't need args, so the perf savings is that no allocation is necessary.

That's not the case here, though, because we need to have the args to pass the Name.  But adding it to the args would create the inconsistency and duplication.  And as Jevan said there's still perf overhead for value types, which could be avoided with some on-demand logic, but then that's adding complication and code size for something's that frequently not used.
