### ISSUE TITLE
Question: .NET 5, WinUI 3, and WinRT APIs available to Desktop Apps

### ISSUE THREAD

**Issue by sjb-sjb** [microsoft/microsoft-ui-xaml#4065]
I have two related questions.

(1) Around April 2019, Microsoft provided a list of APIs that can be called from packaged Desktop apps. (These are in addition to the API that have the DualApiPartition attribute). Has this changed with the November release, is there a more recent version? Is this list going to expand in the future?

(2) When I build a WinUI 3 + .NET 5 packaged desktop application, the libraries linked in under the predefined project include many Windows APIs that are not in the list. Some of these, such as Windows.ApplicationModel.SuspendingOperation, are clearly UWP API. Others, such as Windows.Graphics.Printing.PrintTaskRequest, seem more general purpose. What is the status of all the API that are available in this project definition, can I call them freely from my packaged WinUI 3 + .NET 5 app? Will these be supported going forward, for example are they going to be supported when WinUI 3 supports UWP (in a year or two)?

**Comment by huoyaoyuan** [comment]
You are getting confused with UWP and WinRT. UWP is an application model, while WinRT is a set and model of API.
A brief table (as my understanding):

| |UWP app|Desktop App, Packaged|Desktop App, non-packaged|
|-|-|-|-|
|WinRT api, UWP Windowing|Yes|No|No|
|WinRT api, package identity required|Yes|Yes|No|
|WinRT api, no identity required|Yes|Yes|Yes|
|Win32 api|Restricted|Yes|Yes|

WinUI desktop app is just a desktop app with package identity. WinUI itselt is WinRT component. Currently it requires package identity, so the app needs to be packed. Those Windows.* API is just callable from any desktop app with access of WinRT. No UWP related.

**Comment by sjb-sjb** [comment]
Thanks @huoyaoyuan for the table. It makes sense. Sorry, when I said “when WinUI 3 supports UWP” what I meant was when .NET 5 is available in UWP, which would also be when the combination WinUI 3 + .NET 5 + UWP works ... it is in the roadmap for WInUI I believe.

My question however remains. Is the list of supported WinRT API that I linked to up-to-date, and will this list likely expand in the future? And, why does the WinUI + .NET5 + Desktop project link to a lot of API that are not documented to work from a packaged desktop app — do any of these API work today and will they be documented to work in the future (e.g. in the WinUI+.NET5+UWP scenario).

**Comment by StephenLPeters** [comment]
@stevenbrix @MikeHillberg or @Austin-Lamb FYI

**Comment by sjb-sjb** [comment]
A related question I have about the APIs available under WinUI 3 + .NET 5 is the closure of the APIs. For example if we look at the [list of API available to a desktop app with package identity](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-supported-api) we see that Windows.Services.Store.StoreContext is available to such an app. That would mean, presumably, that the methods can be called from such an app.

However if we call StoreContext.RequestDownloadAndInstallStorePackageUpdatesAsync then the return type is Windows.Foundation.IAsyncOperationWithProgress<StorePackageUpdateResult,StorePackageUpdateStatus>. Unfortunately, the StorePackageUpdateStatus struct neither has the DualApiPartition attribute, nor is it on the list of types available to such an app. The same goes for the IAsyncOperationWithProgress interface. What are we to make of this? Are all structs and all interfaces available to a desktop app with package identity? Or is this method not actually callable from such an app?

**Comment by sjb-sjb** [comment]
@huoyaoyuan in your response you seem to be dividing all WinRT API into three groups, of which two are callable from a desktop + package app. How do I know which API are in which of these three categories?

**Comment by marb2000** [comment]
**Q: Is the DualApiPartition list of supported WinRT API up-to-date, and will this list likely expand in the future?** 
Yes, it should be up-to-date. All the classes containing these attributes should be listed (I think the list is generated automatically ). Unfortunately, no all the APIs that work in Win32 (additionally to UWP) have this attribute. Actually, this attribute is only informative; the platform does nothing with it. My recommendation:
1. Don't assume that because the API does have the DualApiPartition, it won't work.
2. Try to use the WinRT API in your scenario.
3. If it doesn't work, open a bug in the WinUI (for Microsoft.UI.Xaml things) or Reunion site.

**Q: Why does the WinUI + .NET5 + Desktop project link to a lot of API that are not documented to work from a packaged desktop app — do any of these API work today and will they be documented to work in the future (e.g. in the WinUI+.NET5+UWP scenario).**
Yes, it should be documented eventually. @anawishnoff  is working on it.

I hope this helps.

**Comment by sjb-sjb** [comment]
Hi @marb2000 ... thanks however I didn’t really understand your reply.

- On the first Q you cited, this was not actually my question. I was asking about [the list of API that do NOT have the DuslApiPartition  attribute](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-supported-api) 

- On your answer to the second Q, it sounds like you are saying it is simply a question of time before the API that are linked in by a WinUI3 + NET5 + Desktop project are all documented to work. However, that can’t be true given that some of the API, such as CoreDispatcher, will evidently never work in a desktop app. 

Maybe @anawishnoff  can shed some light on this? 

What I would like most of all would be WinUI + NET 5 + UWP (I.e. sooner rather than later).

**Comment by marb2000** [comment]
Let me be more explicit about the documentation 😉. The WinUI current plan is: 
1.  All the published APIs must be documented in the supported releases. 
2.  For Preview releases, we will try to document those that we believe are close to being done. In Previews, you can find some experimental APIs that are still in development, and there are many chances they change the design, so the investment is not worth it. 

Let me use as an example the one you chose: CoreDisptacher. In Preview 3 and 4 (next Preview), CoreDispatcher returns null in Desktop, and we should document it. In supported releases, like Reunion 0.5, CoreDispatcher will be removed from the WinMD (given there is no support for UWP, and in Desktop is not used), so it won't be documented because it doesn't exist.

About the non-DualApiPartition APIs. My point is that some APIs work in some Desktop scenarios and don't have the attribute. So I recommend you try the API in your scenario. At some point, we should create a doc/table that tells you what APIs you can use or the substitute (if there is one). However, I don't foresee this document be ready for Reunion 0.5, perhaps Reunion 1.0 in Fall.

**Comment by sjb-sjb** [comment]
@marb2000, thanks, it is becoming a bit clearer to me. The API list that I referred to is out of date. The API that are linked in will all be supported ... unless they get deleted. So when we get to the supported releases, whatever is linked in will be documented and supported ongoing. Great !!  

From the point of view of developing on the preview, I can take a guess as to whether a given class will make it into the release. For example the SuspendingOperation class, my guess would be that it continues, although the Suspending event may never occur. What about, say Windows.ApplicationModel.DataTransfer.Clipboard ... I would guess or hope Yes. But Windows.Storage.Picker.FIleOpenPicker I would guess maybe not (?) although I can tell you that it or a replacement would be very handy. Is there anything that would help me make these guesses, at a more detailed level than [the roadmap](https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/roadmap.md)?  

It would be logical then that the documentation will also converge, hopefully. For example, the [.NET 5 documentation for UIElement](https://docs.microsoft.com/en-us/dotnet/api/system.windows.uielement?view=net-5.0) says that it is in System.Windows, but in the WinUI + Desktop + .NET 5  project it is in Microsoft.UI.Xaml instead. Since it is all still preview, presumably you may still move things around from one namespace to another. Is it planned, for example, that the classes in Windows.Foundation would move to Microsoft.Foundation ?  I do find the mixing of Windows.* and Microsoft.* namespaces to be very confusing, not to mention of course things like System.Windows.*. 

Thanks!

**Comment by marb2000** [comment]
I agree the mixing of namespaces is confusing, but I don't believe that all the WinRT APIs will be moved to Microsoft namespace. We are using the Microsoft namespace for those namespaces/classes that are lifted out from OS. There are many APIs that are working as expected (for UWP and Win32) in all the Windows 10 versions and don't require to be part of any Reunion's NuGet.  
For example, Windows.Storage.Picker.FIleOpenPicker 😉. It works in Win32 and UWP, although in Win32 it's required to specify the window that owns the picker. Hence there is no plan to moving to Microsoft namespace so far.

About the roadmap. It's a roadmap for basically WinUI 3 UI (basically the Microsoft.UI.Xaml namespace). I think Project Reunion GitHub should be better place for it. Adding @bitcrazed for awareness.

**Comment by marb2000** [comment]
Closing this issue and I hope we answered your question. If we didn't, feel free to reopening and clarify what we left.

**Comment by sjb-sjb** [comment]
Thanks @marb2000  this was a very helpful discussion.
