### ISSUE TITLE
Question: Fully disabling the Compact mode of NavigationView

### ISSUE THREAD

**Issue by MartinZikmund** [microsoft/microsoft-ui-xaml#4109]
Is it possible to completely disable the NavigationView's Compact display mode? When I set the NavigationView `PaneDisplayMode` to `Left`, tapping the toggle button turns the pane into compact mode, instead of completely collapsing it.

**Comment by chingucoding** [comment]
Have you tried setting `IsPaneToggleButtonVisible` to false? That way, the pane toggle button won't be visible and as such you won't enter compact state anymore. I don't think there is a way to have the pane be in left and collapsed to completely hidden.

**Comment by mdtauk** [comment]
> Have you tried setting `IsPaneToggleButtonVisible` to false? That way, the pane toggle button won't be visible and as such you won't enter compact state anymore. I don't think there is a way to have the pane be in left and collapsed to completely hidden.

Do VisualStyleSetters still have breakpoints as the window resizes, even with the ToggleButton not visible @chingucoding ?

**Comment by MartinZikmund** [comment]
@chingucoding This is possible, but that prevents the user from making the content "full screen" which I would like to support. What I want is similar to `LeftMinimal` but with the difference that in open state the pane would be "inline", not overlay

**Comment by mdtauk** [comment]
> @chingucoding This is possible, but that prevents the user from making the content "full screen" which I would like to support. What I want is similar to `LeftMinimal` but with the difference that in open state the pane would be "inline", not overlay

If you wanted to roll your own navigation, you could use the SplitView which the NavigationView is built on top of.

![image](https://user-images.githubusercontent.com/7389110/107063593-79d92880-67d2-11eb-9805-c8acb74a1c43.png)

**Comment by chingucoding** [comment]
> Do VisualStyleSetters still have breakpoints as the window resizes, even with the ToggleButton not visible @chingucoding ?

If you are using auto, yes NavigationView would still listen to that, the logic ignores whether there is a splitbutton or not from what it looks like. Btw, the "Auto" behavior is actually done in code behind (as we are not listening to window size but rather the NavigationViews size).

> @chingucoding This is possible, but that prevents the user from making the content "full screen" which I would like to support. What I want is similar to LeftMinimal but with the difference that in open state the pane would be "inline", not overlay

I'm afraid there is no such option right now. As @mdtauk suggested, SplitView is a good alternative in that case. Another way would be to retemplate and have the "compact" state collapse completely instead of being a narrow strip.

**Comment by MartinZikmund** [comment]
@mdtauk I would prefer to keep the `NavigationView` as it really has a lot of features out of the box. So far the solution that sounds doable would be to hide the toggle button, add my own above the `NavigationView` and then toggle `IsPaneVisible` instead of `IsPaneOpen`. But it would be nice if the control supported this out of the box somehow. I have a feeling it was possible with the `Windows.UI.Xaml.Controls.NavigationView` although I didn't test it now.

**Comment by YuliKl** [comment]
@MartinZikmund I'm a little confused about the exact behavior you're trying to achieve. In PaneDisplayMode Left, while the hamburger button is visible, the user can open or close the pane. In LeftCompact mode, when the pane is closed it appears the same as in Left mode. When LeftCompact is open, the pane shows up as an overlay on top of the content (instead of pushing the content over for a side-by-side view as in Left mode when open). In short, I think what you're describing here:
> What I want is similar to LeftMinimal but with the difference that in open state the pane would be "inline", not overlay

is Left mode.

If the goal is to switch between Left and LeftMinimal modes, I suggest looking at [CompactModeThresholdWidth](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.navigationview.compactmodethresholdwidth?view=winui-2.5). By setting this to a very larger number like infinity, and keeping the Auto PaneDisplayMode, you should be able to skip right over LeftCompact and have NavigationView change modes between Left and LeftMinimal.

**Comment by MartinZikmund** [comment]
@YuliKl sorry, maybe it wasn't well described, but I have an example of what I want to achieve here: http://gallery.platform.uno/. It is WebAssembly, solution, based on the old NavigationView, but that is a detail. When you make the window narrow, you can see it uses the "minimal" version - hence tapping the hamburger shows the overlay pane. However, when you make the window wide, notice that tapping hamburger menu either completely hides the navigation view (making the content full screen, just like with minimal), and opening it shows the pane inline, so it stays shown while navigating throughout the app. So that is what I meant by "disabling" compact mode in Left mode - essentially I wanted a Inline pane experience where the closed pane is completely hidden.

**Comment by YuliKl** [comment]
Got it, thank you for the more detailed explanation. You would like the Left mode NavigationView to close directly into Minimal mode. No, I don't believe this behavior is possible, at least not in a direct way. This was never supported in the older WUXC version of NavigationView, either. 

@chingucoding made some interesting suggestions for workarounds, but I can't think of a reasonable way to implement the exact scenario you've described, @MartinZikmund :(

**Comment by YuliKl** [comment]
@MartinZikmund I believe your question has been answered so I'm closing the issue. Please feel free to reopen if you disagree.
