### ISSUE TITLE
HyperlinkButton shouldn't have extra padding

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/microsoft-ui-xaml#4145]
In my app, I have kept hyperlink buttons after a text block and with the new styling  there's extra padding which doesn't make the UI consistent

**Comment by mdtauk** [comment]
> In my app, I have kept hyperlink buttons after a text block and with the new styling there's extra padding which doesn't make the UI consistent

The HyperlinkButton is designed to sit alongside other Buttons, and so they have padding to match, and to enable displaying the PointerOver and Pressed states.

You should include a Hyperlink inside a TextBox, so they line up.

**Comment by Jaiganeshkumaran** [comment]
@mdtauk No but this is inside a StackPanel with a list of links

**Comment by mdtauk** [comment]
> @mdtauk No but this is inside a StackPanel with a list of links

You can still use a normal Hyperlink control, and not the HyperlinkButton.

**Comment by StephenLPeters** [comment]
The current hyperlink button padding is by design. If this doesn't work for your app we expose the ButtonPadding resource which you can override https://github.com/microsoft/microsoft-ui-xaml/blob/77bbdcf990ae7bed9de662fe1de9476f23e70eaf/dev/CommonStyles/Button_themeresources.xaml#L131 Or you can restyle or retemplate.
