### ISSUE TITLE
[Preview 4] SetTitleBar does not always work

### ISSUE THREAD

**Issue by vadd98** [microsoft/microsoft-ui-xaml#4184]
**Describe the bug**
I created a custom TitleBar using an UserControl. In the main Window I have a Grid which contains a Frame and the UserControl of the TitleBar. 

The exact order is:
```
    <Grid x:Name="MainWindowGrid" TabIndex="0" IsTabStop="True" IsTapEnabled="True">
        <Frame x:Name="MainWindowFrame"/>
        <userControl:TitleBarControl x:Name="MainTitleBar" VerticalAlignment="Top"/>     
    </Grid>
```

I tried to set the custom TitleBar using SetTitleBar, but nothing changes. When I try to grab and move the Window from the TitleBar UserControl nothing happens.

**Steps to reproduce the bug**

1. Create a Window
2. Insert a Grid
3. Insert a Frame and an UserControl (which will behave as the TitleBar) in the Grid
4. Set the UserControl using SetTitleBar
5. Try to move the Window

**Expected behavior**
Grabbing the TitleBar would allow the user to move around the Window

**Screenshots**

**Version Info**
Win32 WinUI 3 Preview 4

NuGet package version: 
Microsoft.WinUI 3.0.0-preview4.210210.4

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by bkaankose** [comment]
I can't try the code out cuz i'm on mobile right now, but did you tried following:

- Setting Canvas.ZIndex for user control.
- Setting ExtendsToTitleBar property for core window.

Maybe there's an integration issue with combination of those. Worth to check out :)

**Comment by StephenLPeters** [comment]
@pratikone FYI

**Comment by vadd98** [comment]
@bkaankose 
I already tried to replace the main grid with a canvas and then setting the ZIndex of the TitleBar to 1 and the ZIndex of the Frame to 2, but nothing changed. 
I did not try to set ExtendsToTitleBar for CoreWindow because I am on Win32 and not on UWP, so if I do not recall wrongly I do not have a CoreWindow.

**Comment by bkaankose** [comment]
https://docs.microsoft.com/en-us/windows/apps/winui/winui3/

- Custom titlebar capabilities: new Window.ExtendsContentIntoTitleBar and Window.SetTitleBar APIs that allow developers to create custom title bars in Desktop apps.

it's included in Preview 4 for the Window from UWP's CoreWindow for Desktop apps. I assume Windows Shell will not allow you to set your own draggable area inside the content when your content is not extended to title bar.

**Comment by marb2000** [comment]
These new  Window.ExtendsContentIntoTitleBar and Window.SetTitleBar  APIs are only for Desktop. ExtendsContentIntoTitleBar requires SetTitleBar and viceversa.

**Comment by MikeHillberg** [comment]
> I assume Windows Shell will not allow you to set your own draggable area inside the content when your content is not extended to title bar.

The purpose of the SetTitleBar method is to allow you to set your own draggable area.

**Comment by jeff-kissinger** [comment]
This works for me except the buttons are hidden.  As marb2000 pointed out there are 2 steps:
1. In the main windows constructor add

**Comment by bkaankose** [comment]
I don't have much experience on WinUI Desktop side, but in regular UWP world your draggable area should respect the margin values returned by LayoutMetricsChanged event in core title bar. [It's documented here.](https://docs.microsoft.com/en-us/windows/uwp/design/shell/title-bar) I assume we don't have in Desktop world.

I tried your code and it's working for me on WinUI Desktop project. However, they are invisible as stated also in [this issue](https://github.com/microsoft/microsoft-ui-xaml/issues/4209).

Few more notes that might be helpful for you when creating custom draggable area from UWP world:

- Your draggable area must have Background assigned. If you want to achieve transparent, just assign 'Transparent' as value. Otherwise UWP XAML Framework will not route event inputs and eventually it'll became not draggable.
- Regarding maximize, minimize and close system buttons in UWP, no matter what your custom draggable area Canvas.ZIndex has, system will render it's own buttons on top of it.

I just wanted to mention that the issue here is invisible system buttons and the notes above can help WinUI dev team to diagnose potential bugs. There might be places that have been forgotten during the process of unification for both code bases :)

**Comment by billhenn** [comment]
@jeff-kissinger I'm trying the same thing injecting a custom header title bar element and my header element covers the system title bar buttons.  They are still there if I render the header semi-transparently.

If I try to put a margin on my header title bar element to give the system title bar buttons room to render, I found that they seem to "move" to top-right align within my title bar element.  So if your header title bar element has a background, it seems to always block them.  This doesn't feel like it's implemented right yet.

From a consumer point of view, I love the option of extending custom content into the title bar (we did that in UWP too).  But...

- The system title bar buttons should render above my content (UWP did that).
- They should tell me how much space they need (UWP supported that).
- They should allow allow rendering color customization (UWP supported that).
- They should also optionally be able to be completely hidden for a scenario where I want to make and use my own custom title bar buttons in place of the system ones.  That's important too.

**Comment by pratikone** [comment]
@billhenn  SetTitlebar for Desktop WinUI apps have some differences to UWP version because they are implemented differently and thus, had different design limitations. We are discussing internally how to address some of these differences in the future releases. For now you can refer them here : https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.window.settitlebar?view=winui-3.0 . Notice that you will need to set Window.ExtendsContentIntoTitleBar  = true for SetTitlebar api to work for custom titlebar.

there are few i can list : 
1. the element you use as candidate for settitlebar should not have a background property (not even transparent) because min/max/close buttons are below in z-order. You can find an alternative way to fix it in the doc mentioned above. 
2. generally avoid using complex ui elements as candidate for settitlebar as it could create layout problems. since the min/max/close are below in z-index, if your custom titlebar candidate is complex and draws over the area of custom titlebar, it will occlude them.


Lastly, if you have a usercontrol custom titlebar sample project hosted on github (or elsewhere), you can share a link and i can try to find what works and what doesn't work and why.

**Comment by pratikone** [comment]
I checked with a sample user control and it is able to work as a custom titlebar. With the points mentioned above in my last comment, can you also check the layout and width of your custom titlebar control. The draggable region is only over the real width of your custom titlebar. So if you custom titlebar 's located at center of the app with 5 unit of width, that would be the draggable region too.

I am closing this bug for now. If above mentioned techniques don't work or you have any followup questions, feel free to re-open it.
