### ISSUE TITLE
Question: Getting the display information on Win32

### ISSUE THREAD

**Issue by rick-palmsens** [microsoft/microsoft-ui-xaml#4205]
I am trying to convert an existing UWP project to WinUI/Win32.

The project uses `DisplayInformation.GetForCurrentView()` in one of the of the controls to get DPI information, which then results in the following error:
> Windows.Graphics.Display: GetForCurrentView must be called on a thread that is associated with a CoreWindow.

`CoreWindow` is a UWP thing, so I'm assuming this function is not supported on Win32. What would be the correct way to get the current DPI (and detect changes to the DPI) from a WinUI/Win32 app?

**Comment by thomasclaudiushuber** [comment]
Hi @rick-palmsens ,

there is currently no API exposed to get DPI information. But you can go via Win32 PInvoke right now.

Steps to try it:
1. Create a new WinUI in Desktop project
2. Add a reference to the NuGet package PInvoke.Win32 to your WinUI desktop project.
3. Implement the MainWindow.xaml.cs file like this:

```
public sealed partial class MainWindow : Window
{
  public MainWindow()
  {
    this.InitializeComponent();
  }

  private void myButton_Click(object sender, RoutedEventArgs e)
  {
    var dpiScalingFactor = GetDpiScalingFactor();
    var dpiPercent = $"{dpiScalingFactor * 100}%";
    myButton.Content = $"DPI Setting: {dpiPercent}";
  }

  private double GetDpiScalingFactor()
  {
    var windowNative = this.As<IWindowNative>();
    var hwnd = windowNative.WindowHandle;

    var dpi = PInvoke.User32.GetDpiForWindow(hwnd);
    return (float)dpi / 96;
  }
}

[ComImport]
[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
[Guid("EECDBF0E-BAE9-4CB6-A68E-9598E1CB57BB")]
internal interface IWindowNative
{
  IntPtr WindowHandle { get; }
}
```

4. The generic As<T> method that I call on the Window instance is an extension method. You need to add the following using directly to get it:

```
using WinRT;
```

That's it.

Take also a look at the [WinUI 3 Demos](https://github.com/microsoft/WinUI-3-Demos) repository from @marb2000 that contains more Window interop scenario. Here is also a center window branch that shows you how to center a WinUI desktop window: https://github.com/microsoft/WinUI-3-Demos/tree/CenterWindow/src/Build2020Demo

**Comment by StephenLPeters** [comment]
@marb2000 FYI

**Comment by marb2000** [comment]
For DPI changes, I do recommend to listen for changes on the **XamlRoot's Changed event.** The XamlRoot is the root of the visual tree and you can get it from any UI Element on your UI.  For example, mybutton.XamlRoot. Then you can use **XamlRoot.RasterizationScale** to get the number of raw physical pixels for each view pixel.

Does this help? If so, can you close the issue, please?
Thanks!

**Comment by jschwizer99** [comment]
@marb2000 

I used DisplayInformation.GetForCurrentView() for a bunch of events related to the display. We then would need workarounds not only for the dpi scaling but also screen rotation:
`
// GetForCurrentView() triggers a crash for WinUI preview4.
// See also https://github.com/microsoft/microsoft-ui-xaml/issues/4174
//const auto currentDisplayInformation{ winrt::Windows::Graphics::Display::DisplayInformation::GetForCurrentView() };

//currentDisplayInformation.DpiChanged([&](
//	winrt::Windows::Graphics::Display::DisplayInformation const& /*sender*/,
//	winrt::Windows::Foundation::IInspectable const&)
//	{
//		OutputDebugStringW(L"Dpi Changed.\n");
//	});

//currentDisplayInformation.OrientationChanged([&](
//	winrt::Windows::Graphics::Display::DisplayInformation const& sender,
//	winrt::Windows::Foundation::IInspectable const&)
//	{
//		OutputDebugStringW(fmt::format(L"OrientationChanged to {}.\n", sender.CurrentOrientation()).c_str());
//	});

//currentDisplayInformation.DisplayContentsInvalidated([&](
//	winrt::Windows::Graphics::Display::DisplayInformation const&,
//	winrt::Windows::Foundation::IInspectable const&)
//	{
//		OutputDebugStringW(L"DisplayContentsInvalidated.\n");
//	});
`
It would be nice to get this information for each window of the application so that the content can be updated. Can you give advice on how to achieve this functionality with the WinUI preview4?

Side note: For the swap chain I use the following functionality to get the raw to view pixel scaling which gives me a nice event.
`
swapChainPanel().CompositionScaleChanged([&](
	winrt::Microsoft::UI::Xaml::Controls::SwapChainPanel const& sender,
	winrt::Windows::Foundation::IInspectable  const&)
	{
		OutputDebugStringW(fmt::format(L"Composition Scale Changed: {}, {}.\n", sender.CompositionScaleX(), sender.CompositionScaleY()).c_str());
	});
`

Many thanks. Juerg.

**Comment by marb2000** [comment]
Um, For orientation changed, I think the workaround is to call Win32's EnumDisplaySettingsEx, that gives you a struct with the dmDisplayOrientation field which values can be DMORIENT_PORTRAIT (1) or DMORIENT_LANDSCAPE (2).  But I didn't have time to try it yet. But  I agree, it will be nice if the Window has a method that tells you the orientation of the display that hosts it.

**Comment by rick-palmsens** [comment]
@marb2000 XamlRoot looks promising, but it is not available from the constructor of a control (probably because it isn't attached yet). Is there a way for me to detect when the XamlRoot is set?

**Comment by marb2000** [comment]
Did you try the Loaded event? @JesseCol can you advice here?

**Comment by mattleibow** [comment]
I am also using this to return the physical screen resolution and all that. I used to use DI on UWP, and when moving to desktop, it would be nice to be able to get a list of screens and then be able to properly manage my app accordingly.

**Comment by rick-palmsens** [comment]
@marb2000 Sorry for the late response, but using the Loaded/Unloaded events is indeed a good way ensure the control is attached to a XamlRoot.

**Comment by bpulliam** [comment]
Closing old questions.

**Comment by FoggyFinder** [comment]
> var windowNative = this.As<IWindowNative>();

this is not supported if run with aot enabled, alternative:

```cs
var hwnd = WinRT.Interop.WindowNative.GetWindowHandle(window);
```

**Comment by castorix** [comment]
> on my system it returns `1.0` while correct value is `1.25` and **XamlRoot's Changed event.** isn't fired when I change system's scale

Like for DPI APIs, you must use a Manifest with _dpiAware_

**Comment by FoggyFinder** [comment]
> 
> Like for DPI APIs, you must use a Manifest with _dpiAware_

I thought default setting is enough ?

```xml
  <application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2</dpiAwareness>
    </windowsSettings>
  </application>
```

**Comment by castorix** [comment]
> I thought default setting is enough ?

On my OS (Windows 10 22H2), if I comment the line with _dpiAware_ (above _dpiAwareness_), it does not work either (I tested by switching 100%/125%)

` <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true/PM</dpiAware>`

**Comment by FoggyFinder** [comment]
made no difference, `RasterizationScale` still is always 1.

Not sure why it doesn't work without dpiAware for you:

https://github.com/microsoft/WindowsAppSDK/pull/1748
