### ISSUE TITLE
Investigate why Compact.xaml doesn't work in MergedDictionary in Application.Resources

### ISSUE THREAD

**Issue by licanhua** [Microsoft/microsoft-ui-xaml#430]
**Describe the bug**
Because XamlControlsResource is already a dictionary, and we need make it to MergedDictionary if we want to add Compact.xaml too. But actually it doesn't work and need to investigate why

![image](https://user-images.githubusercontent.com/6290692/54381946-327ca880-464c-11e9-81f6-73bc5ba7e10b.png)

**Comment by jevansaks** [comment]
@licanhua We should split this issue out since the linked PR won't fix this problem. Maybe use #98 in your PR instead?

**Comment by licanhua** [comment]
We won't fix this bug. Instead we workaround the problem by API

**Comment by DierkDroth** [comment]
> We won't fix this bug. Instead we workaround the problem by API

OK, so how would I merge Compact.xaml and XamlControlsResources at the App level?

**Comment by licanhua** [comment]
@kaiguo Do you have update on this? I remember you were investigate the 'compact' kind of workaround

**Comment by kaiguo** [comment]
> @kaiguo Kai Guo FTE Do you have update on this? 

I think it's a limitation of how our resource lookup works, I still don't have a good way to fix this. See Alan's reply earlier,

The parser *does not* have lookahead capability. 
Implication: forward-references to static/theme resources are forbidden. 
Corollary: a reference to a static/theme resource will completely ignore an override that you specify later in the file.
 
The parser does not assign objects to a property until the element end tag is encountered. 
Implication: `<ResourceDictionary Source="Dictionary2.xaml"></ResourceDictionary>` has no idea that it is inside Application.Resources.MergedDictionaries until after `</ResourceDictionary>` is encountered, which is after Dictionary2.xaml has been run through the parser. 
Implication: the ResourceDictionary defined by Dictionary2.xaml *has no logical parent* at the time of parse because it can't be assigned to the (eventual parent) MergedDictionaries collection until after it has finished initializing, i.e. the parser has finished loading Dictionary2.xaml
Corollary: the other dictionaries specified in Application.Resources.MergedDictionaries are invisible to Dictionary2.xaml
Implication: from the perspective of the framework, Application.Resources *does not exist* while App.xaml is being loaded because you can't assign a value to a variable before that value has finished initializing
Corollary: the resource resolution walk for a static/theme resource reference inside Dictionary2.xaml will only encounter resources that were defined earlier in Dictionary2.xaml or in the platform generic.xaml
 
The code equivalent of assigning your App.xaml to Application.Resources would be something like this:
```C#
Application.Resources = null;
var appXaml = new ResourceDictionary();
var dictionary1 = new ResourceDictionary();
dictionary1.Source = new Uri("Dictionary1.xaml"); // loads the specified markup via black box
appXaml.MergedDictionaries.Add(dictionary1);
 
var dictionary2 = new ResourceDictionary();
dictionary2.Source = new Uri("Dictionary2.xaml"); // loads the specified markup via black box
appXaml.MergedDictionaries.Add(dictionary2);
 
var dictionary3 = new ResourceDictionary();
dictionary3.Source = new Uri("Dictionary3.xaml"); // loads the specified markup via black box
appXaml.MergedDictionaries.Add(dictionary3);
 
Application.Resources = appXaml;
```

It should be clear from the above why what you're trying to do doesn't work; while Dictionary2.xaml is being loaded, Application.Resources is still null dictionary3 doesn't even exist yet, and dictionary2 does not have a parent because it has yet to be added to the appXaml.MergedDictionaries collection. As a result, static/theme resource references inside Dictionary2.xaml literally have no access to any resources defined in Dictionary1.xaml or Dictionary3.xaml.

**Comment by DierkDroth** [comment]
Thanks for your explanation.

However, I don't why understand why XamlControlResourecs is the **only** resource dictionary which my team can't merge in our projects. Frankly, this doesn't make any sense to me. I would kindly ask to seriously consider removing that limitation.

**Comment by StephenLPeters** [comment]
I don't expect that there is something unique about these resouce dictionaries. Are you sure that if you  reproduced the described behavior in two other dictionaries this would not be an issue there? I suspect this just happens to be the only overrides being constructed from markup directly inside of a merged dictionary.  That being said, the experience does seem broken.

**Comment by DierkDroth** [comment]
>> That being said, the experience does seem broken.

Thanks for confirming. 

My team did more research. Basically the problem is that resources defined in XamlControlResources can't be overwritten if both - XamlControlResources and the 'overwrite' - are defined in App.xaml.

However, the same works no problem if both - XamlControlResources and the 'overwrite' -  are defined at the FramewokElement level.

This seems to be inconsistent and likely should be addressed.
