### ISSUE TITLE
Question: Is it possible to use newer WebView2 (pre)releases with UWP WinUI3 (C#)? 

### ISSUE THREAD

**Issue by emimvi** [microsoft/microsoft-ui-xaml#4378]
For WPF i can just download the WebView2 nuget package and get going with the newest prerelease version. However as i understand it, in WinUI3 the WebView2 control is bundled into the package?

Does this mean that the WinUI3 WebView2 version will generally be a bit behind WPF/WinForms, or is there anything i can do myself (possibly locally) to get a newer version? I tried looking for the source to the control that wraps CoreWebViewer2, but without luck, so i'm guessing it's not available?

**Comment by sigmarsson** [comment]
#4306

**Comment by codendone** [comment]
You are correct that the WebView2 element is part of the overall WinUI3 package, and the WebView2 element uses the CoreWebView2 Runtime. The source for the WinUI WebView2 element will eventually be open source with the rest of WinUI3, but we don't have a specific timeline for that, yet.

If your question is about a desire to test with a Beta, Dev, or Canary channel of the WebView2 Runtime, so that you can test against those more recent versions of the Runtime, you should be able to do that by setting the [releaseChannelPreference regkey](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-webview-policies.md#releasechannelpreference) to have the control attempt to load Canary or Dev or Beta before choosing the WebView2 Runtime. Setting this regkey is for testing purposes only.

**Comment by emimvi** [comment]
@codendone Thanks for the information!

To be more specific: I'm interested in the DefaultBackgroundColor api to make the window transparent, which recently got stabilized in Webview2 [version 1.0.774.44](https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes#1077444).
Will Reunion 0.5 include this updated functionality? And if not, do you know when?

**Comment by codendone** [comment]
DefaultBackgroundColor is not exposed in the upcoming Reunion 0.5 release. But even if it were exposed transparency is not currently possible in WinUI3 and we don't have any timeline for if/when transparency will be supported. We'd like to support transparency, but transparency is not possible with the current rendering integration of WebView2 into WinUI3. Significant design and implementation work will be required in multiple components to support transparency, and that is currently unlikely to happen in 2021.

**Comment by emimvi** [comment]
Alright, thank you for the insights!
