### ISSUE TITLE
Proposal: change the "contrast" icon from MDL2 icons to distinguish it from "brightness"

### ISSUE THREAD

**Issue by WolfIcefang** [microsoft/microsoft-ui-xaml#4422]
# Proposal: change the "contrast" icon from MDL2 icons to distinguish it from "brightness"

## Summary

The icon for contrast looks too much like the icon for brightness. When used side by side in a control panel, they are nearly indistinguishable.
![image](https://user-images.githubusercontent.com/38160450/110062011-22c16780-7d2e-11eb-900e-d0b455124268.png)

## Rationale

* The icon for Contrast should be updated because it is too similar to the brightness icon.
* The icon for Contrast can be updated because it is very rarely used. People probably aren't going to properly identify the current icon if it is shown without context.

## Scope

If accepted, the contrast icon MUST be changed.
If accepted, the brightness icon WON'T be changed.
 
## Important Notes

Note: this issue was inspired by the https://github.com/xanderfrangos/twinkle-tray/issues/123#issuecomment-780932532 issue in Twinkle Tray. I am not personally working on Twinkle Tray. 

## Open Questions

I do not have any specific ideas for what an improved Contrast icon could look like; any suggestions would be appreciated.

**Comment by StephenLPeters** [comment]
I think that the MDL2 icon that you are referring to when you say Contrast is this:

![image](https://user-images.githubusercontent.com/7758786/110188223-e47c8480-7dcf-11eb-93e7-29a0c4c03e06.png)

Which is similar but I think that it makes sense that an icon name light and an icon named brightness would be similar.  It is unfortunate if these icons are being using on the same page to deliniate different values though. 

https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font#about-segoe-mdl2-assets

**Comment by StephenLPeters** [comment]
@MarissaMatt FYI

**Comment by xanderfrangos** [comment]
Developer from the referenced issue here. I guess I'll toss my two cents in.

I selected the "Light" MDL2 icon since it was clearly inspired by "contrast" icons:

![contrast-icon-google](https://user-images.githubusercontent.com/33106561/110424570-ffb9ef00-8070-11eb-96ff-928c5eef76c4.jpg)

Even the Photos app seems to think it's contrast related:

![contrast-photos](https://user-images.githubusercontent.com/33106561/110424905-840c7200-8071-11eb-8076-c5fe95ee6fe1.jpg)

Currently, the icon isn't ideal. The circle is too small and the split in the center isn't filled in enough. However, the new version from the Insider build 21327 is better (the new icons are great FYI 😀). Here's the same app using the new icons:

![twinkle-tray-fluent-icons](https://user-images.githubusercontent.com/33106561/110425200-f67d5200-8071-11eb-84be-b7f9c7383bbc.jpg)

I think it would be great for there to be an additional "contrast" icon without light rays. It would fit a wider variety of situations (ex. photo editing, display's physical contrast, and contrast for accessibility) over the existing/new "Light" icon.
