### ISSUE TITLE
Proposal: SplitButton, Disable/Enable only Button portion.

### ISSUE THREAD

**Issue by avknaidu** [Microsoft/microsoft-ui-xaml#443]
# Proposal: SplitButton, Disable/Enable only Button portion.

## Summary

It would be a good feature to disable only the button portion of the Splitbutton but still give an option to keep flyout enabled.

## Rationale

See Example below.

## Functional Requirements

A New Property called `IsButtonPartEnabled` that will enable/disable the button but will keep the flyout part always enabled.

## Important Notes

An example how i use SplitButton in my app is for posting comments. Comments require a minimum 15 characters in length. But SplitButton Flyout has saved comments. So if disable split button completely, users cannot reach saved comments. SplitButton and its flyout should be semi independant.

![sc](https://user-images.githubusercontent.com/6171200/54501975-5989f180-494e-11e9-86b5-352217b8aed8.gif)

**Comment by jevansaks** [comment]
This isn't what we intended SplitButton to be used for. It sounds like you want suggestions, so have you considered [AutoSuggestBox ](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.autosuggestbox) or ComboBox with [IsEditable ](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.combobox.iseditable)= true?

**Comment by avknaidu** [comment]
Hello @jevansaks, Thanks for your quick response. 

I am not looking for a list control with suggestions here. If you look at the GIF above, you can see the flyout has a separate purpose ( in this case loading or saving comments typed into the textbox ) and split button is used to add the comment itself which does not get enabled until certain length of text is typed in. But need users to still open the flyout, load comments from saved list.

Let me know if this is possible with SplitButton. If not, feel free to close the proposal. MUXC provided me with excellent new/old controls to backport my existing projects. I can understand if this is not feasible,

**Comment by YuliKl** [comment]
@avknaidu - You have three distinct commands that you want to offer to your app users: add, save, load. I believe you're trying to make the statement that Add will be used most frequently, which is why you've placed Save and Load into a flyout not always visible on screen. However, SplitButton doesn't convey the right relationship between the commands you're offering. The best usage of SplitButton I've seen has been to offer related commands like 'Save' and 'Save as ...' - these are variants on the same action where one is expected to be used more frequently. In your scenario, I would actually split out the three commands into three unique buttons (looks like you have the screen space for it) and consider using size and/or color to help draw users' attention to Add.
