### ISSUE TITLE
Text input controls inconsistencies

### ISSUE THREAD

**Issue by ghost** [microsoft/microsoft-ui-xaml#4444]
* Inner buttons have different sizes:
![menu](https://user-images.githubusercontent.com/78622729/110326720-b55d5180-8021-11eb-897a-6f6a0459f7a1.png)

* AutoSuggestBox 
  - x button is blurry with >100% scaling
  - doesn't support custom Padding

* ComboBox IsEditable="True"
  - doesn't have 1px bottom border to indicate it's editable
  - on hover it changes height by 1px with >100% scaling, shifting the entire layout
  - the other controls have a text cursor on hover
  - custom Padding doesn't affect focus state
  - CornerRadius doesn't affect the inner button like it does for the other controls

* NumberBox has a different design from the other input controls. Instead of having inner buttons, they are placed next to the TextBox.
This design causes issues like #3987 and makes it harder to support custom properties #4289.
I think it would be better to make it consistent with the other text input controls:
![numberbox](https://user-images.githubusercontent.com/78622729/110326569-7e873b80-8021-11eb-8d86-0292e07b796c.png)

**Comment by StephenLPeters** [comment]
Thanks! When these control's visual updater are complete we'll report back :)

**Comment by gabrielconl** [comment]
I looked into solving some disparities between the text controls, and I've found that they're often doing the same thing again for each control.
One example is with buttons - they're supposed to look pretty much the same, except for the icons, but there is a style for each of them, such as DeleteButtonStyle and QueryButtonStyle.

Wouldn't it be more useful to have a single style for all of those buttons?
Since the old styles aren't actually exposed, I think they could actually be removed entirely.

There could also be exposed styles for toggle buttons (PasswordBox) and repeat buttons (NumberBox).
ComboBox could use the normal buton style, but currently the button functionality is hardcoded.
