### ISSUE TITLE
Switch NavigationView and switch back will trigger Unloaded event twice

### ISSUE THREAD

**Issue by zhuxb711** [microsoft/microsoft-ui-xaml#4512]
**Describe the bug**
Example project: 
[TestApp.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6136424/TestApp.zip)

**Steps to reproduce the bug**

1. Switch to another NaviagationViewItem
2. Switch back to first NaviagationViewItem
3. You will find that Unloaded event trigger twice

**Expected behavior**
One loaded event and one unloaded event. Should not trigger twice

**Version Info**

NuGet package version: [Microsoft.UI.Xaml 2.5.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
@zhuxb711 I would expect each time you perform a navigation a loaded and an unloaded event will occur.  Since you've done two navigations I'd expect two unloaded events. Keep in mind that there is a known "issue" where loaded and unloaded events can occur out of order due to one of the events being asynchronous.

**Comment by zhuxb711** [comment]
@StephenLPeters  I think you misunderstood what I mean.
Suppose there are two NavigationItem: Item1 and Item2.

1. If I switch from Item1 to Item2, Unloaded raised in Item1 and Loaded raised in Item2. That's correct.
2. If I switch from Item2 to Item1 again. Loaded raised in Item1, Unloaded raised in both Item1 and Item2. That's incorrect.

**Comment by StephenLPeters** [comment]
@zhuxb711 are you sure that Unloaded is raised for item1 in step 1?  its possible that the unloaded event wont get fired until after you load item1 again, because Unloaded is (annoyingly) an asynchronous event. If step 1 did not include an unloaded event for item 1 then step 2 is possible.  However it should never be the case that Loaded - Unloaded = 0 but the content is in the visual tree.

**Comment by zhuxb711** [comment]
![GIF 3-19-2021 3-00-47 PM](https://user-images.githubusercontent.com/42038175/111743045-0c85e080-88c4-11eb-99ff-37f65937e071.gif)

@StephenLPeters Yes Unloaded event was triggered 3 times in total.

**Comment by StephenLPeters** [comment]
Can you check the original source of the Unloaded event? unloaded is a routed event, so its possible your handler is seeing an unhandled unloaded event of a child element.  This property https://docs.microsoft.com/en-us/dotnet/api/system.windows.routedeventargs.originalsource?view=net-5.0 tells you which item is actually being unloaded.

**Comment by zhuxb711** [comment]
OriginalSource is null in these Unloaded event @StephenLPeters

**Comment by StephenLPeters** [comment]
Okay, yeah seems like we should take a look.  How is this behavior effecting your app? Priority wise I'm not sure when we will be able to get to it.
