### ISSUE TITLE
TextBlock.SelectionFlyout doesn't work

### ISSUE THREAD

**Issue by xiedongweo** [Microsoft/microsoft-ui-xaml#452]
**Describe the bug**
I’m trying to use the [TextBlock.SelectionFlyout](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.textblock.selectionflyout#Windows_UI_Xaml_Controls_TextBlock_SelectionFlyout) property, but the flyout doesn’t show when text is selected. 

**Steps to reproduce the bug**

```xaml
        <TextBlock x:Name="textb" VerticalAlignment="Center" IsTextSelectionEnabled="True" Text="The flyout that is shown when text is selected, or null if no flyout is shown. The default is an instance of TextCommandBarFlyout.">
            <TextBlock.SelectionFlyout>
                <Flyout>
                    <TextBlock Text="{Binding ElementName=textb,Path=SelectedText}" Foreground="YellowGreen" FontSize="50"></TextBlock>
                </Flyout>
            </TextBlock.SelectionFlyout>
        </TextBlock>
```

1. Select the text on the TextBlock
2. The flyout should open, but now it deosn't work.

**Expected behavior**
The flyout should open.

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)                   |    |
| October 2018 Update (17763)   | Yes   |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by jevansaks** [comment]
@xiedongweo can you clarify the input action? Selecting text with *touch* will display the flyout but with keyboard and mouse the flyout will only appear on right-click. We can clarify that in the API documentation if it's missing.

**Comment by xiedongweo** [comment]
@jevansaks  I select the text with mouse, but even if I right-click, it open the default contect menu `Copy/Selecte All`, not the flyout that I set in `TextBlock.SelectionFlyout`.

**Comment by YuliKl** [comment]
@xiedongweo - unfortunately the behavior you're seeing is by design. The SelectionFlyout property's name is somewhat misleading because of the behavior @jevansaks described. Xaml text controls use this property internally to achieve a very specific experience of showing the standard CommandBarFlyout context menu in its closed state when text inside a RichEditBox is selected with any input device, or when text inside TextBlock or TextBox is selected using touch or pen. Unfortunately we haven't done a great job of documenting the nuances of this behavior. 

We don't have a great answer for your scenario of showing a custom flyout on selection with mouse. You can try using the `SelectionChanged` event, but that code isn't nearly as elegant as assigning the flyout to SelectionFlyout would have been.

**Comment by xiedongweo** [comment]
@YuliKl  So, the [TextBlock.SelectionFlyout](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.textblock.selectionflyout#Windows_UI_Xaml_Controls_TextBlock_SelectionFlyout) document needs to be updated. We need to explain the use of this property. Otherwise, other developers will misunderstand it.

**Comment by YuliKl** [comment]
We've updated the documentation.
