### ISSUE TITLE
Shape filling with wrapped image

### ISSUE THREAD

**Issue by devlers** [microsoft/microsoft-ui-xaml#4527]
Hi,

Is there possibility to fill shape with wrapped (not stretched) image? I mean small image would be multiplied and filled whole shape. Is there plans to add this functionality or suggestion what would best approach to achieve this?

Thanks,
Saulius

**Comment by StephenLPeters** [comment]
@marlenecota I think I remember you doing this for ReactNative.  Do you know how to do it in xaml?

**Comment by StephenLPeters** [comment]
@codendone FYI

**Comment by marlenecota** [comment]
In react-native-windows it was done using [XamlCompositionBrushBase](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.xamlcompositionbrushbase?view=winrt-19041) and Win2d's [BorderEffect ](https://github.com/microsoft/microsoft-ui-xaml/issues/4527)(setting both ExtendX and ExtendY to [Wrap](https://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_CanvasEdgeBehavior.htm)).

Here's react-native-windows code: 
https://github.com/microsoft/react-native-windows/tree/master/vnext/Microsoft.ReactNative/Views/Image

ReactImageBrush is the XamlCompositionBrush and we used a header only implementation of the Border effect because we didn't to bring in all of Win2D.
