### ISSUE TITLE
👩‍💻☎ March WinUI Community Call, Part 2 - March 23, 2021 (Make-up stream)

### ISSUE THREAD

**Issue by anawishnoff** [microsoft/microsoft-ui-xaml#4582]
## The March Community Call(s) have now ended - a recording is available on YouTube here: https://www.youtube.com/watch?v=At9QjATI1eA&t=12s

This week's (3/17) March WinUI Community Call was cut short due to technical/streaming issues. We'll be making up the second half of this call on Tuesday, March 23 at 9AM PT (16:00 UTC). We've compiled all of the questions asked during the 3/17 call, but feel free to use this issue to add more questions. 

# Details 
Date: Tuesday March 23, 2021
Time: 16:00 UTC (9:00 Pacific)

As this will only cover half of a call's worth of content, the call will be ending around 9:35 AM.

Anyone and everyone is welcome - no pre-registration is required.
This will be an informal interactive live stream directly with members of our engineering team.

# Format
The community call is a call among the WinUI team that is live-streamed onto YouTube. We present on new updates, share information, welcome guests, and answer your questions. In this call, we'll be welcoming Uno Platform and doing Q&A.

### **Agenda**
- Ecosystem Spotlight: Bringing your WinUI apps cross-platform with Uno Platform 
- Q&A with the team and spotlight guests - we'll have the same guests as the original 3/17 call, so feel free to direct your questions at any of them.
  - **Questions and topic requests can be pre-submitted by commenting them on this GitHub issue**
  - **Questions can be asked live in the YouTube livestream's comment section**

### **Q&A Code of Conduct**
- To help ensure Q&A remains beneficial for the majority of the call's developer audience, please consider whether your question could be framed so that it might be more broadly relevant to our larger developer audience by ensuring it is reasonably concise, broadly beneficial, well-suited for the fast-paced live Q&A format, or able to spark open ended discussion.  
- Please understand some questions are not well-suited for the fast-paced live Q&A format and should be filed as standalone [Discussion](https://github.com/microsoft/microsoft-ui-xaml/issues/new?assignees=&labels=discussion&template=discussion.md&title=Discussion%3A+%5Byour+discussion+title%5D) or [Question](https://github.com/microsoft/microsoft-ui-xaml/issues/new?assignees=&labels=question&template=question.md&title=Question%3A+%5Byour+question+here%5D) issues where they can be most appropriately handled. Excluding presentation topic requests, this generally includes requests for dedicated follow-ups or technically complex questions that require investigative time or expertise not included in this month's guest list.

**Comment by ChristophePichaud** [comment]
My SQLI friend Clement Sannier FW me this email thread and I am happy for this call. Have a question:
Where does the border appears between Reunion and WinUI github project.
I can't choose: Should I contribute to WinUI XAML or Reunion for C/C++ Windows Contribution Stuff.
For me, for the moment, I am registered to Windows Terminal and it's Just Hyway to Hell to survive in even a little issue (mine is Save Txt Console History). I used to do modifications in cmd.exe and now I should enhance a Call control with Xaml plumbing mixed with WIL and Modern C++ stuff mixed Inner Windows New Way (Modern Windows) to develop Windows OS components.
Let me express my feeling as a 25 years C/C++ Windows Veteran Internal Windows Guy:
(Please don't send tomatoes)
My little Windows XamlUi features WinTerminal makes me sick, feel completely lost, not ISO C++ comfortable and It sends us (Windows cop Developers) to 20 years ago where MS was developping SDK, Libs and Technologies then Products, but this time (since 2017 and Win10 era) it depends on Windows 10 versions or Win10 sdk or VC++ versions supporting last C++17/20 features of C++ language. I volontary put "all in the box" to you to understand it's becoming a little complicated to make Modern Windows Programming.
Ok on the theories, it's all about WibRT

**Comment by Marv51** [comment]
Could somebody speak about the state of WebView2 and what the plans are with that? I have found it to be very difficult to work with and the deployment story seems to not great right now?

**Comment by shaheedmalik** [comment]
What's the WinUI 3 plan creating & maintaining UX consistency between different apps and do these plans factor in touch & Windows 10's Tablet Mode?

**Comment by mrlacey** [comment]
Q: As WinUI3 includes bugs for functionality that works correctly in UWP, does this mean that you started again from scratch when writing code for WinUI3 or did you start by copying/referencing the existing UWP code?  - Please can you talk about the process and what was done to avoid issues where WinUI3 doesn't do things or handle edge cases that work in UWP.

**Comment by huoyaoyuan** [comment]
You look to hurry for RTM.
We can see big works in every previews, but there are also critical issues caused by fundamental change every time. Back to the time of initial release of .NET Core, they've been open sourced for months before RTM.

**Comment by Noemata** [comment]
Can we please have an honest conversation about performance both in terms of UI rendering speed and memory utilization.

Here's a head to head comparison:  https://github.com/Noemata/XamlBenchmark

WinUI is at least 3 times slower than WPF/UWP.  WinUI uses almost 10 times more memory than UWP and 7 times more than WPF.  WinUI is also leaking memory in a big way.

Why has UWP fallen behind WPF in performance (how is that even possible)?

**Comment by mrlacey** [comment]
@anawishnoff  Thank you for having the live captioning for this call. Very helpful and much appreciated. 😄

**Comment by anawishnoff** [comment]
@mrlacey So glad it was helpful - auto-generated is not the best, but I think it's our best option for now :)
