### ISSUE TITLE
Question: WPF ... or?

### ISSUE THREAD

**Issue by wstaelens** [microsoft/microsoft-ui-xaml#4650]
I'm reading about Project Reunion which includes WinUI 3.

We are starting development of a new application which consists of a web version and a desktop version.
For the web version we are using blazor as a natural choise.
For desktop we are going to the WPF.

How is WinUI 3 being positioned?

Is this a future replacement for WPF ?

As now we have winforms, wpf, xamarin.forms (= now called MAUI ?), uwp, ... and WinUI ?

very confusing and we don't want to waste 1 or 2 years of development because we choose a UI technology that microsoft will stop supporting in future.

Is WPF still the right choise? Will WinUI replace WPF? ...?

**Comment by asklar** [comment]
If you are looking to have a mobile/web app and a desktop version, you might want to look at React Native and [React Native for Windows](https://microsoft.github.io/react-native-windows/)

**Comment by omikhailov** [comment]
Well, I'm not affilated with MS, so this is just opinion:
- WinForms is a legacy technology for writing small ad-hoc applications. Code of large WinForms applications tend to quickly become a dump.
- WPF is a framework for building applications for Windows Vista, 7, 8 / 8.1 and 10. Windows has always been famous for excellent backward compatibility and WPF will stay alive for long time, but your application will look outdated unless you will make special efforts. WPF will not evolve anymore and it will be hard to migrate to new frameworks in the future, but it is still a good option for conservative developers.
- UWP is a platform for Windows 10 apps. If you don't have to support legacy OS, just Windows 10, you can make UWP app with WinUI 2 and it will have latest Fluent design and performance of native C++ code even if you are writing it in C#. However, it has limitations: too few controls are available out of the box and you have to work with WinRT APIs having paranoid security and battery-saving restrictions. They will stop supporting WinUI 2 at some point and you will have to migrate to WinUI 3 to have access to latest design updates.
- WinUI 3 allows you build Fluent Windows 10 apps too, but in addition, you have an option to use legacy Win32 APIs. This looks like kind of WPF with UI from UWP. TBH, I have no idea who may need it except Microsoft itself. Seems like they are building a framework for system utilities, file explorer and preinstalled Windows apps. There will be also some UWP option to migrate from WinUI 2. If you will start with pure WPF, you will have to rewrite UI layer to migrate to WinUI.
- Xamarin / MAUI is a tool for cross-platform development. It is extremely limited and painful in use because it has to respect limitations of all platforms. Consider it when you need iOS and Android versions of your app. Consider and reject, because native iOS and native Android developers would build much better app in shorter time than you would spend with Xamarin :-)
- React Native is a cross platform framework for thoose who works with web technologies only. It would be easy to start with it, but once you will face any issues, there will be nobody to help you. It could be good option for simple small cross-platform apps, though.

So, it all depends on your requirements, but for now there are two main choises for native applications: either WPF or UWP with WinUI 2.

**Comment by wstaelens** [comment]
ok, this confirms it that we are still going strong with .net 5 WPF app. Thanks 💪

Really want to see Microsoft putting some extra effort on WPF updates/improvements.

**Comment by robloo** [comment]
@wstaelens WinUI 3 is basically the next iteration of UWP. Both have a lot of differences with WPF and if you are curious what that means from a technical perspective I would encourage you to browse through this document: https://github.com/robloo/PublicDocs/blob/master/UWPvsWPF.md

I would highly recommend staying with WPF if you have no technical reason to move to WinUI 3 (and don't need cross-platform apps). Staying with WPF will also allow you to use .NET 5 and the latest versions of C# right away (which isn't possible with UWP/WinUI 3 right now). WinUI 3 is going to have missing features and a lot of bugs for over a year. In a few years it might be more clear to begin a migration from WPF -> WinUI 3. If you keep the technical differences in mind (from the above document) any future migration should be straighforward.

Going along with @omikhailov, here is the progression of XAML technology over the years. 

![](https://github.com/robloo/PublicDocs/blob/master/XAMLFrameworkEvolution.png?raw=true)

**Comment by StephenLPeters** [comment]
@ryandemopoulos FYI

**Comment by wstaelens** [comment]
@robloo very helpful.

You confirm what we've always felt; UWP is just for simple one page apps like weather, or todo-list apps. You know, the stuff that is cool and fancy but actually not very useful. As a result WinUI is basically the same. Sometimes you just don't want the flat, sliding limited tablet app.
There was once potential when Windows Phone was around but we know how that ended due to lack of apps in the appstore and the MS Windows Phone PM who rather used another phone instead of his Windows Phone. (if you don't use your own shit, it is doomed to fail).

With the acquisition of Xamarin a lot of .NET developers hoped that it would be to actually improve WPF or rewrite WPF internals to make that cross platform so that we could go on with WinForms/WPF as thé crossplatform tech to use.  
Silverlight was awesome! We could "re-use" our WPF/XAML skills. Our mindset was being pushed for years by Microsoft to use WPF and Silverlight.

For now it looks like we are moving to Blazor (+ asp.net core) for web and mobile and WPF for desktop development.

I don't see us creating a complex UI in MAUI/WinUI 3 as we could create with WPF and interact with hardware/system/3rd party APIs/etc... as we would do with WPF.

Conclusion:
Desktop: WPF
Mobile, Web: Blazor / ASP.NET Core

**Comment by omikhailov** [comment]
@asklar Could you explain your opinion instead of reacting so emotionally to every comment here?

**Comment by robloo** [comment]
> You confirm what we've always felt; UWP is just for simple one page apps like weather, or todo-list apps. You know, the stuff that is cool and fancy but actually not very useful. As a result WinUI is basically the same. Sometimes you just don't want the flat, sliding limited tablet app.

Well, I've personally used UWP to make desktop-class apps. It can be done and isn't as difficult as some say. There are missing features from WPF that would make things a bit easier in areas though.

**Comment by Poopooracoocoo** [comment]
> [mentions alexander] Could you explain your opinion instead of reacting so emotionally to every comment here?

Yeah I legit haven't seen a single RNW app. The Xbox app which is JUST for Xbox Game Pass games is RNW but no longer uses MSIX lmao. The Xbox app is rather bad and so is Microsoft's PC situation, so I only used it for a split second. The MS Store is RNW on Xbox ONLY and I still see people complain about it. I don't understand Microsoft. There's not even an RNW demo in their own store. What happened to Microsoft trying PC gaming again? 🤣
