### ISSUE TITLE
System.ExecutionEngineException thrown when calling FindChild<>

### ISSUE THREAD

**Issue by omnilogix** [microsoft/microsoft-ui-xaml#4702]
**Describe the bug**

Calling the FindChild<> extension method on a page crashes the app.

**Steps to reproduce the bug**

[Reunion_Demo.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6237911/Reunion_Demo.zip)

1. Load and run the attached project
2. Click on the button
3. Watch the crash

**Expected behavior**

FindChild<> should return null or a found child

**Screenshots**

![Capture5](https://user-images.githubusercontent.com/9586533/113175722-9311ba80-9200-11eb-8701-ac694f8c70aa.PNG)

**Version Info**

![image](https://user-images.githubusercontent.com/9586533/113175755-9c028c00-9200-11eb-869e-cc4f4da5086d.png)

NuGet package version: 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | YES |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | YES  |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | YES |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

The crash happens while the ListView is included on the page.  Remove the ListView or it's bindings and the FindChild<> call works as expected.  I have observed other combinations of controls that crash when using the FindChild<> call, but this is the scenario that I am presenting for evaluation.

**Comment by StephenLPeters** [comment]
On framework as I suspect its a VisualTreeHelper issues.

**Comment by chrisglein** [comment]
Yep, going to be important to know what `FindChild` does (@michael-hawker).
Potentially related: #4729: VisualTreeHelper has some limitations.

**Comment by michael-hawker** [comment]
Sorry was OOF, adding @Sergio0694 as well who recently helped us on the extensions. We have unit tests covering these scenarios for UWP, so assuming this scenario works there, @omnilogix? Also, have you tried with the latest Project Reunion 0.5 based packages? https://aka.ms/wct-winui3

@chrisglein @StephenLPeters `FindChild` is a Logical tree helper, so it doesn't use the `VisualTreeHelper` class. The code for it lives here: https://github.com/windows-toolkit/WindowsCommunityToolkit/blob/winui/CommunityToolkit.WinUI.UI/Extensions/FrameworkElement/FrameworkElementExtensions.LogicalTree.cs#L101-L228 (which should be identical to [the UWP version here](https://github.com/windows-toolkit/WindowsCommunityToolkit/blob/master/Microsoft.Toolkit.Uwp.UI/Extensions/FrameworkElement/FrameworkElementExtensions.LogicalTree.cs#L101-L228)).

It's mainly iterating through Children based on the control type (`Panel`, `ItemsControl`, etc...) or finding the `Content` property for things like `ContentControl` and `ContentPresenter`. The most complex thing it does is fallback to reflection to grab the `ContentPropertyAttribute`, but that should only be if a type isn't a well known one.

So, I see the following potential scenairos
 - This is a Toolkit bug for both UWP and WinUI 3 that our current tests don't cover - @Sergio0694 mind testing this quick if you have some time?
 - WinUI 3 is including extra things in these collections that are unexpected?
 - C#/WinRT is mapping types oddly?

Would be nice to have more details other than 'execution exception'. Has anyone run the provide repro project yet to track down the exception's source?

**Comment by Sergio0694** [comment]
I'm having issues with the WinUI 3 project on my machine right now as I think the .NET 6 Preview SDK I have installed is causing conflicts, will try that again tomorrow. I did setup a UWP project though (using `WinUI 2.5` and `Microsoft.Toolkit.Uwp.UI 7.0.1`), and that works just fine, the `TabView` control is loaded correctly and there's no crash.

Especially considering the really odd exception (`ExecutionEngineException`, which basically means "whops, the whole runtime just exploded"), I don't think our code (even if it was bugged, which doesn't look like it here) could possibly be causing that, even more so given that the code path in use isn't even using any kind of potentially unsafe/dangerous operations at all. If I had to guess, this seems more related to some internal WinUI/CsWinRT issue rather than a bug in the `FindChild` API itself 🤔

@michael-hawker If it helps, I also added a local reference to the `.Uwp.UI` package so I could debug it, and by stepping into the code I can confirm that that reflection path you mentioned is never triggered in this case (at least, for `TabView` as of `WinUI 2.5`). And as you said already, `VisualTreeHelper` is not used in this API either, so all we're doing is really just going through child elements for elements such as `Panel`, `ItemsControl` and similar, which definitely shouldn't throw, and definitely not throw like that.

@omnilogix your project is using Project Reunion 0.5 - have you tried to upgrade to 0.5.5 to see if the crash is still there?

**Comment by omnilogix** [comment]
@Sergio0694 - I tried to test, but get this error after upgrade to 0.5.5  
**This version of Project Reunion requires WinRT.Runtime.dll version 1.2 or greater.** 
How do I resolve this?

**Comment by michael-hawker** [comment]
@omnilogix did you follow the upgrade steps from https://aka.ms/projectreunion/update-your-app?

**Comment by omnilogix** [comment]
@michael-hawker Thanks for the link.  The app does not crash with the latest bits.

**Comment by michael-hawker** [comment]
@StephenLPeters seems like this is good now, not sure if it was resolved as some other fix or not, so feel free to continue investigation from the WinUI or C#/WinRT side or close.

**Comment by codendone** [comment]
From all comments, this sounds very likely to be a C#/WinRT issue, and 0.5.5 took a big C#/WinRT upgrade.
