### ISSUE TITLE
3 errors and 1 warning show in the Error List when adding a WinUI Custom Control(WinUI) to C++ Blank App(WinUI in UWP) project.

### ISSUE THREAD

**Issue by v-xuyan** [microsoft/microsoft-ui-xaml#4760]
**Describe the bug**
3 errors and 1 warning show in the Error List when adding a WinUI Custom Control(WinUI) to C++ Blank App(WinUI in UWP) project.

**Steps to reproduce the bug**
1. Create a C++ Blank App(WinUI in UWP) project.
2. Build the project and no error.
3. Add a WinUI Custom Control(WinUI) to the project.

**Expected behavior**
No error and warning show in the Error List.

**Actual behavior**
3 errors and 1 warning show in the Error List.
**Screenshots**

![image](https://user-images.githubusercontent.com/65747551/113955742-e7471b00-984e-11eb-9294-b8ad2e7d9591.png)

**Version Info**
Affected Branch: main/d16.9
Affected Build: 31103.253/31025.194
Affected SKU: ENT
Affected Product Language:  EN
Operation System Information:20H1
WinUI3 Template Version: 3.0.0.2102104

**Comment by StephenLPeters** [comment]
@alwu-msft and @fabiant3 FYI

**Comment by krschau** [comment]
Closing this item because the WindowsAppSDK does not support UWP apps, details about which can be found in [this discussion](https://github.com/microsoft/WindowsAppSDK/discussions/1615). If you are still seeing the behavior with a Win32 app using the latest WindowsAppSDK version, please open a new issue.
