### ISSUE TITLE
Question: Non-shareable objects are not allowed on Style Setters

### ISSUE THREAD

**Issue by HppZ** [microsoft/microsoft-ui-xaml#4803]
why can't I do this:
![image](https://user-images.githubusercontent.com/12285582/114529467-8e2b1d00-9c7c-11eb-9947-c2b956c20b93.png)

**Comment by huoyaoyuan** [comment]
Non-sharable objects should be set with templates, including ControlTemplate and DataTemplate. You can use ContentPresentor and its ContentTemplate for simple scenario.

**Comment by StephenLPeters** [comment]
You cannot do that because styles are shared across all instances of a control.  So this style will be applied to every button.  This style will try to set the Button.Content property to the instance of the Grid that is owned by the style.  When that grid is parented to a second button via the content property, we'd be attempting to give a UI element 2 parents, which is not how the UI tree design works.  Instead it is intended that styles will set the Template property which is used to instantiate per instance copies of the template.  Then you can use bindings (like {TemplateBinding}) to populate your template.

**Comment by StephenLPeters** [comment]
Feel free to ask more questions here if you want :)

**Comment by HppZ** [comment]
Thanks~
