### ISSUE TITLE
Proposal:  Enable WinUI 3 Desktop apps to detect whether the shell is in tablet mode

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/microsoft-ui-xaml#4814]
# Proposal: Support UIViewSettings in desktop apps
It seems like WinUI 3 doesn't support it in desktop apps anymore but UIViewSettings is very much relevant since Windows still runs on tablets (don't forget that) and UIViewSettings is required to detect whether the shell is in tablet mode or not so the app can adapt for a touch friendly layout when running in tablet mode and a mouse optimized layout when not running in tablet mode.

**Comment by marb2000** [comment]
@Jaiganeshkumaran, rather than adding an existing WinRT API, I think the proposal is to enable developers can detect whether the shell is in tablet mode so the app can adapt for a touch-friendly layout. I will be also nice to have a counterpart event that fires when the OS switches.
Having these WinRT APIs in Reunion is very handy. Meanwhile, you can use Win32 APIs like GetSystemMetrics (using SM_CONVERTIBLESLATEMODE) and listing the event WM_SETTINGCHANGE. 

You can find a sample here: https://github.com/marb2000/DesktopWindow/blob/9ca98adec9c7820ed489f74fa52efff27c268176/WindowExtensions/DisplayInformation.cs#L118

**Comment by JaiganeshKumaran** [comment]
Seems like an UIViewSettings instance can be retrieved from a desktop app by calling [IUIViewSettingsInterop::GetForWindow](https://learn.microsoft.com/en-us/windows/win32/api/uiviewsettingsinterop/nf-uiviewsettingsinterop-iuiviewsettingsinterop-getforwindow).
