### ISSUE TITLE
Binding does not work in winrt c++ desktop

### ISSUE THREAD

**Issue by shelllet** [microsoft/microsoft-ui-xaml#4848]
# Binding does not work in winrt c++ desktop

binding code in cpp.

```
 {
    Binding biding2;

    dynamic2 = winrt::make<implementation::Dynamic>(L"100");
    biding2.Converter(dynamic2);
    biding2.Mode(Data::BindingMode::TwoWay);


    biding2.UpdateSourceTrigger(Data::UpdateSourceTrigger::PropertyChanged);

    biding2.Source(dynamic2);
    biding2.Path(PropertyPath(L"Value"));
    Hd().SetBinding(Hd().TextProperty(), biding2);
}
```

idl defined in used component.

```
import "Dynamic.idl";

namespace App1
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
        //Dynamic MyProperty;
    }
}

```

if I add `Dynamic` property in `MainWindow` idl file , this works fine.  otherwise if I comment `Dynamic` property, the binding will don't work. maybe `biding2.Path(PropertyPath(L"Value"));` has inernal bug. and if i remove binding path set, it's also works fine. 

Test code: https://github.com/shelllet/App1

**Comment by StephenLPeters** [comment]
@chrisglein and @MikeHillberg FYI

**Comment by chrisglein** [comment]
Believe it is expected that bindings require the metadata to be in the WinMD file to work, which is why this works if you include it in the IDL but not if you don't. If you're using C#, all that's going to happen without having to manage an IDL file. @MikeHillberg and @Scottj1s to confirm.

Assuming so, this is effectively by design for C++ (type metadata is a requirement for binding).
