### ISSUE TITLE
RadioButtons: Changing ItemsSource and SelectedItem/SelectedIndex consecutevily does not update selection

### ISSUE THREAD

**Issue by marcelwgn** [microsoft/microsoft-ui-xaml#4893]
**Describe the bug**

When having a RadioButtons control with ItemsSource and either Selection property bound oneway/twoway does not update correctly if we reset the collection beforehand.

Here is a brunch with the respective setup already being done in the WinUI repo: 
https://github.com/chingucoding/microsoft-ui-xaml/tree/user/chingucoding/radiobuttons-selection-collection-bug
**Steps to reproduce the bug**

1. Create observable object with Items, SelectedItem and SelectedIndex property
2. Bind RadioButtons control to Items and either SelectedItem or SelectedIndex
3. Reset Items, update SelectedItem or SelectedIndex in same callstack and invoke PropertyChanged

**Expected behavior**

Selection should be displayed.
**Screenshots**

**Version Info**

NuGet package version: 

b50399ac19ab18d0fade16534f7eea53be537caa

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19043)              | Yes |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@chingucoding thoughts on the cause of the issue?

**Comment by chingucoding** [comment]
I would suspect a timing issue/life-cycle issue. If you call `UpdateLayout` after updating when using SelectedIndex for binding, the selection indicator shows up.

**Comment by michael-hawker** [comment]
Is this related to #3268 and #3128?

**Comment by danmartinez** [comment]
I believe I'm experiencing this as well, although in my case calling UpdateLayout immediately following the items source change doesn't update the selected state as expected.

Repro details: I created a simple class comprised of a string vector and an integer. I stuck a few instances of these inside an observable vector. Then I bound one of the items in that vector to a RadioButtons control, setting the ItemsSource to the string vector and SelectedIndex to the integer. At this point, if you bind to a different object in the observable vector, the strings/radio buttons will reflect the change, but selection will be cleared rather than set to the value of the bound integer.

**Comment by shatyuka** [comment]
@danmartinez Try calling UpdateLayout() before changing the SelectedIndex property.

**Comment by SnowyWreath** [comment]
This issue still exists in WASDK 2
