### ISSUE TITLE
Proposal: Rename the default branch to "main"

### ISSUE THREAD

**Issue by thomasclaudiushuber** [microsoft/microsoft-ui-xaml#4896]
# Proposal: Rename the default branch to "main"
Currently the default branch uses still the non-inclusive term. All other repos in the .NET space, like [WPF](https://github.com/dotnet/wpf), [WinForms](https://github.com/dotnet/winforms), or [.NET Core](https://github.com/dotnet/core), and also the [Project Reunion repo](https://github.com/microsoft/ProjectReunion) use _main_ already as name for the default branch. 

So, please rename the default branch of this repo to "main"

**Comment by chingucoding** [comment]
Also relevant as there was more discussion around this there: https://github.com/microsoft/microsoft-ui-xaml/issues/2676

**Comment by omikhailov** [comment]
Let's not touch on this topic. The discussion itself will look more chauvinistic than the name of the branch.

**Comment by omikhailov** [comment]
Guys, you can downvote as much as you want, but "master" in Git is a noon that means "original". It contains original code, while branches contain modified code. When you see something else here and make such proposals, _that_ makes other people to feel awkward and _that_ is non-inclusive.

**Comment by chingucoding** [comment]
While `master` has been the default branch (that's how most resources refer to it), that does not mean that that can't change. Saying renaming this thing is not *inclusive* because some people might not have heard about it is a very weak argument. I really doubt that anyone feels awkward about the name "main" for the *MAIN* development branch of a repository. For me, it's  a lot more "awkward" right now because most repositories I work with have adopted "main" as the default branch, while WinUI is standing out right now (as @thomasclaudiushuber also pointed out).

**Comment by kmahone** [comment]
The current convention used across Microsoft is for the primary branch to be named main. I've updated this repo to be consistent with that.
