### ISSUE TITLE
Question: consistency of XAML/Visual transform properties and related APIs

### ISSUE THREAD

**Issue by Sergio0694** [microsoft/microsoft-ui-xaml#4904]
## Overview
Opening this issue as a follow up to [this Windows Community Toolkit PR](https://github.com/windows-toolkit/WindowsCommunityToolkit/pull/3956) related to introducing an attached property for the "Visual.Transform" property. While working on it I've noticed a number of inconsistencies with the way some related APIs are currently structured and documented, and it took me a while to actually figure out how the code needed to be laid out.

Here I'd like to recap my findings and ask for some clarification to the team(s) working on these APIs, and also possibly discuss some improvements that could be made to both the docs and the actual APIs in UWP XAML and WinUI 3 (since they're the same). I'll just list all my observations/questions/proposals below in a numbered list for easier reference:

1) Why is the `Visual.Translation` property hidden/magic? By that I mean:
   - It needs to specifically be enabled beforehand via [`ElementCompositionPreview.SetIsTranslationEnabled`](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.hosting.elementcompositionpreview.setistranslationenabled)
   - It's not directly exposed on the `Visual` class, instead needs to be accessed through [`Visual.Properties.TryGetVector3`](https://docs.microsoft.com/en-us/uwp/api/windows.ui.composition.compositionpropertyset.trygetvector3).
2) With respect to 1., would it be possible to actually enable it by default (like every other `Visual`) property, and possibly to also add a mapping property to the `Visual` class, just like other properties such as eg. `Scale` and `Offset`? The way "Translation" works makes it a bit clunky and requires special handling that isn't needed for any of the other properties.
3) The docs for [`ElementCompositionPreview.SetIsTranslationEnabled`](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.hosting.elementcompositionpreview.setistranslationenabled) don't mention _where_ the enabled property actually is (as in, that it's in the `.Properties` object of `Visual`). I think the docs should be updated to add more context, such as how to get/set values for this properties directly (using `.Properties`), and that it can be animated by just using the "Translation" property on `Visual` from a keyframe composition animation, even though the `Visual` class doesn't actually have that property (which could be confusing for especially beginner devs).
4) As I mentioned [here](https://github.com/windows-toolkit/WindowsCommunityToolkit/pull/3956#issuecomment-825601793), it is my understanding that there are at least 3 different ways to manipulate the translation of a UI element, which all get stacked on top of one another and can be set/animated indipendently. Specifically, we have `Visual.TransformMatrix.Translation`, `Visual.Properties["Translation"]` and `UIElement.Translation`. Is there a specific reason why this is the case? I mean, considering `UIElement.RenderTransform` there's a total of 4 different ways to set/animate the translation of UI elements, as far as I can tell. That's a lot 😄
5) With respect to 4., I noticed that `UIElement.Translation` doesn't just act as a proxy for `Visual.Translation`, but instead is completely indipendent from it, why? Where is this additional translation value stored, and why is it indipendent?
6) I noticed that when using properties such as [`UIElement.Rotation`](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.rotation), or [`UIElement.Scale`](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.scale), trying to then use [`ElementCompositionPreview.GetElementVisual`](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.hosting.elementcompositionpreview.getelementvisual) on a `UIElement` throws an exception ([`UnauthorizedAccessException`](https://docs.microsoft.com/en-us/dotnet/api/system.unauthorizedaccessexception)) saying eg. "Access denied. Calling ElementCompositionPreview.GetElementVisual API is not allowed on this object at this time, as this object currently has the TranslationTransition property in use.". Why is this the case?
7) With respect to 6., that seems like a very critical aspect of those APIs, that isn't currently documented in the docs.

> **NOTE:** I'd be happy to help update the docs once I got the necessary feedbacks and we all agreed on what to change 🙂

## Related Links

- https://github.com/windows-toolkit/WindowsCommunityToolkit/pull/3956
- https://github.com/microsoft/microsoft-ui-xaml/issues/2130

**Comment by StephenLPeters** [comment]
@jeffstall and @codendone FYI

**Comment by StephenLPeters** [comment]
@gegao18 and @kmelmon as well

**Comment by kmelmon** [comment]
Hi @Sergio0694,

Thanks for your observations and questions!  I'll try and answer them and provide some context to help clarify.

First:  The Visual obtained by ECP.GetElementVisual is an object from a lower level component in the platform.  See https://docs.microsoft.com/en-us/windows/uwp/composition/visual-layer for a good overview and explanation of the layering.  This layering produced a number of the behaviors you're observing and should help clarify why things work the way they do.

The Visual.Translation property is actually not a first class property on Visual.  The XAML layer "knows" how to superimpose this property into the visual tree it builds, as it's the one that turns the XAML tree into a visual tree.  There is a cost to doing this, so XAML requires apps to opt-in to using the property, to only pay this cost if the app is actually using the feature.

We discussed making Translation a first class property on Visual, but for various reasons that go beyond the scope of a discussion here, we decided against this.

I agree the docs on SetIsTranslationEnabled could be improved.  I opened this issue to track:
https://github.com/microsoft/microsoft-ui-xaml/issues/4929

It can be confusing to deal with the visual layer.  It is helpful to first understand the layering.  Once this is understood, you might begin to use the visual layer in scenarios where it provides the power of the Windows.UI.Composition features.

The properties you're asking about have evolved over time and this is partly why there are multiple ways of manipulating the visual.  The original API was not in the visual layer at all (UIElement.RenderTransform), but this layer is above the visual layer, and so doesn't have the power of that layer.  We then made it possible to drop down to the visual layer, as it was already being used internally.  This has some history:
-In Windows 10 Creators Update we added the SetIsTranslationEnabled
-Later, in Windows 10, version 1809, we introduced the so-called "facade properties", which includes UIElement.Translation.  This was a major upgrade to the ElementCompositionPreview APIs, and is the recommended way to drop down to the visual layer, provided your app is targeting version 1809 or greater.  if you do use the "facade" properties, you should not also use the ElementCompositionPreview APIs on the same UIElement as they weren't designed to work together (facades is the modern way to drop down to the visual layer, so just use that if it's available on your target platform).  I agree that the exception that gets thrown when trying to use the two types of APIs together is not well documented.  I opened this issue to track: 
 https://github.com/microsoft/microsoft-ui-xaml/issues/4931

Once you drop down to the visual layer, you'll need to understand the Visual properties, which do stack according to well-defined rules.  I believe the order is:
Offset
Translation (as a pseudo property)
Rotate
Scale
TransformMatrix
I may have Rotate and Scale reversed.  Lemme know if you need this clarified.

When we added the Translation property, we decided it should be just after Visual.Offset, in order to provide a "post-layout" translation.  This extra property makes it possible to use XAML layout, which ends up putting the layout offset into Visual.Offset, plus have an additional translation, without stomping over the layout offset.  Visual.TransformMatrix is much later in the stacking order, and is useful for scenarios where you want to control everything.  However it comes with a risk of "property stomping" as UIElement.RenderTransform ends up being mapped to this property.

Hope this answers your questions!  Closing this question for now, feel free to reopen if you have more questions.
