### ISSUE TITLE
Cannot build F# project with Microsoft.ProjectReunion.WinUI

### ISSUE THREAD

**Issue by xperiandri** [microsoft/microsoft-ui-xaml#4954]
**Describe the bug**
F# project that references `Microsoft.ProjectReunion.WinUI` does not build
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2902,7): error MSB4057: The target "XamlPreCompile" does not exist in the project.
```

**Steps to reproduce the bug**
1. Clone https://github.com/xperiandri/Elmish.Uno/tree/uno_winui
2. Check out https://github.com/xperiandri/Elmish.Uno/tree/uno_winui branch
3. Open Elmish.Uno.sln
4. Comment out my work around in Elmish.Uno.fsproj if it present (empty `XamlPreCompile` target)
5. Build Elmish.Uno.fsproj

**Expected behavior**
F# project builds successfully

**Version Info**
Microsoft.ProjectReunion.WinUI 0.5.0-prerelease

NuGet package version: 
0.5.0-prerelease

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Comment by StephenLPeters** [comment]
@alwu-msft FYI about the XPC target.

**Comment by alwu-msft** [comment]
`XamlPreCompile` is defined by a VS target (`Microsoft.Windows.UI.Xaml.Common.targets`). 

@RealTommyKlein what are the implications of WinUI defining and using its own version of `XamlPreCompile`?

**Comment by RealTommyKlein** [comment]
Nothing bad off the top of my head - we'd probably have to do something similar to the repro's workaround to prevent VS's `XamlPreCompile` from running while defining our own target.  We _should_ own that target anyway - no reason for VS to get mixed up in it.

**Comment by xperiandri** [comment]
So, will you add F# for XamlPreCompile?

**Comment by RealTommyKlein** [comment]
I don't think we have plans to support F# for WinUI 3 in general - `XamlPreCompile` is a small part of the work we'd need to support WinUI 3 in F#, we'd also need features like:

- An F# equivalent to CSWinRT so F# WinUI apps could consume native WinRT APIs like C# WinUI apps can with CSWinRT
- Xaml compiler codegen support for F# to implement support for `x:Bind`, `x:Name`, event hookups, and other features handled by Xaml compiler generated code

If you aren't actually compiling `.xaml` pages or need to consume native APIs (doesn't look like `Elmish.Uno` is), you could use `ExcludeAssets="build;buildTransitive"` on the WinUI NuGet package reference to exclude the WinUI specific props/targets that pull in things like `XamlPreCompile`, e.g.:

`    <PackageReference Include="Microsoft.ProjectReunion.WinUI" Version="0.5.6" Condition="$(TargetFramework.StartsWith('net5.0-windows10'))" ExcludeAssets="build;buildTransitive" />`

Or continue stubbing out `XamlPreCompile` like you've been doing, since that's only required when compiling `.xaml` pages.  But you'd be going down an unsupported road and would likely need more hacks to get it working.

**Comment by xperiandri** [comment]
Any updates?

**Comment by marb2000** [comment]
Hi @xperiandri 
Thanks for opening this bug. Unfortunately, WinUI 3 doesn't support F# and there is no plan to support it in 2021 per the current engineering plan. Answer your questions will require investigating and evaluate what is needed to support the language, but we didn't allocate time to do such work yet. There is a feature request for tracking this work: https://github.com/microsoft/microsoft-ui-xaml/issues/740

I will close the bug given it's not a supported scenario.

**Comment by xperiandri** [comment]
![image](https://user-images.githubusercontent.com/2365592/142508111-822401dc-0ac2-4a4a-9f0e-c1886cea00ed.png)
So, finally F# works! 🥳🥳🥳

**Comment by NickDarvey** [comment]
@xperiandri, are you able to share the details/template of how you got it working?

**Comment by xperiandri** [comment]
@NickDarvey yes, let’s connect in Twitter

**Comment by xperiandri** [comment]
https://github.com/xperiandri/Elmish.Uno/blob/ae1f47e914cc1c4b311cea42ea40a9396ba75281/src/Elmish.Uno/Elmish.Uno.fsproj#L67

**Comment by fwaris** [comment]
thanks @xperiandri - this helped me with an F# maui project also
