### ISSUE TITLE
Issue with Image in RichEditBox

### ISSUE THREAD

**Issue by HppZ** [microsoft/microsoft-ui-xaml#4964]
**Describe the bug**

1. Image in RichEditBox sometimes disappears after click / double click several times.
2. How to disable those anchor point around the Image?

**Steps to reproduce the bug**

https://github.com/HppZ/RichBoxBug

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/12285582/117248829-2cbd2f00-ae73-11eb-8acf-fc3b8bd94897.png)
![image](https://user-images.githubusercontent.com/12285582/117248884-3f376880-ae73-11eb-9d80-a358c38404f3.png)

**Version Info**

NuGet package version: 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | No |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| October 2020 Update (19042)        | Yes |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Additional context**

**Comment by HppZ** [comment]
@ranjeshj

**Comment by HppZ** [comment]
OMG

**Comment by HppZ** [comment]
hello

**Comment by HppZ** [comment]
@StephenLPeters PLEASE TAKE A LOOK

**Comment by codendone** [comment]
1. It looks like the image disappearance is caused by an exception when trying to invert the image during selection. The exception (code 80010012) is firing within windowscodecs.dll which eventually returns HRESULT==0x88982f61 ("The image header is unrecognized.") to msftedit!CImage::InvertBitmap. There are JPEG functions being called by windowscodecs.dll, and I don't know if that is expected (perhaps the png has been converted to jpg) or if this might be due to some corruption happening earlier. We'll need to find the right experts to debug this further.
2. Based on code inspection, it looks like images are always considered resizable and therefore will show anchors when selected.

**Comment by HppZ** [comment]
> images are always considered resizable
need an option.

**Comment by codendone** [comment]
If you are using a hard-coded set of images, you could potentially create a custom font for those images and then set the font (via `CharacterFormat.Name`) appropriately for each text range. This could result in the user getting the caret inside that custom font range and accidentally inserting more characters in that font instead of the desired RichEditBox font, though.

**Comment by HppZ** [comment]
> If you are using a hard-coded set of images, you could potentially create a custom font for those images and then set the font (via `CharacterFormat.Name`) appropriately for each text range. This could result in the user getting the caret inside that custom font range and accidentally inserting more characters in that font instead of the desired RichEditBox font, though.

it is not ideal.

**Comment by chrisglein** [comment]
Video of the repro:

https://user-images.githubusercontent.com/26607885/132748466-af4082a7-c321-4dfe-9a6b-041b21c94ead.mp4

I think it happens on resize, and clicking a lot just happens to trigger resize. I've certainly had it happen while intentionally trying to resize in this repro. Once the image stops showing, it never comes back.

Not sure if it's related, but it seems to be the first resize after some background thread exits (`The thread 0x6874 has exited with code 0 (0x0).`) I can resize until then, but then when it exits... next resize bad. Not sure what the thread is. Some image decode thread?
