### ISSUE TITLE
`OnKeyboardAcceleratorInvoked` not called

### ISSUE THREAD

**Issue by Marv51** [microsoft/microsoft-ui-xaml#4991]
**Describe the bug**
[Documentation](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.uielement.onkeyboardacceleratorinvoked?view=winui-3.0) suggests that `OnKeyboardAcceleratorInvoked` is "[c]alled when a keyboard shortcut (or accelerator) is processed in your app." For me that is not the case. Overriding `OnKeyboardAcceleratorInvoked` in a Page is never called.

**Steps to reproduce the bug**
On an empty page add 
```csharp
protected override void OnKeyboardAcceleratorInvoked(KeyboardAcceleratorInvokedEventArgs args)
{
    Debug.WriteLine("OnKeyboardAcceleratorInvoked");
    base.OnKeyboardAcceleratorInvoked(args);
}

private void KeyboardAccelerator_Invoked(KeyboardAccelerator sender, KeyboardAcceleratorInvokedEventArgs args)
{
    Debug.WriteLine("Invoked");
    myButton.Content = "Huh?";
}
```

```xaml
    <StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
        <StackPanel.KeyboardAccelerators>
            <KeyboardAccelerator Key="A" Invoked="KeyboardAccelerator_Invoked" />
        </StackPanel.KeyboardAccelerators>
        <Button x:Name="myButton">Click Me</Button>
    </StackPanel>
```

Start app and press "A" key. Notice the buttons text changed and debug output "Invoked" but no debug output "OnKeyboardAcceleratorInvoked".

**Expected behavior**
Debug output should show `OnKeyboardAcceleratorInvoked`.

**Version Info**
NuGet package version: 
WinUI 3 - Project Reunion 0.5: 0.5.6

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by Marv51** [comment]
Is that the experience others are having too?

**Comment by Austin-Lamb** [comment]
This does feel like a bug to me, I think we're supposed to call OnKeyboardAcceleratorInvoked unless the args.Handled is true - and I don't see how it would be set to true in this case.

**Comment by JJBrychell** [comment]
This feature is working as designed, although the documentation could be clearer. The OnKeyboardAcceleratorInvoked function is only called on those elements where the accelerator is attempted to be invoked. In otherwords, there is a 1-1 correspondence between attempts to raise an event on a KeyboardAccelerator and a call to the overridable onKeyboardAcceleratorInvoked.

In the example presented in this issue, we raise the Invoked event on the KeyboardAccelerator and then the overridable OnKeyboardAcceleratorInvoked is called on the parent of the KeyboardAccelerator object which is the StackPanel, which noops because StackPanel does not override this. If the KeyboardAccelerator had been defined on the Page, then OnKeyboardAcceleratorInvoked will be called on the Page, but since this event does not bubble it will not be called in this scenario..

The confusion in the documentation might come from the fact that it indicates that handled should be set to prevent bubbling. Which is true, but it is not the bubbling of the Invoked event that is being referred to. It is that we bubble the search for the accelerator up the tree. When an accelerator is pressed, we start at the keyboard focused element and determined if it wants it, then its parent and each ancestor up the tree. If the same accelerator is defined on multiple elements in the tree then setting handled to true will stop the search so that both KeyboardAccelertors are not invoked. But each time an accelerator matching the keystroke is found is a separate invocation of a different KeyboardAccelerator and that invocation (nor the companion call to OnKeyboardAcceleratorInvoked) is bubbled.

There is another reason to set the handled event.  Once the search for something to handle accelerator has worked it way up tree, if nothing has handled it, then it will be thrown open to any element defining that accelerator on the page.  This can potentially have the effect of the same accelerator handler being called a second time.
