### ISSUE TITLE
Implicit Animation causes dead lock.

### ISSUE THREAD

**Issue by HppZ** [microsoft/microsoft-ui-xaml#5051]
see here
https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/4038

**Comment by StephenLPeters** [comment]
@stmoy @codendone FYI

**Comment by HppZ** [comment]
@stmoy @codendone please help.

**Comment by HppZ** [comment]
https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/4038#issuecomment-846923494

**Comment by codendone** [comment]
This is a XAML bug: we get stuck in CPopupRoot::GetOpenPopups(), due to a simple code bug where an "unloading" popup (one which is animating out) causes a loop counter to not advance.

This issue has been fixed in WinUI 3. For system UWP XAML avoiding a hide animation is currently your best option. (Having a very short hide animation would reduce the risk, but it would still be non-zero.

**Comment by HppZ** [comment]
so many bugs in system XAML framework, so sad.
