### ISSUE TITLE
Having an invalid resource dictionary in App.xaml will crash the app

### ISSUE THREAD

**Issue by jtorjo** [microsoft/microsoft-ui-xaml#5055]
**Describe the bug**

This error should be somehow handled at compile time. It took me quite a while to figure out what's happening.

Say I have this:

	<Application ...>
		<Application.Resources>
			<ResourceDictionary>
				<ResourceDictionary.MergedDictionaries>
					<XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
					<ResourceDictionary Source="./ScrollViewer.xaml"/>
				</ResourceDictionary.MergedDictionaries>
			</ResourceDictionary>
		</Application.Resources>
	</Application>

At some point, I decide I don't really need ScrollViewer.xaml, and remove it from the project, but I forget to update the App.xaml

At this point, the application will crash at startup, with no clear error. If you're on debug mode, you'll break in debug mode, but can't really access `$exception`, so you have no idea what's going on

**Expected behavior**

This should be caught at compile time, or at least at runtime, throw a meaningful error.

**Comment by chrisglein** [comment]
WinRt exceptions can be a bit obtuse if you're not familiar with them. It's possible there is a meaningful error here but it doesn't surface through the tooling in a way that's obvious. Which can be as bad as no error.

Next action here would be to assemble a repro, look at what gets thrown, and see how that shows in the tooling. That'd inform whether we have a bad error here or a bad experience due to how errors surface.
