### ISSUE TITLE
`Stack overflow`  occurs when co_await asynchronous function in the loop

### ISSUE THREAD

**Issue by shelllet** [microsoft/microsoft-ui-xaml#5078]
The application crash occurs when `co_await` asynchronous function in the loop.
```
      co_await resume_background();

        for (int i = 0; i < 10000; ++i) {

            co_await Test();
       }
```
1. download source code
https://github.com/shelllet/winui_stack_overflow.git

2. compile and run

3. click button 'clickme' 

error:
```
Symbol loading disabled by Include/Exclude setting.
Exception thrown at 0x00007FF7BAD5A77F in App1.exe: 0xC00000FD: Stack overflow (parameters: 0x0000000000000001, 0x0000007CC4403F88).
Unhandled exception at 0x00007FF7BAD5A77F in App1.exe: 0xC00000FD: Stack overflow (parameters: 0x0000000000000001, 0x0000007CC4403F88).
```

https://user-images.githubusercontent.com/16729017/119251842-5e582900-bbdb-11eb-99c6-d57db0a8262d.mp4

**Comment by Jaiganeshkumaran** [comment]
Can you show what the test method does?

**Comment by shelllet** [comment]
> Can you show what the test method does?

https://www.github.com/shelllet/winui_stack_overflow/tree/master/App1%2FMainWindow.xaml.cpp

![Screenshot_20210523-212628_GitHub.jpg](https://user-images.githubusercontent.com/16729017/119262391-a2642180-bc0d-11eb-80d0-220a579fed5f.jpg)
~~~~

**Comment by ranjeshj** [comment]
@jevansaks  any ideas?

**Comment by jevansaks** [comment]
A stack would help. But I'm guessing since your Test function completes immediately, the co_await is calling the completion function synchronously, which then calls the next iteration of the loop synchronously, and so forth. 

Raymond Chen has a multi-part series on better understanding coroutines in C++: https://devblogs.microsoft.com/oldnewthing/20191209-00/?p=103195

It's probably by design. C++ coroutines have a lot of rough edges.
