### ISSUE TITLE
TextBox border is blurry with custom brush

### ISSUE THREAD

**Issue by ghost** [microsoft/microsoft-ui-xaml#5099]
**Describe the bug**
Setting a custom border brush for a TextBox will cause the border to be blurry.

**Steps to reproduce the bug**
```
<TextBox>
    <TextBox.Resources>
        <Thickness x:Key="TextControlBorderThemeThickness">3</Thickness>
        <SolidColorBrush x:Key="TextControlBorderBrush" Color="Red" />
    </TextBox.Resources>
</TextBox>
```

**Screenshots**
<img src="https://user-images.githubusercontent.com/84711285/119854112-78667400-bf19-11eb-8963-73ad7372e442.png"  width="546">

**Version Info**
Microsoft.UI.Xaml 2.6.0-prerelease.210430001

**Additional context**
With v1 styles the border is blurry if the thickness is less than 4px, but with v2 styles it's always blurry.

Edit: if you use a LinearGradientBrush instead of SolidColorBrush the border will always look good, with both v1 and v2 styles.

**Comment by soredake** [comment]
Not stale.

**Comment by JJBrychell** [comment]
This is a bug reported against WinUI2 and there are comments suggesting that work has been done to improve the issue, but it is unclear what the current state is.

Since WinUI2 is currently in maintenance mode and WinUI3 does not default to the rounded corners, we are closing this issue until it is determined if it a significant issue in WinUI3.
