### ISSUE TITLE
[BUG] GroupStyle.Panel

### ISSUE THREAD

**Issue by HppZ** [microsoft/microsoft-ui-xaml#527]
GroupStyle.Panel does not work when set ItemsWrapGrid to GridView.ItemsPanel.

**Comment by chrisglein** [comment]
@HppZ can you clarify what you mean by "does not work"? Was this a compile time issue? Failure at runtime? Or silent failure (didn't do what you expected)? Do you have any code/markup example you can point us to? Thanks!

**Comment by HppZ** [comment]
This is my example code:
https://github.com/HppZ/GroupStyleApp
1,
seems GridView.ItemTemplate not work.

2,
if I change line 75 to ItemsWrapGrid in MainPage.xaml, then GroupStyle.Panel does not work.

**Comment by jevansaks** [comment]
@chrisglein were you following up on this?

**Comment by chrisglein** [comment]
I've looked at the sample and confirmed the behavior. If you set `GridView.GroupStyle.Panel` then `GridView.ItemTemplate` no longer is used. Instead of this:
![image](https://user-images.githubusercontent.com/26607885/56995199-ed59fa80-6b55-11e9-88d5-d2fa771d1b79.png)
You get this:
![image](https://user-images.githubusercontent.com/26607885/56995219-fea30700-6b55-11e9-8776-414d93f0f8b0.png)

There seems to be some discussion about this on this StackOverflow topic: https://stackoverflow.com/questions/33782294/uwp-grouped-gridview-with-wrapgrid
> when the GridView's ItemsPanel is an ItemsWrapGrid (the default) or ItemsStackPanel, GridViewItem uses the template which uses a GridViewItemPresenter instead of a UIElement tree to improve grid performance. And while using this template, setting GroupStyle.Panel property won't affect the GridView

If you follow that discussion they get stuck having to workaround the lack of WrapPanel and pull that from a toolkit.

So there's definitely some quirkiness here. That Stack Overflow response was helpful but I'm not seeing anything in the [relevant doc pages](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.groupstyle.panel#Windows_UI_Xaml_Controls_GroupStyle_Panel). @micahl is there something somewhere else? And do we think we have the right layout suite (and control support) coming to better solve this scenario.

@HppZ can you give us more information on what layout you're trying to receive? There's definitely a cascade of templates involved in getting a grouped GridView to work and I want to be crisp on what you're trying to customize and what you're not.

**Comment by micahl** [comment]
@chrisglein There is quirky behavior on ListView/GridView that stems from when ItemsStackPanel/ItemsWrapGrid were introduced.  It's entirely possible that some of those behaviors weren't fully captured.  

@HppZ, is there a pic of an existing experience that shows the kind of layout you want to achieve? 
 That would help clarify things for me since it seems what you want to do isn't currently supported on GridView.

**Comment by HppZ** [comment]
the screenshot is what I want to achieve, for now I put the "folders" GridView in the Header of the "photos" GridView and calculate the ItemSize respectively to achieve that.
![s1](https://user-images.githubusercontent.com/12285582/57534784-671e8f00-7373-11e9-809e-7cd88852c413.png)

**Comment by HppZ** [comment]
![s1](https://user-images.githubusercontent.com/12285582/57534535-cdef7880-7372-11e9-9a3e-76f710fcd51e.png)
![s1](https://user-images.githubusercontent.com/12285582/57534536-ce880f00-7372-11e9-87bc-8521d1750752.png)

**Comment by HppZ** [comment]
@micahl

**Comment by micahl** [comment]
@HppZ yes that helps to clarify.  Using the GridView's Header as you've done is probably the easiest solution.  One potential con is that the GridView you have in the Header showing the folders won't perform UI virtualization.  Only the main GridView showing your items will still be virtualizing.  Unless the number of folders to show will be enough to fill 4x the viewport the virtualization wouldn't kick in anyway so maybe not an issue?.  Will you need the folders to be virtualized?

**Comment by HppZ** [comment]
Yes, I need UI virtualization.

I don't want to put it in GridView's Header, I think the header is designed for other purpose, the best way to do that is to make it a group, and custom the group panel, but ItemsStackPanel/ItemsWrapGrid does not work with GroupStyle right now, please fix this bug & make it work.

**Comment by micahl** [comment]
We'll need to investigate.  Bear in mind that any potential investigation / fix probably won't happen until sometime after WinUI 3.0 (see #717) which depending on your timeline might be an issue.  If so, there are alternatives that are available today, but they'd require some extra work on your part to set up.

Fwiw, the Header was designed in response to the very common need for including something (anything) ahead of the items as part of the same scrolling surface _but not loose UI virtualization for the items in the ListView/GridView_.  A natural tendency might be to do this:
```xaml
<ScrollViewer>
    <StackPanel>
        <ContentPresenter .../>
        <GridView .../>
    </StackPanel>
</ScrollViewer>
```
But that breaks UI virtualization.  So instead, as a workaround someone can do this:
```xaml
<GridView>
    <GridView.Header>
        <!-- stuff goes here -->
    </GridView.Header>
</GridView>
```

**Comment by HppZ** [comment]
great 👍 
as long as you fix the bug, I feel happy.

please make Xaml more powerful!

**Comment by HppZ** [comment]
I think this issue is related https://github.com/microsoft/microsoft-ui-xaml/issues/527

**Comment by HppZ** [comment]
any update here?
