### ISSUE TITLE
new Window() Exception Unhandled in KernalBase.dll

### ISSUE THREAD

**Issue by jasonalls** [microsoft/microsoft-ui-xaml#5289]
**Describe the bug**
Unhandled exception at 0x00007FF93AE7B39C (KernelBase.dll) in CH11_ResponsiveWinUI3.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x00000212DD548910, 0x0000000000000001). This error happens when instantiating a new Window.

**Steps to reproduce the bug**
1. Create a new WinUI project.
2. Update the myButton_Click method as follows:

		private void myButton_Click(object sender, RoutedEventArgs e)
		{
			Window window = new Window();
			window.Content = new TextBlock() { Text = "Hello" };
			window.Activate();
		}

3. Run the project with the Package project set as the startup project and the target platform set to x64. The Framework is set to net5.0.

**Expected behavior**
I would expect to see a new Window with the text "Hello" displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/11942797/123482487-276f9b80-d5fd-11eb-941a-dd40d5ac4396.png)

**Version Info**

NuGet package version: 
[WinUI 3 - Microsoft.ProjectReunion 0.8: 0.8.0] 
[WinUI 3 - Microsoft.ProjectReunion.Foundation 0.8: 0.8.0] 
[WinUI 3 - Microsoft.ProjectReunion.WinUI 0.8: 0.8.0] 
[Microsoft.Windows.SDK.NET: Assembly Version (10.0.19041.10) File Version (10.0.19041.16)

Windows app type:
Windows Application

Version 20H2 (OS Build 19042.1052)

Windows Desktop

**Additional context**

**Comment by asklar** [comment]
@jasonalls multiple windows is not supported yet. See https://github.com/microsoft/microsoft-ui-xaml/issues/5135#issuecomment-860992084

**Comment by StephenLPeters** [comment]
@marb2000 FYI

**Comment by NeilSteenson** [comment]
Any timescales on when multiple windows will be available?  On launch or before/after?

**Comment by MarkTun6** [comment]
Hi,  We have started the process of converting old WinForm system to WinUI 3 desktop platform. One of the main requirement is to have multiple windows in new system. 

Can you give us some guideline on when multiple windows option will be available please?
So that we need to make decision on whether to go ahead with WinUI 3 or not?

If this is not likely to be available soon then can you suggest whether to:
1. Switch to WinUI 2 first and convert to WinUI 3 later
OR
2. Switch to WPF with Xaml Islands then convert to WinUI 3.

Thanks

**Comment by marb2000** [comment]
Hi there!

Multi-Window support in the same UI thread will be supported in the v1 (Fall 2021), and we deactivated the functionality from the supported versions. Meanwhile, you can use the Preview versions of Project Reunion (Windows App SDK) instead of the supported versions, although it's very buggy.
Hope this helps you to make progress.

**Comment by pratikone** [comment]
multiple windows are now supported. your scenario should work now. closing the bug
