### ISSUE TITLE
Mica material doesn't works in XAML Islands

### ISSUE THREAD

**Issue by sylveon** [microsoft/microsoft-ui-xaml#5319]
**Describe the bug**
Mica material either renders as fully transparent or just plain white in XAML islands.

**Steps to reproduce the bug**

1. Create an XAML Islands app
2. Add `muxc:BackdropMaterial.ApplyToRootOrPageBackground="True"` to a page
3. Load that page

**Expected behavior**
I expected to see the Mica brush.

**Screenshots**
![image](https://user-images.githubusercontent.com/6440374/123857861-da3b4480-d8f0-11eb-9339-1ec10862c40e.png)
![image](https://user-images.githubusercontent.com/6440374/123857882-e1625280-d8f0-11eb-9bff-fb92bc08dcf2.png)

**Version Info**

NuGet package version: 

[Microsoft.UI.Xaml 2.6.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22000)              | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
I don't have a repro project due to the complexity of getting XAML Islands and WinUI set up together.

**Comment by StephenLPeters** [comment]
@jevansaks Is this expected?

**Comment by StephenLPeters** [comment]
@marb2000 FYI

**Comment by jevansaks** [comment]
> @jevansaks Is this expected?

Yes, but we should use this issue to track making it work. The problem is that currently we only know how to get the current Window -- there's no way to get the DesktopWindowXamlSource from an element. We'll need an API for apps that want to do this to tell us what the DesktopWindowXamlSource is to set the mica brush in the right place.

**Comment by sylveon** [comment]
Is that not what XamlRoot is for?

**Comment by sylveon** [comment]
In any case, the `DesktopWindowXamlSource` is abstracted away from the XAML I host in Islands, so I'd love to not have to break that abstraction on my side.

**Comment by Extrimis** [comment]
You can have mica material support in Windows 11 and Windows 10 using DWM Private API, The DWM Api has a private function called `DwmpCreateSharedThumbnailVisual`. This method can be used to acquire the live bitmap of any window into an `IDCompositionVisual`. use this function to capture the desktop hwnd (Progman). Once you get the Visual you can clip the Visual with window `RECT` using the Rectangle Clip or use Atlas Effect from Windows.UI.Composition and then using `IDCompositionBlendEffect `and `IDCompositionGaussianBlurEffect` can give you the Mica Effect. Since this issue is about XAML Islands. you need to convert `IDCompositionVisual` to `Windows.UI.Composition.Visual` and apply all effects., you can do it through [Interop Compositor](https://blog.adeltax.com/interopcompositor-and-coredispatcher/).

A sample demo of this is available [Here](https://github.com/Extrimis/Win32-Acrylic-Effect).
Change This line in the sample from
```C++
compositor->SetAcrylicEffect(hwnd, AcrylicCompositor::BACKDROP_SOURCE_HOSTBACKDROP, param);
```
To
```C++
compositor->SetAcrylicEffect(hwnd, AcrylicCompositor::BACKDROP_SOURCE_DESKTOP, param);
```

This will use the desktop Live bitmap as backdrop. Change the Tint Opacity and blur amount for desired effect.

**I highly does not recommend using DWM private functions, since it can be changed or removed any time, but having something is better than having nothing😁**

**Comment by sylveon** [comment]
Or we could just use acrylic on Windows 10 and manually use the Mica composition API on 11, until WinUI 2 ships a fix.

**Comment by Extrimis** [comment]
> Or we could just use acrylic on Windows 10 and manually use the Mica composition API on 11, until WinUI 2 ships a fix.

Ya its the better option than trusting private Api

**Comment by lhak** [comment]
I added some code implementing mica as a composition brush in the linked app window related issue.

**Comment by sylveon** [comment]
Unfortunately, this code does not help because I use C++

**Comment by sylveon** [comment]
No, it does not help, as composition attributes are ignored by XAML islands.

**Comment by sylveon** [comment]
Any update on this? @StephenLPeters @jevansaks 

It's been well over a year and I still cannot use Mica.

**Comment by sylveon** [comment]
Bump, still an issue

**Comment by DmitriyKomin** [comment]
Just wanted to add context for closure - this is in WinUI2-specific Mica implementation, and unfortunately we are unable to investigate most WinUI2-only issues due to the current focus on WinUI3 (more on the policy [here](https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/contribution_handling.md#winui-2)). If this is a blocker, please consider migration to WinAppSDK where [MicaBackdrop](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.media.micabackdrop?view=windows-app-sdk-1.4) provides fully-featured support for this material.
