### ISSUE TITLE
Question: Is .NET Native dead?

### ISSUE THREAD

**Issue by HppZ** [microsoft/microsoft-ui-xaml#5398]

**Comment by Marv51** [comment]
Maybe someone from Microsoft can post an official reply, but this is what my understanding is:

.NET Native is a technology enabling native ahead of time compilation of .net code. .NET Native was not updated for dotnet core 3.x (in 2019) and it does not sound like it will be updated anytime soon. But since UWP/.NET Native is a part of Windows 10 and 11 I would expect it to be supported for the near future (at least 2025).

True [AOT compilation](https://github.com/dotnet/runtimelab/tree/feature/NativeAOT#readme) is coming back to .NET (for real this time) with .NET 7 next year. Whether that can then be used in WinUI is [unclear ](https://github.com/dotnet/runtimelab/issues/306)to me.

**Comment by StephenLPeters** [comment]
@MikeHillberg and @ryandemopoulos fyi

**Comment by iloxmn** [comment]
Why is it still open? This is a simple question. And we just want a official respond because it's clearly dead.

**Comment by DominicMaas** [comment]
> Why is it still open? This is a simple question. And we just want a official respond because it's clearly dead.

From my understanding, .NET Native (CoreRT) has become NativeAOT (for .NET 7)
