### ISSUE TITLE
WinUI 3: ICustomProperty members are not called

### ISSUE THREAD

**Issue by xperiandri** [microsoft/microsoft-ui-xaml#5402]
I implemented `ICustomPropertyProvider` and `ICustomProperty` for my view model set to `DataContext`.
On WinUI 3 `ICustomPropertyProvider` returns `ICustomProperty` implementation for each property but `ICustomProperty` members are never called. Hence UI is empty.

**Steps to reproduce the bug**
1. Clone https://github.com/xperiandri/Elmish.Uno
2. Check-out `uno_winui` branch
3. Launch `Samples.Windows.Package` project
4. Navigate no any page using the list on the main page

**Expected behavior**
WinUI calls `Getter`'s of `ICustomProperty` instances

**Screenshots**
![image](https://user-images.githubusercontent.com/2365592/124944140-c04ae180-e015-11eb-853f-a658bd15c9f4.png)

**Version Info**

NuGet package version: 
[WinUI 3 - Windows App SDK 0.8: 0.8.0] If you're seeing your issue in older previews of WinUI 3, please try this release.

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| No | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)        | Yes |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

@chiaramooney

**Comment by StephenLPeters** [comment]
@alwu-msft Do you know much about ICustomPropertyProvider and its associated types?

**Comment by alwu-msft** [comment]
@xperiandri Just as a disclaimer, I don't have any experience working with F# code and I'm inexplicably unable to set breakpoints on your `ICustomPropertyProvider` implementation, so apologies in advance for asking stupid questions. 

Were you able to verify that the `ICustomPropertyProvider` implementation's methods were being invoked? My instinctive thought is that WinUI is unable to determine that your custom types implement `ICustomPropertyProvider` or `ICustomProperty`, which then leads me to ask how you're generating a F# WinRT projection; a missing WinRT projection would exhibit similar behavior to what you're seeing.

**Comment by xperiandri** [comment]
According to MSFT presentation from Windows Developer TAP program from November 2020 and https://github.com/microsoft/CsWinRT/issues/602 C# WinRT team state that in .NET 5 interoperability with WinRT is language agnostic

**Comment by xperiandri** [comment]
> Were you able to verify that the ICustomPropertyProvider implementation's methods were being invoked?

Yes, of you set a breakpoint

**Comment by xperiandri** [comment]
But in src/Elmish.Uno/DynamicCustomProperty.fs on line

**Comment by xperiandri** [comment]
The overall implementation is `uno_winui` is implementation the same as in `develop` in

**Comment by alwu-msft** [comment]
> The overall implementation is `uno_winui` is implementation the same as in `develop` in src/Elmish.Uno.Uwp/ViewModel.cs

Presumably the C# version of this scenario works as expected?

**Comment by xperiandri** [comment]
After all since yesterday, yes it works as expected. But it is compiled for UWP, not WinUI .NET 5

**Comment by alwu-msft** [comment]
Yeah, you're correct that Elmish.Uno.Uwp wouldn't be an analogous scenario because .NET Native has built-in WinRT projection support.

@Scottj1s Is CsWinrt projection generation truly language-agnostic? I'm trying to understand why WinUI would be able to successfully QI for an interface on one F# class ([ViewModel](https://github.com/xperiandri/Elmish.Uno/blob/uno_winui/src/Elmish.Uno/ViewModel.fs)) but not another one ([DynamicCustomProperty](https://github.com/xperiandri/Elmish.Uno/blob/uno_winui/src/Elmish.Uno/DynamicCustomProperty.fs)). The best wild guess I can come up with is that the act of assigning an instance of `ViewModel` to the `DataContext` property on the CsWinrt projection of a WinUI class (e.g. `Frame`) causes the F# object to be put inside some kind of CsWinrt wrapper type, and so when WinUI QIs for `ICustomPropertyProvider` the CsWinrt wrapper is able to find and return it. However, I assume that there isn't a true WinRT projection for the `ViewModel` class, so when it in turn returns an instance of `DynamicCustomProperty`, CsWinrt doesn't come into play at all so naturally WinUI is unable to QI it for `ICustomProperty`. Is this a case where they simply need to manually register a bunch of type mappings with CsWinrt? Or are the missing pieces more fundamental than that?

**Comment by xperiandri** [comment]
Any updates?

**Comment by alwu-msft** [comment]
@xperiandri You're correct that because CsWinrt generates CLS-compliant code any .NET language (including F# as you know) is able to *consume* the WinRT projections that it produces. However, that is only part of the WinRT interop story; in order for a pure F# class to advertise that it implements a WinRT interface (e.g. `ICustomProperty`) and have that interface be discoverable/invokable by a WinRT component (e.g. WinUI 3), there needs to be a mapping from the F# class to its WinRT projection. For C# classes, this is done automagically by the CsWinrt machinery, but as there is no equivalent FsWinrt for F# you would have to roll your own solution. Your `ViewModel` class is working by happenstance; assigning it to the projected `FrameworkElement.DataContext` property causes it to be marshalled in a way that appears to allow its `ICustomPropertyProvider` implementation to be discoverable by WinUI, but this is pretty specific case.

You may be able to take advantage of CsWinrt APIs to minimize the amount of code you need to write yourself, but ultimately full F# WinRT interop is simply not a scenario that we currently support (#740 is the proposal to address that).

**Comment by xperiandri** [comment]
@alwu-msft so what do I need to implement manually as a current workaround in order to make it work?

**Comment by alwu-msft** [comment]
To be honest, I couldn't say because I'm very much not an expert in the area. You may be able to glean enough information from the [CsWinRT documentation](https://github.com/microsoft/CsWinRT/tree/master/docs) to determine what gaps need to be filled in.

I'm going to close this issue because this scenario requires F# support for which is already tracked by an existing issue.
