### ISSUE TITLE
DefaultBreadcrumbBarItemStyle is not accessible to customize

### ISSUE THREAD

**Issue by ranjeshj** [microsoft/microsoft-ui-xaml#5455]
DefaultBreadcrumbBarItemStyle needs to be defined in theme resources file.

**Comment by StephenLPeters** [comment]
This is true for the majority of styles for controls authored in Winui2.  However you can just use the default style merging to accomplish customization. ie:

<Style TargetType="BreadcrumbBarItem">
    <Setter Property="Background" Value="Red"/>
</Style>

This style will be merged with the DefaultBreadcrumbBarItemStyle automatically because it is the metadata defined default style.

What scenario does adding it to the theme resources enable?
