### ISSUE TITLE
`Opacity` does not behave correctly

### ISSUE THREAD

**Issue by MartinZikmund** [microsoft/microsoft-ui-xaml#5464]
**Describe the bug**

Noticed by @VitezslavImrysek 🚀

When a parent has an `Opacity` applied to it, it is not applied to the "rendered" version of the contained children, which causes unexpected visual behavior.

**Steps to reproduce the bug**

```
<Canvas Width="300" Height="300" Opacity="0.5">
    <Rectangle Width="100" Height="100" Fill="Red" />
    <Rectangle Canvas.Left="50" Canvas.Top="50" Width="100" Height="100" Fill="Red" />
</Canvas>
```

**WinUI**

![image](https://user-images.githubusercontent.com/1075116/125657745-80b60f17-637c-40a4-9547-29b059ecba72.png)

**WPF**

![image](https://user-images.githubusercontent.com/1075116/125657762-e2c33dbb-c7db-4fb1-9f62-188f13a50013.png)

**Expected behavior**

The WPF behavior is the correct one, as the `Rectangles` are fully opaque so it does not make sense for them to create any kind of "overlap" area when their parent is semi-transparent.

**Screenshots**

See above.

**Version Info**

NuGet package version: 2.6.1

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
This is a Composition setting called OpacityMode, there are two options, push-down and Layered.  Pushdown opacity is significantly more efficient as the system simply multiplies numbers together to get the final opacity value for a pixel. Where as the layered opacity, which is what you are asking for, involves rendering all of the visuals on the same layer to a surface and then applying that opacity to that surface, and inserting that subrendered surface into the tree.

UWP xaml made the decision to always use push-down opacity for the performance benefits, there unfortunately isn't a way to change this and is by design.

**Comment by StephenLPeters** [comment]
@gegao18 @codendone and @adadi-MS Could expand on my explanation if I got something wrong.

**Comment by StephenLPeters** [comment]
@MikeHillberg for the Wpf mismatch
