### ISSUE TITLE
Window caption is hidden but still active after setting ExtendsContentIntoTitleBar

### ISSUE THREAD

**Issue by un-tone** [microsoft/microsoft-ui-xaml#5528]
**Describe the bug**

After setting the Window's property ExtendsContentIntoTitleBar, the window caption is hidden but still exists in some small area at the top of the window.

**Steps to reproduce the bug**

1. Create a MAUI application using the ".NET MAUI app" VS template (with Blazor also works)
1. Go to `App.xaml.cs` in WinUI project
1. Set `MainWindow.ExtendsContentIntoTitleBar = true;` in `OnLaunched` method
1. Run the app and try to drag the window by pressing on this area:
![image](https://user-images.githubusercontent.com/1625378/126517040-81804e29-14a0-4953-94eb-4eb6f533424d.png)
The dragging works. Moreover, the window's caption context menu works also (see the screenshot below).

**Expected behavior**
The window's caption should not be active in any way when `ExtendsContentIntoTitleBar ` is true. The dragging should not work nor does the context menu.

**Screenshots**
![image](https://user-images.githubusercontent.com/1625378/126517592-69982b3e-202e-4cec-9a16-c888a297a032.png)

**Version Info**

NuGet package version: 
Microsoft.ProjectReunion.WinUI 0.8.1

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| 21H1 (19043.1110)        | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
@Austin-Lamb and @pratikone FYI

**Comment by pratikone** [comment]
If I understand the app scenario correctly, there are 2 things happening here : 
1. You are setting MainWindow.ExtendsContentIntoTitleBar = true; but not providing a custom titlebar. In this case, the app creates its own default custom titlebar and places it next to min/max/close buttons.   Exactly at the same spot you have marked.
2. However, you cannot see it or min/max/close buttons because you may have been drawing color over them. The min/max/close and the default titlebar are below in z order to the content of the app. So if you set Grid or StackPanel as top most element in your app and set its background color. It will cover them up. So, if you stop setting background color on topmost uielement, it will show up.

https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.window.settitlebar?view=winui-3.0 details this and shows workarounds to have proper theming in the app.
