### ISSUE TITLE
The InputScope property of NumberBox control is not showing suggestions

### ISSUE THREAD

**Issue by ssaran046** [microsoft/microsoft-ui-xaml#5569]
**Describe the bug**

The InputScope property of NumberBox control is not showing suggestions, but InputScope of TextBox control does show suggestions.

**Steps to reproduce the bug**

1. Create UWP with TextBox and NumberBox control.
2. Set the value to TextBox InputScope, it shows the suggestions.
3. Now, Set the value to NumberBox InputScope, but it does not show the suggestions.

**Expected behavior**

NumberBox InputScope property should show suggestions when typing the value.

**Screenshots**

TextBox

![image](https://user-images.githubusercontent.com/24865096/127307782-fb388d43-9e37-49cd-bfbe-9f56a16a3aca.png)

NumberBox

![image](https://user-images.githubusercontent.com/24865096/127307879-be3a3511-f7fd-4fae-9805-40038ee74cd3.png)

**Version Info**

NuGet package version: 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by mrlacey** [comment]
The `NumberBox` control is a customized version of  (& inherits from)`TextBox`. 
`NumberBox` sets the `InputScope` of the underlying `TextBox` to `Number` and this is not expected to be overridden. Because of this, it does not make sense to present options in the XAML editor.

What are you trying to do with a NumebrBox where it makes sense to use a different InputScope?
If there's a good reason to do something different it may make sense to change the way NumberBox works but I don't think exposing all the available InputScopes via IntelliSense is a good idea.

X-Ref: https://docs.microsoft.com/en-us/windows/apps/design/controls/number-box#input-scope

**Comment by StephenLPeters** [comment]
I think that some input scopes other than number that make sense, like CurrencyAmount, but not all..

**Comment by ssaran046** [comment]
Hi, we can give all the values of InputScopeName to NumberBox, then why we should not show sugesstions to InputScope property.

**Comment by StephenLPeters** [comment]
Because it doesn't really make sense for what a numberbox is intended to do. What is your scenario?

**Comment by ssaran046** [comment]
Some input scope names are applicable for NumberBox like CurrencyAmount, CurrencyAmountSymbol, NumericPin, Numeric. Whenever we set value for input scope, we needs to be typed manually. I excpect suggestion for NumberBox InputScope value as like TextBox. NumberBox allows to give all type of input scope by entering the value manually, then why we not to show suggestion for all type of input scope values even if it allows to manually enter all type of input scopes.

**Comment by StephenLPeters** [comment]
@fabiant3 and @alwu-msft is there anyway to filter the intellisense to do this?

**Comment by alwu-msft** [comment]
*Filtering* likely isn't possible, but it might be possible for us to indicate that Intellisense should prioritize certain suggestions. I don't know why there are no suggestions at all, but it might be due to `NumberBox` not being listed in the (hard-coded) table that VS uses to drive XAML Intellisense suggestions.

**Comment by mrlacey** [comment]
Oh, if only XAML intellisense was extensible....

**Comment by robloo** [comment]
> NumberBox sets the InputScope of the underlying TextBox to Number and this is not expected to be overridden. 

The `InputScope` property for NumberBox was specifically added so this could be customized. @StephenLPeters is correct that several other values besides `Number` make sense. This was all discussed here: https://github.com/microsoft/microsoft-ui-xaml/issues/2710

>Entries that require numerical-only input:
>`CurrencyAmount`, `CurrencyAmountAndSymbol`, `DateDayNumber`, `DateMonthNumber`, `DateYear`, `TimeHour`, `TimeMinutesOrSeconds`, `Digits`, `Number`, `NumberFullWidth`, `NumericPassword`, `NumericPin`, `TelephoneAreaCode`, `TelephoneCountryCode`, `TelephoneLocalNumber`, `TelephoneNumber`

There were issues implementing the `InputScope` property on NumberBox. The TextBox is doing something strange I wasn't able to duplicate. Investigated here: https://github.com/microsoft/microsoft-ui-xaml/pull/3186#issuecomment-696484755 in the original PR.

I'm guessing there is some specialized code at work some place. This is likely related to or the root cause of this Intellisense issue as well. The related bug report is https://github.com/microsoft/microsoft-ui-xaml/issues/3333.

**Comment by mdtauk** [comment]
Shame you can't disable inherited properties
