### ISSUE TITLE
ListViewItemForegroundSelectedPointerOver Resource Not working

### ISSUE THREAD

**Issue by AtosNicoS** [microsoft/microsoft-ui-xaml#5582]
Coming back from https://github.com/microsoft/microsoft-ui-xaml/issues/4939 it seems that `ListViewItemForegroundSelectedPointerOver` Is still not working for me with the latest 2.6.1 nuget package. 

I am setting the following styles:
```xaml
<ListViewItem.Resources>
    <SolidColorBrush x:Key="ListViewItemForeground" Color="Red" />
    <SolidColorBrush x:Key="ListViewItemForegroundSelected" Color="Blue" />
    <SolidColorBrush x:Key="ListViewItemForegroundPointerOver" Color="Green" />
    <!--TODO: This is not working -->
    <SolidColorBrush x:Key="ListViewItemForegroundSelectedPointerOver" Color="Orange" />
</ListViewItem.Resources>
```

**Comment by StephenLPeters** [comment]
ListViewItem's default template is very specialized in order to get the most performance possible due to the extremely large number of elements we expect in many list views.  As a result the default template doesn't and wont use this property, and there is unfortunately not a way to change it.  If you need to change this property you can use the expanded template here: https://github.com/microsoft/microsoft-ui-xaml/blob/9052972906c8a0a1b6cb5d5c61b27d6d27cd7f11/dev/CommonStyles/ListViewItem_themeresources_21h1.xaml#L325 however this will come at the cost of performance.

**Comment by AtosNicoS** [comment]
Hi,
I just tried that out with winui3 1.0.3 but it seems that when I set a new style the application crashes with "Xaml parsing failed". This is the syntax I use: `Style="{ThemeResource DefaultListViewItemStyle}"`

**Comment by AtosNicoS** [comment]
Sorry, I found the issue. I applied the style to the ListView not the inner ListViewItem. It now works.

It seems the `DefaultListViewItemStyle` itself has changed now (on the left is this vertical bar), but the `ListViewItemExpanded` looks like the old one from older uwp. Will this change soon to, or is there also the old `DefaultListViewItemStyle` without the slower expanded version?
