### ISSUE TITLE
MenuFlyoutItem-icon is not greyed out when set to disabled.

### ISSUE THREAD

**Issue by niels9001** [Microsoft/microsoft-ui-xaml#56]
**Describe the bug**

**Steps to reproduce the bug**

1. Create a MenuFlyout on e.g. a ListView
2. Set the MenuFlyoutItem to Disabled via code behind.
3. Icon is not greyed out, the text label is.

Code:
` <MenuFlyout>
                <MenuFlyoutItem Text="This is a text label">
                    <MenuFlyoutItem.Icon>
                        <FontIcon Glyph="&#xE9A1;" />
                    </MenuFlyoutItem.Icon>
                </MenuFlyoutItem>
            </MenuFlyout>`

**Expected behavior**
The icon should be greyed out when disabled, just like the text label.

**Screenshots**
![groupedcombobox](https://i.ibb.co/gRCVwC6/Error.png)

**Version Info**

NuGet package version: 

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [ ] October 2018 Update (17763)
- [X] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by jevansaks** [comment]
@llongley This sounds very familiar, did we fix this in RS5?

**Comment by jevansaks** [comment]
I can confirm this is fixed in latest insider builds and the style for MenuFlyoutItem with this fix is in the Microsoft.UI.Xaml nuget package so if you grab the latest (https://www.nuget.org/packages/Microsoft.UI.Xaml/absoluteLatest) you will see the fix there.

![image](https://user-images.githubusercontent.com/20667023/55113301-fc9fe100-509b-11e9-9d94-9e39008b2677.png)
