### ISSUE TITLE
How to create a floating bar like XboxGameBar

### ISSUE THREAD

**Issue by krulci** [microsoft/microsoft-ui-xaml#5611]
I can't seem to find source code for XboxGameBar. I believe the program is created in UWP as it is required by the app. How is it possible to create the gray transparency background which covers the entire screen when Win+G is activated? How is it possible to create the gamebar (the main one with a tile for settings and displays time) where the windows has no caption button (minimize, maximize, close)?

**Comment by StephenLPeters** [comment]
@MikeHillberg and @codendone Can you weigh in?

I don't think the transparent background is supported in UWP for security reasons and Gamebar as an internal application has special permissions.  (its been a while I could be wrong)

Opening a UWP in full screen mode is pretty easy: https://stackoverflow.com/questions/31758775/windows-10-universal-app-run-in-fullscreen-mode-by-default, which will remove the caption buttons.

**Comment by codendone** [comment]
@StephenLPeters is correct: Transparent UWP apps are not supported. GameBar has special capabilities.

Though it isn't supported yet, a future release of WinUI 3 may support transparent apps (when not running in UWP).

**Comment by krulci** [comment]
@StephenLPeters @StephenLPeters
But how does PowerToy's FancyZone and Run as well as the Shortcut Guide be able to accomplish this?
![image](https://user-images.githubusercontent.com/52474054/128190990-28b32b51-5e96-4d36-9fcc-f28480d5fd53.png)
![image](https://user-images.githubusercontent.com/52474054/128191156-9037efe4-9f77-450c-b86a-3811839260b9.png)
![image](https://user-images.githubusercontent.com/52474054/128191253-f0f52368-5c1c-4e14-9602-887563440dfb.png)

**Comment by StephenLPeters** [comment]
@codendone ?

**Comment by niels9001** [comment]
@krulci PowerToys only uses WinUI 2.6 for its settings app. FancyZones and Run use WPF (and the open-source ModernWPF package for its styling, so they look very much like WinUI).

@StephenLPeters @codendone is there a timeline or roadmap available so we know if/when these capabilities are coming to WinUI 3? Would be nice to have full control over the window, titlebar and window border like in WPF.

**Comment by krulci** [comment]
@niels9001 This might also indeed be how XboxGameBar accomplished to have the Gamebar transparent and without caption.
@StephenLPeters I have tried to create my app in full screen, but the caption still exists. It only allows the coverage of my background to extend to the area of caption. Could it still be impossible to create a windows without caption?

**Comment by codendone** [comment]
@niels9001 We don't have a specific timeline to share currently for these improvements to WinUI 3. Transparency and better control over window/titlebar are high on our priority list. Transparency is more urgent, since most other window and titlebar customizations are possible today even if they aren't easy (such as requiring dropping down to user32 APIs, for example).

@krulci I believe you are correct that the fullscreen mode for UWP still has a caption/titlebar sometimes. Using that API the caption/titlebar will generally be hidden when the mouse isn't near it, but it still exists and auto-shows when the mouse is near and may be visible by default when first showing a window.

**Comment by krulci** [comment]
> @niels9001 We don't have a specific timeline to share currently for these improvements to WinUI 3. Transparency and better control over window/titlebar are high on our priority list. Transparency is more urgent, since most other window and titlebar customizations are possible today even if they aren't easy (such as requiring dropping down to user32 APIs, for example).
> 
> @krulci I believe you are correct that the fullscreen mode for UWP still has a caption/titlebar sometimes. Using that API the caption/titlebar will generally be hidden when the mouse isn't near it, but it still exists and auto-shows when the mouse is near and may be visible by default when first showing a window.

Could the XboxGameBar be using Desktop Bridge? I have been researching these couple days. It seems like one can accomplish it either through XAML Island or Desktop Bridge. Specifically, I think XboxGameBar was made with Desktop Bridge. Especially after reading this post: [https://blogs.windows.com/windowsdeveloper/2017/02/01/adding-uwp-features-existing-pc-software/#IWBsyxuS7edlSyiC.97](url)

**Comment by Dealman** [comment]
While I'm sure XboxGameBar uses a far more sophisticated solution, I have made a fair share of my own overlays for various games using WPF. One public release I have available that sort of uses the same process can be found in my [StickyThumbs](https://github.com/Dealman/StickyThumbs) app.

Basically what I do is create a new window, set the window style to `None`, allow transparency and topmost. Thus it will work as a overlay for pretty much every game that runs as Windowed or Borderless Windowed. No nasty DirectX hooking required, but it likely won't work for fullscreen apps.

You'll have to set up your own logic for moving the window around and resizing, but that's done fairly easily.

As for the keybinding, you can either make your own Win32 hook or use some NuGet package like GlobalMouseKeyHook. I used to use the latter but has since created my own solution for listening to key events globally.

Also a little note regarding backgrounds, if you want a window that is perceived as fully transparent but can be interacted with - set its background as *almost* fully transparent like `#01000000`. If you set it to `#00000000` it will be fully transparent and your cursor hits won't register.

**Comment by duncanmacmichael** [comment]
Closing this issue as it appears to have been answered and has not had activity since June 2023.
