### ISSUE TITLE
Question: Is there a sample show how to use only XAML menu in a Win32 app?

### ISSUE THREAD

**Issue by ysc3839** [microsoft/microsoft-ui-xaml#5642]
It looks like the desktop of Windows 11 is using XAML menu. I want to use XAML menu in my Win32 app, but I can only find samples of embedding XAML UI in a Win32 app. (https://github.com/microsoft/Xaml-Islands-Samples)
So is there a sample show how to use only XAML menu, like Windows 11 Explorer, in a Win32 app?

**Comment by marb2000** [comment]
Not sure if I completely got your question.

Today, you can use [WinUI 2.6](https://docs.microsoft.com/en-us/windows/apps/winui/winui2/winui-2.6) that implements the Windows 11 styles, and use it in C++ Win32 apps with XAML Islands. [Here](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands-cpp) you can find instructions on how to host WinUI 2 controls inside of your Win32 app. We don't have a sample that showcases specifically the XAML MenuBar/CommandBar.

**Comment by ysc3839** [comment]
@marb2000 
> We don't have a sample that showcases specifically the XAML MenuBar/CommandBar.

That's what I need. I know there is XAML Islands. But I just want to keep my old UI, only replace the menu.

**Comment by ysc3839** [comment]
By the way I'm not talking about menu bar, I'm talking about context menu. Just like what you see when right click on the Windows 11 desktop.
![image](https://user-images.githubusercontent.com/12028138/128808300-0b7372b4-c708-4b68-a20f-47e4f19a2ed3.png)

**Comment by sylveon** [comment]
How I achieved it was by hosting an XAML island in an invisible (but always on top) child window that spans my entire window, and when I want to show a `MenuFlyout`, I call [`MenuFlyout.ShowAt`](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.menuflyout.showat?view=winrt-20348), with the position parameter being the cursor position relative to the top-left of my window's client area.

Few notes though:
- The position parameter needs to be divided by [the window's DPI](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getdpiforwindow), because the coordinate system in XAML is DPI-independent.
- Note that Windows 10 has a lot of crashing bugs with `MenuFlyout` in XAML Islands, but everything's fine in 11 (most likely because the shell started dogfooding it).
  - In Windows 10, I simply build off a normal Win32 menu by going recursively through the `MenuFlyout`'s items and making the Win32 equivalent, with the click callback using automation peers to trigger the item.
- Remember to set `ShouldConstrainToRootBounds="False"`, otherwise your menu may never appear.

Here's a small clip of it in action in a tray icon. This was achieved in a similar manner but instead of a child window that spans the entire window, I use an invisible top-level window that follows the result of `Shell_NotifyIconGetRect`. This can use a more "modern" style just by using WinUI 2.6, which wasn't a thing at the time of recording.


https://user-images.githubusercontent.com/6440374/129468207-0380590c-217a-43f6-bfe7-2463090b086f.mp4



@pjmlp the ask is about to make menus in your own app look like this without rewriting the rest of the GUI to Win32, if I understand well, not adding to the Explorer context menus.
