### ISSUE TITLE
Back Button Size to be reduced

### ISSUE THREAD

**Issue by BalaganEngg** [Microsoft/microsoft-ui-xaml#57]
![wp_ss_20181210_0002](https://user-images.githubusercontent.com/19682495/49727157-99797280-fc95-11e8-847f-25925dcfeaa8.png)
Back Button size is greater than Hamburger Menu button it not suitable for view 

This is captured on mobile 640XL using Windows Template Studio

and I also studied something About Showing Alt + Left Tool tip when hover anywhere on the app.

To avoid that Windows Template Studio Created this Line of Code at Shell page

private void OnLoaded(object sender, RoutedEventArgs e)
        {
            // Keyboard accelerators are added here to avoid showing 'Alt + left' tooltip on the page.
            // More info on tracking issue https://github.com/Microsoft/microsoft-ui-xaml/issues/8
            KeyboardAccelerators.Add(_altLeftKeyboardAccelerator);
            KeyboardAccelerators.Add(_backKeyboardAccelerator);
        }

but this code Throw an error for Mobile Application.

Please Review this Also

**Comment by sibille** [comment]
Thanks @jevansaks, I'll open an issue on WTS for the second part

**Comment by chrisglein** [comment]
The NavigationViewBackButton is set to 40x40 by its style. 24pt icon. Picked up from rs_generic.xaml.
The TogglePaneButton is set to 48x44 according to its RS2 style. 16pt icon.

Running the same app on desktop (not phone), we pick up RS5 styles and TogglePaneButton has dropped to 40x40 according to the new RS5 standard density. The NavigationViewBackButon remains at 40x40. So they match in footprint. They also match with 16pt icons.

So there are two issues: The control footprints are different. Also the back button icon size is larger.

Switching to the [2.1 prelease build](https://www.nuget.org/packages/Microsoft.UI.Xaml/2.1.190319001-prerelease) the footprint is fixed (due to downlevel density); both are 40x40. But the 24pt back button icon remains. Again, this appears to be a phone-specific difference. On desktop the icon is 16pt.

**Comment by jevansaks** [comment]
Sadly, phone is going out of support at the end of the year so unless we have a repro on a supported platform (desktop, xbox, etc) then we can't justify spending time on this.
