### ISSUE TITLE
Why is my app responsible for activating MUXC.NavigationViewPaneDisplayMode?

### ISSUE THREAD

**Issue by riverar** [microsoft/microsoft-ui-xaml#5704]
When a WinUI C# app is built, it includes a machine-generated chunk of xaml type metadata code that handles the location and activation of types in the `Microsoft.UI.Xaml` (MUX) namespace.

Microsoft also provides its own metadata provider `MUX.XamlTypeInfo.XamlControlsXamlMetaDataProvider` that is loaded into the process / appdomain. Its name seems to suggest it knows about xaml control types. Yet strangely, it does not know about them all (e.g. `prov.GetXamlType("MUXC.NavigationViewPaneDisplayMode")` fails).

Consider a developer trying to implement their own provider, specifically the `IXamlMetadataProvider.GetXamlType` method:

1. Handle all the foundational types
2. Pass MUXC requests to the `XamlControlsXamlMetaDataProvider` in charge of those
3. If step 2 fails, new up a corresponding XamlType

Looks decent, right?

But now consider that MUX also seems to rely on _feature detection_. That is, it will send down requests for types that may not exist and expect that failure to be bubbled up. So now we're in a bit of trouble with the first implementation. It assumed (via step 3) types not handled by Microsoft's provider would _always_ be the developer's responsibility, but the caller could be expecting a failure to bubble up.

Some data points:
- Requests for `MUXC.NavigationViewPaneDisplayMode` must succeed otherwise MUX will throw
- On the other hand, MUX will also request at least 10 variations of `AcrylicBrush`, swallowing any failures along the way. Some examples:
  * `Microsoft.UI.Xaml.Controls.AcrylicBrush`
  * `Microsoft.UI.Xaml.Data.AcrylicBrush`
  * `Microsoft.UI.Xaml.AcrylicBrush`
  * `Microsoft.UI.Xaml.Controls.Primitives.AcrylicBrush`
  * `Microsoft.UI.Xaml.Automation.AcrylicBrush`
  * `Microsoft.UI.Xaml.Shapes.AcrylicBrush`
  * `Microsoft.UI.Xaml.Media.Media3D.AcrylicBrush`
  * `Microsoft.UI.Xaml.Media.Imaging.AcrylicBrush`
  * `Microsoft.UI.Xaml.Media.Animation.AcrylicBrush`
  * `Microsoft.UI.Xaml.Media.AcrylicBrush`

So perhaps the developer should alter their implementation to be:
1. Handle all the foundational types
2. Pass MUXC requests to the `XamlControlsXamlMetaDataProvider` in charge of those
3. If step 2 fails, try to find/activate that type in the indicated namespace
4. If step 3 fails, bubble up the failure

Q: Is that the right thing to do? I'm concerned that responding incorrectly to the above requests could, potentially, put me into a _quirks_ mode. For example, `AcrylicBrush` could exist in multiple namespaces and I find/activate the older/wrong one too early.

Q: Why isn't `XamlControlsXamlMetaDataProvider` handling requests for its own types?

**Comment by RealTommyKlein** [comment]
Generally, every assembly (both apps and libraries) with `.xaml` files have a Xaml compiler generated metadata provider, which is capable of handling all type information needed for the `.xaml` files in that project.  Application metadata providers will also fall back to metadata providers from any referenced libraries if the app's metadata provider is missing the type information.  Ideally we would only have one metadata provider per app, but as the app project doesn't have access to the source `.xaml` files of referenced libraries to know what type information is needed by their `.xaml` files, each library needs to generate the requisite type information needed by its own `.xaml` files.  So in your example, even though `XamlControlsMetadataProvider` comes from the same assembly as `NavigationViewPaneDisplayMode`, it doesn't need to provide type information unless `NavigationViewPaneDisplayMode` was also used in one of its own `.xaml` files (if your app used `NavigationViewPaneDisplayMode`, it would generate the type information into its metadata provider instead).

So the order of operations when the WinUI framework is trying to resolve a type:

1. WinUI checks its own internal metadata for built-in framework types (e.g. `Button`) - note this should not involve calls out to `IXamlMetadataProvider` at all, the fact the framework is query'ing the metadata provider for a built-in type like `AcrylicBrush` is strange
2. WinUI checks the Xaml compiler's generated metadata provider implemented on the app object as `IXamlMetadataProvider`
    - The app's metadata provider first checks its own generated type information for the type
    - If the app's metadata provider doesn't have type information for the type, it checks metadata providers from referenced libraries as well

Also because metadata providers are expected to fall back and check other referenced metadata providers, not finding a requested type in one of them isn't necessarily an error.
