### ISSUE TITLE
Hovering over the Button with mouse, the button’s foreground changes unexpectedly

### ISSUE THREAD

**Issue by zhuxb711** [microsoft/microsoft-ui-xaml#5717]
**Describe the bug**
Hovering over the Button with mouse, the button’s foreground changes unexpectedly

**Steps to reproduce the bug**
1. Create a button in XAML and with Foreground like "Gray"
2. Run and hover you mouse on it

**Expected behavior**
Should not change the foreground color

**Screenshots**

![GIF 8-18-2021 2-56-02 PM](https://user-images.githubusercontent.com/42038175/129852140-71b81dd8-4bff-4e17-9985-ae85ded57a76.gif)

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.7.0-prerelease.210816001]
[Microsoft.UI.Xaml 2.6.1]
[Microsoft.UI.Xaml 2.6.2-prerelease.210811003]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)            | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
Example code:
```xaml
<StackPanel>
            <Button Foreground="Gray" 
                    Width="100"
                    Content="Hello"/>
            <Button Foreground="Gray"
                    Width="100"
                    Content="Hello" />
            <Button Foreground="Gray"
                    Width="100"
                    Content="Hello" />
            <Button Foreground="Gray"
                    Width="100"
                    Content="Hello" />
            <Button Foreground="Gray"
                    Width="100"
                    Content="Hello" />
            <Button Foreground="Gray"
                    Width="100"
                    Content="Hello" />
            <Button Foreground="Gray"
                    Width="100"
                    Content="Hello" />
</StackPanel>
```

**Comment by zhuxb711** [comment]
Only in dark mode. Light mode is fine.

**Comment by StephenLPeters** [comment]
Very Strange... I played around with this a bunch and can confirm that we have infact broken foregrend property's propagation with the Version2 styles of Winui2.  Confusingly though when I copy the button template into an application that is using ControlsResourcesVersion="Version1" I don't get the issue and when I copy the old template into an app using ControslResourcesVersion="Version2" I do get the issue...

This means that whatever is causing the issue is not in the changes we made to button's template.

A short term fix could be to add Foreground="{TemplateBinding Foreground}" to the button's ContentPresenter here https://github.com/microsoft/microsoft-ui-xaml/blob/eaae2ce70bcbe4b00a9ed2724c7cdbf3f09d8765/dev/CommonStyles/Button_themeresources.xaml#L155, however this fundimentally shouldn't be necessary and I think points to an underlying issue...

@ranjeshj @MikeHillberg and @jevansaks any ideas what might have gone wrong?

**Comment by zhuxb711** [comment]
Thanks, the workaround solve the issue, but it would be better if it could be fixed officially ASAP

**Comment by zhuxb711** [comment]
@StephenLPeters What caused this issue?

**Comment by eugenegff** [comment]
Bug could be reproduced since the very first commit
```
Commit: c464079156f3731165ba5068277935c8ed174207 [c464079]
Parents: 1e5f2b678f
Author: Canhua Li <licanhua@live.com>
Date: Thursday, January 7, 2021 7:22:28 PM
Committer: GitHub
Merge feature/token-experiment to master and make default style to use 2.5 (#3887)
```
when Version is set to StylesVersion::Latest rather than StylesVersion::WinUI_2dot5

**Comment by zhuxb711** [comment]
@eugenegff Well done and thanks for investigate this issue!
