### ISSUE TITLE
NumberBox and displayed keyboard

### ISSUE THREAD

**Issue by pkar70** [microsoft/microsoft-ui-xaml#5725]
`<muxc:NumberBox AcceptsExpression="True"` on phone shows only numeric keyboard - so I cannot enter any expression. In my app, this field is in seconds, and entering expression could be useful (e.g. `60*60` to enter one hour).

**Describe the bug**

**Steps to reproduce the bug**

**Expected behavior**
Keyboard with `+`, `×`, etc

**Screenshots**
`<muxc:NumberBox Name="uiZwloka" Grid.Row="4" Grid.Column="1" Width="120" Text="10" AcceptsExpression="True" SpinButtonPlacementMode="Hidden" HorizontalContentAlignment="Right"  HorizontalAlignment="Left" Minimum="10" Maximum="3600"/>`

![wp_ss_20210819_0001](https://user-images.githubusercontent.com/23451507/130055774-285279e5-a2d3-40e7-8366-e7a3d0940fb7.png)

**Version Info**

NuGet package version:  Microsoft.UI.Xaml 2.6.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)            |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |  Yes   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |
| Mobile                | Yes |

**Additional context**

**Comment by StephenLPeters** [comment]
This behavior is dictated by the [InputScope](https://docs.microsoft.com/en-us/windows/apps/design/controls/number-box#input-scope) property, which defaults to number.  You can change this property if you want a different soft keyboard to show up.  @MikeHillberg and @SavoySchuler (@ranjeshj) we might consider an auto value for the input scope so that when accepts expression is true we can use a different effective input scope.  @pkar70 without that API this is something you'll need to fix yourself by setting the API/
