### ISSUE TITLE
NavigationView - In "Minimal" mode, clicking the SelectedItem does not close the menu flyout

### ISSUE THREAD

**Issue by danbelcher-MSFT** [Microsoft/microsoft-ui-xaml#573]
**Describe the bug**

Given a NavigationView with PaneDisplayMode="LeftMinimal" and three items, clicking the SelectedItem does not close the menu flyout.

**Steps to reproduce the bug**

1. Create a NavView as described above.
2. Launch the app.
3. Open the menu.
4. Select Item 1.  Menu closes.
5. Open the menu.
6. Item 1 is selected.  Click on Item 1.

**Expected behavior**

The menu flyout closes because the user has tried to select an item.

**Version Info**

NuGet package version: **Microsoft.UI.Xaml.2.0.181018004**

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (18362)                   |  Yes   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes   |

**Comment by licanhua** [comment]
@YuliKl Do we need to minimize navview when an item is selected?
It will have problem to select any item except the 1st item when SelectionFollowsFocus is enabled.

**Comment by YuliKl** [comment]
@licanhua - We already close the pane (if it's a flyout) as soon as the user selects an item. This bug is tracking the discrepancy in behavior when selecting the currently-selected item, as opposed to one that's not already selected. Whether or not the pane closes should not depend on which item the user selected.
