### ISSUE TITLE
WinUI 3 - Use extended title bar by default with complete icon and title

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/microsoft-ui-xaml#5773]
Today WinUI 3 uses the default Win32 title bar which has a few issues as I highlighted in #5486 and doesn't look modern. When you extended content into title bar, there's nice modern caption buttons with Fluent tooltip. I think that should be the default even if ExtendsContentIntoTitleBar is false but WinUI should provide a default drag region with app's icon from the manifest and window title as well. When you set ExtendsContentIntoTitleBar as true, you'll have the same caption buttons however the default drag region with icon and title will be removed and you can set your own.

**Comment by StephenLPeters** [comment]
@pratikone and @marb2000 FYI

**Comment by fredemmott** [comment]
> Those who won't bother creating a nice looking app, will not care to ensure their by default extended titlebar will work well with content behind it, or function properly with the proper application of Transparent materials, button colours, and handling inactive states.

It feels notable that the WinUI 3 Controls Gallery app appears to have not felt that this is worth the work.

**Comment by pratikone** [comment]
the newly released WinUI3 controls gallery have WinUI Titlebar control which people can try out.

**Comment by dragonDScript** [comment]
I have to agree with Jaiganesh, if you want to provide as good developer experience as Mac does to their developers, you should at least help people learn about the modern titlebar.

**Comment by EpsiRho** [comment]
Why is this still not implemented and still unreasonable stupid in what is supposed to be considered ready for production?
Using workarounds instead of fixing missing components is not the right answer.

**Comment by Dealman** [comment]
For what it's worth, I was initially also struggling with the `TitleBar` being an absolute headache to work with. I have since started using the Template Studio extension for Visual Studio as promoted by the WinUI Gallery app.

It sets it all up for you and haven't had any issues with the TitleBar since. It even sets up a nice solution for MVVM which is a nice benefit if you like.

- It's properly extended and transparent
- Resizing works as expected
- The little VisualTree helper thingymajigger at the titlebar is interactable again
- Support for icon and title text from the get-go

I highly recommend the template studio if you're new to the WinUI framework like me, it sets up most of the soul draining stuff for you.

**Comment by TekuSP** [comment]
@Dealman That works for new projects, but my project is when it was called Project Reunion two years ago. I hoped there is one centralized taskbar, rather than custom solution, even if pre-generated.

**Comment by pratikone** [comment]
With WinAppSDK 1.4, winui 3 custom titlebar is getting a big overhaul and merging with appwindow titlebar. That leads to better defaults on using custom titlebar and it works well with all low level apis. The icon part is still not default but it is easier to create due to new app. Template Studio and Community Toolkit  will fill this gap and create good ready to use customization around custom titlebar.

**Comment by mdtauk** [comment]
> With WinAppSDK 1.4, winui 3 custom titlebar is getting a big overhaul and merging with appwindow titlebar. That leads to better defaults on using custom titlebar and it works well with all low level apis. The icon part is still not default but it is easier to create due to new api. Template Studio and Community Toolkit will fill this gap and create good ready to use customization around custom titlebar.
> 
> Since this issue is already 2 years old and already has bunch of outdated comments/suggestions which are no longer applicable, I am closing it. Feel free to open a new one for a more specific issue.

@pratikone  Do you know if this will also start to add support to the taller 40 and 48px high Titlebar, marked in the design kit as Future Tall - and as used by the Office apps.

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/7389110/e4dad81a-2dbc-48bf-9190-dcedaa3daaf7)

**Comment by pratikone** [comment]
I am not aware of any discussions related to it so no. This release is aimed at just beahvior parity between old winui3 custom titlebar and the new one merged with appwindow titlebar while providing some good defaults. For any more features, future releases can be aimed
