### ISSUE TITLE
"XAML parsing failed" - do you think this is a good description of the runtime error?

### ISSUE THREAD

**Issue by fiftin** [microsoft/microsoft-ui-xaml#5846]
How developer should looks for an error by this message? Why you can't print error details - XAML fragment, line and error reason?

**Comment by StephenLPeters** [comment]
@RealTommyKlein and @fabiant3 FYI

**Comment by RealTommyKlein** [comment]
Adding @alwu-msft (who owns the parser, but is OOF ) and @manodasanW from the CSWinRT team.  The Xaml framework does surface more detailed information, but it's getting lost when raising the exception.  It seems like CSWinRT's `WinRT.Runtime.dll`, which creates the `Microsoft.UI.Xaml.Markup.XamlParseException` exception (the `"XAML parsing failed"` error) doesn't include the more detailed information contained in the restricted error info (e.g. `"Cannot create instance of type 'Reunion10ExpCSharp.UserControl1' [Line: 12 Position: 10]"`).  Ideally the main exception message would include that additional information, since it's only accessible by looking at the debug spew from the Output window:

![winrt_information](https://user-images.githubusercontent.com/45502154/133175735-ff84000c-918e-4803-9dfa-4c29fd1a964c.png)

@manodasanW, can the `XamlParseException` [here](https://github.com/microsoft/CsWinRT/blob/7acab7ac040622b1733ebda4c2faae75166fb36f/src/WinRT.Runtime/ExceptionHelpers.cs#L147) also use the `restrictedError` string in its exception message to surface this information to developers more easily?  Thanks!

**Comment by manodasanW** [comment]
I have been looking into propagating the restricted error description as part of the exceptions we create from Marshal.GetExceptionForHR.  As part of that, I can also look at propagating it for XamlParseException.

https://github.com/microsoft/CsWinRT/issues/430

**Comment by sigmarsson** [comment]
When such Xaml Parse Error occurs, how shall we figure where exactly ? This is one of older code, which worked with a former WinUI DLL. Xaml ought to be okay.

![image](https://user-images.githubusercontent.com/43340959/165591706-307ac6aa-2f60-4a53-90d0-6a7f48b2c606.png)

**Comment by evelynwu-msft** [comment]
Closing as this morphed in #7033.
