### ISSUE TITLE
Tapped event doesn't fire for MenuFlyoutItem

### ISSUE THREAD

**Issue by HppZ** [microsoft/microsoft-ui-xaml#5861]
``` 
<Button Content="123">
  <Button.Flyout>
      <MenuFlyout>
          <MenuFlyoutItem Background="Transparent" Text="123" Tapped="UIElement_OnTapped"></MenuFlyoutItem>
      </MenuFlyout>
  </Button.Flyout>
</Button>
```

TargetPlatformVersion 19041
TargetPlatformMinVersion 17763

**Comment by StephenLPeters** [comment]
I'm not sure why the tapped event isn't firing for MenuFlyoutItem.  I even tried attaching using AddHandler with handled events too set to true.  Might have something to do with being in a popup, since button does fire the tapped event.   Is there a reason you need the tapped event instead of the Clicked event?

**Comment by HppZ** [comment]
old code uses Tapped event, it works before 17763, so I think it is a bug.

**Comment by joey-palmsens** [comment]
Is this problem fixed in the meanwhile? because on my laptop the Tapped event is also not firing but the RightTapped event does. 

```
<Button Content="Left/Right tapped test">
    <Button.Flyout>
        <MenuFlyout>
            <MenuFlyoutItem 
                Background="Transparent" 
                Text="Tap me" 
                Tapped="MenuFlyoutItem_LefTapped" 
                RightTapped="MenuFlyoutItem_RightTapped">
            </MenuFlyoutItem>
        </MenuFlyout>
    </Button.Flyout>
</Button>
```

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/132881060/b50431b4-edd0-4e9f-bead-91389720c3a5)

**Comment by joey-palmsens** [comment]
Is this problem fixed in the meanwhile? because on my laptop the Tapped event is also not firing but the RightTapped event does.

<Button Content="Left/Right tapped test">
    <Button.Flyout>
        <MenuFlyout>
            <MenuFlyoutItem 
                Background="Transparent" 
                Text="Tap me" 
                Tapped="MenuFlyoutItem_LefTapped" 
                RightTapped="MenuFlyoutItem_RightTapped">
            </MenuFlyoutItem>
        </MenuFlyout>
    </Button.Flyout>
</Button>

**Comment by kmahone** [comment]
The Click event should be used here instead of Tapped. The problem with Tapped is that it is only going to be raised by pointer input (mouse, touch, etc.) but would not be raised in the case of other ways to invoke the MenuFlyoutItem such as keyboard or with UIA via a screen reader such as Narrator. The Click event is more general than any particular input type and so it should be used in this case over Tapped. 

(In my opinion 'Click' event is poorly named, it probably should be something like 'Invoked')

**Comment by YexuanXiao** [comment]
> The Click event should be used here instead of Tapped. The problem with Tapped is that it is only going to be raised by pointer input (mouse, touch, etc.) but would not be raised in the case of other ways to invoke the MenuFlyoutItem such as keyboard or with UIA via a screen reader such as Narrator. The Click event is more general than any particular input type and so it should be used in this case over Tapped.
> 
> (In my opinion 'Click' event is poorly named, it probably should be something like 'Invoked')

I don't agree with this statement. Tapped is a universal event that is owned by any class derived from UIElement, while the Clicked event is owned by only a few classes. So I don't need to remember which classes have Tapped events. Also, the documentation clearly states that the Tapped event responds to mouse clicks, so this bug should be fixed: https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.uielement.tapped?view=windows-app-sdk-1.4
