### ISSUE TITLE
Mica BackDropMaterial not updating when RequestedTheme changes

### ISSUE THREAD

**Issue by felixse** [microsoft/microsoft-ui-xaml#5886]
**Describe the bug**
The Mica material is not toggling between light and dark theme when `RequestedTheme` of the Page to which it is applied changes.

**Steps to reproduce the bug**
1. Apply Mica to Page (`muxc:BackdropMaterial.ApplyToRootOrPageBackground="True"`)
2. Change the `RequestedTheme` Property of Page from Light to Dark

**Expected behavior**
Background changes according to the theme

**Screenshots**

**Version Info**

NuGet package version:  2.7.0-prerelease.210827001

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22454.1000)              | Yes   |
| May 2021 Update (19043)            |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by eugenegff** [comment]
I had similar issue when I set muxc:BackdropMaterial.ApplyToRootOrPageBackground="True" for control that then became Window.Content. The problem was that Mica infrastructure subscribed to the Window.Content.ActualThemeChanged event for soon-to-be-replaced Window.Content, and then lost the ability to feel theme changes.

Either do not change Window.Content, or set muxc:BackdropMaterial.ApplyToRootOrPageBackground="True" in code after completing such change.

**Comment by StephenLPeters** [comment]
@jevansaks FYI

**Comment by jevansaks** [comment]
@eugenegff  is likely correct. Unfortunately we don't have a way to do RequestedTheme for a XamlRoot so you set it on the content but then if the content changes or if you set it on a *child* of the thing that is the root, we don't know about it. 

So you need to set it on Window.Current.Content.RequestedTheme and then don't change Window.Current.Content.

**Comment by AathifMahir** [comment]
> @eugenegff is likely correct. Unfortunately we don't have a way to do RequestedTheme for a XamlRoot so you set it on the content but then if the content changes or if you set it on a _child_ of the thing that is the root, we don't know about it.
> 
> So you need to set it on Window.Current.Content.RequestedTheme and then don't change Window.Current.Content.

I didn't understand this scenario properly, would you mind explaining about this further, My app is Plagued with this issue for while now and still looking for fix

**Comment by eugenegff** [comment]
> I didn't understand this scenario properly, would you mind explaining about this further, My app is Plagued with this issue for while now and still looking for fix

Window.Current.Content holds a Frame. Your Page is a child for this frame. Mica listens to the ActualThemeChanged on the frame, so it does not see your `2. Change the RequestedTheme Property of Page from Light to Dark`, as Page is located below the root Frame. You need to change Window.Current.Content.RequestedTheme rather than Page.RequestedTheme.

I doubt that you replace Window.Current.Content, so other considerations does not apply.

**Comment by AathifMahir** [comment]
> > I didn't understand this scenario properly, would you mind explaining about this further, My app is Plagued with this issue for while now and still looking for fix
> 
> Window.Current.Content holds a Frame. Your Page is a child for this frame. Mica listens to the ActualThemeChanged on the frame, so it does not see your `2. Change the RequestedTheme Property of Page from Light to Dark`, as Page is located below the root Frame. You need to change Window.Current.Content.RequestedTheme rather than Page.RequestedTheme.
> 
> I doubt that you replace Window.Current.Content, so other considerations does not apply.

This is the code sample that i used to change the Theme, mostly similar to xamlcontrolsgallery but still noticing the issue

**Comment by AathifMahir** [comment]
@eugenegff please can you check above source code and mark what's wrong with that?

**Comment by zhuxb711** [comment]
If we want to change the color of Mica during the Theme in System Setting is changing, execute the following will lead to AccessViolationException.

```csharp
BackdropMaterial.SetApplyToRootOrPageBackground(this, false);
BackdropMaterial.SetApplyToRootOrPageBackground(this, true);
```

StackTrace show that this exception was threw in UISettings.AdvancedEffectsEnabled at SystemBackdropComponent

Anyway, my app control its own theme. I have no way to change the theme of Mica manually. So I thought I could sync when system theme is changed. But this exception was threw.

**Comment by zhuxb711** [comment]
![image](https://user-images.githubusercontent.com/42038175/136155062-c32b7503-bf9d-4b29-ba55-1664f340dd76.png)
The location where the exception was threw

**Comment by hippieZhou** [comment]
if you want apply Mica BackDropMaterial when theme changed, can use this way in your app, it's work for me:

```
public static async Task SetRequestedThemeAsync()
{
    foreach (var view in CoreApplication.Views)
    {
        await view.Dispatcher.RunAsync(CoreDispatcherPriority.Normal, () =>
        {
            if (Window.Current.Content is FrameworkElement frameworkElement)
            {
                frameworkElement.RequestedTheme = Theme;
            }
            if (Window.Current.Content is Page root)
            {
                BackdropMaterial.SetApplyToRootOrPageBackground(root, true);
            }
        });
    }
}
```

and remove this config in your page:

```
winui:BackdropMaterial.ApplyToRootOrPageBackground="True"
```

**Comment by DmitriyKomin** [comment]
Just wanted to add context for closure - this is in WinUI2-specific Mica implementation, and unfortunately we are unable to investigate most WinUI2-only issues due to the current focus on WinUI3 (more on the policy [here](https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/contribution_handling.md#winui-2)). If this is a blocker, please consider migration to WinAppSDK where [MicaBackdrop](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.media.micabackdrop?view=windows-app-sdk-1.4) provides fully-featured support for this material.
