### ISSUE TITLE
TabViewItem margin resource doesn't work properly

### ISSUE THREAD

**Issue by ghost** [microsoft/microsoft-ui-xaml#5894]
When you try to change the `TabViewSelectedItemHeaderMargin` resource, you'll notice that the overlays don't move along:
![image](https://user-images.githubusercontent.com/84711285/133639375-cae06aad-d463-4da4-a0e8-3a944547aa5d.png)
This is because the margins for the overlays are hardcoded.
One fix for that would be to also update those with each state, but it wouldn't necessarily be the best option.

A tab is technically made out of two things: the actual tab and the separator. My suggestion is to put the actual tab inside a separate grid. By doing that, you'll only need to apply the margin once, and everything inside will move together.
It would especially be useful if you could have different margins for each state, and even to animate them.

**Comment by StephenLPeters** [comment]
@chingucoding and @beervoley thoughts on this?

**Comment by chingucoding** [comment]
I'm a bit confused what "updating with each state" means here. I think the issue here is that the arcs live outside the grid that the margin get's applied to and thus get pushed outside. Moving them inside a the grid and leave only the separator outside could work here and is probably one of the better ways to solve this.
