### ISSUE TITLE
Providing custom AutomationPeer for control derived from ListView, crash the app on selected item change

### ISSUE THREAD

**Issue by Subashini2129** [microsoft/microsoft-ui-xaml#6046]
### Describe the bug

When creating a custom control that is derived from ListView, providing an AutomationPeer (by overriding OnCreateAutomationPeer) crash the application when the selected item property changes.

See following demo project:
[ListView-Crash-On-CustomAutomationPeer.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7293024/ListView-Crash-On-CustomAutomationPeer.zip)

Switching the base class of the peer to ListViewAutomationPeer fixes the crash, however not using that peer shouldn't crash the application.

### Steps to reproduce the bug

1. Run the sample.
2. Try to select any list view item.

### Expected behavior

Application should not crash on selection.

### Screenshots

![image](https://user-images.githubusercontent.com/56991221/136189191-3ce2b0f8-636e-4e59-a36f-9f8782ebdc5a.png)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

October 2020 Update (19042)

**Comment by chingucoding** [comment]
That's really strange, I think this could be because under the hood ListView or someone else has an assumption of the controls peer type. Curiosly, if you inherit from ListViewBaseAutomationPeer, a different exception get's thrown (`Catastrophic failure (0x8000FFFF (E_UNEXPECTED))`) when navigating to the ListView using Narrator.
