### ISSUE TITLE
1.0 preview2 unusable on VS 2022 Preview 4.1

### ISSUE THREAD

**Issue by martibravo** [microsoft/microsoft-ui-xaml#6067]
**Describe the bug**
I upgraded VS 2022 from 3.1 to 4.1, uninstalled 1.0 experimental and installed the WindowsAppSDK 1.0 preview2 VSIX extension. Created a Blank, Packaged WinUI in Desktop app from template and made the first run, it worked. 

Editing code with Hot Reload enabled makes VS unresponsive and I have to restart it using Task Manager. Or Hot Reload will not work at all while displaying that it's working and running.

**Steps to reproduce the bug**
1.Use latest VS 2022 preview, latest AppSDK VSIX extension.
2. Create new app from templates.
3. Try and run app with Hot Reload enabled. 
4. Edit XAML and click Hot Reload button next to the Continue button.
5. Nothing changes in the app, or VS hangs and becomes completely unresponsive. 
6. Have to restart VS from Task Manager.

**Expected behavior**
I would expect Hot Reload to work and not crash VS. It's useful when editing XAML and UI elements.

**Screenshots**

**Version Info**
WindowsAppSDK version 1.0.0-preview2
Windows 11 build 22471.

NuGet package version: 
Microsoft.WindowsAppSDK.1.0.0-preview2
Microsoft.WindowsAppRuntime.1.0-preview2_0.272.1934

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22471)              |  Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**

**Comment by MGRussell** [comment]
I am having an issue that's almost certainly related. With an identical development software environment when trying to see the Live Visual Tree I get "The WinUI 3 version used by this application is not supported for XAML Hot Reload by this version of Visual Studio. Please upgrade to the latest versions of Visual Studio and WinUI 3." 

Similarly for XAML Live Preview I get "XAML Live Preview is unavailable because either XAML Hot Reload is disabled, application execution was paused before any windows were created, or XAML Live Preview is not supported for your application."

Visual Studio version 17.0.0 Preview 4.1.
Extension Windows App SDK C# VS2022 Templates version 1.0.0.55194741
Extension Single-project MSIX PAckage Tools for VS 2022 [Preview] 0.9.10.2108302
Operation System Version 21H1 build 19043.1237

This only started happening after updating to the latest WindowsAppSDK preview extension. Everything was working fine before.
