### ISSUE TITLE
InkToolbar icons should not scale with text scaling

### ISSUE THREAD

**Issue by sanderl** [microsoft/microsoft-ui-xaml#6106]
### Describe the bug

For the default InkTookbar buttons (BallpointPen, Highlighter, etc.) the icons should not scale when text scaling is enabled. 

### Steps to reproduce the bug

1. Open Xaml Controls Gallery
2. Navigate to the InkToolbar control
3. Go to Settings->Accessibility->Text Size
4. Set the text scaling to 200.

### Expected behavior

The icons in the InkToobar buttons should not scale per the accessibility guidelines.

### Screenshots

Without text scaling:
![image](https://user-images.githubusercontent.com/46726333/137546694-5ed7621d-2357-4b65-97ab-869ea9dcae4e.png)

With text scaling:
![image](https://user-images.githubusercontent.com/46726333/137546773-28ded0dd-8bad-4ea9-a775-6eca41cccfb3.png)

### Windows app type

- [ ] UWP
- [ ] Win32

### Device form factor

Desktop

**Comment by karenbtlai** [comment]
Curious as to why InkToolBar icons specifically should not scale?

**Comment by sanderl** [comment]
> Curious as to why InkToolBar icons specifically should not scale?

Sorry for the slow reply. According to the Text Scaling documentation font icons should not scale:
"Don’t scale font-based icons or symbols
When using font-based icons for emphasis or decoration, disable scaling on these characters.

Set the IsTextScaleFactorEnabled property to false for most XAML controls."

[https://docs.microsoft.com/en-us/windows/apps/design/input/text-scaling](url)

**Comment by PPatBoyd** [comment]
> Sorry for the slow reply. According to the Text Scaling documentation font icons should not scale: "Don’t scale font-based icons or symbols When using font-based icons for emphasis or decoration, disable scaling on these characters.

I realize this has already been changed but I'm interested in your thoughts on why these buttons are decorative -- as buttons they seem functional to me, which would imply they should scale.

**Comment by sanderl** [comment]
> > Sorry for the slow reply. According to the Text Scaling documentation font icons should not scale: "Don’t scale font-based icons or symbols When using font-based icons for emphasis or decoration, disable scaling on these characters.
> 
> I realize this has already been changed but I'm interested in your thoughts on why these buttons are decorative. As buttons they seem functional to me, as well as not font-based -- which would imply they should scale.

This issue was flagged in our app by the accessibility team. I think the main issue is the crowding in the button which makes it very difficult to see the down arrow in the button when text scaling is on.

**Comment by PPatBoyd** [comment]
> > I realize this has already been changed but I'm interested in your thoughts on why these buttons are decorative. As buttons they seem functional to me, as well as not font-based -- which would imply they should scale.
> 
> This issue was flagged in our app by the accessibility team. I think the main issue is the crowding in the button which makes it very difficult to see the down arrow in the button when text scaling is on.

Ahhh, our a11y team has been flagging icon-only buttons for not scaling -- then I stumbled my here😄 

Leaving that aside it seems like the down chevron is aligning differently at each scale and layout adjustments could fix the crowding while keeping the scaling and the same button size.  I'm no designer but drew in mspaint what said adjustments could end up looking like if we:

- lowered the chevron to bottom-align with its original position (dark and light blue indicators)
- lowered it further for less crowding again (orange indicators)
- I'm not sure why the two icons became misaligned but nudged that too (red indicators)
- The pink indicators are present so I don't cheat-shrink the pen icon

...apologies for the barely visible markings, 1px lines...

![image](https://user-images.githubusercontent.com/41588892/172730214-e319d283-8a68-42ef-9c46-101aa5423d22.png)


Putting it out there in case it's a better fit but the a11y teams know better than I do when it's all put together (what a11y concerns arise from paddings/margins? I know we avoid crowding text elements with each other because it becomes less readable, are there similar considerations that apply here?  No idea 😶)
