### ISSUE TITLE
Platform XAML - Exception thrown "Value cannot be null." when using a converter that's implemented in native code from C#

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/microsoft-ui-xaml#6319]
### Describe the bug

When using a XAML converter that's implemented in native code (C++/WinRT) from C#, an ArgumentNullException is thrown. However, it works when using C++. This exception isn't thrown when using a converter implemented in managed code.

Markup:
`<MenuFlyoutItem IsEnabled="{x:Bind IsOnHomePage, Mode=OneWay, Converter={StaticResource BoolNegationConverter}}" />`

Full stack trace:
```
Exception thrown at 0x00007FFDD0A74F69 (KernelBase.dll) in OneToolkit.Showcase.exe: WinRT originate error - 0x80004003 : 'System.ArgumentNullException: Value cannot be null.
   at System.StubHelpers.HStringMarshaler.ConvertToNativeReference(String managed, HSTRING_HEADER* hstringHeader)
   at OneToolkit.UI.Xaml.Converters.BoolReverseConverter.Convert(Object value, Type targetType, Object parameter, String language)
   at OneToolkit.Showcase.Views.MainPage.MainPage_obj1_Bindings.Update_IsOnHomePage(Boolean obj, Int32 phase)
   at OneToolkit.Showcase.Views.MainPage.MainPage_obj1_Bindings.Update_(MainPage obj, Int32 phase)'.

```
I think the issue occurs because the generated code passes null for the string parameter:
```
private void Update_IsOnHomePage(global::System.Boolean obj, int phase)
{
    if ((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
    {
        // Views\MainPage.xaml line 41
        if (!isobj5IsEnabledDisabled)
        {
            XamlBindingSetters.Set_Windows_UI_Xaml_Controls_Control_IsEnabled(this.obj5, (global::System.Boolean)this.LookupConverter("BoolNegationConverter").Convert(obj, typeof(global::System.Boolean), null, null));
        }
    }
}
```

In the Windows Runtime, strings can't have a value of null since it's a value type unlike .NET's String type. The generated code should pass an empty string (string.Empty or "") instead.

### Steps to reproduce the bug

1. Implement a XAML converter in C++ through a Runtime Component.
2. Reference the component from a C# app and use the converter to convert a value without ConverterLanguage set.
3. See that an exception is thrown at runtime.

### Expected behavior

The converter should be usable from C# as well.

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

**Comment by StephenLPeters** [comment]
hmm @Scottj1s @RealTommyKlein I'm not sure where the issue (or if this is by design) is, thoughts?

**Comment by RealTommyKlein** [comment]
Unfortunately this is "by design" - marshalling a null string from C# to C++ throws, like you've found.  However, the generated code can't generally convert null strings to empty strings because managed developer code may make a distinction between the meaning of an empty and null string (e.g. the developer set a `null` string somewhere, binds another property to it, and that property is now the empty string instead of the null value they bound to - which would be very confusing).  Also, the Xaml compiler generally can't determine what converter is going to be used at compile/codegen time, so we wouldn't be able to conditionally use the empty string if the converter was written in C++ but being used from a C# app.

**Comment by Jaiganeshkumaran** [comment]
@RealTommyKlein Always pass string.Empty then instead of null to be safe in all cases.

**Comment by evelynwu-msft** [comment]
By design per @RealTommyKlein.
