### ISSUE TITLE
SymbolIcon can not show icon correct

### ISSUE THREAD

**Issue by 309441166** [microsoft/microsoft-ui-xaml#6392]
### Describe the bug

SymbolIcon can not show icon correct

### Steps to reproduce the bug

        <NavigationView>
            <NavigationView.MenuItems>
                <NavigationViewItem Content="hello" Icon="Accept" />
            </NavigationView.MenuItems>
        </NavigationView>

### Screenshots

![image](https://user-images.githubusercontent.com/17866395/143766665-872aab34-03d5-4a9f-b1f4-ec4225dcbff5.png)

![image](https://user-images.githubusercontent.com/17866395/143766681-33145890-ab25-46a3-a99d-1a6c15daa265.png)

### Windows app type

- [x] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

### Additional context

309441166@qq.com

**Comment by HO-COOH** [comment]
Having the same issue in WinUI3, on Windows 10 Chinese version. I guess the original post is also WinUI3 because I didn't see `muxc` namespace in the XAML code. WinUI2 is all correct on my machine. Here are some more screenshots, comparing WinUI3 vs WinUI2 control gallery.
![image](https://user-images.githubusercontent.com/42881734/148329396-6f5ebf88-6d04-4588-ae3b-f9121b2ebd3b.png)
![image](https://user-images.githubusercontent.com/42881734/148329452-c3f8f054-f674-4a9c-a139-40ab07ef3efc.png)

**Comment by StephenLPeters** [comment]
@MarissaMatt and @licanhua Thoughts on how the app language could be affecting the icon set in Winui3?  @codendone FYI

**Comment by zhuxb711** [comment]
@StephenLPeters Any workaround or ETA to fix this issue? I still see it on Windows App Sdk 1.2

**Comment by niels9001** [comment]
As @jay-o-way pointed out in the PowerToys repo, this is what'a going on:

- SymbolIcon uses glyphs from the E1-E5 range internally. This range has been deprecated and icons might render incorrectly.
- Looks like this issue only happens when Segoe Fluent Icons is installed.
- As a workaround for now, use GlyphIcon.

**Comment by Jay-o-Way** [comment]
Indeed this is a large issue and should have been done years ago: https://github.com/microsoft/microsoft-ui-xaml/issues/8375

**Comment by Jay-o-Way** [comment]
> * Looks like this issue only happens when Segoe Fluent Icons is installed.

Not exactly. Comments mention Windows 10.

**Comment by Jay-o-Way** [comment]
https://github.com/microsoft/microsoft-ui-xaml/issues/6409 (nov. '21!)
https://github.com/MicrosoftDocs/winrt-api/issues/2363

**Comment by Jay-o-Way** [comment]
@karkarl where is the source for the Symbol "assignment"?

**Comment by DJm00n** [comment]
@Jay-o-Way I believe it is from deprecated Segoe UI Symbol font:
>With the release of Windows 10, the Segoe MDL2 Assets font replaced the Windows 8/8.1 Segoe UI Symbol icon font. Segoe UI Symbol will still be available as a "legacy" resource, but we recommend updating your app to use the new Segoe MDL2 Assets.

https://learn.microsoft.com/en-us/windows/apps/design/style/segoe-ui-symbol-font
https://learn.microsoft.com/en-us/typography/font-list/segoe-ui-symbol

**Comment by Jay-o-Way** [comment]
No. Segoe UI is for text. MDL2 is for icons, but shouldn't be hardcodes because Windows 11 uses Fluent. We've said it's not about the font, but the icon codes

**Comment by Jay-o-Way** [comment]
**SymbolIcon** is practically deprecated. See https://github.com/microsoft/microsoft-ui-xaml/issues/5887#issuecomment-1642824614
Use a **FontIcon**.

**Comment by JJBrychell** [comment]
This has been fixed internally and should be release in a release after 1.4.

**Comment by Jay-o-Way** [comment]
@JJBrychell That sounds awesome! Mind if I ask for the pr with those updates? Note that **SymbolIcon enumeration** is something different than the code points used in XAML-UI. (which was updated thanks to people like me who kept hammering on it)
