### ISSUE TITLE
TextBox right border is clipped w/ smaller Width set

### ISSUE THREAD

**Issue by adrientetar** [microsoft/microsoft-ui-xaml#641]
**Describe the bug**

TextBox right border gets clipped if a small enough (e.g. <=60) width is set:

![image](https://user-images.githubusercontent.com/1250894/57045690-b9bec380-6c6e-11e9-81a8-cbc1c2ce4987.png)

Previously reported here: https://developercommunity.visualstudio.com/content/problem/535762/uwp-textbox-width-clipping.html

**Steps to reproduce the bug**

1. Create a page and put `<TextBox AcceptsReturn="True" Width="60" />` in it
2. Visualize it

**Expected behavior**

Right border is visible.

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)                   |    |
| October 2018 Update (17763)   | X   |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | X   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by MikeHillberg** [comment]
I don't see that behavior with the repro as written. But I do see it if the width of the parent is set to 60.

I think what you're seeing is that TextBox's MinWidth is 64, so a width <=63 can cause a clip. You can fix it by setting the MinWidth smaller.

**Comment by adrientetar** [comment]
@MikeHillberg Well, I'm seeing this even is parent's width is larger, and setting MinWidth does not remove the clipping for me:

![image](https://user-images.githubusercontent.com/1250894/57059824-3b3a4400-6cb7-11e9-8fe3-98663518e07d.png)

**Comment by mrlacey** [comment]
The issue is with the definition of the internal border in `TextBox_themeresources.xaml`

_Note, the clipping described in this issue is also seen when setting a `MinHeight` less than 34._

The `Border` has the MinWidth and MinHeight using Theme Resources which can't be overridden [[source](https://github.com/Microsoft/microsoft-ui-xaml/blob/c0ca173d5667d69df1c736a79120282ed9255574/dev/CommonStyles/TextBox_themeresources.xaml#L282)]

```xml
                        <Border x:Name="BorderElement"
                            …
                            MinWidth="{ThemeResource TextControlThemeMinWidth}"
                            MinHeight="{ThemeResource TextControlThemeMinHeight}" />
```

As a temporary workaround in your app, re-templating the control with TemplateBinding to the outer properties seems to work.

```xml
        MinHeight="{TemplateBinding MinHeight}"
        MinWidth="{TemplateBinding MinWidth}"
```

You can see the consequence of changing to using TemplateBinding in the image below.

![example of border being drawn correctly in the designer when using the template bindings](https://user-images.githubusercontent.com/189547/57067392-c53dd900-6cc6-11e9-9b07-3157b14b73da.png)


I don't know the full consequences of changing this in the source though. Someone with better knowledge of the internals of this control will hopefully be able to advise.

**Comment by jevansaks** [comment]
This might have been introduced when doing compact density. What you're doing should work. @ChrisGlein to investigate.
