### ISSUE TITLE
WinUI 3: crash when UseCompactResources=true

### ISSUE THREAD

**Issue by Alovchin91** [microsoft/microsoft-ui-xaml#6432]
**Describe the bug:**

Using Windows App SDK 1.0, create a new WinUI 3 app. Add `UseCompactResources="True"` to existing `XamlControlsResources` in `App.xaml`. Run unpackaged.

_Actual result:_

Crash with the following error:

```
"Cannot locate resource from 'ms-appx:///Microsoft.UI.Xaml/Themes/compact_themeresources.xaml'. [Line: 9 Position: 81]"
```

**Version Info:**

Windows App SDK 1.0

**Comment by alejo4000** [comment]
Removing toolkit labels, as this is not an issue with the Winui 2.7 toolkit. This look slike an issue with WinUI 3/XAML.

**Comment by Alovchin91** [comment]
Is the fix for this bug planned for any release?

**Comment by kmahone** [comment]
The UseCompactResources property was meant to be an experimental-only api and was intended to only show up in experimental releases of Windows App SDK. However, the metadata was incorrectly set on this api and so it is showing up in non-experimental releases in a broken state.

Ideally, we would remove this api from the release builds, however in general we don't remove apis since that can result in compatibility issues (even for apps that are not using the api, since changing the underlying interface of the type will break the layout of the interface at the binary level). 

Since we can't remove it, I will update this api to give a better error message.

At the moment, we do not have plans to bring this api out of experimental and into the fully supported releases.

**Comment by kmahone** [comment]
The error message has been updated to be clearer here. It is unfortunate that we cannot remove this non-functioning api from the stable releases, but that would be a breaking change. If/when we bump the major version of WinAppSDK from 1.x to 2.x that would be a good opportunity to consider making breaking changes such as this.
