### ISSUE TITLE
WinUI 3: crash when UseCompactResources=true

### ISSUE THREAD

**Issue by Alovchin91** [microsoft/microsoft-ui-xaml#6458]
#### Steps to reproduce:

Using Windows App SDK 1.0, create a new WinUI 3 app. Add `UseCompactResources="True"` to existing `XamlControlsResources` in App.xaml. Run unpackaged.

#### Actual result:

Crash with the following error:

```
"Cannot locate resource from 'ms-appx:///Microsoft.UI.Xaml/Themes/compact_themeresources.xaml'. [Line: 9 Position: 81]"
```

**Comment by StephenLPeters** [comment]
The compact density styles are still in preview, I suspect they are being filtered out for the 1.0 release.  However if we are filtering out the xaml file we should also be removing the UseCompactResources API.. Since we aren't and have already shipped that API we might have to add the xaml file to the 1.0 release.  @MikeHillberg @codendone and @ryandemopoulos FYI
