### ISSUE TITLE
SplitButton will be clicked when navigating to the page using Enter key

### ISSUE THREAD

**Issue by lyf6lyf** [microsoft/microsoft-ui-xaml#6502]
### Describe the bug

We have a page that contains a auto-focus `SplitButton`. When we navigate to the page using Enter key, the button will be clicked.

### Steps to reproduce the bug

1. Clone and run [SplitButtonRepro](https://github.com/lyf6lyf/SplitButtonRepro)
2. Add break point to `Page1.Button_Click` and `Page2.SplitButton_Click`.
3. Use keyboard to navigate page 1 and page 2.
4. when open page 1, no breakpoint will be hit.
5. when open page 2, the breakpoint will be hit.

### Expected behavior

No break point should be hit when open page 2.

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Insider Build (22504)

**Comment by vgromfeld** [comment]
I think I've found the root cause of the issue: `SplitButton` is not considering the `KeyDown`/`KeyUp` events as a sequence.
The `Click` event is triggered for any `KeyUp` event (if the released key is on of the supported keys: enter...).

In the sample app, we have the following events sequence when pressing `Enter` on the `NavigationViewItem`:
- `NavigationView.KeyDown` 
- `NavigationView.ItemInvoked`
- `Page2` is displayed
- `SplitButton.GettingFocus` (`FocusState.Programmatic` is requested)
- `SplitButton.Loaded`
- `SplitButton.Focused` (`FocusState.Keyboard` is set since the action has been initiated by the keyboard)
- `SplitButton.KeyUp` (the source is the `SplitButton`)
- `SplitButton.Click`

Since we've changed the focus, the `KeyUp` event is received by the `SplitButton` which triggers its `Click` event whereas it never received any `KeyDown` event.


One mitigation is to manually register to the `PreviewKeyDown`/`PreviewKeyUp` events to properly handle the *down then up* sequence:

```cs
private void SplitButton_PreviewKeyDown(object sender, Windows.UI.Xaml.Input.KeyRoutedEventArgs e)
{
    _isKeyDown = true;
}

private void SplitButton_PreviewKeyUp(object sender, Windows.UI.Xaml.Input.KeyRoutedEventArgs e)
{
    e.Handled = !_isKeyDown;
    _isKeyDown = false;
}
```

**Comment by StephenLPeters** [comment]
Your analysis makes sense to me, another solution would be to navigate on key up instead of key down, and handle that event.

**Comment by vgromfeld** [comment]
@StephenLPeters I think this bug should remain open. The click event is triggered only for a sequence of key down/key up events for all the other controls.

**Comment by lyf6lyf** [comment]
@StephenLPeters This bug still repro in WinAppSDK 1.5. I think it should be re-opened.

**Comment by kmahone** [comment]
Reopening this issue.
