### ISSUE TITLE
CornerRadius reset to 0 when the custom style is applied

### ISSUE THREAD

**Issue by Alexander-Kamenchuk** [microsoft/microsoft-ui-xaml#6516]
### Describe the bug

CornerRadius reset to 0 when the custom style is applied

### Steps to reproduce the bug

  ```xaml
<StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center" Background="#F9F9F9">
        <StackPanel.Resources>
            <Style x:Name="AppBarRed" TargetType="AppBarButton">
                <Setter Property="Foreground" Value="DarkRed"/>
            </Style>
        </StackPanel.Resources>
        <AppBarButton Icon="Like" Label="Like" Background="Orange"/>
        <AppBarButton Icon="Dislike" Style="{StaticResource AppBarRed}" Label="Dislike" Background="Orange"/>
    </StackPanel>
```

### Expected behavior

property "CornerRadius" shouldn't change 

### Screenshots

![image](https://user-images.githubusercontent.com/80826968/147360788-61595501-09fe-4374-8dc1-955d27ebdcf7.png)

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

### Additional context
This is not only with the CommandBar button but also with other WInUI controls

**Comment by BreeceW** [comment]
I understand this to be how styling is supposed to work. To override the WinUI style instead of the system style, you need to put `BasedOn="{StaticResource DefaultAppBarButtonStyle}"` on the style, so the code would be like this:
```xaml
<Style
    x:Name="AppBarRed"
    BasedOn="{StaticResource DefaultAppBarButtonStyle}"
    TargetType="AppBarButton">
    <Setter Property="Foreground" Value="DarkRed" />
</Style>
```
and it would look like this:
![Two app bar buttons, both with rounded corners, and the one on the right has red text](https://user-images.githubusercontent.com/18747724/147374065-bf1dd2d0-b20e-46e7-bc96-1532e84da92d.png)

**Comment by StephenLPeters** [comment]
BreeceW is correct, this is how we recommend
