### ISSUE TITLE
Possible mistake in readme.txt from Microsoft.UI.Xaml NuGet Package (version 2.7.0)

### ISSUE THREAD

**Issue by johnnygerard** [microsoft/microsoft-ui-xaml#6521]
The issue relates to the overriding of resources.

The README says:

> If you have other resources, then we recommend you add those to the XamlControlsResources' MergedDictionaries.
> This works with the platform's resource system to allow overrides of the XamlControlsResources resources.

With the following XAML code snippet:

```
<Application
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:controls="using:Microsoft.UI.Xaml.Controls">
    <Application.Resources>
        <controls:XamlControlsResources>
            <controls:XamlControlsResources.MergedDictionaries>
                <!-- Other app resources here -->
            </controls:XamlControlsResources.MergedDictionaries>
        </controls:XamlControlsResources>
    </Application.Resources>
</Application>
```

If you place your app resources in the XamlControlsResources' MergedDictionaries, those resources will be overriden by the XamlControlsResources.

If the opposite effect was intented, that is to be able to override the XamlControlsResources, the following code could be used (as mentioned in [Getting started with the Windows UI 2 Library](https://docs.microsoft.com/en-us/windows/apps/winui/winui2/getting-started)):

```
<Application.Resources>
    <ResourceDictionary>
        <ResourceDictionary.MergedDictionaries>
            <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
        </ResourceDictionary.MergedDictionaries>
    </ResourceDictionary>
</Application.Resources>
```

**Comment by Panda-Sharp** [comment]
I'd suggest to clarify once and for all what's the correct way, also would be nice to provide some samples

cc https://github.com/MicrosoftDocs/windows-uwp/pull/3557

**Comment by StephenLPeters** [comment]
The code snippet in the documentation works for resources defined in ThemeDicitionaries of XCR because the lookup order is BaseDictionary->MergedDictionaries->ThemeDictionaries.  The order that you have suggested will not work because the system originates resource lookups for resources referenced in styles defined in App.xaml from the dictionary the style is defined in.  This means the system wont walk back up the dictionary tree to find the resource defined in the parent dictionary that XCR is in.
