### ISSUE TITLE
Unable to find Default style for Expander Control

### ISSUE THREAD

**Issue by hassaanmasood** [microsoft/microsoft-ui-xaml#6528]
I am using Win UI 2.7 with UWP and I want to set a MaxWidth property for all expander controls across the application by extending the default style. But the default style is not being found.  However, extending styles for other controls is working fine. Please have a look and let me know if I am making a mistake or this is an issue.

The name of the default style for expander is mentioned at:
https://github.com/microsoft/microsoft-ui-xaml/blob/release/2.7/dev/Expander/Expander.xaml

Below is the code from my App.xaml file:

```
<Application x:Class="DCS.APP.UWP.App"
			 xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
			 xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
			 xmlns:muxc="using:Microsoft.UI.Xaml.Controls"
			 xmlns:animatedvisuals="using:Microsoft.UI.Xaml.Controls.AnimatedVisuals">
	<Application.Resources>
		<ResourceDictionary>
			<ResourceDictionary.MergedDictionaries>
				<muxc:XamlControlsResources ControlsResourcesVersion="Version2"/>
			</ResourceDictionary.MergedDictionaries>
			<ResourceDictionary.ThemeDictionaries>
				<ResourceDictionary x:Key="Light">
					<SolidColorBrush x:Key="CaptionTextBlockStyle"
									 Color="Black" />
				</ResourceDictionary>
				<ResourceDictionary x:Key="Dark">
					<SolidColorBrush x:Key="CaptionTextBlockStyle"
									 Color="White" />
				</ResourceDictionary>
				<ResourceDictionary x:Key="HighContrast">
					<SolidColorBrush x:Key="CaptionTextBlockStyle"
									 Color="{ThemeResource SystemColorWindowTextColor}" />
				</ResourceDictionary>
			</ResourceDictionary.ThemeDictionaries>
			<Style TargetType="TextBox"
				   BasedOn="{StaticResource DefaultTextBoxStyle}">
				<Setter Property="BorderBrush"
						Value="{ThemeResource ComboBoxBorderBrush}" />
				<Setter Property="FontWeight"
						Value="SemiBold" />
			</Style>
			<Style TargetType="ComboBox"
				   BasedOn="{StaticResource DefaultComboBoxStyle}">
				<Setter Property="FontWeight"
						Value="SemiBold" />
			</Style>
			<Style TargetType="AutoSuggestBox"
				   BasedOn="{StaticResource DefaultAutoSuggestBoxStyle}">
				<Setter Property="FontWeight"
						Value="SemiBold" />
			</Style>
			<Style TargetType="CalendarDatePicker"
				   BasedOn="{StaticResource DefaultCalendarDatePicker}">
				<Setter Property="FontWeight"
						Value="SemiBold" />
			</Style>
			<Style x:Key="AccentIcons"
				   TargetType="FontIcon">
				<Setter Property="Foreground"
						Value="{ThemeResource SystemAccentColor}" />
			</Style>
			<Style TargetType="muxc:Expander"
				   BasedOn="{StaticResource DefaultExpanderStyle}">
				<Setter Property="MaxWidth"
						Value="1000" />
			</Style>
		</ResourceDictionary>
	</Application.Resources>
</Application>
```

**Comment by StephenLPeters** [comment]
Yeah, this is a pretty confusing issue.  The problem is that because the Expander control is authored in the winui2 package we don't have to include its style in XamlControlsResources.  It is the metadata defined default style for the control so any style that is not explicitly based on some other style will be based on the one with author in Winui2.  With the other controls in your example, they are authored in system xaml so the meta data defined default style is the one in system's generic.xaml.  So we've packaged that style in XCR with the name DefaultFooStyle so that custom styles can be based on those.  In this case you can fix your sample by just deleting the BasedOn.

I think we should maybe also include styles like these in XCR, to reduce confusions like this, however it does have a perf cost..
