### ISSUE TITLE
xaml compiler cannot find type in other project when using x:Bind in ControlTemplate

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#662]
VSF_TYPE_MARKDOWNThe control and its template its defined in VB project.
The type containing the function is defined in C# project, targets .net standard (in new sdk).
Using function binding (`{x:Bind(ns:Helpers.SomeMethod(Prop, 'arg'))}`) will cause xaml compiler to say &quot;cannot find type ns:Helpers&quot;.
Moving the helper into the same project can make it compiles.
Doing the same binding out of ControlTemplate works fine.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/510575/xaml-compiler-cannot-find-type-in-other-project-wh.html
VSTS ticketId: 832923_
_These are the original issue comments:_

Visual Studio Feedback System on 3/31/2019, 07:01 PM (35 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by stevenbrix** [comment]
The syntax for function binding is this: `{x:Bind ns:Helpers.SomeMethod(Prop, 'arg')}`

The syntax described in the bug is for casting of types, and when I use it I see different errors than what's being reported. I'll need a sample app that repros this in order to investigate this any further.

I created a repro and I see errors like this:
`  C:\Users\skirb\source\repos\WinUI3App\App1\MainPage.xaml(14,35): XamlCompiler error WMC1110: Invalid binding path '(cs2:Class1.SomeMethod('red'))' : Syntax error at symbol '('`

**Comment by danzil** [comment]
@stevenbrix (cs2:Class1.SomeMethod('red')) looks like an invalid x:Bind to me. Your function binding syntax that you said works - {x:Bind ns:Helpers.SomeMethod(Prop, 'arg')} is the way to go.

**Comment by stevenbrix** [comment]
@danzil thanks for closing this. I left this open because of the claim that the same x:Bind worked outside of a control template. But closing is more appropriate.

I'm wondering if there was missing a reference, since the bug claimed that the same code worked when moving it between projects.

I wish the vsfeedback used peoples GitHub account so we could follow up with them.

**Comment by huoyaoyuan** [comment]
@stevenbrix @danzil It was me to open the vsfeedback issue.
I can confirm all references are present, because missing reference also breaks same expression out of control template.

**Comment by stevenbrix** [comment]
> @stevenbrix @danzil It was me to open the vsfeedback issue.
> I can confirm all references are present, because missing reference also breaks same expression out of control template.

Hey @huoyaoyuan, thanks for helping us solve the mystery ☺️

Are you able to share a repro project so we can have a better understanding of what's going on? Otherwise, I'm afraid there isn't enough information in this bug report for us to move forward
