### ISSUE TITLE
WinUI 3 System.IO.Stream as Windows.Storage.Streams.IRandomAccessStream throw an exception.

### ISSUE THREAD

**Issue by xiao-cao-x** [microsoft/microsoft-ui-xaml#6658]
WinUI 3 Stream.AsRandomAccessStream throw an exception.

```cs
Stream s = await client.GetStreamAsync(url);
BitmapImage bitmap = new();
await bitmap.SetSourceAsync(s.AsRandomAccessStream());
```

exception `System.NotSupportedException:“Cannot use the specified Stream as a Windows Runtime IRandomAccessStream because this Stream does not support seeking.”`

```cs
Stream s = await client.GetStreamAsync(url);
BitmapImage bitmap = new();

MemoryStream ms = new();
s.CopyTo(ms);

await bitmap.SetSourceAsync(ms.AsRandomAccessStream());
```
exception `System.Runtime.InteropServices.COMException:“The component cannot be found. (0x88982F50)”`

**Comment by chausner** [comment]
The first exception is relatively clear. You are calling `HttpClient.GetStreamAsync` which returns the HTTP response stream which is not seekable. Your workaround of copying the stream to a `MemoryStream` seems right. You probably want to use `CopyToAsync` though to avoid blocking.

About the second exception, I am not so sure but it might be related to the fact that you are not seeking to the beginning of the stream after copying. Have you tried `ms.Seek(0, SeekOrigin.Begin)` before calling `SetSourceAsync`?

**Comment by dylech30th** [comment]
The pointer to the original stream may not be at the start position, which causes the `BitmapImge` to read corrupted data from the stream, though I'm not very sure, it seems that `The component cannot be found` mostly raised on `BitmapImage` because of the format cannot be detected (thus the image cannot be decoded), calling `ms.Seek(0, SeekOrigin.Begin)` to set the stream pointer to the start position.

**Comment by xiao-cao-x** [comment]
have already solved
