### ISSUE TITLE
Question: How to convert Mouse Screen position to Canvas relative  position?

### ISSUE THREAD

**Issue by shelllet** [microsoft/microsoft-ui-xaml#6671]
I  call win32 api  `GetCursorPos` to get mouse position.

but i don't know how to convert screen position to canvas relative postion when `KeyboardAccelerator` responsed.

**Comment by WelterDevelopment** [comment]
If you use WinUI, why don't you use the UIElement.PointerMoved event to track the cursor position relative to a UIElement (e.g. your RootGrid)?

**Comment by shelllet** [comment]
> If you use WinUI, why don't you use the UIElement.PointerMoved event to track the cursor position relative to a UIElement (e.g. your RootGrid)?

yeah, i have used [ winui3 / c++] , 
i can't do that in `PointerMoved` event , because i need to response `ctrl +v` keyboard event and pasted item to canvas at the mouse position.

**Comment by WelterDevelopment** [comment]
Yes, that is what I meant with tracking the cursor position.
``` csharp
PointerPoint CurrentPointerPoint { get; set; }

private async void Canvas_PointerMoved(object sender, PointerRoutedEventArgs e)
{
  CurrentPointerPoint = e.GetCurrentPoint(Canvas);
}
```
Then you can always get the CurrentPointerPoint(.Position) from any method you want. That's a clean solution and I even wouldn't call it a workaround, since the actual object you want to get is the canvas relative position, which GetCurrentPoint() directly delivers (as long as you don't need cursor positions outside of the canvas, for whatever reason). You can even make CurrentPointerPoint a bindable DependencyProperty to always print the current coordinates or crosshairs and stuff like that.

Considering the long-term plans of WinAppSDK and the current state of issue tracking in this repo, I wouldn't expect any actually new features to be implemented to WinUI/WinAppSDK for at least a year..

**Comment by StephenLPeters** [comment]
I think WelterDevelopment's suggestion is what I would recommend, but @MikeHillberg might have other suggestiosn as well.
