### ISSUE TITLE
Unable to customize Expander control by overriding resource keys

### ISSUE THREAD

**Issue by AndradeL** [microsoft/microsoft-ui-xaml#6688]
### Describe the bug

The Expander class API guide recommends modifying specific resource keys for customizing the look of the Expander: 
https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.expander?view=winui-2.6#remarks

When trying to do so by setting: <x:Double x:Key="ExpanderChevronGlyphSize">20</x:Double> for example, nothing changes.
Some of the resources actually works, like setting <SolidColorBrush x:Key="ExpanderChevronPointerOverBackground" Color="Red"/>

I've tried setting this properties both on the App scope and in a Page scope but none of them work.

### Steps to reproduce the bug

1. Instantiate a Expander in a Page
2. Add <x:Double x:Key="ExpanderChevronGlyphSize">20</x:Double> to Page.Resources to see if there is any change in the Expander UI.

### Expected behavior

The UI elements of the Expander that reference the resource keys should change properly, as specified in its API reference.

### Screenshots

Default chevron style is the same as when trying to customize:
![image](https://user-images.githubusercontent.com/35670657/152986156-47d1c2d3-1135-406c-ae36-6a574a02b349.png)

### NuGet package version

Microsoft.UI.Xaml 2.6.2

### Windows app type

- [X] UWP
- [ ] Win32

### Windows version

May 2021 Update (19043)

### Additional context

Processor	Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz   1.99 GHz
Installed RAM	24.0 GB (23.9 GB usable)
System type	64-bit operating system, x64-based processor

Edition	Windows 10 Enterprise
Version	21H2
OS build	19044.1466
Experience	Windows Feature Experience Pack 120.2212.3920.0

**Comment by StephenLPeters** [comment]
ExpanderChevronGlyphSize is referenced via static resource https://github.com/microsoft/microsoft-ui-xaml/blob/397647efba2406b2df2ddc37cf2225c966d63d20/dev/Expander/Expander_themeresources.xaml#L365, which unfortunately means that the UI Tree resource dictionary wont be searched (because this style is defined in your app.xaml)  Additionally the resource is defined in the base dictionary of XCR https://github.com/microsoft/microsoft-ui-xaml/blob/397647efba2406b2df2ddc37cf2225c966d63d20/dev/Expander/Expander_themeresources.xaml#L116, which means that there isn't a place in the XCR that this resource can be overrided and found by the lookup. 
We should change this resource to be referenced via theme resource so that it can be overriden at the page level. 

@AndradeL are there other resources with this control that you want to override and can't?

**Comment by AndradeL** [comment]
I've already found a way to fix this problem on my code by customizing a copy of the ControlTemplate, however I believe it's important to have it consistent with documentation specified on https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.expander?view=winui-2.6#remarks

**Comment by bogdan-patraucean** [comment]
@AndradeL can you please give me a sample? I try to remove the padding but with no succes..
