### ISSUE TITLE
Image Source Uri path(ms-appx) problem 

### ISSUE THREAD

**Issue by felinepunch** [microsoft/microsoft-ui-xaml#6800]
### Describe the bug

```<Image Name="Logo" Width="300" Source="ms-appx:///tiger.png"/>```

is working well. but
```<Image Name="Logo2" Width="300" Source="ms-appx:///images/tiger.png"/> ```
dose not show any image. (///)

```<Image Name="Logo2" Width="300" Source="ms-appx://images/tiger.png"/> ```
shows image well. (//)

https://docs.microsoft.com/en-us/windows/uwp/app-resources/uri-schemes
In this page, "ms-appx:///images/logo.png" is recommend. but '///' dosen't working.
 

### Steps to reproduce the bug

Microsoft Visual Studio Community 2022 (64-bit) 17.1.0
Create a WinUI 3 project
Make images directory
Copy a image to root and images directory
Add Image tag as described above 

### NuGet package version

WinUI 3 - Windows App SDK 1.0

### Windows app type

- [ ] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

**Comment by StephenLPeters** [comment]
@codendone putting this on rendering for the image area, but it could be a xaml parser issue @RealTommyKlein

**Comment by kflygare-gpsw** [comment]
Running into a similar issue in .xaml parsing. 2 vs 3 / seems to be necessary depending on whether the URI is done through XAML or CS binding.

```
        private static string FOLDER_LOCATION_CS = "ms-appx:///App/Assets/Folder/";
        private static string FOLDER_LOCATION_XAML = "ms-appx://App/Assets/Folder/";
```
In *.cs, the following works
`       var filterFile = await StorageFile.GetFileFromApplicationUriAsync(new Uri(FOLDER_LOCATION_CS + "jsonFile.json"));`
Using `://` results in: 
`System.Runtime.InteropServices.COMException: 'Error HRESULT E_FAIL has been returned from a call to a COM component.'`

In .xaml, binding to a string path fails to find the source if /// is used.
Using `:///` seemed to be working in both scenarios prior to packaging being introduced.

WinUI 3.0, Win11 machine

**Comment by eduardobragaxz** [comment]
I can't get local images or videos to show up with any of these examples.

**Comment by JJBrychell** [comment]
We are unable to repro this issue on 1.3 version of WinAppSdk. Using the following Xaml:

   <Image Grid.Row="0" Grid.Column="0" Name="Logo0" Width="100" Source="ms-appx:///Owl0.jpg"/>
   <Image Grid.Row="1" Grid.Column="0" Name="Logo2" Width="100" Source="ms-appx://Owl2.jpg"/>
   
   <Image Grid.Row="0" Grid.Column="1" Name="Logo1" Width="100" Source="ms-appx:///Assets/Owl1.jpg"/>
   <Image Grid.Row="1" Grid.Column="1" Name="Logo3" Width="100" Source="ms-appx://Assets/Owl3.jpg"/>

The two images that use ms-appx:/// show up correctly and the other two do not. We also attempted on a 1.1 version with the same result. It is hard to further diagnose without a complete repro since we are unable to tell if the images in the sample code mentioned are in the correct directory, have been added to the build with the appropriate build characteristics or whether images are corrupted.

We are closing this issue as No Repro, but if you find the issue still occurs and can provide us with a more complete repro, feel free to reopen it.

**Comment by IM-001** [comment]
It happens specifically for me in the case of an unpackaged app.
