### ISSUE TITLE
GetForCurrentView() shouldn't be used when the control is hosted in XamlIsland

### ISSUE THREAD

**Issue by eklipse2k8** [microsoft/microsoft-ui-xaml#687]
It looks like in 
```
bool MaterialHelper::IsFullScreenOrTabletMode()
```
GetForCurrentView() is being called which throws an 'Element not found' exception when running in a XamlIsland.

**Comment by jevansaks** [comment]
Is the exception handled? I know this code has a lot of first chance exceptions that are obnoxious to continue past in the debugger. Prior to Xaml Islands we only hit them in internal-only scenarios so it wasn't a big deal.

**Comment by eklipse2k8** [comment]
They are being catched, but I think getting trapped in the debugger is quite annoying indeed. Plus it doesn't seem like invalid and shouldn't be throwing an exception at all.

**Comment by jevansaks** [comment]
Totally understand, first chance exceptions are obnoxious. I just wanted to clarify that was the issue.

**Comment by jevansaks** [comment]
(I'll let @codendone figure out how to handle this as the WinUI version of the materials are known to not fully work in islands)

**Comment by codendone** [comment]
@chingucoding In theory this code could drop to the abi for this call, so it can handle or ignore the hresult without an exception.  DispatcherHelper's TryGetCoreApplicationCurrentView() was changed to do this.

**Comment by chingucoding** [comment]
I assume this would be something that needs to be done inside the OS? Or is this something we could achieve inside WinUI 2? Would that be the preferred solution for this issue?

**Comment by jevansaks** [comment]
@chingucoding We can do it in WinUI2 if we want to avoid the crash, you can take a look at #1434 for the strategy. Basically you need to find the ABI definition of the interface (you can find it in the SDK headers or in the C++/WinRT generated headers). Make sure to keep any parameter types that we don't call as void* to reduce the amount of ABI types you need to pull in.

In fact, now that I look at the other PR maybe you can just use the TryGetCoreApplicationCurrentView that's already there to detect this case?

**Comment by chingucoding** [comment]
I didn't know that, great that we can make this change in WinUI 2. @ranjeshj Do you think we should do this now or is this something that needs wait on anything else?

Regarding reusing the existing TryGetCoreApplicationCurrentView, I am not sure if we could use this. The documentation doesn't really state when GetCurrentView might crash and thus the helper return null. If those are the same, yes we could use this.

I've also noticed that we do some try catching in other areas too, maybe we should tackle this once holistically. Having try catches in a lot of places isn't the best in my opinion. @kmahone FYI since you were the one providing a crash free method for GtCurrentView.
