### ISSUE TITLE
Output of swap chain panel is distorted if it gets scaled to a small size

### ISSUE THREAD

**Issue by lhak** [microsoft/microsoft-ui-xaml#6919]
### Describe the bug

Adding a swap chain panel to a WinUI 3 app (using Win2D) and adapting it to the window size using a ViewBox results in distortion of the output (white flashes) if the resulting output gets too small (In my test about 1/2 of the swap chain size). This is a regression compared to using XAML islands where this does not happen.

### Steps to reproduce the bug

1. Run the attached repro project
2. Decrease window size and observe distortion 

[SwapChainPanelRepro.zip](https://github.com/microsoft/microsoft-ui-xaml/files/8395737/SwapChainPanelRepro.zip)

### Expected behavior

No distortion

### NuGet package version

WinUI 3 - Windows App SDK 1.0

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

**Comment by castorix** [comment]
This bug is still present in 1.1.0 (I did not test 1.1.1), 
but you can render the SwapChain without SwapChainPanel, with a child window (_CreateSwapChainForHwnd_) or with DirectComposition (_CreateSwapChainForComposition_, _DCompositionCreateDevice_, [IDCompositionVisual::SetContent](https://docs.microsoft.com/en-us/windows/win32/api/dcomp/nf-dcomp-idcompositionvisual-setcontent) )

**Comment by lhak** [comment]
@castorix The bug is still present in 1.1.1 and no, I cannot use your workarounds as the swapchain is put inside a XAML scrollviewer.

**Comment by lhak** [comment]
Seems that in 1.2 this was partially fixed. There is still some flicker during resizing, but it renders fine once the swapchain size stays constant.
