### ISSUE TITLE
Discussion: WinUI 3.0/Windows App SDK 1.x Tutorials On Microsoft Learn

### ISSUE THREAD

**Issue by riccardo10** [microsoft/microsoft-ui-xaml#6962]
# Discussion: WinUI 3.0 Series On Microsoft Learn

## Related Links

Hi,
WinUI and in particular, WinUI 3.0, looks very promising as a development platform, so thanks for the great work you all are doing, especially given the constraints you have to manage.
I am an experienced .net developer (15+ years) but I'm uber-new to the whole XAML/WinUI 3.0 space and ecosystem.

I am currently watching the WinUI Community Call for 16th March 2022 and want to give some feedback,

As this is all very new to me, it would be awesome if you can set up a series of tutorials for WinUI 3.0 (including its own flavour of XAML) on **Microsoft Learn**. 
That would definitely go a long way to help newbies like me who are trying to get their foot into the door. Right now, it does feel very overwhelming and it feels like it would take someone with exceptional resilience to keep pushing on.

I also think it would be wise to make a separate series on Microsoft Learn for Windows App SDK as it appears to be more low-level.

Thank you.

**Comment by kmgallahan** [comment]
Many/most old UWP tutorials, blog entries, stackoverflow posts, etc. also apply to WinUI 3.

They use the same flavor of XAML, just with a namespace switch to Microsoft.UI.XAML instead of Windows.UI.XAML.

Some differences include application lifecycle events (launching, suspension), how the main window is instantiated (no more CoreWindow), UI scheduling (new DispatcherQueue), and deployment. Covered pretty well [here](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/feature-mapping-table).

There is a blog series titled "Build your first WinUI 3 app" by MS here to help get started: 

https://blogs.windows.com/windowsdeveloper/2022/01/28/build-your-first-winui-3-app-part-1/

**Comment by RossCoeH** [comment]
Recent examples of winui 3 have been found at https://xamlbrewer.wordpress.com/
He writes clearly with sample apps that show more than just first steps. Scroll down his blog to find other apps like Master-Detail app in winui 3. I found them helpful.

**Comment by bpulliam** [comment]
Can this item be closed?
