### ISSUE TITLE
Microsoft Design involvement in WinUI 3.0 and beyond

### ISSUE THREAD

**Issue by mdtauk** [microsoft/microsoft-ui-xaml#699]
Once WinUI 3.0 goes fully open, as new feature requests come in and new controls are added.  Will any members of the Fluent/Microsoft Design teams play a role here in evaluating control designs, and try to maintain consistency with ALL Microsoft UI frameworks?

WPF, WinForms, WinUI 3.0, Fabric - these will all be open source, and updateable outside of the Windows OS.  So a new control in one, could be added to the others, and their designs adjusted to match - truly making it a single **Windows App Platform** as mentioned at Build 2019

**Comment by pag3** [comment]
If you check out the [Fluent Design System website](http://fluent.microsoft.com) or watch this year's BUILD session on [Fluent Design System: The Journey to Cross-Platform](https://mybuild.techcommunity.microsoft.com/sessions/77014) you should take away this landscape:
- The Windows UI Library ("WinUI") is the definitive source for Fluent Design System on Windows.
- The "UI Fabric" web, iOS, and Android libraries are, respectively, the definitive source for Fluent Design System on web, iOS, and Android.

As discussed in that session, the teams are working to bring greater coherence to experiences built with these libraries.  For example, progress was shown during the talk on bringing the UI Fabric Web library into greater alignment with WinUI.  You may have also noticed issues in the WinUI repo tracking bringing even more alignment from this end: https://github.com/microsoft/microsoft-ui-xaml/issues/524

You shouldn't have to wait for WinUI 3.0 per se... the design teams _already_ work closely with us on WinUI - and have since the start - to define the control designs as well as any visual, interactive, and functional updates to those designs over time. That includes improvements that come out of new feature requests from the community.

Even using WinUI 2.x you can get the latest Fluent Design styles for all controls (even the inbox controls) following the instructions in the [Getting Started guide](https://docs.microsoft.com/en-us/uwp/toolkits/winui/getting-started).

For WPF and WinForms a recommended way to take advantage of the Fluent Design System is to use WinUI via XAML Islands. That will become easier with WinUI 3.0. There are also some community projects that try to bring elements of Fluent Design System directly to those frameworks (esp. around the visual styles).

**Comment by mdtauk** [comment]
Thank you for the reply @pag3 The fact that there is a lot of overlap between Fabric Web, and Fluent UWP does lead a way to combining these different styles.

I was greatly interested and enthused to hear about plans for WinUI 3.0 - at present, WinUI 2.x does not include all controls, like the Buttons, CheckBoxes, TextFields etc.  So no behavioural changes can be implemented right now - but as the design of these controls is under the ownership of Microsoft Design teams, any proposed changes by us outsiders, would still need approval.

PWAs could appear like native experiences if the design of these controls were identical.

WPF is another odd ball, in that over time it has supported different ResourceDictionaries and designs for apps running on Windows XP Luna Blue, Green and Royale visual styles.  Which also gained Aero styles to match Vista and Windows 7.  Is now the time to add a Fluent option for WPF apps running on Windows 10?

WinForms I assume will always take their appearance from the GDI CommonControls within the Windows VisualStyle resources.  Will the now Open Source WinForms ever move to update those controls?

There are a lot of little loose threads where things could align better visually, but don't, and having a roadmap or knowing if there is an intention to bring all these designs together in the future.

The message I took from Build, is that the separation and differentiation of UWP & Win32 is ending.  As it becomes the **Windows Presentation Platform**.  So the next step surely should be trying to eliminate the differences between them.  Visual Design being the most obvious.

https://mybuild.techcommunity.microsoft.com/sessions/77008?source=sessions#top-anchor

**Comment by Felix-Dev** [comment]
> The message I took from Build, is that the separation and differentiation of UWP & Win32 is ending. As it becomes the Windows Presentation Platform. So the next step surely should be trying to eliminate the differences between them. Visual Design being the most obvious.

> XAML Islands is about bringing UWP XAML elements to these older platforms - but these platforms have native controls which could be made to fit closer to Fluent design - even if some elements like Acrylic, Motion, Touch wont be shared by all natively.

I was under the impression the [Windows Presentation Platform](https://pbs.twimg.com/media/D6B2KgAX4AAHejN.jpg:large) is realized by WinUI 3.0, enabling you to use the exact same controls in all your native Windows apps (UWP, WPF and WinForms). UWP/WinUI controls look & feel won't be ported over to exisiting WPF/WinForms controls - if you want to ship apps like those with a native Windows 10 look & feel, you **will** have to use WinUI 3.0 via XAML Islands.

It was said quite clearly that going forward WinUI will be the only source of innovation for native Win 10 design elements, so I expect WinForms/WPF to remain (largely) untouched. Looking at the commits in this repo, we see that the WinUI team is also hard at work to close gaps between Win32 controls and their UWP counterparts.

So, to my understanding, for any app in the future with Windows 10 native look & feel: Use WinUI 3.0 (instead of the in-built platform controls).

**Comment by Poopooracoocoo** [comment]
When I think about Windows UI I think about [this](https://docs.microsoft.com/en-us/windows/desktop/controls/visual-styles-overview). Windows 10 modified the buttons but even more could be changed to align so much more with Fluent. I also feel that File Explorer's dark theme wasn't done right. 

We can't just pretend everything else doesn't exist because they are all over Windows. Not even File Explorer uses WinUI. I think what @mdtauk is saying what I'm saying: they *should* all have the same style. 

i wish i could react to comments with a sad emoji
