### ISSUE TITLE
TabView Keyboard Accelerators trigger multiple times after selected TabViewItem has changed

### ISSUE THREAD

**Issue by edoust** [microsoft/microsoft-ui-xaml#7046]
### Describe the bug

Given a tabview with a keyboard accelerator (e.g. on `Ctrl+T`), after changing the selected item, the keyboard accelerator is executed multiple times

### Steps to reproduce the bug

1. Create a tabview
2. Attach a keyboard accelerator to `Ctrl+T`
3. Run the app, change the selected tabviewitem
4. Press the shortcut `Ctrl+T` and see the handler method being called twice

### Expected behavior

Keyboard accelerators should execute once

### Screenshots

![tabview](https://user-images.githubusercontent.com/6137595/166215458-e3189cdc-53ed-4769-8045-2fb082888bac.gif)

I am pressing `Ctrl+T` every time new tabs show up, after changing selection one press of Ctrl+T calls the method two times

### NuGet package version

WinUI 3 - Windows App SDK 1.0.3

### Windows app type

- [ ] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

### Additional context

Happens also on `1.1.0-preview2`

Target is `net6.0-windows10.0.22000.0`

**Comment by ndungbw** [comment]
Hi, 
I am not sure if it's a feature or bug of Windows App.
My suggestion is in your handler method, you have to set the args.Handled = true in order to avoiding being invoked twice.
Something like this:
`private void Test_Invoked(KeyboardAccelerator sender, KeyboardAcceleratorInvokedEventArgs args)
{
    //Do something
    args.Handled = true;
}`
My similar problem is solve [here](https://learn.microsoft.com/en-us/answers/questions/1145063/how-to-make-keyboardaccelerator39s-event-handler-o.html)

**Comment by gwalschlager** [comment]
I'm having essentially the same issue. I'm using a XamlUICommand that used in a context menu. If I execute the command from the context menu, the handler is called once. If executed from the keyboard using the accelerator assigned to the command, the handler is called twice.

**Comment by greatoceansoftware** [comment]
I am having the same issue. It only happens when a particular tab is opened (1 of 6). Each tab has a page that runs it's on XamlUICommand that uses the CTRL+I keyboard accelerator. As long as the offending tab/page is not opened, the keyboard accelerator works fine on the remaining 5 tabs. The command is attached to a MenuFlyoutItem on the Flyout of an AppBarButton in a CommandBar that is at the top of each page on its respective tab.

After visiting the offending tab (whether the XamlUICommand is used or not), the CTRL+I accelerator causes the respective XamlUICommands to run twice. Running them from their MenuFlyoutItems always runs correctly in all circumstances (only runs once).
