### ISSUE TITLE
👨‍💻☎ WinUI Community Call: May 18, 2022

### ISSUE THREAD

**Issue by gabbybilka** [microsoft/microsoft-ui-xaml#7116]
### https://www.youtube.com/watch?v=hor2EYnvqws

# Details
Date: May 18, 2022
Time: 16:00-17:00 UTC (9:00-10:00am Pacific)

Anyone and everyone is welcome - no pre-registration is required.
This will be an informal interactive live stream directly with members of our engineering team.

# Format
The community call is a call among the WinUI team that is live-streamed onto YouTube. We present on new updates, share information, welcome guests, and answer your questions. In this month's call, we'll be joined by several team members to give an inside look into a few of the latest features available in WinAppSDK 1.1. 

### **Agenda**
- Intro
- Latest news around WinUI 3 & WinAppSDK releases & content
- How, why, and behind the scenes for self-contained applications
- Inside look at Mica & Background Acrylic in WinUI 3 & WinAppSDK
- Overview of app Notifications in WinUI 3 apps
- Q&A

### **Q&A Code of Conduct**
- To help ensure Q&A remains beneficial for the majority of the call's developer audience, please consider whether your question could be framed so that it might be more broadly relevant to our larger developer audience by ensuring it is reasonably concise, broadly beneficial, well-suited for the fast-paced live Q&A format, or able to spark open ended discussion.  
- Please understand some questions are not well-suited for the fast-paced live Q&A format and should be filed as standalone [Discussion](https://github.com/microsoft/microsoft-ui-xaml/issues/new?assignees=&labels=discussion&template=discussion.md&title=Discussion%3A+%5Byour+discussion+title%5D) or [Question](https://github.com/microsoft/microsoft-ui-xaml/issues/new?assignees=&labels=question&template=question.md&title=Question%3A+%5Byour+question+here%5D) issues where they can be most appropriately handled. Excluding presentation topic requests, this generally includes requests for dedicated follow-ups or technically complex questions that require investigative time or expertise not included in this month's guest list.

### Leave us your questions in the comments on this issue or live in the YouTube chat during the stream!

**Comment by Samuel12321** [comment]
When will WinUI 3 Background Acrylic be supported in Windows 10?

**Comment by DominicMaas** [comment]
> When will WinUI 3 Background Acrylic be supported in Windows 10?

I can't remember where I read it (twitter?), but I'm not sure it will (apparently the technical reasons to why will be brought up on the call)

**Comment by Samuel12321** [comment]
> > When will WinUI 3 Background Acrylic be supported in Windows 10?
> 
> I can't remember where I read it (twitter?), but I'm not sure it will (apparently the technical reasons to why will be brought up on the call)

I hope this isn't the case, it would be hugely limiting for Winui3 (it would make it unusable for my team), if it doesn't perform the same on windows 10 as 11.
Windows 10 still makes up the majority of the market share.

**Comment by VoidExploiter** [comment]
We rolled out our application for our customers with WindowsAppSDK 1.0.3. The main issue we are facing is that, most of the customers don't have webview2 runtime in their machine. In that case webview2 show's "Download Edge Webview2 Runtime" with a link.

Issue 1: The link redirect to download Microsoft Edge rather than redirecting to Webview2 runtime downloader
Issue 2: Even though if a user has Chromium edge(latest update) installed it still asks the user to download the runtime library

Probable solution: Bundling the Webview2 Runtime along with app.
Issue in this solution: increases the size of the application (approximately increases by 600 MB with both x86 and x64 installer) 

Question: what's the long term solution instead of bunding it along with the app ?

![image](https://user-images.githubusercontent.com/17567708/169019593-b9c9274c-d411-4903-9f41-926b2d7b6426.png)

**Comment by kmgallahan** [comment]
@VoidExploiter Did you read the docs?

https://docs.microsoft.com/microsoft-edge/webview2/concepts/distribution

**Comment by simon-knuth** [comment]
When can we expect improvements to the title bar in WinUI 3 for scenarios with interactive elements?

- `Window.SetTitleBar()` is super easy to use, but apparently doesn't support interactive controls on top of it (e.g. a global search box or account picker)
https://github.com/microsoft/microsoft-ui-xaml/issues/6070
https://github.com/microsoft/microsoft-ui-xaml/issues/4233

- `AppWindowTitleBar.SetDragRectangles()` only works on Windows 11, is cumbersome and generates unresponsive areas if the rectangles are changed repeatedly at runtime (e.g. when the window is resized, the DPI changes or tabs are opened/closed)
https://github.com/microsoft/WindowsAppSDK/issues/1626
perhaps https://github.com/microsoft/WindowsAppSDK/issues/2453

These issues are pretty severe and I honestly wouldn't be able to release an app in this state without major changes to the visual design.

**Comment by Marv51** [comment]
Can you speak some about crash reporting?

For apps distributed outside of the store this is pretty different compared to both UWP and WPF/WinForms.

It seems it is impossible to catch some exceptions? #5221, #6153

Is a fatal native exception in a C#+WinUI app by definition a WinUI/WinAppSDK/CsWinRT bug? 
(Like it was in WPF/WinForms)

Microsoft AppCenter does not catch native exceptions and misses many managed exceptions (presumably because of the previously mentioned issues). Of those exceptions that do get reported, most are rather opaque.

If Microsoft shares diagnostic information with developers I have not been able to access that. I have added my code signing certificate to the Partner account, and joined a "Desktop Application" program, but I can't access any telemetry data. 
Can you maybe create some instructions how this should be setup?

**Comment by VoidExploiter** [comment]
> 

My bad

**Comment by Scottj1s** [comment]
> It seems it is impossible to catch some exceptions? #5221, #6153
> 
> Is a fatal native exception in a C#+WinUI app by definition a WinUI/WinAppSDK/CsWinRT bug? (Like it was in WPF/WinForms)

Yes, we have a regression in the exception handling experience in Visual Studio, relative to UWP.  It's in the backlog and we're hoping to improve things soon.  A native exception in a C# app is not always a bug in the framework (WinAppSDK/CsWinRT).  It may be breaking on first chance (given the C++/WinRT implementation of WinUI dlls).  I would look for evidence of the exception in the output tab and explicitly break on that.

**Comment by lukeblevins** [comment]
@RBrid Was the fix for TabView memory leak incorporated in the Windows platform or WinUI3 yet?

Context: https://github.com/microsoft/microsoft-ui-xaml/issues/6979

**Comment by Scottj1s** [comment]
> @RBrid Was the fix for TabView memory leak incorporated in the Windows platform or WinUI3 yet?

@lukeblevins, not sure if this is a duplicate issue, but a similar leak has been fixed in Windows App SDK 1.2 Preview 3:
https://github.com/microsoft/microsoft-ui-xaml/issues/6894#issuecomment-1101864492

**Comment by p-monteiro** [comment]
HotReload is not working when developing an app who needs elevated privileges [(Issue)](https://github.com/microsoft/WindowsAppSDK/issues/896)

Will this be fixed in 1.1?

**Comment by marb2000** [comment]
<< The previous comment was deleted for not following the [code of conduct](https://github.com/microsoft/microsoft-ui-xaml/blob/main/CODE_OF_CONDUCT.md). >>

**Comment by lukeblevins** [comment]
@Scottj1s I didn't think previews of 1.2 were available yet, let alone 1.2 Preview 3.

In any case, on 1.1 Preview 3, the issue with `TabView` *is not* fixed. Having any kind of complex visual tree for the item's `Content` or `ContentTemplate` results in it not being freed from memory once closed. In fact, opening multiple tabs that should share the same ContentTemplate and selecting each of them seems to recreate a visual tree upon each selection because memory usage goes up each time. 

The last bit of info I heard was from @RBrid and it was confirmed to be fixed in WASDK and the platform with an OS servicing release dated for May 17th.

**Comment by mrlacey** [comment]
June call details?

**Comment by gabbybilka** [comment]
> How come the invitation for the past community call was posted mere hours before the call and not (at least several) days in advance?

@artkat Last month, we were still finalizing the agenda until the post date, and I made the (incorrect) call to wait to post the issue until it was fully confirmed. Not making the same mistake this month ⬇️

> June call details?

@mrlacey June's call discussion is available here: https://github.com/microsoft/microsoft-ui-xaml/issues/7209
