### ISSUE TITLE
Elements in custom title bar are not drawn when a background colour is specified

### ISSUE THREAD

**Issue by knightmeister** [microsoft/microsoft-ui-xaml#7125]
### Describe the bug

There are a lot of issues with custom titlebars, but this one "takes the cake".

I have some elements in a custom title bar - the app name and a search box. This was working and rendering correctly, until the last day or so. The app name and search box are now no longer rendering, all that can be seen is the application background. There have been no code changes or configuration changes at all.

~~In troubleshooting this, I've had two other users run the package on their system and it displays as intended. I even created a new user account on my PC and it displays.~~

**Update** In investigating this, the issue occurs after applying custom titlebar background colours as documented at https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.window.settitlebar?view=winui-3.0#colors 

This was working for me for months up until 4-5 days ago, something has updated somewhere in the stack that has broken this.

What could possibly cause this to happen?

I'm using the Windows App SDK 1.0 templates in Visual Studio 2022 current stable (17.2).

The close/min/max buttons draw as they should, are functional and the window can be dragged. The custom elements just aren't being drawn.

### Steps to reproduce the bug

Sorry, I can't give a reproduction to this. The issue is not easily reproducible, but something has changed in the operating system to break this.

### Expected behavior

Custom titlebar draws.

### NuGet package version

1.0.0

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022

**Comment by pratikone** [comment]
Hi, sorry for the confusion. We are in process of updating our docs so new information is not up there. 

You don't need to set `WindowCaptionBackground`. You can just set it to `Transparent` and set background color property on uielement which is set as titlebar.  That way it won't paint over your titlebar's contents.

**Comment by riverar** [comment]
@pratikone Can we re-open this? Why does changing the `WindowCaptionBackground` brush not work properly here? Appreciate you provided a _workaround_ but there's a bug here right?

**Comment by pratikone** [comment]
@riverar as of now, it is a design limitation since 1.0 release of winappsdk. We are moving away from using `WindowCaptionBackground ` for theming. it only exists for backward compat. before,  there were a lot of bugs where app content was covering up min/max/close buttons because they were lower in z order in visibility, hence i had to change the design so that min max close and its background area which is determined by `WindowCaptionBackground ` remains highest in z-order. this is a side effect of that.  It cannot be changed without any alternative design implementation.

As of now, I am working on a solution which merges winappsdk titlebar with winui3 custom titlebar. with that approach, a lot of problems like these will get resolved. however, we will still be moving away from using `WindowCaptionBackground` for coloring the titlebar.

**Comment by riverar** [comment]
@pratikone Got it, thanks for the background!

**Comment by symonxdd** [comment]
Can I ask why this is closed when it's still not fixed in the latest SDK? I still can't set the title bar, when overwriting these in App.xaml:

```cs
<SolidColorBrush x:Key="WindowCaptionBackground" Color="#121212"/>
<SolidColorBrush x:Key="WindowCaptionBackgroundDisabled" Color="#121212"/>
```

![image](https://user-images.githubusercontent.com/45405238/225803744-4a04c0f1-92c7-445e-8f10-429b59b7b58a.png)
