### ISSUE TITLE
Question: How to use user controls from another project in published app?

### ISSUE THREAD

**Issue by Iris0905** [microsoft/microsoft-ui-xaml#7233]
I created a shared WinUI 3 class library project for some user controls, and added the shared project as a reference to the main project (unpackaged). It works fine when building and running from visual studio, or running from the bin folder. But after publishing the main project, the published app could not load those user controls anymore. A "XAML parsing failed" exception was thrown. 

Looking into the content of the shared project dll in the publish folder, the user control looks for the xaml file like this:

```
        /// <summary>
        /// InitializeComponent()
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 1.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void InitializeComponent()
        {
            if (_contentLoaded)
                return;

            _contentLoaded = true;

            global::System.Uri resourceLocator = new global::System.Uri("ms-appx:///SharedProject/MyControl.xaml");
            global::Microsoft.UI.Xaml.Application.LoadComponent(this, resourceLocator, global::Microsoft.UI.Xaml.Controls.Primitives.ComponentResourceLocation.Nested);
        }
```

This SharedProject/MyControl.xaml file exists in the bin folder but is not included in the publish folder. I could get the published app work by copying it over, but it's not a good idea to deliver raw code files to customers. Any suggestions?

**Comment by MEK3DK** [comment]
As reported in many other bugs you can't do it.
I know it is difficult to believe since this has been something you could do for 20+ years in other frameworks, but for now it does not work.

There are many, but examples of other bugs like this one: 
[How to link WinUI library](https://github.com/microsoft/microsoft-ui-xaml/issues/7180)
[WinUI 3 Cant instantiate a UserControl from a location outside the application package or directory (XamlParseException)](https://github.com/microsoft/microsoft-ui-xaml/issues/6299)

**Comment by Iris0905** [comment]
Thank you for pointing out the other reported bugs. Yes, it is difficult to believe this is something not in the plan yet... It is definitely an important feature that's supposed to be supported in any UI framework.
