### ISSUE TITLE
Bug: TeachingTip doesn't use assigned colors when it pops up the second time 

### ISSUE THREAD

**Issue by JustinXinLiu** [microsoft/microsoft-ui-xaml#724]
**Describe the bug**
I have set the `Background` on the style and it works the very first time, but the second time when I pop up the `TeachingTip`, it changes to use the default background color.

        <Style TargetType="winui:TeachingTip">
            <Setter Property="Background" Value="{StaticResource Brush-Blue-0}" />

**Steps to reproduce the bug**
1. Run the app from [here](https://github.com/microsoft/InsiderDevTourDemos19/tree/master/Sessions/ui/Uwp.App).
2. Click on the circular button on the bottom left. Dismiss the `TeachingTip` and click on the button again.

**Expected behavior**
It should always display the colors that I defined.

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.1.190405004.2

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build                              | Yes   |

**Comment by jevansaks** [comment]
Thanks for the standalone repro! We'll take a look.

**Comment by jevansaks** [comment]
Ok so the bug here is that when the TeachingTip is LightDismiss it gets its background from the resource named `TeachingTipTransientBackground` ... but only after the first show. So it seems that the real bug here is that we don't enter the LightDismiss VSM state the first time.

If you want to override the background you'll also need to override TeachingTipTransientBackground. We'll use this bug to track that it doesn't pull from TeachingTipTransientBackground for the first show.
