### ISSUE TITLE
NavigationView Accessibility: NavigationViewItems do not read out unselected state

### ISSUE THREAD

**Issue by joshkoon** [microsoft/microsoft-ui-xaml#733]
**Describe the bug**
When using Narrator, the selected NavViewItem will include its selected state in the automation name. Unselected items do not include their status.

**Steps to reproduce the bug**
1. Create an app with a NavigationView
2. With Narrator running, navigate between items in the list

**Expected behavior**
Unselected items should include "unselected" as part of their automation name.

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.1.190405004

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (latest)                   | Yes   |
| October 2018 Update (17763)   |    |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by jevansaks** [comment]
Two things reported here:
1) It's stated that Automation Name includes the selection state, which is not the case. The control implements the selection provider and is reported through that pattern as selected/unselected.
2) Narrator is responsible for reading out the selection state here and talking to them it's by design -- they're always looking for ways to reduce verbosity and it is intentional that unselected items do not read out "unselected".
