### ISSUE TITLE
Renaming xaml file breaks everything in C++/WinRT

### ISSUE THREAD

**Issue by HO-COOH** [microsoft/microsoft-ui-xaml#7365]
### Describe the bug

Renaming a xaml file breaks the internal mechanics. Components and member functions not found, changes to the xaml no longer reflects on the internal `.xaml.g.cpp` files and casues compilation error.

### Steps to reproduce the bug

1. Create a "blank app" project with C++/WinRT, with the automatically-generated `MainPage.xaml`
2. Renaming the `XamlPage.xaml` -> `XamlPage2.xaml`
3. Change the `#include "MainPage.h"` -> `#include "MainPage2.h"` in the now renamed `MainPage2.cpp`, do the same thing in `App.cpp`
4. Build and run the project, it can successfully run now, but the things are already broken.
5. Make changes to the now renamed `MainPage2.xaml` like adding another button called `myButton2`

### Screenshots
![image](https://user-images.githubusercontent.com/42881734/178650631-df2e9017-6b0b-406d-a0b9-3de6b652ab67.png)

`MainPage2.xaml.g.hpp` errors here
![image](https://user-images.githubusercontent.com/42881734/178650485-76203ee8-5684-4699-8127-ca3b417a3d15.png)

### NuGet package version

Microsoft.UI.Xaml 2.7.1

### Windows app type

- [X] UWP
- [ ] Win32

**Comment by Link1J** [comment]
Workarounds:
1) Don't do that.
2) Include `MainPage2.xaml.g.h` after `MainPage.g.h`. Your on your own fixing all the compiler errors with this.

What is happening:
XAML compiler generates files based on the XAML file name, where C++/WinRT includes files based on the type name. In fact the first build hides the problem, as a `MainPage.xaml.g.h` is left over from it. Because of this, it hide the fact that the new code from the XAML compiler wasn't included.

There is nothing on the C++/WinRT side that can be done to fix this, because it doesn't have enough info. Really the bug here is with how the XAML compiler generates files. In fact, it causes a lot of problems, because you can't put XAML files in subdirectories in C++. And the XAML compiler's file generation works just fine for C#, what it was originally created for.

**Comment by HO-COOH** [comment]
Thanks @Link1J for this insight, it seems like nowhere mentioned on the C++WinRT doc. What you said sounds like an awfully half-baked implementation for Xaml compiler

**Comment by krschau** [comment]
Is this the kind of thing where Cleaning the project would help? Assuming you've fixed includes, etc, to reference up-to-date names.

**Comment by Link1J** [comment]
@krschau No. And fixing the includes is basically impossible.

**Comment by HO-COOH** [comment]
@krschau Isn't this something to be improved?
