### ISSUE TITLE
Microsoft-UI-Xaml V2.8 conflict with Microsoft.Toolkit.Uwp.UI.Controls V7.1.2

### ISSUE THREAD

**Issue by OneFingerCodingWarrior** [microsoft/microsoft-ui-xaml#7397]
### Describe the bug

1、After Update to V2.8, got the following error
PRI175: 0x80073b0f - Processing Resources failed with error: Duplicate Entry.
2、V2.7.1 works fine 

### Steps to reproduce the bug

Please compile the attachment project

### NuGet package version

Microsoft.UI.Xaml 2.8.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (20H2): Build 19042

### Additional context

[App3.zip](https://github.com/microsoft/microsoft-ui-xaml/files/9139108/App3.zip)

**Comment by MagicAndre1981** [comment]
this often happens with version mismatch of dependencies. Toolkit is [using 2.7](https://github.com/CommunityToolkit/WindowsCommunityToolkit/blob/78161891471e366935a7475f4b85148471707280/build/Windows.Toolkit.UWP.Controls.targets#L8), so the version needs to be increase in toolkit. Raise an issue there

**Comment by OneFingerCodingWarrior** [comment]
The problem is if Microsoft.Toolkit.Uwp.UI.Controls is referenced in the main project , everything is fine.
And error arise only when it is referenced in a class library .
Maybe i should wait Toolkit update dependencies to WinUI 2.8, and then try again.

**Comment by OneFingerCodingWarrior** [comment]
One more question: if Toolkit is targeting 2.7, why 2.71 is fine, but 2.8.0 is not ?

**Comment by NGame1** [comment]
> The problem is if Microsoft.Toolkit.Uwp.UI.Controls is referenced in the main project , everything is fine. And error arise only when it is referenced in a class library . Maybe i should wait Toolkit update dependencies to WinUI 2.8, and then try again.

I also have the same issue. It's also fine on 2.7.2 just 2.8 having the issue.
I also have the following error too on 2.8, however, 2.7.x versions are fine.
PRI277: 0x80073b0f - Conflicting values for resource 'Files/Microsoft.UI.Xaml/DensityStyles/Compact.xbf'

**Comment by krschau** [comment]
I suspect that @MagicAndre1981 is right, and the issue is that WCT is still pointing to 2.7.1. @michael-hawker, do you agree?

**Comment by MagicAndre1981** [comment]
> One more question: if Toolkit is targeting 2.7, why 2.71 is fine, but 2.8.0 is not ?

I have no idea, I just remember that this error occurred in the past if version mismatches occurred for Xamarin.Forms or Microsoft.NETCore.UniversalWindowsPlatform

**Comment by NGame1** [comment]
> Microsoft.NETCore.UniversalWindowsPlatform

I'm using Microsoft.NETCore.UniversalWindowsPlatform 6.2.14 on main project and class libraries.

**Comment by Arlodotexe** [comment]
👋 After some investigation, I found that this issue is still present when the Community Toolkit is removed from the equation.

It can be reproduced using only class libraries and the Microsoft.UI.Xaml nuget package:
![image](https://user-images.githubusercontent.com/9384894/186529792-8e1dc540-52b3-4056-ab32-064d41df1781.png)

After additional testing, the issue will go away if either of these conditions are met:
- The `Microsoft.UI.Xaml` version used in the transitive dependency matches the version used in the referencing project.
- Or, explicitly install the `Microsoft.UI.Xaml` package version you'd like to you in the project that references the problematic package/project with a reference to a lower version (install to `ClassLibraryWithWinUI28` in the screnshot above)

Since this issue can be reproduced without the Toolkit, we're recommending a workaround for developers and handing this back to the WinUI team from [here](https://github.com/CommunityToolkit/WindowsCommunityToolkit/issues/4612#issuecomment-1226488137).

**Comment by antokhio** [comment]
Just bumped in to this, as soon as i reference 
`Microsoft.Toolkit.Uwp.UI.Controls` Main project and class library i get `PRI175: 0x80073b0f - Processing Resources failed with error: Duplicate Entry.`

omg 4 hours to waste because of this

**Comment by michaelrinderle** [comment]
> Just bumped in to this, as soon as i reference `Microsoft.Toolkit.Uwp.UI.Controls` Main project and Class Library i get `PRI175: 0x80073b0f - Processing Resources failed with error: Duplicate Entry.`
> 
> omg 4 hours to waste because of this
> 
> EDIT: seems happens if `Microsoft.Toolkit.Uwp.UI.Controls` installed without `Microsoft.UI.Xaml` in Class Library project

I can confirm you need Microsoft.UI.Xaml in a UWP class library if you use Microsoft.Toolkit.Uwp.UI.Controls. 

Thank for the pointer! I would have spent even more time than that if I didn't find your post!
