### ISSUE TITLE
Cannot add or modify Context-Menu (right-click) of RichTextBlock

### ISSUE THREAD

**Issue by ivberg** [microsoft/microsoft-ui-xaml#7561]
### Describe the bug

Cannot add or modify Context-Menu (right-click) of RichTextBlock

I am not 100% sure this is not possible with WinAppSDK 1.1.3, but after searching the Internet for a while looking at potential solutions, and playing around with the APIs - this doesn't seem currently possible (or buggy?)

I wrote a min-repro app that attempts this here-
https://github.com/ivberg/WinUI3ModifyContextMenu

Here are resources I used to attempt to figure this out:
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.textbox.contextmenuopening?view=winrt-22621
https://docs.microsoft.com/en-us/windows/apps/design/controls/command-bar-flyout
https://github.com/microsoft/WinUI-Gallery/blob/260cb720ef83b3d134bc4805cffcfac9461dce33/WinUIGallery/ControlPages/CommandBarPage.xaml.cs // This is helpful for WinUI2 as example but I am doing what this is doing and it's not working
https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.AppBarButton?view=winrt-22621

### Steps to reproduce the bug

1. Create a new WinAppSDK 1.0 and WinUI3 project
2. Add a super simple RichTextBlock
```
<RichTextBlock>
    <Paragraph>I am a RichTextBlock.</Paragraph>
</RichTextBlock>
```
3.You will get default behavior of Copy and Select All when right clicking on text
4. Attempt to modify  RichTextBlock to add your own menu item and couldn't get it working
5. Behavior of flyout.SecondaryCommands.Add(newAppBarButton) is inconsistent. Sometimes there are no items present. Other times the 2 existing items of Copy and Select All are present. Either way adding the new AppBarButton seems to work in code. However, the new menu item still doesn't show??

See code at https://github.com/ivberg/WinUI3ModifyContextMenu

### Expected behavior

1. Devs can programmatically modify the behavior of controls like RichTextBlock to add their own right-click commands.

### NuGet package version

WinUI 3 - Windows App SDK 1.1.3

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (22H2): Build 22621

**Comment by codendone** [comment]
The problem is [TextCommandBarFlyout's own Opening event handler](https://github.com/microsoft/microsoft-ui-xaml/blob/0c556e89bf4d539c2fb3e5fe0a71e57a79fb3a1b/dev/CommandBarFlyout/TextCommandBarFlyout.cpp#L20) calls its `UpdateButtons` function which [clears SecondaryCommands](https://github.com/microsoft/microsoft-ui-xaml/blob/0c556e89bf4d539c2fb3e5fe0a71e57a79fb3a1b/dev/CommandBarFlyout/TextCommandBarFlyout.cpp#L164).

One option is to have your code register for `TextCommandBarFlyout.Opening`, which will get called after TextCommandBarFlyout's handling (since it registered first), and add/edit the items at that point if needed.
