### ISSUE TITLE
Binding not works in TabViewItem HeaderTemplate

### ISSUE THREAD

**Issue by DeepthiCG** [microsoft/microsoft-ui-xaml#7571]
### Describe the bug

In a UWP application which uses WinUI control TabView, data binding not works in HeaderTemplate of TabViewItem.
In the below code, first TabViewItem uses HeaderTemplate  to show the header. 
Data binding using x:Bind is done to TextBlock control inside the DataTemplate. 
myModel is a ViewModel class that is possible to bind. Its instance is created and updated in MainPage class.

`<StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">

        <muxc:TabView>

            <muxc:TabView.TabItems>
                <muxc:TabViewItem>
                    <muxc:TabViewItem.HeaderTemplate>
                        <DataTemplate x:DataType="local:MainPage">
                            <TextBlock Text="{x:Bind myModel.MyProperty }" />
                        </DataTemplate>
                    </muxc:TabViewItem.HeaderTemplate>
                </muxc:TabViewItem>
                <muxc:TabViewItem Header="PowerShell">
                    <muxc:TabViewItem.IconSource>
                        <muxc:SymbolIconSource Symbol="Placeholder" />
                    </muxc:TabViewItem.IconSource>
                </muxc:TabViewItem>
                <muxc:TabViewItem Header="Windows Subsystem for Linux">
                    <muxc:TabViewItem.IconSource>
                        <muxc:SymbolIconSource Symbol="Placeholder" />
                    </muxc:TabViewItem.IconSource>
                </muxc:TabViewItem>
            </muxc:TabView.TabItems>
        </muxc:TabView>
    </StackPanel>`

### Steps to reproduce the bug

Details added in above section

### NuGet package version

Microsoft.UI.Xaml 2.8.0

### Windows app type

- [X] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

**Comment by David-Buyer** [comment]
Similar issue in this stuff:

` <ComboBox x:Name="CtrPassportTypes" SelectedValue="{Binding ApplicationCurrentTarget, Source={StaticResource Core}, Converter={StaticResource ApplicationTargetEnumConverter}, Mode=TwoWay}" Width="300" Header="Tipologia Passaporto" 
                          SelectedValuePath="Tag">
                    <ComboBox.HeaderTemplate>
                        <DataTemplate x:DataType="ComboBox">
                            <TextBlock HorizontalAlignment="Left" VerticalAlignment="Top" **Text="{x:Bind Header}"** />
                        </DataTemplate>
                    </ComboBox.HeaderTemplate>
  </ComboBox>`

I have resolved using {Binding} syntax:

` <TextBlock HorizontalAlignment="Left" VerticalAlignment="Top" **Text="{Binding Path=Header, ElementName=CtrPassportTypes}"** />`

{x:Bind} syntax seems to be prone to a lot of bugs still.

**Comment by aturnbul** [comment]
I've found that most controls using `xxxxx.HeaderTemplate` have a similar issue in **WindowsAppSDK v1.2.221116.1**. For example
``` 
<ToggleSwitch Header="Resize">
    <ToggleSwitch.HeaderTemplate>
       <DataTemplate x:DataType="ToggleSwitch">
           <TextBlock Text="{x:Bind Header}"/>
       </DataTemplate>
    </ToggleSwitch.HeaderTemplate>
</ToggleSwitch>
```
doesn't work.

**But the problem doesn't appear to be `x:Bind`** but rather the way the XAML code generator expands `xxxxx.HeaderTemplate` when the templated parent `Header `property contains a string. The issue is that in these cases, the `DataContext `of the targeted control (`TextBlock` here but could be a `ContentPresenter`, etc.) is changed to the actual string in `Header` ("Resize" in this example) rather than the the templated control ('ToggleSwitch') as expected. This happens whether you use `Binding` or `x:Bind`. Please see the code generated in `MainPage.g.cs`, in particular what happens in the `DataContextChangedHandler `for the relevant `MainPage_objx_Bindings` class.

The easiest workaround for the moment is to use
```
<TextBlock Text="{Binding}"/>
```
to bind directly to the templated object which then defaults to using the string representation. Even in this case you'll see the `DataContext` has been set to the string contents of `Header`, but `TextBlock.Text `will be, too. Curiously, if you really want to use `x:Bind`, try
```
<DataTemplate x:DataType="x:String">
    <TextBlock Text="{x:Bind}"/>
</DataTemplate>
```
I hope this helps solve the underlying issue.
