### ISSUE TITLE
WinUI3 RuntimeComponent with BlankPage(WinUI3) cannot import to WinUI3 Desktop application development project

### ISSUE THREAD

**Issue by thureinmaung** [microsoft/microsoft-ui-xaml#7658]
### Describe the bug

1. Created WinUi3 Runtime Component.
2. Create the Functions , import .winmd file from WinUI3 Desktop application and calling the created functions is working fine.
3. Add new BlankPage (WinUI3) to the WinUi3 Runtime Component project.
4. Import .winmd file from  WinUI3 Desktop application recompile encounter  error C2039: 'RuntimeComponent1WinUI3': is not a member of 'winrt'
Please kindly advise as i am stacking here, thanks in advance.

### Steps to reproduce the bug

1. Created WinUi3 Runtime Component.
2. Create the Functions , import .winmd file from WinUI3 Desktop application and calling the created functions is working fine.
3. Add new BlankPage (WinUI3) to the WinUi3 Runtime Component project.
4. Import .winmd file from  WinUI3 Desktop application recompile encounter  error C2039: 'RuntimeComponent1WinUI3': is not a member of 'winrt'
Please kindly advise as i am stacking here, thanks in advance.

### Windows app type

- [ ] UWP
- [ ] Win32

**Comment by DarranRowe** [comment]
After looking into this, I noticed that the full error message is along the lines of:
```
2>C:\Users\Darran\source\repos\Meh\Meh\Generated Files\XamlTypeInfo.g.cpp(318,44): error C2039: 'Test': is not a member of 'winrt'
```
This is quite interesting since this shows that the issue is in the generated metadata that the Xaml compiler generates. In particular, it is in the code that the application's metadata provider looks for other providers.
```
std::vector<::winrt::Microsoft::UI::Xaml::Markup::IXamlMetadataProvider> const& XamlTypeInfoProvider::OtherProviders()
{
    if (_otherProviders.empty())
    {
        _otherProviders.push_back(::winrt::Microsoft::UI::Xaml::XamlTypeInfo::XamlControlsXamlMetaDataProvider());
        _otherProviders.push_back(::winrt::Test::XamlMetaDataProvider()); //Here
    }
    return _otherProviders;
}
```
Having a bit of a look through this generated source file, while it generates the code to get the metadata provider from another component, it doesn't add any headers to define the provider types. My thought is that the Xaml compiler can't know what header it needs to include, so it expects you to provide this.
So after seeing this, I did one simple thing. In the application's precompiled header, I added the include for the added component.
```
//pch.h
#pragma once
#include <windows.h>
#include <unknwn.h>
#include <restrictederrorinfo.h>
#include <hstring.h>

// Undefine GetCurrentTime macro to prevent
// conflict with Storyboard::GetCurrentTime
#undef GetCurrentTime

#include <winrt/Windows.Foundation.h>
#include <winrt/Windows.Foundation.Collections.h>
#include <winrt/Windows.ApplicationModel.Activation.h>
#include <winrt/Microsoft.UI.Composition.h>
#include <winrt/Microsoft.UI.Xaml.h>
#include <winrt/Microsoft.UI.Xaml.Controls.h>
#include <winrt/Microsoft.UI.Xaml.Controls.Primitives.h>
#include <winrt/Microsoft.UI.Xaml.Data.h>
#include <winrt/Microsoft.UI.Xaml.Interop.h>
#include <winrt/Microsoft.UI.Xaml.Markup.h>
#include <winrt/Microsoft.UI.Xaml.Media.h>
#include <winrt/Microsoft.UI.Xaml.Navigation.h>
#include <winrt/Microsoft.UI.Xaml.Shapes.h>
#include <winrt/Microsoft.UI.Dispatching.h>
#include <winrt/Test.h> //<-Here
#include <wil/cppwinrt_helpers.h>
```
Since XamlTypeInfo.g.xpp includes pch.h, then it provides the type information for the external metadata provider and allows the application to compile successfully.
So try adding the header that defines RuntimeComponent1WinUI3 in your application's precompiled header and see if that helps.
