### ISSUE TITLE
Setting a `Foreground` on a `SplitButton` does not apply to the dropdown half

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/microsoft-ui-xaml#7673]
re: https://github.com/microsoft/terminal/pull/13871

See source:
https://github.com/microsoft/microsoft-ui-xaml/blob/33732458ede38166f9127675898e4760c82b89bb/dev/SplitButton/SplitButton.xaml#L290-L293

We were setting `Foreground` on the SplitButton we use as our new tab button. However, the visual styles for the secondary button use `Foreground="{ThemeResource SplitButtonForegroundSecondary}" `, so they'll just always ignore the `Foreground` property (even if the primary button respects it).

Also, this seems to have regressed in #3887, which first shipped in 2.6.1

https://github.com/microsoft/microsoft-ui-xaml/blame/33732458ede38166f9127675898e4760c82b89bb/dev/SplitButton/SplitButton.xaml#L292

If this is by design, that's fine - but it should be documented as such.

**Comment by zadjii-msft** [comment]
Nothing has changed here ; still an issue.

**Comment by karkarl** [comment]
Hey @zadjii-msft, this is by design, since SplitView's primary and secondary texts uses different brush colours. Templatebinding both elements to SplitView.Foreground will not allow them to consume different brushes, and ultimately remove flexibility in customization.

I agree much work should be done in terms of documentation since it's not immediately obvious what element Foreground (nor Background) sets. Happy to discuss further for ideas.
