### ISSUE TITLE
ToggleSwitch doesn't issue Tapped event

### ISSUE THREAD

**Issue by AndrewKeepCoding** [microsoft/microsoft-ui-xaml#7698]
### Describe the bug

- ``ToggleSwitch`` DOES NOT fire ``Tapped`` events
- ``IsTapEnabled`` DOES NOT make any difference
- ``RightTapped`` and ``DoubleTapped`` DO fire their events
- ``ToggleButton`` DOES fire ``Tapped`` events

### Steps to reproduce the bug

1. Add a ``ToggleSwitch`` control.
2. Add an event handler to ``Tapped`` event.
3. Run the app and click the ``ToggleSwitch`` control and see if ``ToggleSwitch_Tapped()`` is called
```xaml
<ToggleSwitch Tapped="ToggleSwitch_Tapped" />
```

### Expected behavior

``ToggleSwitch_Tapped()`` should be called when the ``ToggleSwitch`` is tapped (clicked).

### NuGet package version

WinUI 3 - Windows App SDK 1.1.4

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

**Comment by AndrewKeepCoding** [comment]
> If you're looking for when the ToggleSwitch state changes, you should listen for Toggled event. Checked and Unchecked for ToggleButton.
Yes, in general I totally agree with you. 
I'm just trying to answer this [question](https://stackoverflow.com/q/73628143/2411960) in StackOverflow, and suggested exactly what you suggested, but there is a request that the ``Toggled`` event cannot be used.

**Comment by AndrewKeepCoding** [comment]
> I believe that this is expected, as pointer events are probably marked as handled within the control logic and hence they're not propagated for further processing.

As I mentioned in the top, the ``ToggleButton`` DOES fire the ``Tapped`` event. I don't see why the ``ToggleSwitch`` and the ``ToggleButton`` need to behave different when is tapped.

**Comment by AndrewKeepCoding** [comment]
This is still reproducible in WindowsAppSDK v1.3.230602002.

**Comment by kmahone** [comment]
In general, you should not try to directly handle the pointer input events (e.g. Tapped, PointerPressed, etc.)  on a Control such as ToggleSwitch. Instead you should use the higher-level events that are defined on the Control itself - such as the Toggled event in the case of ToggleSwitch.

In general, Controls will internally handle the input events that are raised on them and will mark them as handled in such cases. This means that the events will not be raised externally. It is best to handle the events such as Button.Click and ToggleSwitch.Toggled since these are not tied directly to a particular input mode, they are raised regardless of how the user invokes the control (mouse, touch, keyboard, UIAutomation, etc.).
