### ISSUE TITLE
DEP1700 Error WinUI3 

### ISSUE THREAD

**Issue by savian-net** [microsoft/microsoft-ui-xaml#7754]
I have a large WinUI project that was working last time I opened it, now I get DEP1700 Error:

DEP1700: The recipe file "X:\repos\####\bin\x64\Debug\net6.0-windows10.0.19041.0\win10-x64\####.build.appxrecipe" does not exist. You may need to build your project.

This is on latest VS2022 Preview. I have spent a day on  this error to no avail. I can't debug it or doing anything else, 

Steps taken:

Cleared the nuget cache,
Built a sample app (it works)
Cleaned, deleted obj/bin over and over. 
Build Configuration has Deploy checked

Any suggestions would be appreciated

**Comment by gautambjain** [comment]
Any fix for this please?

Getting same error for a packaged 64 bit WinUI 3 project on VS 2022 (v17.3.3)

**Comment by rmonyer** [comment]
I am also having the same issues and I have also done all of the steps mentioned about and even a 'dotnet restore'.

This is really frustrating and seems like a MAUI bug.

**Comment by symbiogenesis** [comment]
try adding this to the MAUI csproj:

	```
<PropertyGroup>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

```

**Comment by rmonyer** [comment]
For me it had to do with the target framework for the "Windows Machine".  It was targeting .net 6.0 which was missing the recipe file.  I either had to revert to the other framework in the list or copy the recipe appx file from the one successful debug builds to the .net 6.0 debug build folder.  Also, thank you @symbiogenesis for that suggestion.  I checked the csproj file and it did have that OutputType, but with a condition.  Not sure if that was also interfering, but because this is a shared project, I hesitate to change it.

**Comment by gautambjain** [comment]
The error stopped when I switched from "Packaged" to "Unpackaged" config when debugging.

**Comment by HakamFostok** [comment]
This is real bug and I really do not know what this is closed, it should be re-opened again please

**Comment by symbiogenesis** [comment]
This one seems like a heisenbug. I see it with my MAUI app occasionally. But it just seems to go away eventually. Might have to do with visual studio. I think using the dotnet CLI is more reliable.

**Comment by michael-hawker** [comment]
This error is generally due to a mismatch between the configuration within the app `WindowsPackageType` and the configuration VS is trying to run.

<img width="190" height="115" alt="Image" src="https://github.com/user-attachments/assets/69f1f21b-5dc9-469d-abe5-be92b733a294" />

You need to make sure they match when running the project with the dropdown.

i.e. if you have WindowsPackageType  None  in your csproj, you need to run the Unpackaged version (at least that's what the project intends).
