### ISSUE TITLE
Cannot author a C++ WinUI 3 component

### ISSUE THREAD

**Issue by MarkIngramUK** [microsoft/microsoft-ui-xaml#7839]
### Describe the bug

Following the discussion here (https://github.com/microsoft/WindowsAppSDK/discussions/3013), it seems like the ability to author a C++ WinUI 3 component is not supported "out the box" in Visual Studio. 
Attempting to write a component in C++ and then consume it results in the following error message:

```
Exception thrown at 0x00007FFB1846474C (KernelBase.dll) in ControlTest.exe: WinRT originate error - 0x80004005 : 'Cannot locate resource from 'ms-appx:///FancyControl.xaml'.'.
```

### Steps to reproduce the bug

Create a C++ WinUI 3 component.
Create a C++ WinUI 3 application.
Add a project reference to the component, in the application's project file.
Attempt to use the component within the XAML of the application.

### Expected behavior

To be able to use C++ end-to-end.

### NuGet package version

WinUI 3 - Windows App SDK 1.1.5

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (22H2): Build 22621, Windows 11 (21H2): Build 22000

**Comment by MarkIngramUK** [comment]
This is still a problem that needs resolving. Either support C++ or don't. Don't leave it in some weird in between state.

**Comment by DarranRowe** [comment]
C++ components have always been supported. This is the result of another known issue.
The [release notes for 1.0](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel#winui-3-2) always had a workaround in them. The templates that come with Visual Studio 2022 17.8 also updated the runtime component template so that it doesn't need this.
