### ISSUE TITLE
Settings PublishAppxPackage = true causes a build error when referencing a class library that has WindowsPackageType = None

### ISSUE THREAD

**Issue by sbanni** [microsoft/microsoft-ui-xaml#7846]
### Describe the bug

Settings PublishAppxPackage = true causes a build error when referencing a class library that has WindowsPackageType = None

### Steps to reproduce the bug

Steps to Reproduce

Create a .NET Maui App
Build, Test, Publish (windows)
Should succeed.
Add a .NET Maui Class Library to the Solution.
Add a Shared Project reference to the Class Library.
Build and Run (will still work)
Publish…
Fails with “Improper project configuration: WindowsPackageType is set to None, but PublishAppxPackage is set to true.”

### Packaging type

Packaged (MSIX)

### IDE

Visual Studio 2022-preview

**Comment by solomonfried** [comment]
While waiting for this to be resolved, I have a question which may help clear this up for me.
In Xamarin, if I wanted a shared library that included Controls (Pages, Views...), I would create a Net Standard 2 library and add Xamarin.Forms Nuget package to it. I could then Add ContentPages, ContentViews. etc... into that library.

With MAUI, it seems I need to create a "MAUI Class Library" to accomplish the same thing.  
If I create a simple .NET 6 library, I am unable to add Pages, Buttons, etc...

Am I correct, or am I doing something wrong?

**Comment by a-einstein** [comment]
Any workaround?

I am unable to publish now.

**Comment by 1thenikita** [comment]
Please, fix this bug. It makes it impossible to properly test applications on samples.

**Comment by a-einstein** [comment]
Again, prioritize this.
I cannot publish at all.
Not in Visual Studio.
Not on Azure.
I am trying to get a first MAUI deliverable.

**Comment by jodendaal** [comment]
How frustrating I too ran into this not sure how to resolve. Luckily I was just prototyping something I thought would be a good idea. Maybe not, bringing back memories of trying to use xamarin many years ago :(

**Comment by oliverholliday** [comment]
Is there any workaround for this?

Not being able to actually ship a MAUI app seems to be a fundamental problem with the MAUI ecosystem.

**Comment by evelynwu-msft** [comment]
@oliverholliday The fix for this is in the upcoming Windows App SDK 1.3 release.

**Comment by gabbybilka** [comment]
:tada:`Microsoft.WindowsAppSDK v1.3.0` has been released which fixes this issue.
* [Release Notes](https://aka.ms/windowsappsdk/1.3/1.3.0/release-notes)
* [Nuget](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.3.230331000) to try it out.

**Comment by AnithaRaniT** [comment]
I'm also facing the issue, which is blocking me the production release. Please someone help me to overcome this issue. 

I'm unable to update the Microsoft.WindowsAppSDK version from 1.2.221109.1 to any higher version due to my project is blocking this from the update. PFA FYI

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/45478510/6d4ad289-cc06-4b88-94ec-b874e2d02a77)


I found one suggestion is that to add in the .csproj file is that,

`<ItemGroup Condition="'$(TargetFramework)'=='net7.0-windows10.0.17763'">
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.3.230331000" />
  </ItemGroup>`


after adding that also not able to publish the app package for the windows platform. 


Here is my target platforms:
`	<TargetFrameworks>net7.0-ios;net7.0-android33.0</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net7.0-windows10.0.20348.0</TargetFrameworks>`


@gabbybilka, @evelynwu-msft  Please provide some solution for this as this is high priority which is blocking from the production release.

Here is my VS version details. 

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/45478510/d8edc03c-1c48-4580-8ecc-1ae3fd3bc1fc)


Please let me know if any details required

**Comment by WestcountryBusiness** [comment]
I have exactly the same issue as documented above.  Issue is including a MAui class library project with my Maui app.  Class library was for common services for future apps but as this my first, have moved services back within this app for now.  By removing the class library project, problem resolved.  Will hope for a solution before I need to create a second Maui app as will need the shared app library then.

**Comment by MarcAlx** [comment]
Hi, to bypass this problem, occuring only in VS2022, I directly use the `dotnet publish` command.

     dotnet publish -f net7.0-windows10.0.19041.0 -c Release /p:RuntimeIdentifierOverride=win10-x64

Once done I got a ready to use `msix`. 

_n.b signing your app maybe needed before distribution._

**Comment by WestcountryBusiness** [comment]
> Hi, to bypass this problem, occuring only in VS2022, I directly use the `dotnet publish` command.
> 
> ```
>  dotnet publish -f net7.0-windows10.0.19041.0 -c Release /p:RuntimeIdentifierOverride=win10-x64
> ```
> 
> Once done I got a ready to use `msix`.
> 
> _n.b signing your app maybe needed before distribution._

Thanks, Marc. That fixed it for me too.

**Comment by TamerIrdais** [comment]
This issue is still active using VS 2022 version 17.8.3 so why is it still marked as "closed"?
We can't publish from VS IDE and we can't update Microsoft.WindowsAppSDK NuGet to version 1.3 because its locked, so what's the solution here?

No one from Microsoft is caring to give feedback on this very critical issue.
