### ISSUE TITLE
'IUnknown': ambiguous symbol (compiling source file App.xaml.cpp)

### ISSUE THREAD

**Issue by petercoin** [microsoft/microsoft-ui-xaml#7905]
### Describe the bug

I am trying to use IMMDevice and CComPtr in my WinUI 3 desktop application but I got an error like the title.
However, the issue didn't occur on my another project.
Therefore, I did some research and found that the error can be reproduced with specific declaration sequence.
Please see the reproduce steps.

### Steps to reproduce the bug

1. Create a C++ WinUI 3 desktop packaged with WAP project
2. Add 
```
#include <atlbase.h>
#include <mmdeviceapi.h>
#include <vector>
```
to MainWindow.xaml.h

3. Add
```
std::vector<CComPtr<IMMDevice>> devices;
```
as a member of MainWindow class.

4. Build
5. You will get the error like title.
6. Add
```
CComPtr<IMMDevice> device;
```
before above devices variable.
It will look like:
```
CComPtr<IMMDevice> device;
std::vector<CComPtr<IMMDevice>> devices;
```
7. Build
8. No any error will be received.

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

Microsoft.Windows.CppWinRT v2.0.210806.1
Microsoft.Windows.ImplementationLibrary v1.0.211019.2
Microsoft.Windows.SDK.BuildTools v10.0.22000.194
Microsoft.Windows.AppSDK v1.1.3

**Comment by DarranRowe** [comment]
Yup, this is one of the problems of the default template code. It designed to allow you to quickly start writing code, but it has some problems. Including wrl.h also causes problems.

The problem here is that the start of the file has:

```
using namespace winrt;
using namespace Windows::Foundation;
```

This causes your problem because it brings winrt::Windows::Foundation into the global scope. To help with the C++/WinRT projection, there exists a couple of helper wrappers. The two biggest ones are winrt::Windows::Foundation::IInspectable and, because IInspectable derives from it, winrt::Windows::Foundation::IUnknown. This means that in App.xaml.cpp, an unqualified IUnknown could refer to ::IUnknown as defined in unknwn.h, or winrt::Windows::Foundation::IUnknown as defined as part of the C++/WinRT projection.

When I start a new project with WinUI, one of the first things I do is sort out the namespaces in App.xaml.cpp. So as an example of what I do:

```
#include "pch.h"

#include "App.xaml.h"
#include "MainWindow.xaml.h"

namespace winrt
{
    //Makes wf an alias of winrt::Windows::Foundation
    namespace wf = Windows::Foundation;
    //Makes mux an alias of winrt::Microsoft::UI::Xaml
    namespace mux = Microsoft::UI::Xaml;
    //Makes muxc an alias of winrt::Microsoft::UI::Xaml::Controls
    namespace muxc = Microsoft::UI::Xaml::Controls;
    //Makes muxn an alias of winrt::Microsoft::UI::Xaml::Navigation
    namespace muxn = Microsoft::UI::Xaml::Navigation;
}

// To learn more about WinUI, the WinUI project structure,
// and more about our project templates, see: http://aka.ms/winui-project-info.

namespace winrt::App2::implementation
{
    /// <summary>
    /// Initializes the singleton application object.  This is the first line of authored code
    /// executed, and as such is the logical equivalent of main() or WinMain().
    /// </summary>
    App::App()
    {
        InitializeComponent();

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BREAK_ON_UNHANDLED_EXCEPTION
        UnhandledException([this](wf::IInspectable const &, mux::UnhandledExceptionEventArgs const &e)
            {
                if (IsDebuggerPresent())
                {
                    auto errorMessage = e.Message();
                    __debugbreak();
                }
            });
#endif
    }

    /// <summary>
    /// Invoked when the application is launched normally by the end user.  Other entry points
    /// will be used such as when the application is launched to open a specific file.
    /// </summary>
    /// <param name="e">Details about the launch request and process.</param>
    void App::OnLaunched(mux::LaunchActivatedEventArgs const &)
    {
        window = make<MainWindow>();
        window.Activate();
    }
}
```

The namespace App2 comes from the fact that the project is named App2. But as you can see, I use namespaces and namespace aliases to qualify names. With this code, IUnknown would unambiguously refer to ::IUnknown since you need to use a fully qualified name to refer to winrt::Windows::Foundation::IUnknown.

**Comment by petercoin** [comment]
@DarranRowe Thanks for your help.
It works well!
IMHO, the MSFT team still needs to solve this problem for better user experience...

**Comment by petercoin** [comment]
@DarranRowe Thanks for your help.
It works well!
However, the MSFT team still needs to solve this problem for better user experience...

**Comment by Scottj1s** [comment]
@petercoin, closing this issue as you now have a workaround.  If you have any ideas for how to improve use of COM interfaces without negatively impacting more common scenarios, please create a feature request.
