### ISSUE TITLE
Unable to naturally set TargetFramework to Net 7.0

### ISSUE THREAD

**Issue by EmilysDad** [microsoft/microsoft-ui-xaml#7969]
### Describe the bug

Given Microsoft Visual Studio Community 2022, Version 17.4.1+33110.190, unable to set the target framework for a WinUI 3 project to Net 7.

Attempts result in Error, MSB4086, A numeric comparison was attempted on "$(TargetPlatformVersion)" that evaluates to "" instead of a number, in condition "'$(TargetPlatformVersion)' < '10.0.18362.0'".

OS is Windows 10 version is 22H2 19045.2311.

### Steps to reproduce the bug

1. Create a new "Blank App, Packaged (WinUI 3 in Desktop)
2. Change project target framework from net6.0 to net7.0.

### Expected behavior

Windows App SDK 1.2 and WinUI 3 reportedly supports NET 7.

### NuGet package version

WinUI 3 - Windows App SDK 1.2.1: 1.2.221116.1

Microsoft.WindowsAppSDK  Version=1.2.221116.1
Microsoft.Windows.SDK.BuildTools Version=10.0.22621.755

### Windows version

OS is Windows 10 version is 22H2 19045.2311.

### Additional context

Changing target framework will remove error and allow build, but the test app will not run.

```
<TargetFramework>net7.0-windows10.0.19041.0</TargetFramework>
```

results in System.DllNotFoundException: 'Unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)' in auto-generated App.g.i.cs.

**Comment by Panda-Sharp** [comment]
> > Expected behavior
> > Windows App SDK 1.2 and WinUI 3 reportedly supports NET 7.
> 
> It works fine for me. This indicates there is likely some problem with your environment, but I'm not sure what needs to be changed / fixed.

It doesn't work if you do it from the UI, I experienced it myself and also several devs that I know reported the same issue

**Comment by kmgallahan** [comment]
@Panda-Sharp Yes, but OP also said:

> Changing target framework will remove error and allow build, but the test app will not run.

**Comment by Panda-Sharp** [comment]
> @Panda-Sharp Yes, but OP also said:
> 
> > Changing target framework will remove error and allow build, but the test app will not run.

Ooops my bad, I missed that part

**Comment by DarranRowe** [comment]
@EmilysDad
Just to be sure, but is this a packaged or unpackaged application?

If it is packaged, have you made sure that the package is referencing the Windows App SDK properly? You should be able to tell from the AppxManifest file.

If it is unpackaged, are you putting the WindowsPackageType attribute into the .csproj file or broken the Main function out into a separate file and are manually calling the bootstrap initialiser?

I just tried it myself, and while I did have to manually edit the project file to switch over to .NET 7, I have no issues with running the application.

**Comment by EmilysDad** [comment]
@DarranRowe 
As stated, it's packaged. No changes to the template provided in "Blank App, Packaged (WinUI 3 in Desktop)"

The test app is created making no additional changes to that template.

If visual studio's project settings is used-- using the drop down controls -- it breaks as stated in OP.

For the record,

'''
    <TargetFramework>net7.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
'''

manually writing, appears to be the only way to get the project to both build and run without error.

Is this intended? It appears extremely brittle to me.

**Comment by myokeeh** [comment]
https://github.com/microsoft/TemplateStudio/discussions/4605

**Comment by manodasanW** [comment]
> Change project target framework from net6.0 to net7.0.

When you use the UI to change the `Target framework`, Visual Studio resets the values for `Target OS` and `Target OS version` which are dropdowns in UI right below `Target framework`.  If you were to also set them back to the previous values in the UI (i.e. Windows and respective Windows OS version you were using), I feel like the first issue shouldn't hit.  WinAppSDK should have a better error message for when a non Windows version specific TFM is used which is tracked by https://github.com/microsoft/WindowsAppSDK/issues/2762

**Comment by athulrajts** [comment]
when i change target framework to
```
<TargetFramework>net7.0-windows10.0.19041.0</TargetFramework>
```
It builds but it still seems to be targeting net6.0 since the output directory didn't change
```
\bin\x64\Debug\net6.0-windows10.0.19041.0\win10-x64\ProjectName.dll
```
when i refer a class library targeting net7.0 in this project it gives this error.
```
Error NU1201	Project <ClassLib> is not compatible with net6.0-windows10.0.19041 (.NETCoreApp,Version=v6.0). Project <ClassLib> supports: net7.0 (.NETCoreApp,Version=v7.0)	<ProjectName>	
```

**Comment by EmilysDad** [comment]
The principal issue is that these project settings should be unambiguous and not be used for hidden recipes.

TargetFramework should be just that, the framework (e.g., net7.0, net6.0, etc.)

TargetOS, TargetPlatformMinVersion, etc. should also be  unambiguous and settable without unintended consequences.

These details should be informative without being prescriptive to use the framework or SDK.

**Comment by DarranRowe** [comment]
Well, after messing around with this a bit, part of me is wondering if this is actually a Windows App SDK problem.

If you create a Wpf application and use the properties for that, then you notice a couple of interesting quirks in how the C# project system works. The target OS version defaults to Windows 7, and when you change the target framework, Visual Studio should reset the target OS version to Windows 7. I was testing this on Visual Studio 17.4.1 initially, and 17.4.2 since the update was released. One important thing is that any change to the target framework, up or down, will cause the target OS to reset to Windows 7.

Now, if in a WinUI 3/Windows App SDK project you change the target framework from 6 to 7 then this causes the TargetFramework value in the project file to go bad. But interestingly, it works in reverse too. If you edit the TargetFramework value to target a valid .NET 7 version and then use the project properties to change the target framework to .NET 6, the TargetFramework value ends up being net6.0 with no OS version. I think that it is trying to reset the target OS to Windows 7 here too, but since Windows 7 isn't a valid target for the Windows App SDK, then this is failing.

So yes, this is definitely something that has to be fixed. Right now, the best work around seems to be:
1) Go to solution explorer.
2) Double click the project to open the .csproj file.
3) Manually set the TargetFramework value to a valid target version, such as net7.0-windows10.0.19041.0.
4) Save the .csproj file.
5) Exit visual studio and then start it again.

Unloading and reloading the project probably works just as well here, but it is basically to force Visual Studio to read the project again with the modified values. This is still probably overkill, but I honestly don't trust the C# project system.

In the case that you have tried to set the target framework through the project properties and this failed, then the steps above should be able to recover this, as long as you set a valid TargetFramework, save the project and force Visual Studio to re-read the project file before you try to build the project again.

**Comment by Scottj1s** [comment]
Closing as this is a [Visual Studio issue](https://developercommunity.visualstudio.com/t/Using-C-project-properties-to-change-Ta/10220321?port=1026&fsid=655d9ec9-05c6-46dd-a7cf-1284ed96845d&ref=native&refTime=1670006497287&refUserId=3ecae279-b085-41e5-8176-afdfb2972795), and something [Windows App SDK should guard against](https://github.com/microsoft/WindowsAppSDK/issues/2762).
