### ISSUE TITLE
MediaPlayerElement cannot display text in subtitles

### ISSUE THREAD

**Issue by qian-o** [microsoft/microsoft-ui-xaml#7981]
### Describe the bug

![image](https://user-images.githubusercontent.com/84434846/202857055-86958185-6f4e-4640-ab6d-553e9901859d.png)
![image](https://user-images.githubusercontent.com/84434846/202857061-dcf99ed7-f754-43f9-87c3-a268ff8881a4.png)
WinUI:
![image](https://user-images.githubusercontent.com/84434846/202857102-3e70f1d9-312a-45e4-aa8b-ab8f38b2f1a8.png)
![image](https://user-images.githubusercontent.com/84434846/202857149-9a61aa60-8515-4530-bc41-fd7c08ead668.png)

### Steps to reproduce the bug

1.Create a MediaPlayerElement control.
2.Create a MediaSource and add a TimedTextSource instance to ExternalTimedTextSources.
3.The Source property of the MediaPlayerElement binds to the MediaSource

### NuGet package version

Windows App SDK 1.2.1: 1.2.221116.1

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by Loganeek** [comment]
It seems the problem of the default caption style.

Try:
1. Go to "Settings > Accessibility > Captions > Caption style > Edit".
2. Change the text effects "None" to "Uniform" or others.

|before|after|
| ----------- | ----------- |
|<img width="537" alt="屏幕截图 2023-06-04 183140" src="https://github.com/microsoft/microsoft-ui-xaml/assets/8295171/d30fd10e-b7e5-4622-8eb2-6289bf59869d">|<img width="536" alt="屏幕截图 2023-06-04 183149" src="https://github.com/microsoft/microsoft-ui-xaml/assets/8295171/cad8d82d-ab17-4792-bd0c-c0366fd686f8">|
|<img width="552" alt="屏幕截图 2023-06-04 191826" src="https://github.com/microsoft/microsoft-ui-xaml/assets/8295171/fcf6928a-41b5-4ae7-8c85-b9a886474942">|<img width="582" alt="屏幕截图 2023-06-04 193711" src="https://github.com/microsoft/microsoft-ui-xaml/assets/8295171/91a92598-6a90-407f-aac4-8a4cd4e70a7d">|

It works for me.

**Comment by qian-o** [comment]
Thank you for your response, but I have already found an alternative to MediaPlayerElement.

**Comment by softworkz** [comment]
Here's a non-programmatic solution. When you merge this REG file, it will add a captioning theme with empty configuration, named "Controlled by Application" and sets it as active.

After that, all subtitle styles are controlled by the application again (TimedTextStyle).

[WindowsCaptionsDefaultProfile.zip](https://github.com/ffmpeginteropx/FFmpegInteropX/files/13397454/WindowsCaptionsDefaultProfile.zip)

**Comment by DmitriyKomin** [comment]
@qian-o, thank you for reporting the issue. I can confirm CC text is not rendered when Effects is set to _None_ or _Drop Shadow_ (but does render with _Raised/Depressed/Uniform_). This is a regression from the initial WASDK preview release containing MediaPlayerElement (1.2.220902.1-preview1). I will continue investigating this further.

**Comment by softworkz** [comment]
> I will continue investigating this further.

@DmitriyKomin - no need. I did all the work already: https://github.com/microsoft/microsoft-ui-xaml/issues/9126

**Comment by DmitriyKomin** [comment]
@qian-o, confirming the issue is fixed internally for WinAppSDK 1.6. 

@softworkz, note this was a bug in WinUI3 CC rendering unrelated to the other issues raised around MPE CC rendering in #9126.

Specifically, captions weren't rendering for 2 out of the 5 possible Edge Effects settings - _None and Drop Shadow_. In these cases - where we don't generate SpriteVisuals to simulate an effect - layout never got run on the underlying TextBlock, causing a 0 size for the SpriteVisual backing the CompositionVisualSurface WinUI3 uses to render captions. The fix ensures UpdateLayout() is called on the TextBlock for all Edge Effects settings.

**Comment by softworkz** [comment]
> @softworkz, note this was a bug in WinUI3 CC rendering unrelated to the other issues raised around MPE CC rendering in #9126. I will make sure to follow up on the other ones separately.

Excellent, thanks!

**Comment by qian-o** [comment]
> @qian-o, I can confirm the issue is fixed internally for WinAppSDK 1.6. Specifically, captions weren't rendering for 2 out of the 5 possible Edge Effects settings - _None and Drop Shadow_. In these cases - where we don't generate SpriteVisuals to simulate an effect - layout never got run on the underlying TextBlock, causing a 0 size for the SpriteVisual backing the CompositionVisualSurface WinUI3 uses to render captions. The fix ensures UpdateLayout() is called on the TextBlock for all Edge Effects settings.
> 
> @softworkz, note this was a bug in WinUI3 CC rendering unrelated to the other issues raised around MPE CC rendering in #9126. I will make sure to follow up on the other ones separately.

Thank you for your participation. Looking forward to further improvements in the next version. Much appreciated.

**Comment by softworkz** [comment]
@DmitriyKomin - A general note on the whole subject:

When working with subtitles/closedcaptions, you are using [TimedTextStyle](https://learn.microsoft.com/en-us/uwp/api/windows.media.core.timedtextstyle), which provides very detailed settings to control the appearance of subtitles, but one thing is missing: 

There is no "Effect" property. This can only be controlled from the Windows settings app and in code, it can only be read but not changed: [ClosedCaptionProperties.FontEffect](https://learn.microsoft.com/en-us/uwp/api/windows.media.closedcaptioning.closedcaptionproperties.fonteffect).

Also, the latter properties partially (really weird and stupid) overrride those which you can set with TimedTextStyle. 
All that doesn't fit together and doesn't make sense the way it is and needs architectural review in general. 
But first of all, I hope the worst parts can be fixed in some way....
