### ISSUE TITLE
Restore Button Is Missing

### ISSUE THREAD

**Issue by DJRM2021** [microsoft/microsoft-ui-xaml#8053]
### Describe the bug

The Restore Window button on the top-right corner of a window is missing and replaced automatically by a Maximize button.
This issue only happens on WinUI 3 desktop apps that uses a custom title bar.
Here is a screenshot of the 3 main buttons (Minimize, Maximize, Close) of an already-maximized window.
![image](https://user-images.githubusercontent.com/77593544/210094075-efe6bc34-2dc2-451d-b34d-341d38fe0999.png)
If the window is already maximized thru code, the Restore button should be the one displayed, and not the Maximize button.
![image](https://user-images.githubusercontent.com/77593544/210094174-2abe7743-043a-4e8a-a3cb-489f601d9d73.png)

### Steps to reproduce the bug

1. Set the custom title bar in the C# code-behind. AppTitleBar is defined in the XAML file. Please define your own.
![image](https://user-images.githubusercontent.com/77593544/210094370-8c261382-9bf3-442f-b241-dc3f27e0c476.png)

2. Define the method that maximizes the window using [AppWindow](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/windowing/windowing-overview)
![image](https://user-images.githubusercontent.com/77593544/210094798-49abf883-1e88-4a82-803a-f48b3b8e4a16.png)

3. Add the method created to the constructor method.
![image](https://user-images.githubusercontent.com/77593544/210094897-e0b48ca7-4488-4d6d-b13a-7129dc56a971.png)

Run the app.

### Expected behavior

If the window is already maximized thru code, upon display of the window on screen, the Restore button should show instead of the Maximize button.

### NuGet package version

WinUI 3 - Windows App SDK 1.2.2: 1.2.221209.1

### Windows version

Windows 11 (22H2): Build 22621

**Comment by pratikone** [comment]
I checked it yesterday. Your code is calling `Maximize()` in constructor which is too early for the maximize button. Maximize button in WinUI 3 custom titlebar is a typical Xaml button. It gets created after XamlRoot. In constructor, even XamlRoot is null because it gets created later. Since it is not created by the time maximize function gets called, its icon is not updated correctly. 

You can just add a `Loaded` event listener to any UIElement in your app like AppTitleBar and call your code in there.

```c#
public MainWindow()
 {
    this.InitializeComponent();
     ...
    // Appwindow captured in appWindow variable
    AppTitleBar.Loaded += (_, _) =>
    {
       AppWindowPresenter p = appWindow.Presenter;   // you may want to write extra code to capture appwindow variable 
       OverlappedPresenter wp;
       wp = (OverlappedPresenter)p;
       wp.Maximize();
    };

...
```
This Loaded event handler will be called when all UI elements have been created, XamlRoot has been created and as a result, min max and close buttons are created too.

Since it is a side effect of design of Xaml Root and creation of UI elements, I am closing this bug.
