### ISSUE TITLE
Background color tearing when resizing window

### ISSUE THREAD

**Issue by wormusmaximus** [microsoft/microsoft-ui-xaml#8092]
### Describe the bug

The background color of top level control of window has tearing effect when the user drags the window to resize.

If you create default WINUI3 app in visual studio then change top level child control of the MainWindow.xaml to Grid and set background color non-transparent color (ex. red). 

Then start app and drag the window to resize. You will see that the border on the right side is white. Like the grid object is not adapting quick enough.

### Steps to reproduce the bug

// USING DEFAULT WINUI3 APP TEMPLATE.

// CHANGED TOP LEVEL CONTROL TO GRID AND SET BACKGROUND COLOR. BELOW IS ONLY CODE MainWindow.xaml CONTAINS.

```
<Grid Background="Red">
        <StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
            <Button x:Name="myButton" Click="myButton_Click">Click Me</Button>
        </StackPanel>
    </Grid>
```

### Screenshots

Screenshot of issue.
https://1drv.ms/v/s!AmXfyJ0hgFGtgcNm1Z0xWvZnQDatCw?e=zdmLpq

### NuGet package version

WinUI 3 - Windows App SDK 1.2.2: 1.2.221209.1

### Windows version

Windows 11 (21H2): Build 22000

**Comment by wormusmaximus** [comment]
The WinUI3 Gallery App doesn't seem to have this problem, but I can't figure out how to fix it in non UWP app.

**Comment by DarranRowe** [comment]
Just to ask, is this what you mean?

https://user-images.githubusercontent.com/52577874/212414863-15f63e61-03b9-4343-bcd5-9d216ab34f2e.mp4

If so, then this is a difficult problem to deal with because of what needs to be done on a resize. What's more, a resize like that is normally made up of several small resize operations and each of them can do some very heavy things.
