### ISSUE TITLE
Accessibility Bug

### ISSUE THREAD

**Issue by HppZ** [microsoft/microsoft-ui-xaml#814]
UI accessibility checker reported an error as blow:
![image](https://user-images.githubusercontent.com/12285582/59016303-883fa600-8873-11e9-9a83-4a98f242b3ac.png)

then  I created an empty UWP project, and the checker still report that error.
I think this is a bug.

Windows 10 1903.

**Comment by jevansaks** [comment]
@HppZ does the Accessibility Insights tool report this problem too? I'm not familiar with the UIAccess tool.

**Comment by HppZ** [comment]
C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64\AccChecker\acccheckui.exe

1, run a UWP empty app
2, run the acccheckui.exe
3, verifications menu -> enable all
4, verifications tab -> choose window from list
5, verifications menu -> run now
6, wait for results

**Comment by jevansaks** [comment]
@robgallo @karanbirsingh @AhmedAbdoOrtiga I see you as contributors to [accessibility insights](https://github.com/microsoft/accessibility-insights-windows). Do you know about this AccCheckUI tool? It seems the current recommendation would be to use Accessibility Insights now instead of that tool, right?

**Comment by RobGallo** [comment]
Hi, Jevan,

Yes, please use Accessibility Insights. You can learn all about it at https://accessibilityinsights.io/.

Thanks,
Rob
