### ISSUE TITLE
The Textbox cursor color is transparent

### ISSUE THREAD

**Issue by lgBlog** [microsoft/microsoft-ui-xaml#8207]
### Describe the bug

When the mica background is enabled, the theme is Light.

After redefining the resource, the Textbox cursor becomes transparent. 
```
<Grid.Resources>
      <SolidColorBrush x:Key="TextControlBackgroundFocused" Color="Transparent"/>
</Grid.Resources>
```

### Steps to reproduce the bug

1.Set the Mica background。
2.
  ```
    <StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
        <StackPanel.Resources>
            <SolidColorBrush x:Key="TextControlBackgroundFocused" Color="Transparent"/>
        </StackPanel.Resources>
        <TextBox Height="100" Width="200"/>
    </StackPanel>
```
3.Click the Textbox to get focus.

### Expected behavior

The cursor should be black.

### Screenshots

![image](https://user-images.githubusercontent.com/84497351/219874274-7e26f911-421b-4879-b373-0bfe4c74c036.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.2.3: 1.2.230118.102

### Windows version

Windows 11 (22H2): Build 22621

**Comment by steam3d** [comment]
Windows App SDK 1.4.231008000 still has ths issue

**Comment by codendone** [comment]
Because of implementation details, this is expected behavior. The best option is to ensure that TextBoxes have an opaque background at least when they have key focus.

**Implementation Details:**
The TextBox cursor/caret are drawn with [DestinationInvert](https://learn.microsoft.com/windows/windows-app-sdk/api/winrt/microsoft.ui.composition.compositioncompositemode#fields), which inverts whatever color is at each pixel of the cursor. DestinationInvert is used to ensure visibility for any pixels regardless of whether they are text or background pixels or what color the text is (for emoji or potentially multi-color RichEditBoxes).

In general, that's all fine. There can be problems if the text or background are a medium gray, since the closer to the middle the pixels are between white and black, the closer the inverted color will also be. But the text and background colors are commonly far enough apart to ensure adequate constrast which also avoids an issue with inverting.

But the place where we hit a problem here is if the background beneath the TextBox is unknown. The background will be unknown when it is "external" content which isn't drawn by the WinAppSDK compositor. Mica and DesktopAcrylic backgrounds are two forms of external content (drawn by Windows), and WebView2, MediaPlayerElement, and SwapChainPanel are other forms of external content. For any form of external content, all the WinAppSDK compositor code can see is transparent black pixels where external content is (since the external content is drawn by Windows on a layer below the WinAppSDK compositor's rendering). The WinAppSDK compositor computing the inverted color will therefore invert that transparent black to be white.

Unfortunately, there isn't any way for the WinAppSDK compositor to see the real color of what is behind in order to correctly compute the inverted color. Given this, the best option is to ensure that TextBoxes have an opaque background at least when they have key focus.

**Comment by codendone** [comment]
Switching to a single color would have issues where the cursor isn't always visible, such as not being visible if the text color is used and the cursor is over text, or not being visible if the background color is used and the cursor is over the background. A completely different color could be used, such as red (assuming the text color isn't set to red), but this is not a standard design.

Hypothetically, a property could be added to support setting a fallback color if a non-standard design is wanted, or the cursor could be made styleable such that it could, for example, be the text color with a background color outline. (This has some extra complications when the cursor needs the direction indicator for right-to-left or bidirectional text.) But a fallback color or style support is not a feature we're likely to prioritize anytime soon.

**Comment by taublast** [comment]
Why not introduce a Brush for cursor tint so that if it's set, it would be applied; if not - then use DestinationInvert default.
