### ISSUE TITLE
`KeyboardAccelerator` added to `KeyboardAccelerators` executes twice

### ISSUE THREAD

**Issue by grork** [microsoft/microsoft-ui-xaml#8212]
### Describe the bug

When a `KeyboardAccelerator` is added to an elements `KeyboardAccelerators` collection, it is executed **twice**. Apparently once for key down, and another for key up.

### Steps to reproduce the bug

1. Create a new Blank WinUI 3 app
2. Open `MainWindow.xaml`, add `x:Name="Thing"` to the stack panel
3. Open `MainWindow.xaml.cs`
4. In the constructor add
```cs
var shortcut = new KeyboardAccelerator()
{
    Key = Windows.System.VirtualKey.P
};

shortcut.Invoked += (_, _) => System.Diagnostics.Debug.WriteLine("I shall say this only once");
this.Thing.KeyboardAccelerators.Add(shortcut)
```

5. Run with debugger
6. Press P with focus in the app

### Expected behavior

"I shall say this only once" appears **once** in the debug output window

### Screenshots

"I shall say this only once" appears **twice** in the debug output window

### NuGet package version

WinUI 3 - Windows App SDK 1.2.3: 1.2.230118.102

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

This does *NOT* repro with system xaml (aka UWP project template)

**Comment by MikeHillberg** [comment]
Are you setting `args.Handled` to true in the invoke handler?

**Comment by grork** [comment]
I am not — in either the WinUI or UWP version (where this does not repro)

**Comment by grork** [comment]
I can confirm that setting that in the WinUI 3 version does work around the issue.

Is this the *expected* behaviour? It seems odd to require this — the docs mention setting `Handled = true` to prevent bubbling, but this isn’t a bubbled scenario — I’m adding to the accelerators the first-child-of-`Window`, so I don’t expect anyone higher to be handling it.

**Comment by lhak** [comment]
I see the same issue when using a StandardUICommand and its default keyboard accelerator. The associated event handler is invoked multiple times. There is also no Handled parameter in the ExecuteRequested event handler to workaround this bug.

**Comment by JJBrychell** [comment]
I have been able to repro this in a UWP application with system Xaml and have confirmed that that the implementation is the same for both it and WinUI.

The framework allows the KeyDown event to route before checking for accelerators so that if an application chooses to handle the keydown, the accelerator processing will be skipped.  

While processing the keydown, it also checks for any local accelerators since if there are multiple accelerators defined with the same key, we want to process the one "closest" to the keyboard focus.  

Once the KeyDown has been routed, if it hasn't been handled, then the global accelerator processing is triggered to allow all accelerators a chance at it.

While technically, it could be argued that global accelerator process should skip anything that was checked during the keydown routing, that is not the way either UWP or WinUI accelerators are implemented, and they rely on the application marking the event as handled to prevent the duplicate execution.  So the behavior is currently by design.

**Comment by lhak** [comment]
@JJBrychell So what is the correct way to use an accelerator with StandardUICommand or XamlUICommand? There is no Handled property in the ExecuteRequestedEventArgs class.

**Comment by greatoceansoftware** [comment]
I'm experiencing a similar problem:

Having two controls on a page that expose a StandardUICommand, such as a MenuFlyoutItem and an AppBarButton, causes the command to run twice when using the KeyboardAccelerator for the command. Removing one control that exposes the command appears to resolve the issue.

I'd like to see some type of "Handled" flag that can be passed from the event handler as well to prevent the code from running multiple times.
