### ISSUE TITLE
symbolicon, pathicon do not center align 

### ISSUE THREAD

**Issue by KWodarczyk** [microsoft/microsoft-ui-xaml#8218]
### Describe the bug

symbolicon, pathicon do not center align 

### Steps to reproduce the bug

just create new winui project for desktop an paste this code

```
<Grid Background="Green" HorizontalAlignment="Center" VerticalAlignment="Center">

        <Viewbox 
            Width="80"
            Height="80"
            HorizontalAlignment="Center" 
            VerticalAlignment="Center">

            <SymbolIcon
                VerticalAlignment="Center"
                HorizontalAlignment="Center"
                Foreground="White"
                Symbol="Clock" />

        </Viewbox>
    </Grid>
```

### Expected behavior

should see icon center aligned 

### Screenshots

![image](https://user-images.githubusercontent.com/5243438/220461793-c2f028d5-02e0-4ceb-8967-2c81275f921c.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.2.3: 1.2.230118.102

### Windows version

Windows 10 (21H2): Build 19044

**Comment by Jay-o-Way** [comment]
Quick questions: does changing the Viewbox size change the space? Does using Fonticon change anything?

**Comment by KWodarczyk** [comment]
Why this is closed ? It's still a bug. It should remain open, otherwise people will get false impression that things are getting fixed but they are not.

**Comment by Masterain98** [comment]
@llongley @microsoftopensource This is an obvious bug. Can you give a reason for closing this issue as not planned? I see that your coworkers are doing this for you and most of the reasons they give are because the issue is not with WinUI3, but how do you explain this WinUI3 issue? Is this another "error" generated when closing issues in bulk?

**Comment by DmitriyKomin** [comment]
@Masterain98 Thank you for you feedback.

> Can you give a reason for closing this issue as not planned? I see that your coworkers are doing this for you and most of the reasons they give are because the issue is not with WinUI3, but how do you explain this WinUI3 issue? 

In this case, there indeed a WinUI3 issue, but unfortunately one we are not able to prioritize enough compared with other reported issues across the platform. While it would certainly be preferable if all glyphs in Segoe MDL2 Assets font centered correctly, we suspect centering problems show up only in specific glyphs. In these cases, developers can reasonably work around by adjusting SymbolIcon.Margin to fine-tune the position. A related concern with fixing this (at least naively) is it would regress apps already using Margin-based workarounds and such regressions being subtle and unintrusive would be tricky to detect.

> Is this another "error" generated when closing issues in bulk?

No, this was reviewed and discussed by myself and several colleagues working on WinUI. I apologize for the lack of context on the closure, it is certainly appropriate to expect here. We're currently adjusting our GH review process, and will try to make sure we include comments to explain "Won't Fix" resolutions.

@KWodarczyk thank you also for chiming in. The bug was closed as 'Not Planned' (also with closed-Won't Fix label) so hopefully it's clear the problem is not being addressed in the platform.

**Comment by Jay-o-Way** [comment]
...what about my questions..?

**Comment by Lightczx** [comment]
Even the start menu icon is not center aligned 🤣🤣🤣
![fd403032e3d70c006d6bf85b19312659](https://github.com/microsoft/microsoft-ui-xaml/assets/36357191/9f394d7d-ba03-4c20-a230-a84272a71002)

**Comment by Jay-o-Way** [comment]
@llongley we deserve an answer! Or I'm telling @bpulliam
@KWodarczyk can you answer my questions too?

**Comment by KWodarczyk** [comment]
@Jay-o-Way  once I get time I will.
