### ISSUE TITLE
Microsoft.UI.Xaml.UnhandledExceptionEventArgs: "Unspecified Error"

### ISSUE THREAD

**Issue by markolbert** [microsoft/microsoft-ui-xaml#8339]
### Describe the bug

There's not much I can do to describe this error, since the error itself is totally and completely useless in providing any information about what went wrong :). I'm not even sure what's throwing the error, except that I don't think it's in my code (because I turned on "break on first exception" for every exception in Visual Studio and no additional information was reported).

I'm not sure if this is a WinUI 3 issue or something else, but it would be really, really, really helpful if whoever is in charge of the code base that's tossing exceptions with useless error messages like "Unspecified Error" looked through their code and replaced each and every occurrence with something meaningful. Because right now all the "error reporting" amounts to is "something went wrong". Which I kind of knew because my app crashed :).

### Steps to reproduce the bug

I'm happy to provide my code to someone if they want to examine it. But since I can't get rid of the bug and I have no idea where it came from I can't describe how to reproduce it.

### Expected behavior

A helpful error message which gave at least a hint of what went wrong would be very nice.

### NuGet package version

None

### Windows version

Windows 11 (22H2): Build 22621

**Comment by markolbert** [comment]
Interesting, and thanx for the perspective/insight. I'm sorry to hear how common unhandled exceptions are. It seems like poor coding practice or system architecture (don't take that personally, please). And similar to what I would expect to do myself, as a reasonably decent but amateur programmer :).

Before I close this, any thoughts on why unhandled exceptions are allowed to be generated? For example, is it the result of "don't have time to do it the right way"? Or "too bad we didn't think of it, but implementing it now would require significant redesign"? Or "great idea, but it would seriously hamper performance if we designed the library that way?" Or something else?

Just curious.

**Comment by kmgallahan** [comment]
> don't take that personally, please

I had zero involvement and agree that [vexing exceptions](https://ericlippert.com/2008/09/10/vexing-exceptions/) are a bad thing.

> any thoughts on why unhandled exceptions are allowed to be generated?

Window's code base is 2-3 decades old, and WinRT + C#/WinRT is ~10 years old. Hard to say what went into the exception-related decisions over that long of a time span, but can't really be helped much at this point.

I imagine part of the thinking is that no internal exceptions should be handled throughout windows so that any external code can catch them and do whatever it likes (including debuggers). Poor error naming/details comes down to the complexity of root cause analysis: https://devblogs.microsoft.com/oldnewthing/20040422-00/?p=39683

**Comment by markolbert** [comment]
A nice article, and now I know the term to search on for more info (root cause analysis). Thanx! I’ll close the issue
