### ISSUE TITLE
How to capture crashes in WinUI3 application in debug mode

### ISSUE THREAD

**Issue by NandishNR** [microsoft/microsoft-ui-xaml#8356]
### Describe the bug

Came up with bigger application using WinUI3 and facing difficulty to find crashes. Application will crash without any clue on what it is crashing. Tried with enabling all kind of exceptions but not able to track.

Used DebugSettings and registered UnhandledException but not able to capture.

### Steps to reproduce the bug

No such steps to mention here

### NuGet package version

None

**Comment by RoyLicx** [comment]
I want to know when does the crash happens.  Does it happen as soon as you launch the app or it happens when the app has been running for a while?

I’d also suggest that you could try to narrow down the issue first. You could try to remove some parts of the code from your app to confirm which part will cause the crash. Then you could delete unnecessary code, share a repro and repro steps with us. So we could check this issue further.

Besides, could you please take a look at the event viewer to check the error information?

**Comment by duncanmacmichael** [comment]
This seems like a general troubleshooting issue with no specific context or concrete direction for closure. I'm going to close it for now as it appears to have gone dormant - if the original poster replies to Roy's comment, we can re-open.
