### ISSUE TITLE
WinUI 2.8+ requires WebView2 winmd, which forces a DLL into the package

### ISSUE THREAD

**Issue by DHowett** [microsoft/microsoft-ui-xaml#8357]
### Describe the bug

Building with WinUI 2.8 requires an additional package dependency on `Microsoft.Web.WebView2`.

The build rules for `Microsoft.Web.WebView2` forcibly copy `Microsoft.Web.WebView2.dll` into my package.

I am not using WebView2. This costs 600kb on disk, which my WPG disk size gates complain about.

I cannot build a project that uses XAML without this dependency.

Can XAML package the necessary parts of the WebView2 `winmd` itself, and include them as a reference? That way, you only need to depend on `Microsoft.Web.WebView2` if you're actually using WebView2.

### Steps to reproduce the bug

Add a dependency on the XAML 2.8 package.

### NuGet package version

WinUI 2 - Microsoft.UI.Xaml 2.8.2

**Comment by zadjii-msft** [comment]
As a point of note for other readers: We worked around this with something _incredibly silly_: https://github.com/microsoft/terminal/pull/15096/files

Essentially, instead of `Import`ing `Microsoft.Web.WebView2.targets`, we added a `Reference` directly to `Microsoft.Web.WebView2.Core.winmd` from the WebView2 package. This let us ingest _just_ the winmd for the sake of mdmerge, but not include the DLL in our package. Since the DLL is only loaded if you try to instantiate a WebView, and we weren't using a WebView, we can safely leave it out of our package.

**Comment by sylveon** [comment]
I have my own silly workaround for this:
```xml
  <Target Name="RemoveWebView2" BeforeTargets="ResolveAssemblyReferences">
    <ItemGroup>
      <_WebView2Reference Include="@(Reference)" Condition="'%(Filename)' == 'Microsoft.Web.WebView2.Core'" />
      <Reference Remove="@(_WebView2Reference)" />
      <Reference Include="@(_WebView2Reference)" RemoveMetadata="Implementation" />

      <ReferenceCopyLocalPaths Remove="@(ReferenceCopyLocalPaths)" Condition="'%(Filename)' == 'Microsoft.Web.WebView2.Core'" />
    </ItemGroup>
  </Target>
```

**Comment by sylveon** [comment]
If you're using C++, you can save more disk space by avoiding copying the winmd file in your output package, like this:
```xml
<Reference Include="@(_WebView2Reference)" RemoveMetadata="Implementation">
  <Private>false</Private>
</Reference>
```

**Comment by DmitriyKomin** [comment]
Unfortunately we are not currently investigating WinUI2 issues that are not business or security critical (more on the policy [here](https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/contribution_handling.md#winui-2)).
