### ISSUE TITLE
SymbolIcon broken in non english languages.

### ISSUE THREAD

**Issue by ZH-PurpleFox** [microsoft/microsoft-ui-xaml#8385]
### Describe the bug

The control symbolIcon of Winui3 will cause garbled code in non English environments

### Steps to reproduce the bug
     ##<SymbolIcon Symbol="Refresh"></SymbolIcon>

### Expected behavior

The control will be garbled instead of the expected Symbol.

### Screenshots

![批注 2023-04-12 093249](https://user-images.githubusercontent.com/130520997/231324767-ef374fd5-e5f1-4754-88e7-4d55a6fb56a9.png)

### NuGet package version

None

### Windows version

Windows 10 (21H2): Build 19044

**Comment by Jay-o-Way** [comment]
I know **exactly** why: https://github.com/MicrosoftDocs/winrt-api/issues/2363
Shame on Microsoft, for not having this fixed years ago.

**Comment by Jay-o-Way** [comment]
@crutkas where is this list with (what I call) "translations"? I'll do it myself if I have to.

**Comment by Jay-o-Way** [comment]
@karkarl this is what I meant in my pr

**Comment by Jay-o-Way** [comment]
**SymbolIcon** is practically deprecated. See https://github.com/microsoft/microsoft-ui-xaml/issues/5887#issuecomment-1642824614
Use a **FontIcon**.

**Comment by Jay-o-Way** [comment]
Hi @llongley can you explain how this issue is fixed?

**Comment by codendone** [comment]
@Jay-o-Way Looking at the internal issue, it looks like this was the fix: #8379. This fix was also in WinAppSDK 1.4.

**Comment by Jay-o-Way** [comment]
@codendone that's absolutely impossible. Those were specific icons in specific places. SymbolIcon uses a table to convert the words to numbers and that is not public. How is it possible that I have to tell you Microsoft people this? 😡

**Comment by Jay-o-Way** [comment]
@llongley please do clear up?

**Comment by karkarl** [comment]
Hey @Jay-o-Way, the fix for this issue was in 2 parts:
1) Update FontIcons in existing controls for WinUI2 & WInUI3 to the appropriate glyphs
2) Update the SymbolEnum to also map to the appropriate glyphs

The linked comment above (https://github.com/microsoft/microsoft-ui-xaml/pull/8379) was to update the controls in WinUI2. The same fix was ported over to WinUI3, and a separate PR was merged in for SymbolEnum. Both these PRs are internal and serviced for WASDK 1.4. Please let me know if you are still able to repro this issue.

Please reference the comment [here ](https://github.com/microsoft/microsoft-ui-xaml/pull/8379#issuecomment-1593855795)explaining.

**Comment by Jay-o-Way** [comment]
Okay, so it's internal and thus invisible, right? That's good to know. A comment like such would have been nice.

**Comment by karkarl** [comment]
> Okay, so it's internal and thus invisible, right? That's good to know. A comment like such would have been nice.

Actually, WinUI3 source is available now! Here's the code that maps the glyphs for your reference: https://github.com/microsoft/microsoft-ui-xaml/blob/winui3/release/1.5-stable/dxaml/xcp/core/core/elements/icon.cpp#L448

Note that the decision to write a map rather than replacing the glyphs explicitly is to avoid any breaking changes in the SymbolEnum API (and a whole formal API review).

**Comment by Jay-o-Way** [comment]
@karkarl thank you so much! I absolutely love the usefulness of your communication! You're the best!
