### ISSUE TITLE
winui3 and uwp Drag And Drop Bug

### ISSUE THREAD

**Issue by ZH-PurpleFox** [microsoft/microsoft-ui-xaml#8406]
### Describe the bug

 ```
<Grid AllowDrop="True" CanDrag="True" DragEnter="dragenter" Drop="drop">
        <Grid.RowDefinitions>
            <RowDefinition Height="*"/>
            <RowDefinition Height="Auto" />
        </Grid.RowDefinitions>
        <Image Grid.Row="0" Name="image" Stretch="Fill" CanDrag="True"></Image>
        <Button HorizontalAlignment="Center" Click="SelectImage" Content="select image" Grid.Row="1"/>
    </Grid>
```

> As shown in the above code, drag and drop can only be triggered on the button, and cannot be triggered in other areas
But when I add a background color to the grid
As follows：
 ```
<Grid AllowDrop="True" CanDrag="True" DragEnter="dragenter" Drop="drop"
          **_Background="White"_**>
        <Grid.RowDefinitions>
            <RowDefinition Height="*"/>
            <RowDefinition Height="Auto" />
        </Grid.RowDefinitions>
        <Image Grid.Row="0" Name="image" Stretch="Fill" CanDrag="True"></Image>
        <Button HorizontalAlignment="Center" Click="SelectImage" Content="select image" Grid.Row="1"/>
    </Grid>
```
Grid will trigger drag and drop events normally

**From this, it can be inferred that the empty layout cannot trigger the drag and drop events normally. Please correct it as soon as possible
UWP also has this bug**

### Steps to reproduce the bug

1.Establish the Winui3 project
2.Add grid layout
3.Enable drop and drop events

### NuGet package version

None

**Comment by codendone** [comment]
This is based on how input in general works: an element only receives pointer input (mouse/touch/pen) in areas where the element has visual content. That visual content includes any background or border for panels, as well as any visual content from children elements. As you discovered, setting `Background="white"` on the Grid will allow it to receive input for the entire bounds of the Grid, whereas otherwise it will only be where its children elements have visuals. If you want the Grid to receive input without having a visible background, you can set `Background="transparent"`, where `transparent` is a special hint for XAML that you want this area to be considered as having visual content without actually changing how things look on screen.

**Comment by ZH-PurpleFox** [comment]
ok，
It's just a detail, not a bug
