### ISSUE TITLE
[WinAppSDK] [WebView2] Context menu display behind the app window

### ISSUE THREAD

**Issue by Jimex** [microsoft/microsoft-ui-xaml#8506]
### Describe the bug

The context menu in the webview2 was displayed behind the app window, obstructed by the app window.

### Steps to reproduce the bug

1. Open the WinUI 3 Gallery app
2. Go to Media -> WebView 2
3. Right-click on the content in WebView2 browser 

### Expected behavior

The context menu should be displayed on top of the app window

### Screenshots

![image](https://github.com/microsoft/WindowsAppSDK/assets/3145858/94451c87-1311-4d58-afb6-141575185b7a)

### NuGet package version

None

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

**Comment by DmitriyKomin** [comment]
There has indeed been a regression in the WebView2Runtime affecting WinAppSDK WebView2 and causing context menus have incorrect z-order / appear behind the app window. That bug has been fixed in WebView2Runtime. Per [@champnic](https://github.com/champnic) on [@MicrosoftEdge](https://github.com/MicrosoftEdge):

> The fix is now in 113, 114, and 115. Devs can use Canary and Dev channels with the fix, and Stable should begin rollout today with the fix in 113.

> Here are the build numbers with the fixes in the respective major versions:
113.0.1774.51
114.0.1823.22
115.0.1853.0
