### ISSUE TITLE
Lack of touch interaction with the scrollbar.

### ISSUE THREAD

**Issue by Przeklin** [microsoft/microsoft-ui-xaml#8530]
### Describe the bug

When I try to use the scrollbar to scroll the content and there is a RepeatButton in the Generic.xaml styles, it doesn't respond to touch input. However, everything works fine when using a mouse. Also, when I try to use the HorizontalThumb element, the scrolling is not smooth, and it behaves in a very strange way. Specifically, when I want to scroll to the left, I have to perform gestures to the right. Everything works smoothly with the mouse, but when touch is involved, the behavior is terrible. Below I have uploaded a video file to illustrate the problem when the cursor disappears I start using touch. The arrows do not show the reapeatbutton being pressed at all.

### Steps to reproduce the bug

Unfortunately, I have no idea how to remove this error

### Expected behavior

The scrollbar behaves the same way as it does with the mouse.

### Screenshots

https://github.com/microsoft/microsoft-ui-xaml/assets/45576806/f48eaf15-4611-457f-a87e-f8b97db9d93a

### NuGet package version

WinUI 3 - Windows App SDK 1.3.1: 1.3.230502000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by RBrid** [comment]
Thank for the report. We consider this by design - the ScrollBar does not respond to touch input to let the underlying ScrollView or ScrollViewer surface handle the input and perform a pan or zoon operation. The user needs to use the mouse in the first place to show the Thumb and RepeatButtons, so having them support touch input is not critical.

**Comment by Poopooracoocoo** [comment]
So iPads are still a superior tablet experience. Got it.
