### ISSUE TITLE
Dialog button does not show all text at 200% scaling

### ISSUE THREAD

**Issue by marzha** [microsoft/microsoft-ui-xaml#864]
**Describe the bug**
We (Photos team) got this bug as a part of accessibility testing

**Steps to reproduce the bug**

1. Create dialog box with a button with long text
2. Set the screen resolution to 1280x768.
3. Set text size to 225% (Settings -> Ease of access -> Make text bigger).

**Expected behavior**
Text in dialog box does not scale with 200% text scaling

**Screenshots**

**Version Info**

NuGet package version: 
Standard content dialog

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (18908)              | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |
| Anniversary Update (14393)         |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |

**Additional context**
Link to bug https://microsoft.visualstudio.com/OS/_workitems/edit/22018027?src=WorkItemMention&src-action=artifact_link

**Comment by jevansaks** [comment]
Only font size scales with the text scaling setting, but the UI sizes don't. Things like ContentDialog have fixed width and don't grow. Should we consider having some of these things be more elastic or having text scaling factor in to dialog sizes? Flipping this to a feature request.

**Comment by YuliKl** [comment]
> Things like ContentDialog have fixed width and don't grow. 

That's not entirely true. ContentDialog has two resources in generic.xaml that control its width:
```xaml
<x:Double x:Key="ContentDialogMinWidth">320</x:Double>
<x:Double x:Key="ContentDialogMaxWidth">548</x:Double>
```
When playing with the Xaml Controls Gallery, I can see the sample dialog become wider with the increased font size.

@marzha, the Photos app appears to have run up against the 548 max width at 100% text scale. I don't know the history of why 548 was chosen as the maximum width for ContentDialog and I hesitate to change this width in the SDK. But I'm not aware of a reason why the Photos app can't make the change locally by, for example, changing the ContentDialogMaxWidth of just this backup dialog.

**Comment by KevBrown42** [comment]
I don't think that making this control work well in this scenario (which is an accessibility requirement) should be up to each app.  We would need to update every usage of the common control in the app in case the button text translated to something too long to display at 200% text size in any of the languages that we support.

I think there is a valid design question about how this common dialog should support 200% text scaling (should the button get more width or height?), but I don't think each app should have to work around the issue. 

Could you please reconsider?

Thanks!

**Comment by YuliKl** [comment]
Another option is to change ContentDialog's button text to wrap, but we've avoided doing this in the past. @Chigy, do you have context as to why that is?
Also tagging @stmoy in case you have any other thoughts/suggestions.

**Comment by YuliKl** [comment]
@marzha, @KevBrown42 - I continue to believe that the most straight-forward solution to this problem is at the app level rather than the control level. ContentDialog's buttons have undergone a lot of finessing to support a majority of app scenarios. I don't think we'll be able to prioritize changing them any time soon.

To fix this particular issue, I recommend making one of the following changes in your app:
* Shorten the text that's being clipped. You can likely remove one of the words in the label without loss of meaning.
* Allow this instance of ContentDialog to become even wider, as outlined in my earlier reply.
* Add your own buttons to ContentDialog's content instead of leveraging the built-in ones. I don't necessarily recommend this option because you'll need to do quite a bit of work to recreate the default buttons' keyboard behavior.

I realize that it would be more convenient for ContentDialog to provide a solution out of the box. Unfortunately we're heads down working on [WinUI 3.0](https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/roadmap.md) and can't prioritize revisiting ContentDialog's design when app-side solutions exist.
