### ISSUE TITLE
Cannot hide caption button on titlebar

### ISSUE THREAD

**Issue by khoabui1412** [microsoft/microsoft-ui-xaml#8705]
### Describe the bug

Following https://github.com/castorix/WinUI3_CustomCaption,
Override x:Key="WindowChromeStyle" to hide caption buttons, so I can add my custom caption with appropriate height and style.
But when updating to wasdk ver 1.4-preview1, I cannot hide the caption button anymore.

### Steps to reproduce the bug

Update wasdk to ver 1.4-preview1 with above source

### NuGet package version

WinUI 3 - Windows App SDK 1.4 Preview 1: 1.4.230628000-preview1

**Comment by riverar** [comment]
@Scottj1s @pratikone @rkarman Looks like a 1.3 to 1.4 regression beware; any thoughts on why the captions/etc. are no longer pulling from app resource dictionaries?

WAS 1.3.230502000
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/475132/419969df-5eba-4e03-a89c-80c62f4bbf45)

WAS 1.4.230628000-preview1
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/475132/91230dc3-054e-4336-b536-0bc497e05dcc)

Simpler repro (file, new, WinUI packaged...)

MainWindow.xaml
```
<?xml version="1.0" encoding="utf-8"?>
<Window
    x:Class="winui_1_3.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:winui_1_3"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
        <Button x:Name="myButton" Click="myButton_Click">Click Me</Button>

        <Grid x:Name="AppTitleBar">
        </Grid>
    </StackPanel>
    
</Window>
```

MainWindow.xaml.cs
```
    public MainWindow()
    {
        this.InitializeComponent();

        ExtendsContentIntoTitleBar = true;
        SetTitleBar(AppTitleBar);
    }
```

App.xaml
```
...
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
                <!-- Other merged dictionaries here -->
            </ResourceDictionary.MergedDictionaries>

            <SolidColorBrush x:Key="WindowCaptionButtonBackground" Color="Green" Opacity="0.4"/>
            <SolidColorBrush x:Key="WindowCaptionButtonBackgroundPointerOver" Color="Yellow" Opacity="0.5"/>
            <SolidColorBrush x:Key="CloseButtonBackgroundPointerOver" Color="Magenta" Opacity="0.8"/>

        </ResourceDictionary>
    </Application.Resources>
...
```

**Comment by DarranRowe** [comment]
I do remember them mentioning that they would be consolidating windowing related things with AppWindow. I think it was with the intent that things that should logically be in AppWindow/AppWindowTitleBar would use the same behaviour as those.
If this is true then as a complete and utter guess, it would be possible that not everything is hooked up yet. From your screenshots, the 1.4 custom title bar looks a little larger and sharper. The older implementation of the custom title bar didn't work properly with scaling larger than 100%, but AppWindowTitleBar's implementation did.
I guess one way to test this out is to remove the minimise and maximise buttons. Since I believe that Window's custom title bar implementation still kept all 3 buttons, but AppWindowTilteBar's implementation removed them properly.

**Comment by DarranRowe** [comment]
Yeah, 1.4 Preview 1 is acting more like it is using AppWindowTitleBar's implementation rather than Window's implementation from 1.3.
Using the code:
```
MainWindow::MainWindow()
{
    InitializeComponent();

    auto win_native = try_as<IWindowNative>();
    HWND native_handle{};
    win_native->get_WindowHandle(&native_handle);

    DWORD ws = static_cast<DWORD>(GetWindowLongPtrW(native_handle, GWL_STYLE));
    DWORD nws = ws & (~WS_MINIMIZEBOX) & (~WS_MAXIMIZEBOX);
    SetWindowLongPtrW(native_handle, GWL_STYLE, nws);
    ExtendsContentIntoTitleBar(true);
}
```
to initialise the window, 1.3 gives:

![Screenshot 2023-08-05 003701](https://github.com/microsoft/microsoft-ui-xaml/assets/52577874/a4d23bae-04ee-4361-9a6f-17cab4822107)

where 1.4 gives:

![Screenshot 2023-08-05 004314](https://github.com/microsoft/microsoft-ui-xaml/assets/52577874/c9a5e2e3-2894-40b9-8657-523fb14195af)

As reference, a Windows API application using AppWindowTitleBar.ExtendsContentIntoTitleBar looks like:

![Screenshot 2023-08-05 002642](https://github.com/microsoft/microsoft-ui-xaml/assets/52577874/da778a6b-41b6-4949-8487-32be5e89c998)

This was from a little sample that was messing around with the Visual Layer.

**Comment by khoabui1412** [comment]
It's also messed up with Drag and Maximizable when ExtendsContentIntoTitleBar=true. In 1.3, I can use ExtendsContentIntoTitleBar = true, then hide caption button to disable Maximization, but in 1.4, I cannot disable maximization when ExtendsContentIntoTitleBar=true.
Actually, better winUI3 should support api to hide fully the default titlebar (since the custom titlebar is not fully supported yet), then I can easily to add the custom titlebar and its behavior (drag, maximize,...) by windows native api.

**Comment by DarranRowe** [comment]
You shouldn't need to do anything weird to disable maximise. As an example, using AppWindowTitleBar for 1.3, removing the WS_MAXIMIZEBOX style results in the maximise button being greyed out and unclickable.

![Screenshot 2023-08-05 131931](https://github.com/microsoft/microsoft-ui-xaml/assets/52577874/e7b142e6-c2e2-4d66-9dde-bbdac516de90)

There is a bug with 1.4 where it will show it in the greyed out colours, but the button will still be clickable. But when this is fixed, all you should have to do is get the presenter from AppWindow and tell it not to be maximisable.

```
    MainWindow::MainWindow()
    {
        InitializeComponent();

        auto presenter = AppWindow().Presenter().as<Microsoft::UI::Windowing::OverlappedPresenter>();
        presenter.IsMaximizable(false);

        ExtendsContentIntoTitleBar(true);
    }
```

I used SetWindowLongPtr in my previous post, but the whole point of that was to explicitly show that AppWindowTitleBar respected the window styles. OverlappedPresenter.IsMaximizable and OverlappedPresenter.IsMinimizable modify the styles and these would be how you would modify this.

For the drag region, since 1.4 could be thought of as effectively forwarding Window.ExtendsContentIntoTitleBar to AppWindowTitleBar.ExtendsContentIntoTitleBar, this means that using the means described in [Title bar customization](https://learn.microsoft.com/en-us/windows/apps/develop/title-bar?tabs=wasdk#title-bar-content-and-drag-regions) to put interactive content would be how you would set the drag region. However, there are hints in the 1.4 .winmd files that this will change.
For 1.4 Preview 1, SetDragRectangles is defined as:
```
[deprecated("Use Microsoft.UI.Input.InputNonClientPointerSource.ConfigureRegion instead of SetDragRectangles.  For more info, see MSDN.", deprecate, Microsoft.Foundation.WindowsAppSDKContract, 1.4)] HRESULT SetDragRectangles([in] UINT32 __valueSize, [in] [size_is(__valueSize)] Windows.Graphics.RectInt32* value);
```
in idl. However, this InputNonClientPointerSource doesn't exist in 1.4 Preview 1. Checking 1.4 Experimental 1 results in:
```
            [contract(Microsoft.Foundation.WindowsAppSDKContract, 1.4)]
            [exclusiveto(Microsoft.UI.Input.InputNonClientPointerSource)]
            [experimental]
            [uuid(E1675231-4078-5F25-83B2-DA8FA52590FB)]
            interface IInputNonClientPointerSource : IInspectable
            {
                HRESULT ConfigureRegion([in] Microsoft.UI.Input.NonClientRegionKind region, [in] UINT32 __rectsSize, [in] [size_is(__rectsSize)] Windows.Graphics.RectInt32* rects);
                HRESULT ClearAllRegions();
                HRESULT ClearRegion([in] Microsoft.UI.Input.NonClientRegionKind region);
                HRESULT QueryRegion([in] Microsoft.UI.Input.NonClientRegionKind region, [out] UINT32* __resultSize, [out] [retval] [size_is(, *__resultSize)] Windows.Graphics.RectInt32** result);
                [eventadd] HRESULT CaptionTapped([in] Windows.Foundation.TypedEventHandler<Microsoft.UI.Input.InputNonClientPointerSource*, Microsoft.UI.Input.NonClientRegionCaptionTappedEventArgs*>* handler, [out] [retval] EventRegistrationToken* token);
                [eventremove] HRESULT CaptionTapped([in] EventRegistrationToken token);
                [eventadd] HRESULT ConfigurationChanged([in] Windows.Foundation.TypedEventHandler<Microsoft.UI.Input.InputNonClientPointerSource*, Microsoft.UI.Input.NonClientRegionConfigurationChangedEventArgs*>* handler, [out] [retval] EventRegistrationToken* token);
                [eventremove] HRESULT ConfigurationChanged([in] EventRegistrationToken token);
                [eventadd] HRESULT Hover([in] Windows.Foundation.TypedEventHandler<Microsoft.UI.Input.InputNonClientPointerSource*, Microsoft.UI.Input.NonClientRegionHoverEventArgs*>* handler, [out] [retval] EventRegistrationToken* token);
                [eventremove] HRESULT Hover([in] EventRegistrationToken token);
            }
```
So it looks like this will be the way to configure the title bar drag region in the future.

**Comment by riverar** [comment]
We have demonstrated the 1.4 regression, now we pray we can make enough noise to get someone's attention. 🙂

**Comment by khoabui1412** [comment]
The reason I do this because I want the title bar like this: 
<img width="122" alt="image" src="https://github.com/microsoft/microsoft-ui-xaml/assets/65955727/4d0b1d0d-f2dd-490e-a0ee-21aeb248fead">
In ver1.3: I can hide default titlebar by set ExtendsContentIntoTitleBar and collapse resource caption in app resource, then add my titlebar by win api.
In ver1.4: I cannot pull caption resource, so I tried:
`            ((OverlappedPresenter)this.AppWindow.Presenter).SetBorderAndTitleBar(true, false);`
But it has redundant edge line at the top of titlebar:
<img width="153" alt="image" src="https://github.com/microsoft/microsoft-ui-xaml/assets/65955727/6522d6a3-6d56-442d-b650-489fa1756ea7">

**Comment by DarranRowe** [comment]
Is setting the button colours via AppWindowTitleBar not working?
Since you still haven't really explained exactly what you are trying to do, I have to make the assumption off of your last post that you are just making the title bar constantly dark coloured.

![Screenshot 2023-08-07 102508](https://github.com/microsoft/microsoft-ui-xaml/assets/52577874/f1dd0a57-aecc-4b64-91b5-c8db164abddd)

While the rest of the custom title bar hasn't been set here, as you can see, the close button has been set to black. The code for this was a relatively simple:
```
	void main_window::set_caption_button_colour()
	{
		auto title_bar = m_appwindow.TitleBar();

		if (AppWindowTitleBar::IsCustomizationSupported() && title_bar.ExtendsContentIntoTitleBar())
		{
			auto black_colour = Colors::Black();
			auto white_colour = Colors::White();
			auto dark_grey = Colors::DarkGray();

			title_bar.ButtonBackgroundColor(IReference(black_colour));
			title_bar.ButtonForegroundColor(IReference(white_colour));
			title_bar.ButtonInactiveBackgroundColor(IReference(black_colour));
			title_bar.ButtonInactiveForegroundColor(IReference(dark_grey));
		}
	}
```
IIRC, this should work even on Windows 10 since this is working with full customisation. The restriction for simple customisation should be down to setting the colours requires using DwmSetWindowAttribute, and the colours are only available starting with Windows 11.

Anyway, the problem you are seeing is an underlying Windows problem. When you have the WS_THICKFRAME style (aka resizable) without the WS_CAPTION style, then Windows paints that line at the top of the window.

**Comment by khoabui1412** [comment]
@DarranRowe, what Iam trying to do is custom not only title bar but caption button with other size(margin, width, height, image,...), you can see my title bar and caption button will have smaller height compared to default

**Comment by DarranRowe** [comment]
Right, I can see how using that method to override the title bar would be easier than having to set things up using DWM.
I hope this issue is fixed for you quickly.

**Comment by pratikone** [comment]
With winappsdk 1.4, WinUI 3 custom titlebar uses appwindow titlebar under the hood. As a result, it is more stable, design wise consistent and other thing. But, it also means it is less customizable and follows strict guidelines which appwindow titlebar enforces. One of them is caption buttons cannot be hidden. You can create a feature request for this which would be a separate issue from this.

If you want to go experiemental, try removing WS_MAXIMIZEBOX style and see if it removes maximize button. I remember discussing this with appwindow titlebar owners and they mentioned that some functionality will break due to missing maximize button. But you can try it.

Another approach would be to set caption button colors to match background. However, it cannot be set to transparent by design.

Last one is to roll out own custom titlebar but use https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.input.inputnonclientpointersource to do NC heavy lifting
