### ISSUE TITLE
NavigationView hamburger button shows the Focus rectangle when using the mouse when resizing

### ISSUE THREAD

**Issue by ArchieCoder** [microsoft/microsoft-ui-xaml#8706]
### Describe the bug

Using the mouse, when resizing at smaller size, the big white rectangle will appear around the hamburger menu. It's affecting all apps using the NavigationView.

https://github.com/microsoft/microsoft-ui-xaml/assets/1608424/b04a3c55-c00d-4d8c-b8b0-7494080da6ff

Screenshots
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/1608424/6b51f167-13ca-47b7-9281-573885d82ee6)

### Steps to reproduce the bug

1- Launch the WinUI 3 gallery app by Microsoft
2- Resize the app to a smaller size using the mouse

### Expected behavior

No focus rectangle

### NuGet package version

WinUI 3 - Windows App SDK 1.3.3: 1.3.230724000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by ArchieCoder** [comment]
@sotanakamura oops, I forgot to specify that the sample app is the WinUI 3 Gallery app. I modified it.

I logged the bug 1 year ago but I forgot to make it "not dead".

The bug affects all the apps using the NavigationView control.

**Comment by sotanakamura** [comment]
https://github.com/microsoft/microsoft-ui-xaml/issues/7088#issue-1234232680

**Comment by riverar** [comment]
Can't reproduce this in code or WinUI Gallery. What version of the app are you using?

https://github.com/microsoft/microsoft-ui-xaml/assets/475132/9a8ee02c-9a03-4f96-9184-bde56cef1da7

**Comment by kmgallahan** [comment]
@riverar To reliably repro I have to first collapse the NavigationMenu, then click the search icon, then resize.

Also note that doing it this way causes a focus box to first appear around the "Home" entry when the menu initially collapses, unless the back button is active, in which case it gets focus.

I think focus is just getting transferred to the first enabled focusable item on the page if whatever was previously focused gets removed.

**Comment by ArchieCoder** [comment]
@riverar Windows 11 22H2 - 22621.2070

Video WinUI 2 and 3.
https://github.com/microsoft/microsoft-ui-xaml/assets/1608424/4f3dd16f-6a09-481b-b4fe-58ca932e7dff

**Comment by riverar** [comment]
Thanks @ArchieCoder, I can reproduce the focus visual appearing now.

I don't think there's a WinUI bug here.

WinUI 3 Gallery appears to set **keyboard** focus state on its `AutoSuggestBox` at startup, if I'm reading the code correctly ([code](https://github.com/microsoft/WinUI-Gallery/blob/main/WinUIGallery/Navigation/NavigationRootPage.xaml.cs#L269-L272)):

```csharp
if ( NavigationViewControl.DisplayMode == NavigationViewDisplayMode.Expanded)
{
    controlsSearchBox.Focus(FocusState.Keyboard);
}
```

This focus state is retained during collapse of the `AutoSuggestBox` when the window is resized. Because you did not change focus using the mouse (or any other means), keyboard focus and the associated visual shifts to a visible control. (If it didn't, the user could potentially get lost.)

I would argue this is a WinUI Gallery bug; they should probably use `FocusState.Programmatic` instead.

Example of both states in action included below.

https://github.com/microsoft/microsoft-ui-xaml/assets/475132/1d3ad234-d880-4511-8fff-24f15640d851

https://github.com/microsoft/microsoft-ui-xaml/assets/475132/720a83a6-4e58-4632-9f94-68c636c168a2

**Comment by ArchieCoder** [comment]
Thanks again @riverar. Agree to close!
