### ISSUE TITLE
BitmapImage is not loading the online OSM link URI in the view

### ISSUE THREAD

**Issue by VishalOmprasad** [microsoft/microsoft-ui-xaml#8724]
### Describe the bug

We are using the BitmapImage to set the ImageSource for the custom view in the native Xamarin.Forms code. In order to obtain the online URI of OSM (https://a.tile.openstreetmap.org/1/1/1.png), we have used the BitmapImage. However, the BitmapImage has failed to load the online OSM URI link. We received an exception in the ImageFailed event. We have prepared a simple UWP sample to replicate the issue.

Sample link: 
[App2.zip](https://github.com/microsoft/microsoft-ui-xaml/files/12287223/App2.zip)

### Steps to reproduce the bug

1. Run the sample.
2. exception will thrown.be

### Expected behavior

The OSM tile image should be loaded.

### Screenshots

<img width="464" alt="UWP-OSM-ErrorMessage" src="https://github.com/microsoft/microsoft-ui-xaml/assets/102582824/f4839a8d-1a02-435b-8ac7-f5f2345012f1">

### NuGet package version

None

**Comment by DmitriyKomin** [comment]
Hi @VishalOmprasad, thank you for filing the issue. The provided repro app is UWP + OS Windows.UI.Xaml.dll, and unfortunately we are not currently investigating UWP/OS Xaml/WinUI2 issues that are not business or security critical (more on the policy [here](https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/contribution_handling.md#winui-2)). Please comment here if you determine that the issue reproes in WinAppSDK/WinUI3, and we will investigate.

On a side note - since network error is reported, could it be related to UWP capabilities? In the repro project, only _Internet (Client)_ capability is checked, perhaps some other(s) are needed for successful network transfer (eg _Internet(Client & Server)_, _Private Networks (Client & Server)_, etc)?
