### ISSUE TITLE
Not entering into App destructor on Application close.

### ISSUE THREAD

**Issue by Ajith-GS** [microsoft/microsoft-ui-xaml#8734]
### Describe the bug

I have created an app distructor in the App class of a WinUI3 project. But the distructor is never called when closing the application.
My requirement is to show some UI in the WinUI 3 window whenever I click a button from a native Win32 application. The WinUI3 window is showing the first time, but the second time it crashes. I think this is because the app instance was not releasing when closing the WinUI3 window.
Any help is appreciated.

### Steps to reproduce the bug

1. Create C++ project template from "Blank App, Packaged (WinUI3 in Desktop)"
2. Add App::~App() to h/cpp with some code and a breakpoint.
3. Start debug.
4. Close app.
5. The breakpoint never hits.

### Expected behavior

The breakpoint must be hit every time you close the application.

### NuGet package version

Windows App SDK 1.3.2: 1.3.230602002

### Packaging type

Unpackaged

### Windows version

Windows 10 version 22H2 (19045, 2022 Update)

### IDE

Visual Studio 2022

**Comment by DarranRowe** [comment]
This has been happening for quite a while.
This still happens in 1.4 Preview 1.
I ended up testing to see how many extra Release calls it would take to destroy the App instance. In 1.4 Preview 1, it only took one extra Release for App's destructor to run. To me, this means that there is one outstanding strong reference being held somewhere.

**Comment by Ajith-GS** [comment]
> This has been happening for quite a while. This still happens in 1.4 Preview 1. I ended up testing to see how many extra Release calls it would take to destroy the App instance. In 1.4 Preview 1, it only took one extra Release for App's destructor to run. To me, this means that there is one outstanding strong reference being held somewhere.

Hi, how do we can perform this extra release? Could you please share a sample code snippet?

**Comment by DarranRowe** [comment]
Honestly, in this case I would have to decline providing a code sample. Calling Release on App here is completely bypassing the reference counting mechanism, and while it does destroy the object, it doesn't remove the strong reference that was keeping it alive. In essence, this can end up in a use after free, and the probability for this happening increases the longer the application runs. The little test got away with it due to the fact that I did the release just before wWinMain returned, so the application was exiting, but this is not something that should be seen as normal. It is certainly something that I wouldn't do in a production application.
With that disclaimer out of the way, I won't stop you working it out yourself. The biggest hint I will give you is that one thing I do when I need the guaranteed destruction of objects is modify App to include a little Cleanup member function.

```
#pragma once

#include "App.xaml.g.h"

namespace winrt::Meh::implementation
{
	struct App : AppT<App>
	{
		App();
		~App();

		void OnLaunched(Microsoft::UI::Xaml::LaunchActivatedEventArgs const&);

		winrt::Microsoft::UI::Xaml::Window Window() const;

		void Cleanup();

	private:
		winrt::Microsoft::UI::Xaml::Window window{ nullptr };
	};
}
```

An example implementation of this is:
```
    void App::Cleanup()
    {
        window = nullptr;
    }
```

The intent of this is to destroy the reference to the main application window that App holds.

My wWinMain function is implemented as follows:
```
int APIENTRY wWinMain(_In_ HINSTANCE, _In_opt_ HINSTANCE, _In_ LPWSTR, _In_ int)
{
	check_process_requirements();
	winrt::Microsoft::UI::Xaml::Application app = nullptr;

	winrt::Microsoft::UI::Xaml::Application::Start(
		[&app](auto &&)
		{
			app = winrt::make<winrt::Meh::implementation::App>();
		});

	auto app_inst = app.as<winrt::Meh::implementation::App>();
	app_inst->Cleanup();
	app_inst = nullptr;
	app = nullptr;

	return 0;
}
```
To quick notes are,
1) The check_process_requirements function does the call to XamlCheckProcessRequirements that the generated version does. I just factored it out into a separate function.
2) The call to init_apartment was placed into a global struct, where it is called in the constructor.
Anyway, you can grab the instance of App here by taking advantage of the fact that you can provide a lambda to the call to Application::Start. You can obviously take advantage of this to get your App instance back into the main function that way.

**Comment by JesseCol** [comment]
Hi there, this behavior is actually due to the Xaml debugging tools in VS, not the Xaml runtime itself.  To see this, in VS open Debug | Options... and then in Debugging / XAML Hot Reload, uncheck the "Enable XAML Hot Reload" checkbox.  Now, I believe you'll see your App dtor get hit.  You can also see this in Windbg, for example, which doesn't use the Xaml debugging tools.

This also means that if you add an extra release, you'll probably get crashes when VS is not attached (as Darran suggested, it's usually not safe to mess with refcounting).

Another option here, if you just want to run code that executes when the thread is getting destroyed, is subscribing to the DispatcherQueue.ShutdownStarting event.  Another option is to define your own WinMain.

I'm keeping this open for now because it would be still be good to fix this issue.

**Comment by JesseCol** [comment]
We decided not to address this.  These debugging tools are somewhat intrusive and do change the state of the app.  Thanks!
