### ISSUE TITLE
Menubar Flyout item accelerators are aligned differently when opened for the second time

### ISSUE THREAD

**Issue by zkacso-dev** [microsoft/microsoft-ui-xaml#8755]
### Describe the bug

Within a `MenuBar` the `MenuFlyoutItem` control's accelerator keys are aligned to the right when you first open the flyout, but all consequent opens will align the accelerator keys to the left.

### Steps to reproduce the bug

``` 
<MenuBar>
        <MenuBarItem Title="File">
            <MenuBarItem.Items>
                <MenuFlyoutItem Text="AAA">
                    <MenuFlyoutItem.KeyboardAccelerators>
                        <KeyboardAccelerator Key="A" Modifiers="Control" />
                    </MenuFlyoutItem.KeyboardAccelerators>
                </MenuFlyoutItem>
                <MenuFlyoutItem Text="BBB">
                    <MenuFlyoutItem.KeyboardAccelerators>
                        <KeyboardAccelerator Key="A" />
                    </MenuFlyoutItem.KeyboardAccelerators>
                </MenuFlyoutItem>
            </MenuBarItem.Items>
        </MenuBarItem>
    </MenuBar>
```
With this example code:
1. Open the File menu (Accelerators are aligned to the right)
2. Close the File menu
3. Open it again (Accelerator are aligned to the left)

### Expected behavior

alignment should be consistent when opening the flyout

### Screenshots

First open:
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/60542138/c73a380b-4a42-4b71-a68e-102b061b4282)

All consequent opens:
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/60542138/7d55fc7c-b7d7-462a-ae55-04ab669a24e8)

### NuGet package version

WinUI 3 - Windows App SDK 1.3.3: 1.3.230724000

### Windows version

Windows 10 (21H2): Build 19044

**Comment by JJBrychell** [comment]
Interestingly, it was a bug that caused it to show correctly the first time otherwise the actual bug would have caused them to always be left aligned.

The menu aligns the accelerator values by explicitly setting the size of all the TextBlock that contains the accelerator key text to the size of the largest one, and right aligning the TextBlock.  The first calculation for these widths occurs too early so the TextBlocks are just the size of their content and when they are right aligned, the appear justified to the right.  However, the second (and subsequent) times that the dialog is shown it has computed the correct size of the largest Text blocks and so all the textblocks are the same size and aligned on both the right and left.  BUT, the text in the text block was still being left aligned.  Consequently, the accelerator strings appeared left aligned on the second (and subsequent) invocations.

The fix is in and scheduled for 1.5
