### ISSUE TITLE
NumberBox and Decimals

### ISSUE THREAD

**Issue by tkillingerAlro** [microsoft/microsoft-ui-xaml#8780]
### Describe the bug

Certain values cause rounding errors when the control is unfocused.
Examples of values that cause this behavior.
25.8, .0001, 294.1, 2924.8

https://github.com/microsoft/WindowsAppSDK/assets/133376107/2ff301af-6689-46cc-8190-5e7685af00ae

### Steps to reproduce the bug

1. Open up the WinUI 3 Gallery that is available on the Microsoft Store
2. Navigate to numberbox
3. Enter 25.8 and focus on another control

### Expected behavior

Numbers do not change and stay the same.

### NuGet package version

Windows App SDK 1.3.2: 1.3.230602002

### Additional context

This seems to be across multiple versions of the Windows App SDK.

**Comment by tkillingerAlro** [comment]
Any Update on this?

 I can confirm Win UI 2 does not have this issue.  Also curious as to why this doesn't have the bug label as I'm sure this is not intended behavior.

**Comment by TroelsL** [comment]
We also observe this bug. And it renders the NumberBox unusable. We tried looking for workarounds, but (somewhat ironically), using a DecimalFormatter with an IncrementNumberRounder does not seem possible as we are unable to set the Increment to 0.0001. This will throw an exception due the setter throwing an System.ArgumentException: 'The parameter is incorrect.' because somewhere 0.0001 gets converted to 9.9999997473787516E-05, which doesn't match the rules specified here:

https://learn.microsoft.com/en-us/uwp/api/windows.globalization.numberformatting.incrementnumberrounder.increment?view=winrt-22621#windows-globalization-numberformatting-incrementnumberrounder-increment
