### ISSUE TITLE
v1.4.0-preview2 Xaml Hosting - 'Class not registered'

### ISSUE THREAD

**Issue by Ajith-GS** [microsoft/microsoft-ui-xaml#8784]
### Describe the bug

I am trying to host standard controls using the steps described in the following page:
https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/host-standard-control-with-xaml-islands-cpp#use-the-xaml-hosting-api-to-host-a-winrt-xaml-control
with Windows App SDK 1.4 Preview 2.
But the following line throwing Class not registered exception.
WindowsXamlManager winxamlmanager = WindowsXamlManager::InitializeForCurrentThread(); 

How do I fix this issue?
Is there any sample code available?

### Steps to reproduce the bug

1.Perform the steps described in the following page.
https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/host-standard-control-with-xaml-islands-cpp#use-the-xaml-hosting-api-to-host-a-winrt-xaml-control
2.Install the NuGet package "Microsoft.WindowsAppSDK.1.4.230811000-preview2"
3.Replace the Windows namespace with Microsoft.
4.Build and run the application.

### Expected behavior

Application should run without any exception.

### NuGet package version

Windows App SDK 1.4 Preview 2: 1.4.230811000-preview2

### Packaging type

Unpackaged

### Windows version

Windows 10 version 22H2 (19045, 2022 Update)

### IDE

Visual Studio 2022

### Additional context

Any help would be greatly appreciated. Thank you.

**Comment by Ajith-GS** [comment]
> Because you are referencing the Windows App SDK, your bug report states that the application is unpackaged and because your description doesn't mention anything along these lines, I'll ask the obvious question. Did you remember to initialise the Windows App SDK? [As documented](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/use-windows-app-sdk-run-time), when you are using the Windows App SDK in an unpackaged application, you either need to set the WindowsPackageType property to None in the project file, or you need to use the bootstrapper API or (on Windows 11) the Windows 11 Dynamic Dependencies API to reference it. You could also set the project to be self contained too. An excerpt from the little test application that I wrote to test this out has:
> 
> ```
> #include "pch.h"
> #include "application.h"
> #include "main_window.h"
> #include <WindowsAppSDK-VersionInfo.h>
> #include <MddBootstrap.h>
> 
> struct bootstrap_winappsdk
> {
> 	bootstrap_winappsdk()
> 	{
> 		MddBootstrapInitialize2(WINDOWSAPPSDK_RELEASE_MAJORMINOR, WINDOWSAPPSDK_RELEASE_VERSION_TAG_W, {}, MddBootstrapInitializeOptions_None);
> 	}
> 	~bootstrap_winappsdk()
> 	{
> 		MddBootstrapShutdown();
> 	}
> };
> 
> application::com_initialiser apartment_init = application::com_initialiser(false);
> bootstrap_winappsdk s_winappsdk_bootstrap;
> 
> int do_main(HINSTANCE inst, int cmdshow)
> {
> 	auto xmdp = winrt::Microsoft::UI::Xaml::XamlTypeInfo::XamlControlsXamlMetaDataProvider();
> 
> 	application::application main_application({xmdp});
> 	main_application.create_shared_compositor();
> 
> 	auto xcr = winrt::Microsoft::UI::Xaml::Controls::XamlControlsResources();
> 	main_application.merge_resource_dictionary(xcr);
> 
> 	windowing::main_window *main_window = windowing::main_window::create(inst, main_application.get_shared_compositor());
> 	main_window->show_window(cmdshow);
> 	main_window->update_window();
> 
> 	auto result = main_application.run_message_pump();
> 
> 	main_application.close_application();
> 	main_application.destroy_shared_compositor();
> 	application::application::clear_message_queue();
> 
> 	main_application.close_dispatcher_queue();
> 	return result;
> }
> ```
> 
> While a lot of it isn't that important here, please pay attention to the fact that I am using MddBootstrapInitialize2 in a static variable. This means that the application will call MddBootstrapInitialize2 prior to getting into wWinMain, and MddBootstrapShutdown after wWinMain returns. I am using wWinMain as the entry point in this application, but this doesn't matter.
> 
> --Edit-- [XamlIslandTest3.zip](https://github.com/microsoft/WindowsAppSDK/files/12414377/XamlIslandTest3.zip)
> 
> This is an incomplete sample. I have been going through one of my earlier samples that did some fun stuff with WinUI 2 hosted in Xaml Islands and have been rewriting it to work with WinUI 3. It doesn't have everything yet, notably it is missing the functionality to navigate between content islands and regular child windows. However, it is good enough to show what you need to get as far as showing the UI.

Thank you for your response.
I am trying to add the following header 
`
#include <Microsoft.UI.Xaml.Hosting.DesktopWindowXamlSource.h>	
`
for achieving this,
`ito interop = _desktopWindowXamlSource.as<IDesktopWindowXamlSourceNative>();
        check_hresult(interop->AttachToWindow(hWnd));`
But getting the following error.
`Cannot open include file: 'Microsoft.UI.Xaml.Hosting.DesktopWindowXamlSource.h': No such file or directory	`	

Are we not able to use IDesktopWindowXamlSourceNative in Windows App SDK 1.4 or am I missing anything?

**Comment by DarranRowe** [comment]
It was removed. The operations that were exposed through this have been moved, two of them are available on the main WinRT interface.

For the ones that used to take HWNDs, they have been updated to use [WindowId](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.windowid?view=windows-app-sdk-1.4). You use [GetWindowIdFromWindow](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/win32/winrt-microsoft.ui.interop/nf-winrt-microsoft-ui-interop-getwindowidfromwindow) to get the WindowId.
IDesktopWindowXamlSourceNative::AttachToWindow has been exposed as [DesktopWindowXamlSource.Initialize](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.hosting.desktopwindowxamlsource.initialize?view=windows-app-sdk-1.4#microsoft-ui-xaml-hosting-desktopwindowxamlsource-initialize(microsoft-ui-windowid)). The semantics are the same, you use the WindowId to specify the parent window instead of the HWND.
IDesktopWindowXamlSourceNative::get_WindowHandle has been exposed as [DesktopSiteBridge.WindowId](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.content.desktopsitebridge.windowid?view=windows-app-sdk-1.4#microsoft-ui-content-desktopsitebridge-windowid). You would then get the associated instance from [DesktopWindowXamlSource.SiteBridge](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.hosting.desktopwindowxamlsource.sitebridge?view=windows-app-sdk-1.4). SiteBridge gives you a [DesktopChildSiteBridge](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.content.desktopchildsitebridge?view=windows-app-sdk-1.4), but this inherits from DesktopSiteBridge.
IDesktopWindowXamlSourceNative2::PreTranslateMessage has no direct comparison, but a header named Microsoft.UI.Dispatching.Interop.h was added. This contains a function named ContentPreTranslateMessage. This seems to do the work of all of the individual PreTranslateMessage functions. It is exported from Microsoft.WindowsAppRuntime.dll. If you want to use this, either make the function delay loaded or use a runtime dynamic reference to it.

**Comment by JesseCol** [comment]
I'm going to close this out for now, but please feel free to re-open if you have additional questions or feedback.  Thanks!

**Comment by Ajith-GS** [comment]
> Thanks @DarranRowe for providing that info!
> 
> We have a new sample for using DesktopWindowXamlSource in 1.4 in progress here: [microsoft/WindowsAppSDK-Samples#307](https://github.com/microsoft/WindowsAppSDK-Samples/pull/307)
> 
> Note that the page linked above (https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/host-standard-control-with-xaml-islands-cpp#use-the-xaml-hosting-api-to-host-a-winrt-xaml-control) is about the Windows.UI.Xaml.Hosting APIs. The WinAppSDK APIs are in Microsoft.UI.Xaml.Hosting.
> 
> Please have a look and see if it helps you out. Feedback welcome and appreciated.
> 
> Thanks!

Thank you so much for your support.
I have tired the sample application available in the `https://github.com/microsoft/WindowsAppSDK-Samples/tree/main/Samples/Islands` repo. It's working fine, but I noticed some exceptions when closing the application.

My actual problem is the ResourceManagerRequested event is not hitting. I have added the following code with necessary headers and namespaces after the `auto simpleIslandApp{ winrt::make<winrt::SimpleIslandApp::implementation::App>() };` line:
`simpleIslandApp.ResourceManagerRequested([](winrt::IInspectable const&, winrt::ResourceManagerRequestedEventArgs const& EventArgs)
{
    OutputDebugString(L"\nResourceManagerRequested...\n");
});`

But it never entered the callback. This is required for me to load the custom resource manager.
Is there anything I am missing to trigger the ResourceManagerRequested event?
Thank you.
