### ISSUE TITLE
Controls (dropdowns) that overhangs the title bar, not clickable (also in WinUI Gallery)

### ISSUE THREAD

**Issue by Fritierkelle** [microsoft/microsoft-ui-xaml#8788]
### Describe the bug

If you open a combo box and the first item is not selected, then the combo box dropdown opens above the combo box. If the dropdown protrudes over the customized titlebar, even though the combo box is placed below the title bar, then everything above the title bar can no longer be clicked.

If the overhanging part of the combo box is above the system buttons, the system buttons will respond even though they are covered by the combo box dropdown.

### Steps to reproduce the bug

Tested it in c# and c++ (with combo boxes), also in the WinUi Gallery.

1. Just go to the combox site in the WinUI Gallery and test it with the dropdown "Documentation" **button**.
2. Watch the video how I tested this.

https://github.com/microsoft/microsoft-ui-xaml/assets/19283500/9032f03d-92f0-4c15-96a6-4b653401a043

I minimized the window that the dropdown button sits just below the title bar.
The same thing happens when you place a combo box well below the title bar but have a large drop down due to a larger number of items.

In the video you can see that the top item is not responsive as it sits above the title bar. If that is above the system button then the system buttons will be responsive even though you are in the dropdown.

### Expected behavior

Responding from the items above the title bar.

It might be a good workaround if you could set the dropdown to only open downwards or something.

### NuGet package version

WinUI 3 - Windows App SDK 1.3.3: 1.3.230724000

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

oops, wasn't intentional that it was created with my old account.
The whole thing is probably related to this, but was closed by the bot (created by me):
https://github.com/microsoft/microsoft-ui-xaml/issues/8051

**Comment by Akronae** [comment]
I have the exact same issue, I wanted to have a custom Title Bar, or at least a title bar that would fit the host theme, and it also happens that the first component I placed is a combobox. I thought I did something wrong but apparently even WinUI Gallery is buggy.

I would not only expect the first combo box item to be clickable, but also the item not to overlap the title bar at all like with the "native" title bar.

Any Idea how to get around?

**Comment by zadjii-msft** [comment]
@pratikone this super curious. 

I'd guess this is due to the invisible drag region HWND being on top of the XAML flyout. AMAZINGLY though, this _isn't_ a problem with the Terminal's titlebar. Of course, we're not using the WinUI3 custom titlebar, but our implementations aren't all that different...

**Comment by lhak** [comment]
I think this is currently expected to happen because the stable winui 3 release does not support out-of-bounds flyouts.

**Comment by DarranRowe** [comment]
@zadjii-msft
While there are a couple of things that I would have to double check and get proof for, I think this is caused by the lack of interaction between Microsoft.UI.Xaml.Window and Microsoft.UI.Windowing.AppWindowTitleBar.
The most obvious sign of this is if you use AppWindowTitleBar.ExtendsContentIntoTitleBar to make the custom title bar available, Window.ExtendsContentIntoTitleBar will return false if you query it. The same is true the other way around. So I think that in this case, Window and the Xaml host isn't aware that it isn't supposed to use the top portion of the client area.
1.4 is better, but there are still problems. Window.ExtendsContentIntoTitleBar is using AppWindowTitleBar's implementation. However:
```
    MainWindow::MainWindow()
    {
        InitializeComponent();

        ExtendsContentIntoTitleBar(true);
        auto extended = AppWindow().TitleBar().ExtendsContentIntoTitleBar();
    }
```
will set extended to true, however:
```
    MainWindow::MainWindow()
    {
        InitializeComponent();

        AppWindow().TitleBar()ExtendsContentIntoTitleBar(true);
        auto extended = ExtendsContentIntoTitleBar();
    }
```
will set extended to false. But at least it is using the better implementation now.
Hopefully, this problem will fix itself with 1.4 naturally though.

**Comment by codendone** [comment]
@DarranRowe's theory is correct: ComboBox's code to size/position the dropdown doesn't account for ExtendsContentIntoTitleBar. In 1.4, `Popup.ShouldConstrainToRootBounds=false` will be supported and ComboBox uses that to have its popup be able to extend outside the window and above the titlebar. That fixes this issue for controls using that property.

**Comment by Fritierkelle** [comment]
It's fixed as far as i can see, really cool.
Tested it in WinUI3 with a ComboBox and Windows App SDK Version 1.4.1 (1.4.230913002).
