### ISSUE TITLE
TreeView crashes when using TemplateSelector and loading certain amount of nodes

### ISSUE THREAD

**Issue by ADD-Lorenzo-Martin** [microsoft/microsoft-ui-xaml#8791]
### Describe the bug

When adding a TemplateSelector to a TreeView with several different templates, after loading the TreeView with an ItemsSource with a certain number of elements, the App will crash complaining of an exception when trying to cast the ViewModel bount to a node.

It seems like it is trying to reuse a node but if it was bound formerly to a specific viewmodel type, and later it is bound to another type, it still tries to cast the current viewmodel to the other one's type.

A sample App is supplied.
[WinUITreeviewErrors.zip](https://github.com/microsoft/microsoft-ui-xaml/files/12451122/WinUITreeviewErrors.zip)

### Steps to reproduce the bug

Launch the sample application and it should crash.

### Expected behavior

Being able to have an items source for a TreeView, with any amount of elements of several types that should be represented through a Template selector without crashing.

### Screenshots

The exception shown after launching the sample Application:

![TreeViewCrash](https://github.com/microsoft/microsoft-ui-xaml/assets/106528099/1cb08c60-a438-4918-8e97-74c38cdb1454)

### NuGet package version

None

**Comment by ADD-Lorenzo-Martin** [comment]
This issue is related to #7618 that was closed recently by the bot without being solved.

**Comment by fabianoriccardi** [comment]
Before any bot thinks that this is issue should be closed for inactivity, I can confirm that this issue is still valid in WASDK 1.5.5. In particular, I have just downloaded and update all the deps in the example provided by @ADD-Lorenzo-Martin. It compiles, but it crashes immediately at startup. 

For curiosity, I have tried to change the abstract class TreeNodeViewModelBase into a non-abstract class (and make the changes to make it compile), but it crashes for the same reason at startup.

**Comment by ADD-Lorenzo-Martin** [comment]
@llongley Could you please tell me the issue number where this issue is going to be treated, in order to follow it. I see another closed issue where this one was mentioned (#7618)

**Comment by codendone** [comment]
@ADD-Lorenzo-Martin Looking at the internal bug, this was resolved as duplicate of #2121.
