### ISSUE TITLE
Preserve WebView2 state when in TabView tabs

### ISSUE THREAD

**Issue by manfromarce** [microsoft/microsoft-ui-xaml#8868]
### Describe the bug

Having multiple WebView2 instances in TabView tabs produces a bad experience:
- when selected tab changes, the WebView2 and its page are reloaded
- when dragging tabs across windows, weird issues occur. The second windows is always forceably focused, and closing the first window makes all WebView instances in other windows invisible

### Steps to reproduce the bug

You can reproduce this in the TabView full windowing sample from WinUi Gallery, if you replace the tab content with WebView2.

### Expected behavior

For the first issue the TabView could expose a property to prevent tab content unloading when selection changes. 
For the second issue the WebView2 should preserve its state and be rendered properly when its parent window changes, or a method to change its parent window should be provided.

### NuGet package version

WinUI 3 - Windows App SDK 1.4.0: 1.4.230822000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by ranjeshj** [comment]
This is by design. TabView chooses the selected tab's content and sets it on the frame, so I believe that is loading/unloading the WebView2 which is not what you want here. You can use TabVIew just for the tab strip header and use your own frame to show the content. In this case, you can do whatever you want including keeping the WebView2's alive and not unload.
