### ISSUE TITLE
Not able to set WinUI3 Window as Parent Window in MFC

### ISSUE THREAD

**Issue by Ajith-GS** [microsoft/microsoft-ui-xaml#8900]
### Describe the bug

Hi,
We are using the following implementation to show a WinUI 3 UI over the existing MFC application:

- Get the WinUI3.0 window handle from the WinUI3 project using the XAML window-created event handler.
- Using the Windows API, position the WinUI3.0 window over the MFC dialog window.

This implementation has been working so far until the Windows App SDK's release, 1.3.
While upgrading our projects to the latest Windows App SDK 1.4 version, the MFC project threw an exception in the below code.
![image001](https://github.com/microsoft/WindowsAppSDK/assets/74490999/5fbaef8b-479c-45e4-aa32-871720779f51)

Where m_xamlHwnd is the WinUI3 Window handle.

1. Is this the issue caused by any of the latest features introduced in Windows App SDK 1.4?
2. Are we not able to use this implementation anymore?
3. Should we completely rely on the latest XAML Island technology available in Windows App SDK 1.4 for modernising existing MFC applications?

Any help is greatly appreciated.

### Steps to reproduce the bug

•	Create an unpackaged, self-contained WinUI3.0 application containing the new UI.
•	Make the WinUI3.0 application output type as a DLL.
•	For MFC application, Provide C++\WinRT and WinAppSDK support.
•	Refer the WinUI3.0 application DLL project in MFC application project.
•	Start the WinUI3.0 application from MFC application and show the new UI over the MFC dialog.

### Expected behavior

The application should run and show the WinUI 3 UI.

### Screenshots

The Visual Studio output window is given below.
![image002](https://github.com/microsoft/WindowsAppSDK/assets/74490999/c04daa31-74e6-46ad-9515-c9994fd0cd97)

### NuGet package version

Windows App SDK 1.4.0: 1.4.230822000

### Packaging type

Unpackaged

### Windows version

Windows 10 version 22H2 (19045, 2022 Update)

### IDE

Visual Studio 2022

**Comment by JesseCol** [comment]
Hello, today in WinAppSDK 1.4, a DesktopWindowXamlSource HWND parent chain cannot be changed -- this is currently by-design.  If you need to put Xaml content elsewhere in your HWND hierarchy, you'll need to create a new/different DesktopWindowXamlSource for it.  Apologies for the inconvenience.

Here's a sample of how to use DesktopWindowXamlSource in WinAppSDK 1.4: https://github.com/microsoft/WindowsAppSDK-Samples/tree/main/Samples/Islands

>Is this the issue caused by any of the latest features introduced in Windows App SDK 1.4?
Yes, this is intentional/by-design behavior in WinAppSDK 1.4.

>Are we not able to use this implementation anymore?
DesktopWindowXamlSource is a fully-supported part of WinAppSDK.  But it doesn't currently support the HWND parent chain changing while it's in use.

>Should we completely rely on the latest XAML Island technology available in Windows App SDK 1.4 for modernising existing MFC applications?
I don't know all your requirements, but yes, I expect Xaml Islands in WinAppSDK 1.4 will usually be a good option for modernizing an MFC app.

Thanks!
