### ISSUE TITLE
Graphic glitches applying BackdropMaterial and multiple view

### ISSUE THREAD

**Issue by andelby** [microsoft/microsoft-ui-xaml#8911]
### Describe the bug

Graphic glitches ( accent color background view) applying BackdropMaterial and use AppWindow.TryCreateAsync(); to create a new Window.

Project sample https://github.com/microsoft/WinUI-Gallery/blob/winui2/WinUIGallery/TabViewPages/TabViewWindowingSamplePage.xaml: 

Complete sample : [App1.zip](https://github.com/microsoft/microsoft-ui-xaml/files/12708603/App1.zip)

### Steps to reproduce the bug

- Page whit "BackdropMaterial.ApplyToRootOrPageBackground="True"".
- Create a new Window with AppWindow.TryCreateAsync();

### Expected behavior

Same Mica effect in both views.

### Screenshots

First view. (OK)
![Screenshot 2023-09-24 152704](https://github.com/microsoft/microsoft-ui-xaml/assets/7497813/ebab1ec5-0979-4f71-ba0a-2bc8db0417fd) 
Second view after tab drag out. (NOK)

![Screenshot 2023-09-24 152715](https://github.com/microsoft/microsoft-ui-xaml/assets/7497813/cb8c1a10-e113-4b65-aba1-79d6689af056) 
Difference.
![Screenshot 2023-09-24 152755](https://github.com/microsoft/microsoft-ui-xaml/assets/7497813/a22862f0-579b-409e-b25a-c0ce14e8273f)

### NuGet package version

WinUI 2 - Microsoft.UI.Xaml 2.8.2

### Windows version

Windows 11 (22H2): Build 22621

**Comment by DmitriyKomin** [comment]
This is in WinUI2-specific Mica implementation, and unfortunately we are unable to investigate most WinUI2-only issues due to the current focus on WinUI3 (more on the policy [here](https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/contribution_handling.md#winui-2)). If this is a blocker, please consider migration to WinAppSDK where [MicaBackdrop](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.media.micabackdrop?view=windows-app-sdk-1.4) provides fully-featured support for this material.
