### ISSUE TITLE
WindowCaption* brushes don't work in 1.4

### ISSUE THREAD

**Issue by tpoint75** [microsoft/microsoft-ui-xaml#8961]
### Describe the bug

These settings will be ignored in WinAppSDK 1.4 

### Steps to reproduce the bug

add 
`<SolidColorBrush x:Key="WindowCaptionBackground">Green</SolidColorBrush>`
`<SolidColorBrush x:Key="WindowCaptionBackgroundDisabled">LightGreen</SolidColorBrush>`
`<SolidColorBrush x:Key="WindowCaptionForeground">Red</SolidColorBrush>`
`<SolidColorBrush x:Key="WindowCaptionForegroundDisabled">Pink</SolidColorBrush>`
too ResourceDictionary in app.xaml

### NuGet package version

WinUI 3 - Windows App SDK 1.4.1: 1.4.230913002

### Additional context

win10 V22H2 (Build 19045.3324)

**Comment by pratikone** [comment]
Hi, thanks for pointing this out. This is by design. With new appwindow titlebar merge, we overhauled the theming and it uses different apis. For the sake of backward compatibility, this is kept but it results in no-op. You can refer to the titlebar sample in winiui gallery for the way to do it. [Release notes](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel#custom-titlebar--appwindow-titlebar-merger)

meanwhile I will do 2 things to bring better clarity on this
1. update the Microsoft docs for WinUI 3 custom titlebar so that it mentions this change.
2. find a way to show deprecated api message during compilation for it.

**Comment by tpoint75** [comment]
If change the design from dark to light the close, min, max buttons doesn't change there colors and these windows captions keys was the workaround for that. With this merge I suspected, that this workaround is not needed anymore. But now nothing is working right. What have I missed? How to use the custom TitleBar the right way?

**Comment by tpoint75** [comment]
Hmm, I looked in the in WinUI3 Gallery App and setting the Foreground Color isn't working!
In the examppkle code:
[titlebar sample](https://github.com/microsoft/WinUI-Gallery/blob/main/WinUIGallery/ControlPages/TitleBarPage.xaml.cs) you set
window.AppWindow.TitleBar.ButtonForegroundColor = color;
But i don't know how to do it in c++:
AppWindow().TitleBar().ButtonForegroundColor(Colors::Black());
or
ApplicationView::GetForCurrentView().TitleBar().ButtonForegroundColor(Colors::Black());
or
MyCustomTitleBar().as<winrt::Windows::UI::WindowManagement::AppWindowTitleBar>().ButtonForegroundColor(Colors::Black());
or
MyCustomTitleBar().as<Windowing::AppWindowTitleBar>().ButtonForegroundColor(Colors::Black());
doesn't compile.

I had some trouble in the past wit this:
https://github.com/microsoft/microsoft-ui-xaml/issues/7125
and now again!. Please tell me how to change Foregound Colors of the max, min and close buttons in winrt/c++!
and the Background Color should also be set to get the right color on hover these buttons.

I am also wondering how to get rid of this black row of one pixel height on top of the titlebar! Is there any fix for that?

**Comment by bpulliam** [comment]
The docs have been updated. https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.window.settitlebar?view=windows-app-sdk-1.4
