### ISSUE TITLE
Microsoft.Win32.SystemEvents.DisplaySettingsChanged throw exception in WinUI3 project

### ISSUE THREAD

**Issue by antoniohou** [microsoft/microsoft-ui-xaml#9013]
### Describe the bug

In my WinUI3 project, I want to change window size when user change the scaling or resolution. I use the Microsoft.Win32.SystemEvents nuget. After I regist DisplaySettingsChanged event. It will throw "Exception thrown: 'System.NotSupportedException' in Microsoft.InteractiveExperiences.Projection.dll
The send method is not supported, use Post instead.". I want to know is there something I can do or other solution I can used. Thanks!

### Steps to reproduce the bug

1. Create a blank WinUI3 project
2. Install Microsoft.Win32.SystemEvents nuget.
3. In public MainWindow() add SystemEvents.DisplaySettingsChanged += DisplaySettingsChanged;
4. Add private void DisplaySettingsChanged(object? sender, EventArgs e) function
5. Run the app
6. Change the screen resolution or scaling
7. Get the exception

### NuGet package version

WinUI 3 - Windows App SDK 1.4.2: 1.4.231008000

### Windows version

Windows 10 (21H2): Build 19044

**Comment by antoniohou** [comment]
I found out that I can traditionally use WM_DISPLAYCHANGE to know resolution changed.
But this event works find with .net wpf. I thinks it sould as same with WinUI3 too.

**Comment by castorix** [comment]
> I found out that I can traditionally use WM_DISPLAYCHANGE to know resolution changed. But this event works find with .net wpf. I thinks it sould as same with WinUI3 too.

Yes, WM_DISPLAYCHANGE works correctly in WinUI 3, like for any Desktop app
(tested on Windows 10 22H2)

**Comment by gegao18** [comment]
Thanks for reporting. WinAppSDK isn't compatible with Microsoft.Win32.SystemEvents's DisplayChanged event. You've found a workaround in WM_DISPLAYCHANGE. XamlRoot.Changed might work as well (XamlRoot has a RasterizationScale and a Size property).

**Comment by softworkz** [comment]
It is still possible to use Microsoft.Win32.SystemEvents. You just mustn't let it use the synchronization context implementation of WinUI3 and sync it back to the UI thread yourself instead - like this for example: 

```cs
// Must be called from the UI thread
public void RegisterSystemEvent()
{
    var dispatcherQueue = DispatcherQueue.GetForCurrentThread();
    ThreadPool.QueueUserWorkItem(
        _ => Microsoft.Win32.SystemEvents.DisplaySettingsChanged += (_, _) => dispatcherQueue.TryEnqueue(this.SystemEvents_DisplaySettingsChanged),
        null);
}

// Gets invoked on the UI thread
private void SystemEvents_DisplaySettingsChanged()
{
    // do something...
}
```

Microsoft.Win32.SystemEvents tries to play nice by firing its events synced to the synchronization context (=on the thread) where the event has been registered. The DispatcherQueue-based synchronization context doesn't like [SynchronizationContext.Send](https://learn.microsoft.com/en-us/dotnet/api/system.threading.synchronizationcontext.send?view=net-8.0) but only SynchronizationContext.Post, that's why it fails.
By registering on a ThreadPoolThread (which doesn't have such SynchronizationContext, you avoid this behavior and you get the events fired on arbitrary threads, which can easily be manially relayed to the UI thread with TryEnqueue.

**Comment by rcg-wae** [comment]
@softworkz 

Thank you so much!

I just had to do a similar thing to detect time zone changes with SystemEvents.TimeChanged - if you don't subscribe off thread then the event will just never be raised.

```
        ThreadPool.QueueUserWorkItem(_ =>
        {
            SystemEvents.TimeChanged += (_, __) =>
            {

            };
        });
```
