### ISSUE TITLE
Memory leaks on navigation

### ISSUE THREAD

**Issue by BrancheyJuhas** [microsoft/microsoft-ui-xaml#9044]
### Which version of the app?

WinUI 3 Gallery

### Description

Memory used by application is constantly increasing reaching values 8 times the initial memory required when navigaing. To reproduce this bug, click through the elements in navigation pane (navigate through different pages a lot of times).

### Screenshots

![image](https://github.com/microsoft/WinUI-Gallery/assets/98485942/06866484-02e7-416e-9ef6-afe8ed40dc96)

### Windows version

Windows 11 22H2 (22621)

**Comment by ranjeshj** [comment]
@chingucoding @BrancheyJuhas this is by design. The garbage collector will not cleanup if there is plenty of memory to work with. That does not mean the app is leaking. You can force a GC collect or put memory pressure to force GC to run which works as @chingucoding noticed above. If you see a monotonous increase without ever going back down, then there is likely a leak.
