### ISSUE TITLE
Xbox UWP app: Pointer mode does not work properly when scaling is set to default (200 %)

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#9076]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Xbox-UWP-app:-Pointer-mode-does-not-work/10512787)._

---
The UWP app is configured for the Xbox so that the pointer mode is only enabled when requested (RequiresPointerMode = ApplicationRequiresPointerMode.WhenRequested). The scaling is set to default (200 % for UWP apps). One page was created with a ScrollViewer and one with a WebView2 element. Both elements have the properties "RequiresPointer=WhenEngaged" and "IsFocusEngagementEnabled=True". As soon as the elements receive the focus and the pointer mode is activated (IsFocusEngaged = True), the pointer appears. However, the pointer can only be used in 25 % of the area of the element at the top left. As soon as scaling is disabled (ApplicationViewScaling.TrySetDisableLayoutScaling(true)) and the app is displayed at 100 %, the pointer can be navigated over the entire area of the element.

---
#### Feedback Bot on 11/12/2023, 05:55 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by itschmiederk** [comment]
This is an UWP issue, not a WinUI issue!

### Example with pointer issue:

**App.xaml.cs:**
```
public App()
{
    this.InitializeComponent();
    this.Suspending += OnSuspending;

    if (AnalyticsInfo.VersionInfo.DeviceFamily == "Windows.Xbox")
    {
        this.RequiresPointerMode = ApplicationRequiresPointerMode.WhenRequested;
        //ApplicationViewScaling.TrySetDisableLayoutScaling(true);
    }
}
```

**MainPage.xaml:**
```
<Grid>
    <Grid.RowDefinitions>
        <RowDefinition Height="Auto" />
        <RowDefinition Height="*" />
    </Grid.RowDefinitions>
    <TextBox Grid.Row="0" Text="Test" />
    <ScrollViewer
        x:Name="ScrollViewer"
        Grid.Row="1"
        IsFocusEngagementEnabled="True"
        RequiresPointer="WhenEngaged"
        GotFocus="ScrollViewer_GotFocus">
        <StackPanel>
            <TextBlock Text="Hello" />
        </StackPanel>
    </ScrollViewer>
</Grid>
```
**MainPage.xaml.cs:**
```
public MainPage()
{
    this.InitializeComponent();
}

private void ScrollViewer_GotFocus(object sender, RoutedEventArgs args)
{
    ScrollViewer.IsFocusEngaged = true;
}
```

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

_No response_

### SDK Version

1.0.2088.41

### Framework

WinUI2/UWP

### Operating System

Xbox

### OS Version

10.0.25398.2538

**Comment by ranjeshj** [comment]
Please see this note regarding WinUI2 issues. Closing as not planned.
https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/contribution_handling.md#winui-2

**Comment by remokeitel** [comment]
This is business critical, because my commercial app is not working without fixing the issue! I need WebView2 for the use case. On Xbox there are no alternatives of using UWP.

**Comment by duncanmacmichael** [comment]
Hi @remokeitel, thank you so much for opening this and bringing it to our attention. Our intention with WinUI2 bugs is to address them if they severely impact our business priorities, such as if a UWP bug caused a system vulnerability, but I can see why you understood the note the way you did. Apologies if this was confusing - I've updated the wording to make things a little clearer (see this PR: https://github.com/microsoft/microsoft-ui-xaml/pull/9129). In the meantime, I'm sorry but this bug is not on our plan to fix.
