### ISSUE TITLE
Proposal: Improve the default Light and Dark Theme colours

### ISSUE THREAD

**Issue by mdtauk** [microsoft/microsoft-ui-xaml#920]
# Proposal: Improve the default Light and Dark Theme colours

## Summary
Update the default ThemeResources used in both Dark and Light themes, to improve the visual design of UI, and to address common changes app designers make, to work around the defaults.

## Rationale
Within Microsoft, many products have made changes to how their app handles Dark Themes in their UIs.  As a result whilst most apps appear to be mostly consistent with their Light Theme styling, their Dark Themes are inconsistent, and give the impression of an unpolished and inelegant design.

Common changes I have noticed:
* Apps move away from Pure Black and sometimes from Pure White for surfaces.  This mostly affects the Dark Theme, where pure black is avoided.
* Elevation, which introduces hierarchy and structure through shadows, are much less effective with Pure Black backgrounds.
* Office's Win32 apps offer both Black and Dark Gray theme options, but even Black avoids pure black everywhere except the Title Bar

## Important Notes
For devices which use OLED screen technologies, there can be some power efficiencies with using Pure Black - consideration for how these devices may handle Dark Theme defaults should be made.

## Open Questions
Beyond whether the defaults need to change...
What should these defaults be?
What best practice and examples should we look to for these decisions?

## Examples and Thinking
I have been putting some thought into this, and have looked at a few examples from Microsoft, and took my replacement black colour from the UWP OneNote app.

![Proposed Light Theme](https://user-images.githubusercontent.com/7389110/59955887-b08aef80-9484-11e9-8cdd-2a828befc5cf.png)
_Example Light Theme colours_

![Proposed Dark Theme](https://user-images.githubusercontent.com/7389110/59955892-b385e000-9484-11e9-907e-286a462b7309.png)
_Example Dark Theme colours_

![Colour Formulas](https://user-images.githubusercontent.com/7389110/59955898-b680d080-9484-11e9-840f-62d87364eb27.png)
_How I determined the colour values_

## References
![Current Light Theme](https://user-images.githubusercontent.com/7389110/59955927-dfa16100-9484-11e9-98c1-5d8aec0a82e6.png)
_Current 19H1 Light Theme colours_

![Current Dark Theme](https://user-images.githubusercontent.com/7389110/59955930-e334e800-9484-11e9-9c34-bfa7260530e4.png)
_Current 19H1 Dark Theme colours_

![Outlook UWP Screenshot](https://user-images.githubusercontent.com/7389110/59955954-124b5980-9485-11e9-87cd-f3f6f68a6ef5.png)
_Outlook UWP Screenshot (using custom dark theme colours)_

![Microsoft Store Screenshot](https://user-images.githubusercontent.com/7389110/59956002-5d656c80-9485-11e9-9e13-8907fa4e3957.png)
_Microsoft Store Screenshot (using custom dark theme colours)_

![Settings Screenshot](https://user-images.githubusercontent.com/7389110/59956036-99003680-9485-11e9-9a05-8c2bd830bcb0.png)
_Settings Screen (using the default dark theme colours and pure black)_

**Comment by duke7553** [comment]
# Expanded Documentation of Color Usage
Great work on these mock-ups @mdtauk . Even if there aren't any improvements to the Light and Dark theme colors at this time, I think it would benefit the community (and internal Microsoft developers) to have clear documentation on the following aspects:

- **What background colors should be used for the dark theme?** It's understood that a "one size fits all" approach won't suffice for the various app scenarios. However, the design docs need to clarify if pure black or dark gray should be used for the dark theme.

- **What background colors should be used for the light theme?** While pure white was formerly the standard color, newer Microsoft applications (e.g. Chromium Edge and Microsoft Store) are using a light gray. In what scenarios, if at all, should developers use this shade in their app?

- **How and where should these colors be used to differentiate areas of the UI?** It should be clear to developers which UI elements qualify as being a different color shade from the rest in order to convey their utility. (e.g. The address bar in Chromium Edge is a lighter color than other elements in its light theme; The NavigationView pane color is currently different than the default application background color)

Addressing these common developer concerns when improvements to the default theme colors are evaluated will clear up some of the confusion on how a Fluent application's colors should feel while furthering the open design principles of Microsoft.

**Comment by MartinZikmund** [comment]
I really like this proposal 👌 . The suggested sets of color are more pleasing to the eye. The original "all white" and "all black" were too strong - and apps did look a bit too simplistic and less polished and I am aware many developers manually adjusted their defaults.

Definitely I am all in for consistency across the board, especially for first party apps 😊

**Comment by shaheedmalik** [comment]
These are consistency changes that need to be made.

>* 
@duke7553
**What background colors should be used for the dark theme?** It's understood that a "one size fits all" approach won't suffice for the various app scenarios. However, the design docs need to clarify if pure black or dark gray should be used for the dark theme.
> *

What scenarios exist other than various design teams changing things for the sake of change?
I know in many cases each team made a new "not as dark" mode because a standard wasn't set and the new theme wasn't baked into the templates. Until this day, I don't know what quantifiable reason why Settings looks different from Word, which looks different from Microsoft Store, which looks different from the Calculator app. Pick a color scheme stick to it.

If the one fits all approach doesn't work, then those scenarios can make a secondary custom color scheme in addition the the standardized color scheme.

**Comment by mdtauk** [comment]
@shaheedmalik  I don't think introducing more themes is going to help things.  Microsoft were the first to offer a choice of Light and Dark UIs OS wide.  It has taken a while, but this year's iOS and Android releases are adding this choice.  

Android is mobile only, but they still avoid pure black.  
macOS avoids pure black, and adds a colour blend ( like I propose here #921 ), but iOS's Dark Mode does use pure black, because most of their phones use OLED screens.

I was asked to simplify my original proposal into separate actionable items, but the idea of having Windows detect the type of display, and adjusting the base dark colour to fit, was something I suggested.

But I would wager that most Windows devices are using LCD displays, and as such, the new default should change IMO.

**Comment by shaheedmalik** [comment]
> @shaheedmalik I don't think introducing more themes is going to help things. Microsoft were the first to offer a choice of Light and Dark UIs OS wide. It has taken a while, but this year's iOS and Android releases are adding this choice.
> 
> Android is mobile only, but they still avoid pure black.
> macOS avoids pure black, and adds a colour blend ( like I propose here #921 ), but iOS's Dark Mode does use pure black, because most of their phones use OLED screens.
> 
> I was asked to simplify my original proposal into separate actionable items, but the idea of having Windows detect the type of display, and adjusting the base dark colour to fit, was something I suggested.
> 
> But I would wager that most Windows devices are using LCD displays, and as such, the new default should change IMO.

You mis read what I stated. The original dark mode was solid black. Since there wasn't a standardized color scheme for dark gray, every team made their own different dark gray dark mode. 

What I am asking for is a consistent dark mode. Read the comment I am replying to.

**Comment by mdtauk** [comment]
>If the one fits all approach doesn't work, then those scenarios can make a secondary custom color scheme in addition the the standardized color scheme.
>
This was the comment I was responding to.

>I know in many cases each team made a new "not as dark" mode because a standard wasn't set and the new theme wasn't baked into the templates. 
>
The standard is what the resources are set to, things like ``ApplicationPageBackgroundColor`` in the Theme Resources, but it seems obvious that some app designers did not like those defaults, and so they changed them.  Moving away from Pure Black is a common thread with Dark Modes across the board.

Not just changing the default resources, but also _persuading/mandating_ Microsoft teams stick to the new defaults will be needed - to try to bring more consistency to Windows.

**Comment by shaheedmalik** [comment]
> The standard is what the resources are set to, things like `ApplicationPageBackgroundColor` in the Theme Resources, but it seems obvious that some app designers did not like those defaults, and so they changed them. Moving away from Pure Black is a common thread with Dark Modes across the board.

You are still misreading what I stated. When they went to Dark Gray as the new dark mode, it wasn't standardized in the templates (as the templates were still black) thus all the differnt dark gray dark modes are different.

**Comment by mdtauk** [comment]
>You are still misreading what I stated. When they went to Dark Gray as the new dark mode, it wasn't standardized in the templates (as the templates were still black) thus all the differnt dark gray dark modes are different.
>
Yup, it was individual teams, deciding the default colours were not right/not good - and doing their own thing.  It is why I am proposing taking a fresh look at these default ThemeResources, and finding a new default that all microsoft apps can be happy with

**Comment by mdtauk** [comment]
@chigy  Microsoft seems to be giving their Dark Mode support a push with Microsoft 365.

https://medium.com/microsoft-design/designing-dark-mode-31400530787a

Perhaps the research done by the Office teams can be fed into Windows and improve how the ThemeResources are chosen and used?

**Comment by chigy** [comment]
> Perhaps the research done by the Office teams can be fed into Windows and improve how the ThemeResources are chosen and used?

@mdtauk , it is something I am fully aware and trying to figure out the best way to move forward, but this is currently Office team's POV and there's still much work to do to consolidate that with all the other parts of the company.

**Comment by mdtauk** [comment]
@chigy   I am glad to hear it is something under consideration.  WinUI 3.0 - and Microsoft's ModernOS plans, seem like the ideal time to give everything a refresh, and re-evaluate past decisions.

There is an issue being worked on to fix contrast ratio colours at the moment, and handling Contrast over accent colours, so new ThemeResources may be needed to "fix" these, and it seems a natural coming together of the stars ✨

**Comment by chigy** [comment]
> @chigy I am glad to hear it is something under consideration. WinUI 3.0 - and Microsoft's ModernOS plans, seem like the ideal time to give everything a refresh, and re-evaluate past decisions.

@mdtauk , just to be super clear, I am not making any promises here and surely not committing anything for WinUI 3.0.

**Comment by MartinZikmund** [comment]
@mdtauk Maybe, for now, an option would be to add these themes as one of the defaults in the [Fluent XAML Theme Editor](https://github.com/microsoft/fluent-xaml-theme-editor) 🙂

**Comment by axcadsd** [comment]
The current pure white / pure black themes look pretty bland/ugly to me. Hopefully the sun valley refresh improves the themes.

**Comment by mdtauk** [comment]
I think we are about ready to close this issue.  WinUI 2.6 and Windows 11 have updated the default Light and Dark theme colours!
