### ISSUE TITLE
AcrylicBrush overliad on MediaPlayerElement does not apply blur effect to video content

### ISSUE THREAD

**Issue by jumhyn-browser** [microsoft/microsoft-ui-xaml#9267]
### Describe the bug

When applied over a `MediaPlayerElement`, the blur effect from an `AcrylicBrush` is not applied to the video content. Other UI elements have the blur applied fine.

### Steps to reproduce the bug

Set up a UI where a portion is occupied by a `MediaPlayerElement` and another portion by something else (e.g. a solid-color `Rectangle`).
Put a `Border` with an `AcrylicBrush` background on top of that UI.

### Expected behavior

`AcrylicBrush` applies blur effect to all content including `MediaPlayerElement`.

### Screenshots

This screenshot shows an `AcrylicBrush` (tint color black, tint and luminosity opacity set to 0) overlaid on a UI with video content and a red `Rectangle`. Rectangle is visible, video content is not

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/140427381/baa3bd33-3bd9-47dd-974c-eaaebd4bd186)

### NuGet package version

None

**Comment by jumhyn-browser** [comment]
Maybe related to #5025 ?

**Comment by DarranRowe** [comment]
I think all of this should be detailed in the [Visual Layer for WinUI 3 documentation](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/composition). This documentation states that the MediaPlayerElement content it is then rendered via Windows.UI.Composition. Since there is no interoperability between Windows.UI.Composition and Microsoft.UI.Composition right now, the effects are unable to see the MediaPlayerElement's content and thus is unable to sample pixels and work on it.

**Comment by jumhyn-browser** [comment]
ah, yep, that addresses this head-on @DarranRowe, thanks!! Is this considered wontfix, then, or is there any expectation that these pipelines would be more interoperable at some point (soon? 😇)

**Comment by DarranRowe** [comment]
I'm not sure if it will be soon, but there have been other posters expressing an interest in this. So you should consider this a bug report or at the very least a +1 for a feature proposal.

**Comment by ranjeshj** [comment]
This is currently by design.
