### ISSUE TITLE
Binding using a specified source fails

### ISSUE THREAD

**Issue by eriklimakc** [microsoft/microsoft-ui-xaml#9375]
### Describe the bug

When attempting to bind data from the ViewModel to a Custom UserControl created entirely in C# the binding fails and no data appears.

### Steps to reproduce the bug

**Repro app: [FrameControl.zip](https://github.com/microsoft/WindowsAppSDK/files/14446965/FrameControl.zip)**

MainWindow.xaml
```xml
<StackPanel x:Name="RootElement" 
            Orientation="Horizontal"
            HorizontalAlignment="Center"
            VerticalAlignment="Center" />

```

MainWindow.xaml.cs
```csharp
public MainWindow()
{
	this.InitializeComponent();

	RootElement.DataContext = new MainPageViewModel();

	var frameControl = new FrameControl();
	frameControl.SetBinding(FrameControl.CaptionProperty, new Binding
	{
		Path = new PropertyPath(nameof(MainPageViewModel.Title))
	});

	RootElement.Children.Add(frameControl);
}
```

MainPageViewModel
```csharp
public partial class MainPageViewModel : ObservableObject
{
	[ObservableProperty]
	private string _title = "Hello!";
}
```

FrameControl
```csharp
public partial class FrameControl : UserControl
{
	public string Caption
	{
		get { return (string)GetValue(CaptionProperty); }
		set { SetValue(CaptionProperty, value); }
	}

	public static readonly DependencyProperty CaptionProperty =
		DependencyProperty.Register(nameof(Caption), typeof(string), typeof(FrameControl), new PropertyMetadata(""));

	public FrameControl()
	{
		var grid = new Grid();
		grid.ColumnDefinitions.Add(new ColumnDefinition() { Width = GridLength.Auto });
		grid.ColumnDefinitions.Add(new ColumnDefinition() { Width = new GridLength(1, GridUnitType.Star) });

		var border = new Border
		{
			Width = 300,
			Background = new SolidColorBrush(Colors.Blue)
		};
		Grid.SetColumn(border, 0);

		var textBlock = new TextBlock
		{
			FontSize = 30,
			Foreground = new SolidColorBrush(Colors.White)
		};
		textBlock.SetBinding(TextBlock.TextProperty, new Binding
		{
			Path = new PropertyPath(nameof(Caption)),
			Source = this,
			Mode = BindingMode.OneWay
		});
		Grid.SetColumn(textBlock, 1);

		grid.Children.Add(border);
		grid.Children.Add(textBlock);

		Content = grid;
	}
}
```

### Expected behavior

The source binding should work.

### Current
![image](https://github.com/microsoft/WindowsAppSDK/assets/114886335/e55f46cb-bfb0-45f9-a9ce-1bfeaf62769d)

### Expected
![image](https://github.com/microsoft/WindowsAppSDK/assets/114886335/2b1765c7-f3c9-4435-9a86-b54e9d7ce65b)

### NuGet package version

None

**Comment by evelynwu-msft** [comment]
@eriklimakc Because `FrameControl` ultimately inherits from `DependencyObject` it needs to follow the rules for a `DependencyObject`. Specifically, it needs to have type information that can be located through the app's (generated by default) `IXamlMetadataProvider` implementation. If `FrameControl` were referenced directly in XAML markup then this type information would be automatically included in the `IXamlMetadataProvider` implementation but because it is not you need to decorate the type with the `[Bindable]` attribute in order to force its inclusion. Note that `MainPageViewModel` does not have the same requirement because it does not inherit from `DependencyObject`.
