### ISSUE TITLE
Proposal: Z-depth control in XAML code

### ISSUE THREAD

**Issue by thejimmyj57** [microsoft/microsoft-ui-xaml#938]
Proposal: Z-Depth Control in XAML Code

Since the Z-depth has to currently be set in the code-behind, it makes it very difficult to set for Datatemplated elements since they cannot be accessed by their name. Maybe being able to set it directly in the XAML would be good?

**Comment by jevansaks** [comment]
As of Windows 1809, UIElement now has a [Translation property](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.UIElement.Translation)! This is how you can set and animate Z from markup.

**Comment by thejimmyj57** [comment]
@jevansaks Could you demonstrate how to use it? I cannot find a code snippet online to use Vector3 in the markup. Thanks!

**Comment by jevansaks** [comment]
@thejimmyj57 Sure, try this:

```
    <Button Translation="0,0,12"/>
```

**Comment by stmoy** [comment]
@thejimmyj57 - if the property is not showing up in Visual Studio Intellisense, ensure that the app's minimum target version is 1809+. Otherwise the markup compiler will complain and say that it cannot find the property. 

In addition to adding the Translation property, we also added the ability to implicitly animate it when it changes. The [Xaml Controls Gallery](https://aka.ms/xamlgalleryapp) has a page on "Implicit Transitions", but the snippet is here:
```
<!-- Automatically animate changes to Translation -->
<Rectangle x:Name="rectangle" Width="50" Height="50" Translation="0,0,0" >
    <Rectangle.TranslationTransition>
        <Vector3Transition />
    </Rectangle.TranslationTransition>
</Rectangle>
```

Using the TranslationTransition property will also animate the ThemeShadow if one is applied.
