### ISSUE TITLE
Border with corner radius, border thickness, background renders a gap between content and border

### ISSUE THREAD

**Issue by tibitoth** [microsoft/microsoft-ui-xaml#9454]
### Describe the bug

Border with corner radius, border thickness, background renders a gap between content and border

### Steps to reproduce the bug

1. Create a new WinUI project
2. Place the following repro code into MainWindow.xaml

```xml
<Grid Background="Red">
    <Border Width="40"
            Height="80"
            HorizontalAlignment="Center"
            VerticalAlignment="Center"
            Background="Black"
            BorderBrush="#272727"
            BorderThickness="2"
            CornerRadius="16" />
</Grid>
```

### Expected behavior

Red (or any other background) does not pass through between border and its inner background.

### Screenshots

Red bg with magnifier:

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/8333960/bcbccb45-12d1-4e16-bf6f-9b53d9d44b11)

white bg with magnifier

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/8333960/23ab7cf1-6ae4-4fd5-be05-38ec7ae2fd31)

white bg 100%

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/8333960/8aba9210-0502-4b3d-8791-761cb6735bd5)

### NuGet package version

WinUI 3 - Windows App SDK 1.5.1: 1.5.240311000

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

Workaround:

Place an additional Border under the problematic Border with the same background without border:

```xml
<Grid Background="Red">
    <Border Width="40"
            Height="80"
            HorizontalAlignment="Center"
            VerticalAlignment="Center"
            Background="Black"
            CornerRadius="16" />
    <Border Width="40"
            Height="80"
            HorizontalAlignment="Center"
            VerticalAlignment="Center"
            Background="Black"
            BorderBrush="#272727"
            BorderThickness="2"
            CornerRadius="16" />
</Grid>
```

**Comment by gegao18** [comment]
Thanks for reporting this. This is caused by a seam between the two visuals generated by the Border element (background and border). In cases where the border brush is fully opaque, your workaround works well, because the Border in the back will have an expanded Background visual since it has no border component defined. In your workaround, you can remove Background="Black" from the Border at the front to save another Visual - the Border in the front generates the border component, and the one in the back generates the background.

We try to avoid seams where we can but rounded corners create antialiasing which makes this difficult in general. It's unlikely we'll get to this issue soon, especially since there's a workaround.
