### ISSUE TITLE
Exception thrown by ShowPrintUIForWindowAsync method on Windows Server 2019.

### ISSUE THREAD

**Issue by deepika134** [microsoft/microsoft-ui-xaml#9558]
### Describe the bug

when running the ShowPrintUIForWindowAsync method on Windows Server 2019, an exception occurs. I have attached the exception screen below ,
![MicrosoftTeams-image (33)](https://github.com/microsoft/microsoft-ui-xaml/assets/87310214/82f63dfd-d9e0-41d5-99da-884a9024376a)

### Steps to reproduce the bug

- Run the attached sample on a machine with Windows Server 2019 installed.
- Click the button to execute the associated functionality.
- Observe that the application throws an exception upon clicking the button.

**Sample** : [App1.zip](https://github.com/microsoft/microsoft-ui-xaml/files/15025979/App1.zip)

### Expected behavior

The application should invoke the ShowPrintUIForWindowAsync method, opening the print preview dialogue properly. The dialogue should display the print preview of the document or content intended for printing, allowing the user to preview and adjust printing settings as needed before proceeding with the printing process. There should be no exceptions thrown during this process, ensuring a seamless user experience.

### NuGet package version

None

**Comment by codendone** [comment]
I think this relates to #4419. Per a comment in that issue, the fix was serviced to Windows 19045 ([internal bug](http://task.ms/41649749)). The fix likely wasn't serviced to Windows Server 2019.

**Comment by codendone** [comment]
The fix is indeed not on Windows Server 2019, and that version has passed its [mainstream end-of-support date](https://learn.microsoft.com/lifecycle/products/windows-server-2019).

I think if you're paying for extended support, you could request this fix through your support contract, though I don't know whether this bug meets their severity requirements.

The best alternative otherwise is probably to have an OS version check and either block printing or use Win32 printing APIs.
