### ISSUE TITLE
Question: [Lights that affects multiple UIElements ]

### ISSUE THREAD

**Issue by kdma** [microsoft/microsoft-ui-xaml#958]
Hello!
I followed the last Microsoft Build event with interest expecially the parts regarding the fluent design implementation in the soon to be WindowsUI. 

I am curious on the implementation details of this light behaviour that effects multiple UIElements at once.
![x](https://media.giphy.com/media/Q99jzr9OQEZ9gREDRS/giphy.gif). 
I tried to search in the repo and I found multiple classes lights related but I didn't manage  to find where the magic happens.
 Can you point me in the right direction or does it happen in the composition layer?
Thank you and nice work this new design framework is awesome!

**Comment by jevansaks** [comment]
Sure, happy to give some details about this! You can find the code for Reveal split between the [RevealBrush](https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/Materials/Reveal/RevealBrush.cpp) and the [RevealBorderLight](https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/Lights/RevealBorderLight.cpp). 

The short answer is that this takes advantage of the [XamlLight](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.xamllight) support. The RevealBorderLight is created and attached to the Window's root and then it positions the light using a [PointerPositionPropertySet](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.hosting.elementcompositionpreview.getpointerpositionpropertyset).

Then the RevealBorderBrush sets itself as a target of the light using [AddTargetBrush](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.xamllight.addtargetbrush#Windows_UI_Xaml_Media_XamlLight_AddTargetBrush_System_String_Windows_UI_Xaml_Media_Brush_) so that it gets targeted by the light.

Hope this helps!

**Comment by kdma** [comment]
Thank you for the detailed answer.

I didn't think of brushes as something "reactive" in the UI , now it makes sense! 

Now all I have left to do is to persuade my team to fade out WPF and go crazy with the lights 🚨

**Comment by Tartarusome** [comment]
This is very useful! However, I’ve noticed that the effect can be achieved with a `RadialGradientBrush` that only affects the border/background. 
In WinUI 3, I placed it inside a `SpiritVisual`, on top layer of the control, and successfully simulated the Reveal Highlight by limiting the area with path clipping using the `Microsoft Composition API`. 
I’m wondering if my solution performs better, else should I rewrite by using `XamlLight`?
Because by 2025 they have stopped support for reveal style, but still good with `XamlLight`.
