### ISSUE TITLE
PublishSingleFile + no WindowsAppSDKSelfContained is broken

### ISSUE THREAD

**Issue by na1307** [microsoft/microsoft-ui-xaml#9658]
### Describe the bug

Apps that use PublishSingleFile and do not use WindowsAppSDKSelfContained fail with a file not found and xaml parse failed error.

### Steps to reproduce the bug

1. Publish and run [this solution](https://github.com/na1307/test/tree/main/App1).

### Expected behavior

The app should run normally.

### Screenshots

![화면 캡처 2024-05-16 224250](https://github.com/microsoft/WindowsAppSDK/assets/103810717/dc792e7c-2f03-4207-aaee-d1df63cac098)

### NuGet package version

Windows App SDK 1.5.3: 1.5.240428000

### Packaging type

Unpackaged

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by Scottj1s** [comment]
@na1307 Thanks for reporting this.  The scenario of PublishSingleFile is not officially supported with either WindowsAppSdkSelfContained or SelfContained set to false.  The reason is that a single file deployment is considered by most users to be zero config.  That said, if your scenario requires that combination, you can disable the warning via WindowsAppSDKSingleFileVerifyConfiguration=false.  

I was able to repro the failure. The root cause is that the MICROSOFT_WINDOWSAPPRUNTIME_BASE_DIRECTORY environment variable is not being set at startup.  (The WindowsAppSDKSingleFileVerifyConfiguration target should have warned about this, but contains a logic error, which has been fixed.)

You can work around this in two ways:
1. Add the call in your app constructor:
```
    public App() {
        // Set base directory env var for PublishSingleFile support (referenced by SxS redirection)
        Environment.SetEnvironmentVariable("MICROSOFT_WINDOWSAPPRUNTIME_BASE_DIRECTORY", AppContext.BaseDirectory);
        InitializeComponent();
    }
```
2. Enable the Windows App SDK undocked reg-free auto-initialization logic, which does the same thing:
```
  <PropertyGroup>
    <WindowsAppSdkUndockedRegFreeWinRTInitialize>true</WindowsAppSdkUndockedRegFreeWinRTInitialize>
  </PropertyGroup>
```

**Comment by na1307** [comment]
@Scottj1s Thank you. I think that solved the problem. Can I close this issue now?

**Comment by Scottj1s** [comment]
@na1307 Thanks for confirming
