### ISSUE TITLE
Failing to install on arm

### ISSUE THREAD

**Issue by CrazyWolf13** [microsoft/microsoft-ui-xaml#9742]
### Describe the bug

Hi I tried installing Winget accoring to the instructions here -> https://learn.microsoft.com/en-us/windows/package-manager/winget/#install-winget-on-windows-sandbox inside Windows Sandbox. These Commands work withing x64 but on my Snapdragon Dell with arm they fail. Screenshot is attatched below.

### Steps to reproduce the bug

1. Run the commands posted by Microsoft on this url https://learn.microsoft.com/en-us/windows/package-manager/winget/#install-winget-on-windows-sandbox
2. See a failed installation for winget, but likely caused by ui.xaml

### Expected behavior

Ui.Xaml.2.8 should also work on arm, so one can install winget.

### Screenshots

![grafik](https://github.com/microsoft/microsoft-ui-xaml/assets/96661824/c1f1b528-b90a-4b57-bfe3-3664d7c3dee3)

### NuGet package version

WinUI 2 - Microsoft.UI.Xaml 2.8.2

### Windows version

Windows 11 (22H2): Build 22621

**Comment by DarranRowe** [comment]
Check your dependencies.
That screenshot shows that you installed the x64 version of some of them, and then attempted to install the ARM64 version of the Desktop App Installer. When you install from a bundle, Windows will choose the most appropriate for the system.
So you either install the ARM64 version of WinUI 2.8 and VCLibs, or the x64 version of the Desktop App Installer. It is better performance wise to install the ARM64 version. Also, yes, ARM64 versions of all of these exist.

**Comment by CrazyWolf13** [comment]
Hi @DarranRowe 

Thanks for that insanely quick response!
I could not find a way to install a specific, in this case x64 version of DesktopAppInstaller with `Add-AppxPackage`, or is there some secret argument I'm missing?

Or how am I expected to install it inside Sandbox?

**Comment by DarranRowe** [comment]
As I already mentioned, you really should prefer the ARM64 version on an ARM64 device.
The ARM64 version of the VCLibs redistributable framework package can be found either [from here](https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/cpp/libraries/c-runtime-packages-desktop-bridge#how-to-install-and-update-desktop-framework-packages), or you can find it on a system with Visual Studio installed.

![Screenshot 2024-06-19 140941](https://github.com/microsoft/microsoft-ui-xaml/assets/52577874/9e9dc5ba-d59f-4b2e-8222-cbe8b6cab477)

For WinUI 2.8, you can get the ARM64 version of the redistributable framework package can be found in the NuGet package.

![Screenshot 2024-06-19 141259](https://github.com/microsoft/microsoft-ui-xaml/assets/52577874/53da78d6-7bd3-4b56-882a-70eac6106fab)

These are the proper dependencies for the ARM64 version. The NuGet .nupkg file is just a renamed .zip file. So any method of extracting .zip files will allow you to extract the package and grab the ARM64 version of the WinUI 2.8 package.

The other option, if you really really need the x64 version of the Desktop App Installer, is, again, remember that .msixbundle files are just renamed .zip files.

![Screenshot 2024-06-19 141759](https://github.com/microsoft/microsoft-ui-xaml/assets/52577874/2d4ad59a-1219-4d31-9a88-bfa9c7ba33dd)

You can see the AppInstaller_x64.msix file in there. This is what you use to install the x64 version of the Desktop App Installer. The package also contains the ARM64 version:

![Screenshot 2024-06-19 142052](https://github.com/microsoft/microsoft-ui-xaml/assets/52577874/0985696c-b946-4bdd-bdca-b6cb3cfdbeff)

Since this is a better fit for an ARM64 system, then it is choosing that version. However, if you notice, you also have all of the other packages, which are split resources. It is easier to install packages using the bundle in this case. I want to double check that I am not missing anything, so I am going to check these steps on my Surface Pro X (ARM64). I'll edit this post when I have verified things.

**Comment by CrazyWolf13** [comment]
Hi
Again huge thanks, that worked flawlessly now!

Only thing that I could not get to work is msstore source, but this error can be overcome by adding `winget install .... --source winget`

I created a little automation, that automatically installs winget inside sandbox on sandbox launch:
https://github.com/CrazyWolf13/scripts-collection/tree/main/better-sandbox
