### ISSUE TITLE
The `TextBlock.Padding` value behaves unexpectedly.

### ISSUE THREAD

**Issue by Tamilarasan-Paranthaman** [microsoft/microsoft-ui-xaml#9760]
### Describe the bug

The `Padding` value set on the `TextBlock` was not applied properly when **`TextBlock.TextWrapping`** was set to **`Wrap`.**

```xaml
<StackPanel Orientation="Vertical" HorizontalAlignment="Center" VerticalAlignment="Center">
    <Border Background="Red">
        <TextBlock Text="Maria Anders Ant Fuller Maria Anders Ant Fuller Thomas Hardy Tim Adams Hanna Moos Martin King"
               TextWrapping="Wrap"
               Height="50"
               Padding="15,15,15,15"
               Width="250"/>
    </Border>
</StackPanel>
```

### Steps to reproduce the bug

1. Create a new WinUI Desktop app.
2. Replace MainWindow XAML with the above. 
3. Run the app in VS and see the TextBlock padding. 

### Expected behavior

It appears that the `left` and `bottom` padding was not applied to the `TextBlock.` The same code works fine with TextBox instead of TextBlock. 

I have attached the image difference for both **TextBlock (red background)** and **TextBox (green background)** with the same configuration.

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/93904422/e253a815-8187-4ef3-b4cf-59e6369e63f3)

I'm not sure if it is a bug or if it works as intended.

### NuGet package version

WinUI 3 - Windows App SDK 1.5.4: 1.5.240607001

### Windows version

Windows 11 (22H2): Build 22621

**Comment by codendone** [comment]
Yes, this is working as expected.

Left padding is working correctly in your image, otherwise the text would be tight against the left side of the red rectangle. (There is more space on the right side due to where the text wrapped.)

Bottom padding doesn't really get used. The Padding property impacts where the text is positioned (top+left) and where it wraps (right). The text with those layout constraints then gets drawn. TextBlock.Padding does not apply a clip if there is too much text.
