### ISSUE TITLE
The Loading event of UserControl is not triggered while the Loaded event is triggered when Visibility is Collapsed.

### ISSUE THREAD

**Issue by lbdalmendrayMyradar** [microsoft/microsoft-ui-xaml#9778]
### Describe the bug

The Loading event of UserControl is not triggered while the Loaded event is triggered. This is happening when Visibility is Collapsed. 

If I create a new UserControl(MyUserControl) and I subscribe to Loading and Loaded events the only event thrown is the Loaded event. The visibility of the MyUserControl is Collapsed. If I changed that visibility to Visible on running time the Loading event is thrown.

I created and shared a simple project called LoadingIssueSample (see LoadingIssueSample.zip). It is just a simple new Blank App, Packaged(WinUI 3 in Desktop) project. I created the MyUserControl subcribing to the Loading and Loaded events and registering each called in the output. The MainWindow.xaml contains the MyUserControl with Visibility = "Collapsed".

[LoadingIssueSample.zip](https://github.com/user-attachments/files/16055025/LoadingIssueSample.zip)

### Steps to reproduce the bug

1. Unzip LoadingIssueSample.zip.
2.  Open LoadingIssueSample.sln using Visual Studio 2022
3. Build and Run the LoadingIssueSample
4. Watch the Output window and see that ---- LOADED EVENT ---- is the only one executed.
5. On running time: Go to MainWindow.xaml and change the MyUserControl visibility to Visible
6. Watch the Output window and see that ---- LOADING EVENT ---- is now executed.
7. You can try doing all these steps debugging and adding a break point to MyUserControl_Loaded and MyUserControl_Loading in MyUserControl.xaml.cs in see the logic there.

### Expected behavior

The expected result is that every time a Loaded event is triggered it is because the Loading event was triggered before as well.

### NuGet package version

WinUI 3 - Windows App SDK 1.5.4: 1.5.240607001

### Additional context

Windows version : Windows 11 Pro 23H2

**Comment by lbdalmendrayMyradar** [comment]
Good afternoon. I would like to know if there is any feedback that can be shared. I would also like to know if there is any estimated time to have a solution.

**Comment by JJBrychell** [comment]
This is a known issue that results from the somewhat complicated (and possibly misnamed) loading/loaded/unloaded sequence that occurs. We are actively looking at how we can resolve this and make things clearer, but we have not yet settled on an approach that actually would achieve that goal while still providing the functionality that needs to be relied on.

Although these three events are part of the element load process, the triggers for them are not quite as straight forward.

- Loading occurs when an element is first measured. This is the first opportunity an application has to start the download of external resources that might be needed.
- Loaded occurs late in layout cycle after all templates have been applied. This is the first opportunity an application has to access the full tree that is generated from any templated controls beneath it.
- Unloaded occurs when the element is removed from the active Xaml tree. This is when the application knows that it can release any resources that it may have allocated.

The other important aspect is that Loading and Loaded are synchronous events and Unloaded is asynchronous (since there generally is no urgency in releasing resources no longer used).

Based on these triggering events, you can see why you get the behavior that you do.  Adding a collapsed control to the tree will not get a loading event because we don't measure collapsed elements.  But once the next layout pass occurs, the loaded event will fire because the element is now in a stable state (e.g. all templates that are going to be expanded already are).

If you make the element visible, you will then get the loading event because it will be measured for the first time.

We agree that this is not optimal and certainly not intuitive, but we are currently hampered in fixing this by two things.  The first is, it just isn't clear (or nobody has had a good enough idea) how to implement these (or other) events to clear things up and still get the right functionality.  The second is that anything that we come up with is most likely to be a significant breaking change which we cannot do in a dot release.  Since WinAppSdk 2.0 is not currently on the calendar, we have no current timeline for a solution.

So technically, this is by design, but I am going to resolve it as a dup of https://github.com/microsoft/microsoft-ui-xaml/issues/8342 as that is the issue that we are tracking while trying to come up with a better solution.
