### ISSUE TITLE
The ContentControl was unloaded before the view was loaded while being used in the ContentDialog.

### ISSUE THREAD

**Issue by SwathiDhatchanamoorthi** [microsoft/microsoft-ui-xaml#9785]
### Describe the bug

We have a custom control derived from ContentControl. While using this custom control within the ContentDialog, the Unloaded event of the ContentControl is called before the view is loaded.
The custom control’s Unloaded event was triggered multiple times.

### Steps to reproduce the bug

1. Add the breakpoints in the CustomControl Loaded event and Unloaded event.
2. Run the sample.
3. Click the "Click Me" button. 
[WINUI_ContentControl.zip](https://github.com/user-attachments/files/16082464/WINUI_ContentControl.zip)

### Expected behavior

 The Unloaded event of the CustomControl should not be triggered before the view is loaded.

### Screenshots

https://github.com/microsoft/microsoft-ui-xaml/assets/102227044/febf11f5-ef59-46f8-b66a-1a49764a4ddd

### NuGet package version

None

**Comment by JJBrychell** [comment]
This is a known issue that results from the somewhat complicated (and possibly misnamed) loading/loaded/unloaded sequence that occurs (as well as an oddity of how content controls are shown).   We are actively looking at how we can resolve this and make things clearer, but we have not yet settled on an approach that actually would achieve that goal while still providing the functionality that needs to be relied on.

Although these three events are part of the element load process, the triggers for them are not quite as straight forward.

- Loading occurs when an element is first measured.  This is the first opportunity an application has to start the download of external resources that might be needed.
- Loaded occurs late in layout cycle after all templates have been applied.  This is the first opportunity an application has to access the full tree that is generated from any templated controls beneath it.
- Unloaded occurs when the element is removed from the active Xaml tree.  This is when the application knows that it can release any resources that it may have allocated.

The other important aspect is that Loading and Loaded are synchronous events and Unloaded is asynchronous (since there generally is no urgency in releasing resources not longer used).

That gets combined with the oddity in about how the smoke background of the content dialog is handled.  In order to ensure that content dialog is layered on top of the background, after the background is applied, the dialog is removed from the tree and re-added to get the right z-order.

What happens is when you show the dialog, it gets added to the tree.  We then go through the first measure raising the Loading event Synchronously.  As part of the measure pass, we expand the content dialog template, which contains the smoke background.  The smoke background is moved to its own layer and the content dialog is remove and re-added to get the right z-order.  But in doing this it triggers an Unloaded event Asynchronously.  The measure (and arrange) pass completes and the Loaded event is raised synchronously.  However, the Unloading event is still queued.  So, when the full frame completes, it is processed meaning the order of events generated is Loading->Loaded->Unloaded with the element still being loaded in the tree.

The triggers for each of these events were specifically chosen as opportune times for application do different types of work, but they certainly don't fall into what you would expect from Loading->Loaded->Unloaded, especially in these more complex (or unplanned for) scenarios.

As a workaround we recommend that application check the IsLoaded property when processing the Unloaded event and if it returns true, skip the unloaded code since there will be another opportunity to do that work when Unloaded is called again when the element actually leaves the tree for good.

So while not clear (or intuitive) this is currently by design, but I am going to resolve it as a dup of https://github.com/microsoft/microsoft-ui-xaml/issues/8342 as that is the issue that we are tracking while trying to come up with a better solution.
