### ISSUE TITLE
AnnotatedScrollBar slides off screen

### ISSUE THREAD

**Issue by gi-b716** [microsoft/microsoft-ui-xaml#9854]
### Which version of the app?

WinUI 3 Gallery

### Description

In WinUi3 Gallery's AnnotatedScrollBar demo, when the window is not maximized, dragging the slider outside of the window allows it to continue to move

### Screenshots

https://github.com/user-attachments/assets/d065d3d4-176d-4127-9eea-0a72cf4577bc

### Windows version

Windows 11 23H2 (22631)

```[tasklist]
### Tasks
```

**Comment by karkarl** [comment]
It seems to be normal to be able to drag scrollviewer in the same pointer event even when the mouse has left the window boundaries. It seems the issue is with the height of the scrollviewer not adapting to the height of the window, since it's a scrollviewer in scrollviewer scenario in WinUI-Gallery. This is poor design in general cases, but makes sense for the gallery scenario.

**Comment by JohnnyWestlake** [comment]
I would say this is expected behaviour personally and present on all scroll controls - i.e, the scrollbar captures the pointer and lets you continue scroll even of not directly touching it, partly because of how thin the scrollbar can be.

**Comment by ranjeshj** [comment]
Yes. This is by design.
