### ISSUE TITLE
Proposal: Windows.UI.ViewManagement.ProjectionManager availability

### ISSUE THREAD

**Issue by FredeJ** [microsoft/microsoft-ui-xaml#996]
# Proposal: Windows.UI.ViewManagement.ProjectionManager availability

## Summary
Allow applications written with WinUI to easily stream to other screens, using the Windows.UI.ViewManagement.ProjectionManager framework.

## Rationale

* Allow easy creation of apps that are capable of streaming to other screens.
* If streaming to other screens through WinUI is extremely easy, WinUI could become the default choice when wanting to write an application that's capable of sharing content on a different screen.
* With the addition of the MS-MICE protocol in Windows, Windows is poised to 
* The API and functionality already exists. It "merely" needs to be made generally available.

## Important Notes

The API already exists and is documented at https://docs.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.projectionmanager .
Sample code is available at https://github.com/microsoft/Windows-universal-samples/blob/master/Samples/AdvancedCasting/cs/05_Multi_View_Media_Application.xaml.cs 

However the API is limited to UWP applications.

I'm looking to implement a feature in an existing application, to make it capable of streaming parts or all of my application to another screen. It seems that the Windows.UI.ViewManagement.ProjectionManager framework is exactly what I'm looking for, however it's not possible to rewrite my application to use UWP. Instead, it would be great if this framework was available for general application use.

I am unsure whether this is the right place to raise this feature request. But, as the feature already exists inside Windows.UI, I figured it might not be far off :)

**Comment by jevansaks** [comment]
Thanks for filing this, we can certainly help route this request to the right team.

**Comment by ryandemopoulos** [comment]
@FredeJ, thanks for filing this issue.  This class isn't part of WinUI, but since I couldn’t find a good place to route this request to, I decided to chat with some folks internally on what our plans are here.  
 
The short answer is that ProjectionManager is actually on path to be deprecated in the future, but the functionality it provides is being planned to be built into the new AppWindow class.  When built, the plan is to provide that for Win32 apps as well—not just UWP apps.  So basically, the goal is to enable what you’re asking for, but via AppWindow.

I'll wait a bit and then close this issue down, but I'll keep it open for a bit first in case you have any other questions I can help with.

**Comment by FredeJ** [comment]
Thanks a lot for getting back to me! That certainly sounds like the right path - I'm looking forward to seeing.

Any chance you can lift the lid a little bit for when I can expect this? I get that you probably don't want to commit to a timeline or anything similar, but it would be nice to know if it's this year, for example.

From my point of view the question is: Should i wait for this to be implemented or should I explore other options?

**Comment by FredeJ** [comment]
Oh, and specifically I would want to render a 3D model. Do you know if there's any planned support for that?

**Comment by jevansaks** [comment]
> Oh, and specifically I would want to render a 3D model. Do you know if there's any planned support for that?

Check out #686.

**Comment by ryandemopoulos** [comment]
@FredeJ Yeah, I definitely don't want to commit to a timeline (and actually, it's not even my timeline to commit to since I don't own this :)  My best guess is sometime next year--that is a guess, and not a particularly informed one.

Definitely check out #686 though, as Jevan linked.  (@GeorgeS2019 might be able to provide an update on how that is progressing over on that issue)

**Comment by GeorgeS2019** [comment]
There has been progress made with #686. Members who are interested on gITF 3D model viewer do contribute new issues to [#686](https://github.com/microsoft/microsoft-ui-xaml/issues/686)
